### ISSUE TITLE
Domoticz

### ISSUE THREAD

**Issue by darkvirus10** [SynoCommunity/spksrc#1041]
After the installation on my DS1512+ it is impossible to start the package. Error message: faill, file format invalid

**Comment by Dr-Bean** [comment]
Fyi, Domoticz 2.0.2112-5 has been published on the repository.

As this issue has been open for quite a while and includes a lot of outdated information, I am going to close it.
For problems with the current package or feature requests, you have the opportunity to start fresh: please open a new issue instead of posting to this one, or better yet, open a pull request with your improvements.
Thanks.

**Comment by Decipher** [comment]
Please refer to #1478 for work on Openzwave support for Domoticz. I have started, and have made a commit to a branch, but I am playing around with things I don't entirely understand yet, so relish any help from others.
