### ISSUE TITLE
Upgraded Synology DS1813+ to DSM 5.1-5004. Now SABnzbd 0.7.18-10 can't run

### ISSUE THREAD

**Issue by Korgun** [SynoCommunity/spksrc#1315]
I received an e-mail from Synology indicating 5.1 was available, so I upgraded my DS1813+ to DSM 5.1-5004. Now SABnzbd 0.7.18-10 can't run. Status shows Stopped and when i go to Action > Run it tries, but then it gives an error 'Failed to run the package service'.

So far all I've tried to do is restart the synology. I'll try to uninstall and reinstall over the weekend, but right now it won't load for me. Anyone else have this issue?

**Comment by wickedwally** [comment]
Hi everyone,

Please excuse me if this is not the proper place to put this comment.

I upgraded to the 1815+ (running DSM 5.1 off the bat) recently and although I didn't have any issues on my 1511 when I upgraded it to DSM 5.1, it seemed that with a new install I had trouble with permissions and sab, SB, CP etc were unable to read/write to the download folders.

After spending a week trying to learn basic linux and tinkering with ssh, I got it working.  Turns out, though, all I had to do was set the 'users' group permissions to RW in the Synology GUI (thanks for that tip, Diaoul!).  It seems, as stated by others above, that when sab, SB, CP, etc is installed on 5.1, usernames for these packages are automatically created (appropriately named after each package).  This, however, can only be seen in the back end (using ssh) and not in the Synology GUI.  These created users are put into the 'users' group, hence giving RW permissions to this group alleviated my issues.

My new concern, however, is that any subsequent user I add to my Synology also automatically gets put into the 'users' group and cannot be removed.  Although I would like to give any new user I add R abilities, I don't necessarily want them to RW (or delete for that matter!).

I have tried to learn how to move the primary group of the package users from the 'users' group into another (I created one called SynoGroup) but it seems I have hit the limit of the weeks worth of Linux knowledge.  The thought was that I could give SynoGroup the RW access and that would allow the packages to RW while allowing me to give future users that are added to 'users' group only R access.

Am I on the right track, and if so, could someone please lend a hand or point me in the direction of what I should do?

Much thanks in advance!
