### ISSUE TITLE
Security - local authentication broken

### ISSUE THREAD

**Issue by bobertato** [SynoCommunity/spksrc#1378]
Hi,

It's great that GateOne has made it to the Synology DiskStation but perhaps the following security issue should be looked into:

Default installation of GateOne allows anyone to launch sessions. This isn't very secure. It would be better to set authentication as Synology DiskStation local accounts or Admin only to prevent the service being used as a jumping point for malicious third parties who discover the service using network scanners.

Also the ability to enable local "pam" authentication as detailed in official GateOne documentation is broken on the Synology GatePne package (but not in the original GateOne package when installed on other systems) preventing users from securing GateOne on Synology DiskStations using the GateOne configuration files (such as /usr/local/gateone/var/server.conf  [different location on other systems]).

Many thanks (and the next release is much anticipated).

**Comment by patsissons** [comment]
The issue is that the debian package `python-pam` is not available (https://packages.debian.org/stable/python/python-pam). 

Unfortunately the GateOne app does not gracefully report the missing dependency so you're left to guess. You can confirm it is missing by running `/volume1/@appstore/gateone/env/bin/python -c "import PAM"`. Note that this `python-pam` package is not to be confused with the pip package `python-pam` (https://pypi.python.org/pypi/python-pam/1.8.2). I don't know enough about GateOne or this pip package to understand why the pip package was not used instead (I assume there is a good reason). The debian package includes a compiled assembly with python bindings, whereas the pip package is pure python.

I'm trying to research how much effort is required to compile the debian package, if I make any progress I'll try and report it here.

**Comment by Dr-Bean** [comment]
GateOne 20150311-5 has been published on the repository. #1526 adds PAM auth to a certain extent, although I'd suggest to take a look at the PR for the details.
