### ISSUE TITLE
Unrar for DS413 with (PPC QorIQ) does not work. 

### ISSUE THREAD

**Issue by STRYKER69** [SynoCommunity/spksrc#1426]
Unrar with DS413 (PPC QorIQ) does not work on Packages from SabNZBd and NZBGet.
When it start on Console come the Message "File not found".
When replace Unrar with the PPCVersion of rtlabs there are no problems.
Looks like an error by compiling.

**Comment by Dr-Bean** [comment]
Can you provide the DSM version you're working with?

**Comment by STRYKER69** [comment]
DSM 4.3 -3827

**Comment by Dr-Bean** [comment]
The Qoriq DSM4.3 toolchains haven't changed, the digests are still valid. The changes in the framework should not have been able to cause this, because it focuses mainly on adding new toolchains. The unrar version was updated 2 months ago, and there were packages with that version released too.

Up to now, I have not heard of other people with the same issue...so just to be sure, and since I can't come up with an explanation otherwise, are you sure you don't have any local changes that could cause this?

@Diaoul, ideas maybe?

**Comment by STRYKER69** [comment]
The problem also exists for several months and involved even the previous versions. Since I replace the unrar from rarlab by self.
It also will not notice everybody. SABnzbd and NZBGet automatically use the Unrar from the Syno in "usr / syno / bin" when the command not work .

The first version from Unrar5 in the Packages worked very slowly but it works. The Unrar 5 from the last ~2 Packages works no longer.

**Comment by STRYKER69** [comment]
Here a picture from them. i renamed the Unrar to unrar2 for Test otherwise start the unrar from "usr / syno / bin"
![syno](https://cloud.githubusercontent.com/assets/4297335/5605933/c7cd4260-9416-11e4-8107-93c0d6b5e648.png)

**Comment by Dr-Bean** [comment]
That's kind of helpful info, could've used that to start off with. It's possible the issue was introduced by a particular version of Unrar, or maybe the -O3 flag.
Can you be more specific as to the version of Unrar5, or a date when you noticed it first? The first unrar v5 was introduced on Aug 31, 2013...and it's hard to believe it hasn't worked since then.

**Comment by STRYKER69** [comment]
I am sorry for the unnecessary excitement.
Your unrar version ( unrar 5.20 beta 3 ) works fine.
I forgot to write the paths when run.
I guess I'm not as fit in Linux as I thought.

Sorry again

**Comment by Dr-Bean** [comment]
No problem. Glad to hear you got it solved, I was considering building a whole bunch of unrar files to see if you could get one to work ;)
