### ISSUE TITLE
ZNC won't run on DS415+

### ISSUE THREAD

**Issue by sachse** [SynoCommunity/spksrc#1427]
ZNC installs without errors on DSM 5.1-5021 Update 2 running on a DS415+, but when I try to start it I get "Failed to run the package service". The log is empty.

**Comment by sunbiker** [comment]
have it on the 1815+ too

**Comment by Dr-Bean** [comment]
Can you run `/var/packages/znc/scripts/start-stop-status start` via command line?
It should show some information useable for troubleshooting.

**Comment by sachse** [comment]
I can only run that command after giving shell access to the ZNC user. Once I've done that I get this:
```
[ .. ] Checking for list of available modules...
[ >> ] ok
[ .. ] Opening config [/usr/local/znc/var/configs/znc.conf]...
[ >> ] ok
[ ** ] Found old config from ZNC < 0.203. Saving a backup of it.
[ .. ] Creating a config backup...
[ >> ] /usr/local/znc/var/configs/znc.conf.pre-1.4
[ .. ] Loading global module [webadmin]...
[ >> ] [/usr/local/znc/lib/znc/webadmin.so]
[ .. ] Binding to port [8250]...
[ >> ] ok
[ .. ] Binding to port [+8251]...
[ !! ] Unable to locate pem file: [/usr/local/znc/var/znc.pem]
[ ?? ] Would you like to create a new pem file? (yes/no) [yes]: 
```

**Comment by Dr-Bean** [comment]
The fact that the shell is set to `/sbin/nologin` could very well be the cause too. The installer takes care of generating a certificate [here](https://github.com/SynoCommunity/spksrc/blob/develop/spk/znc/src/installer.sh#L40), but it probably fails because it doesn't have permissions.

So, if there's no cert, it fails to run. Can you check by typing `yes`/enter in the dialog above: it should create the cert, and start znc?

**Comment by sachse** [comment]
I can confirm that the package runs once the user has shell access and the certificate is generated. Although I created the certificate by using the same command the install script uses, I forgot to do it through the binary.

It also seems like ZNC tries to back up the config file every time the service starts.

```
/var/packages/znc/scripts/start-stop-status start
Starting ZNC ...
[ .. ] Checking for list of available modules...
[ >> ] ok
[ .. ] Opening config [/usr/local/znc/var/configs/znc.conf]...
[ >> ] ok
[ ** ] Found old config from ZNC < 0.203. Saving a backup of it.
[ .. ] Creating a config backup...
[ !! ] File exists
[ .. ] Loading global module [webadmin]...
[ >> ] [/usr/local/znc/lib/znc/webadmin.so]
[ .. ] Binding to port [8250]...
[ >> ] ok
[ .. ] Binding to port [+8251]...
[ >> ] ok
[ ** ] Loading user [admin]
[ .. ] Forking into the background...
[ >> ] [pid: 12334]
[ .. ] Writing pid file [/usr/local/znc/var/znc.pid]...
[ >> ] ok
[ ** ] ZNC 1.4 - http://znc.in
```

**Comment by Dr-Bean** [comment]
ZNC makes a backup of the config file, because format-wise, it's out of date for this version of ZNC. We could probably update it to the latest format, even though it's not strictly needed (and it'll only apply to new installations, existing installations will not be updated)

One question left, I think: After creating the .pem file, does ZNC still need the shell to run?

**Comment by sachse** [comment]
It won't run for me without the shell.

**Comment by Dr-Bean** [comment]
@saschpe I think we're going to have to revert #1075 to fix this. Perhaps you're able to confirm the issue yourself?

**Comment by saschpe** [comment]
No big deal. I wonder why I didn't face the issue so far though...

**Comment by charlesjohnson** [comment]
Confirmed, giving the zinc user a shell fixed it here too.

**Comment by Dr-Bean** [comment]
ZNC 1.4-10 has just been published on the repository, fixing the shell for new installs, adding some modules, and some general maintenance to the package.

Note: if your ZNC package currently does not run, it's likely that is caused by the user shell being disabled. Please remove the current package and reinstall the updated version (The user recreation is not integrated in the package: it's effectively more trouble than it's worth)
