### ISSUE TITLE
[Request] Package for ComicTagger a tools for Mylar

### ISSUE THREAD

**Issue by Nonobis** [SynoCommunity/spksrc#1449]
Hi,

Could somebody make a package for ComicTagger (http://code.google.com/p/comictagger/downloads/list). It's a tool used by mylar. It's in python. I think the only pre-requisities is "configparser".
There is a guide for install it here : http://mylar.forumatic.com/viewtopic.php?f=12&t=11

Thx by advance.
##

**Comment by Diaoul** [comment]
Latest commit is from July 2014, is this project maintained? This is the most important issue of Mylar, it's not maintained.

**Comment by Nonobis** [comment]
@Diaoul : the last commit on mylar develop branch was 21 hour ago ... and 22 days ago on master branch. For comictagger, i can't tell sorry ... i will ask to mylar dev, if he know anything about the state of comictagger project.
@evilhero : i am asking for a separate comictagger package for synology, do you know if comictagger is still maintened ?

**Comment by evilhero** [comment]
It's maintained, but it only gets bug fixes as of late, but it's fully functional otherwise. I believe the owner has put his time into other projects, but will provide fixes as needed, bit only if the current version becomes non-functional (this is just what I've gathered from reading their forums). 

I do plan on asking the maintainer for permission to include Comictagger within mylar, but the pre-requisite for configparser would still be on the user to install.
