### ISSUE TITLE
env: setup.py: No such file or directory

### ISSUE THREAD

**Issue by beardicus** [SynoCommunity/spksrc#1454]
I imagine this is something easy and pretty dumb on my part, but I'm stumped. This happens to any python module I try to compile, but let's use `pycurl` for an example:

### Procedure
- `git clone https://github.com/cytec/spksrc-vagrant.git` 
- `cd spksrc-vagrant`
- `vagrant up`
- `vagrant ssh`
- `cd spksrc/cross/pycurl/`
- `make arch-88f6281`

### Results
(after successfully compiling dependencies)
```
===>  Extracting for pycurl
tar -xzpf /home/vagrant/spksrc/cross/pycurl/../../distrib/pycurl-7.19.5.tar.gz -C /home/vagrant/spksrc/cross/pycurl/work-88f6281-4.3 
===>  Patching for pycurl
===>  Configuring for pycurl
===>  Compiling for pycurl
env: setup.py: No such file or directory
make[1]: *** [compile_python_module] Error 127
make[1]: Leaving directory `/home/vagrant/spksrc/cross/pycurl'
make: [arch-88f6281] Error 2 (ignored)
```

I checked to make sure the vagrant box had all the spksrc dependencies installed, and it appears to be complete. Makefiles make my head hurt. I'm missing something obvious, right?

**Comment by Diaoul** [comment]
You can't just build pycurl as it is a python module, not some standalone binary. It needs to be compiled with spk/python or spk/python3.

**Comment by beardicus** [comment]
Ok. Thanks for the direction. I'm trying to package [attic](https://attic-backup.org/). Waiting for spk/python to build right now, and then we'll see if I can muddle along further.

**Comment by dsheyp** [comment]
i'm also interested in compiling a python module with spk/python. how does this work?

**Comment by Dr-Bean** [comment]
Take a look at the Mercurial package or the Flexget package as examples. If your module needs (cross-)compiling, add cross/Python and some basic modules as `BUILD_DEPENDS` to your SPK Makefile, along with the module you wish to compile. 
See [here](https://github.com/SynoCommunity/spksrc/blob/develop/spk/mercurial/Makefile#L7) or [here](https://github.com/SynoCommunity/spksrc/blob/develop/spk/flexget/Makefile#L8)
Your module will end up as a wheel (file), which can subsequently be added to the package contents and installed during package installation.

If the module does not need to be (cross-)compiled, look at the [SABnzbd package](https://github.com/SynoCommunity/spksrc/blob/develop/spk/sabnzbd/Makefile#L8) for an easier example: simply add the necessary modules as a `WHEEL` dependency. 
The module will also end up as a wheel, but because it does not need Python to compile it, it's much faster to build.

**Comment by dsheyp** [comment]
thanks dr-bean!

**Comment by Dr-Bean** [comment]
See my earlier comment. I'll close this for now, but let us know if you need a hand.
