### ISSUE TITLE
Transmission displaying bad information on several sites.

### ISSUE THREAD

**Issue by croftyboy** [SynoCommunity/spksrc#1460]
The newer version of transmission '2.04-2.84' is displaying some bad information on some trackers making them think you are cheating, wich will get you banned.
This is not for all trackers tho. Seams random or mayby hopw the trackers read the information.

Would be nice to have several version of transmission to chose from to install instead of just the latest.

**Comment by Dr-Bean** [comment]
Personally, not a big fan of an additional Transmission package on the repo, although I can understand the need. I'd like to hear @Diaoul's opinion on this.

If we do decide to add an older version of Transmission, two things:
- We do not want the two packages of Transmission to interfere with one another. Specifically: use a separate installation dir, separate user, separate port.
- We're not going to add more than one additional package. The most obvious choice for a version would be the newest version that does not have the buggy reporting issue, or something along those lines. Which version would that be?

**Comment by croftyboy** [comment]
Transmission 2.03 would be the ideal choice.

**Comment by Diaoul** [comment]
If you want to keep an old transmission just don't update it in the Package
Center. I'm against adding multiple versions of transmission as this is an
edge case. I'll add a proper vagrant file so you can rebuild the
transmission you want easily with spksrc.

**Comment by Dr-Bean** [comment]
Just playing devil's advocate here, but might be less of an edge case than you think ;) It's been requested over here more than once (although usually in completely unrelated tickets...), and there are more than a couple forum posts on the same subject.

**Comment by piwi82** [comment]
The easiest solution would be to provide version 2.03 <u>only</u> until the tracker issue is solved.
Thus people having this problem will have to uninstall their current version and then install this older one.

**Comment by Dr-Bean** [comment]
Yep, agree. But, for it to show up in Package Center as installable, you'd still need to set `${PACKAGE}` to something else than `Transmission`, right? (because we don't want to downgrade everyone to 2.03 so we don't just want to bump `SPK_REV` after changing the version)

Then, if ${PACKAGE} is changed, the installdir is automatically different, because it uses the same var. Might as well change user and port too, and completely split off to two packages. 
Or are we talking manual installation outside of Package Center, because then the above isn't valid of course?

**Comment by piwi82** [comment]
I don't think it is important that the package shows up in Package Center as the latest version of Transmission should be removed from the repo. Regarding the tracker bug in Transmission, it would be preferable that users uninstall the latest version and then install version 2.03 that will be available in Package Center.

**Comment by Dr-Bean** [comment]
Hm. Might have misunderstood what you meant, so to be sure: Are you saying we remove the current Transmission-2.84 package, and essentially replace that package with 2.03 until the reporting issue is resolved? I'd say no to that ;) 

Here's why:
The issue that @croftyboy is talking about only affects people using private trackers, where newer versions of Transmission (anything over 2.03 apparently) are banned because they report incorrect statistics (the seedratio does not always report correctly, or something like that). 

For private trackers, that's considered very important, because members are expected to upload to a certain ratio, e.g. 2 or more, otherwise you're booted off the tracker. 
On the other hand, public trackers don't care about that, so the majority of people using Transmission are not affected.

Even though it's not a majority, there are still a fair number of people who use private trackers, and thus need an older versions of Transmission (or a different client, fwiw). That is, until a future version of Transmission solves the issue, but I have no idea if that's in the works...it's not particularly a _new_ issue.
@croftyboy Correct me if I'm wrong :)

**Comment by piwi82** [comment]
Oh sorry Dr-Bean, I wasn't aware only private trackers were concerned. :confused:

**Comment by Oleekae** [comment]
sorry but is it so complicated to provide the v2.03 installer manually to download?

**Comment by Dr-Bean** [comment]
Not particularly, no, but that's not part of the service SynoCommunity provides. We either put it on the SynoCommunity package repository, or not.
As @Diaoul mentioned before, you can build the package yourself, so that is not the issue here.

**Comment by Diaoul** [comment]
Manual download is dangerous because it doesn't block install when dependencies are not satisfied and downgrade is not supported in our packages so it might just not work if you try that.

**Comment by Oleekae** [comment]
Well it is your wise decision, nothing to argue on this topic. And thank you for your support
