### ISSUE TITLE
[REQUEST] add libgdiplus.so to Sonarr (beta) package

### ISSUE THREAD

**Issue by EvtK** [SynoCommunity/spksrc#1466]
The new version of Sonarr uses the library libgdiplus.so for resizing banners and art images of tv series. Since it needs to be installed, and currently isn't, it's causing errors. Is it possible to add this to the package. For more detail and explanation see this topic on sonarr forums:

https://forums.sonarr.tv/t/mediacover-errors-since-update-to-2-0-0-2788/3892/3

many thanks

**Comment by cytec** [comment]
i dont think this is possible... libgdiplus has a lot of dependencies to compile (including x11) for more info see https://github.com/SynoCommunity/spksrc/issues/1346#issuecomment-64791810

**Comment by Dr-Bean** [comment]
I was looking at this for a bit, trying to find what exactly the requirements are for libgdiplus (haven't found it yet, anyone have a link?), but I did come across this PR: https://github.com/mono/libgdiplus/pull/13.

Maybe someone has the opportunity to check it out, see if it's useable? (ping @maxrogers too, I noticed the Sonarr thread on the issue)

**Comment by maxrogers** [comment]
@Dr-Bean @cytec @EvtK, I have been fooling around with this just a little bit. I think our best option will be to compile libgdiplus in native and pull the "libgdiplus.so" library file from the native compile (like we do with the necessary mono dlls.) This would work as long as libgdiplus.so is truly a library (doesn't need a specific compile.) I would think it is. I started that process but I do not know how to properly add dependencies in native. At least, I can't seem to get it to work like it does in cross. I added ``DEPENDS = native/glib`` to the Makefile but I still get: 

```configure: error: Package requirements (glib-2.0 >= 2.2.3) were not met: No package 'glib-2.0' found```

Any pointers on adding glib as a dependency in native?

FYI, I also tested a compile in cross. I added all of the dependencies except x11. As expected, without x11 I get an x11 related error... I haven't attempted to try to cross-compile x11 due to what I assume will be a dependency tree nightmare

**Comment by Taloth** [comment]
@maxrogers If it's easier to get a imagemagick dependency working, I can try to use that as option. Looks like I could do imagemagick without libgdiplus.

**Comment by Taloth** [comment]
@maxrogers
Talked to the other devs at Sonarr and looked at some options, we're never going to be able to solve this dependency problem for every platform mainly because the libraries are versioned differently on all those distributions. We have an reliable alternative in mind, best part is that you won't have to do anything for it. It involves skyhook, so it means we won't need libgdiplus nor imagemagick.

In any case, I pushed a new version to master that should get rid of the errors and the corrupt posters. And silently serve the full sized image instead, as originally intended.

https://forums.sonarr.tv/t/mediacover-errors-fixed-in-2-0-0-2837/3954

**Comment by maxrogers** [comment]
@Taloth, sounds good. Haha, it was proving fairly challenging. Are all platforms going to use this alternative then or just non-windows/linux systems?

**Comment by EvtK** [comment]
hi guys, I'm not that skilled to be of any assistance in this kind of issues, but I just wanted to let know I really appreciate that you picked this up right away!

**Comment by Dr-Bean** [comment]
@maxrogers Seems I missed your question somehow, sorry about that. Not an expert on that part of spksrc, but I doubt it's possible to depend on a native build from another native build. Diaoul would probably have a proper answer for you though.

@Taloth Thanks for the info, appreciate that you're keeping us up to date here :)

**Comment by Taloth** [comment]
Probably all platforms, we're just going to serve resized images from skyhook and let CF cache em.

**Comment by maxrogers** [comment]
Just for future reference @Diaoul, is it possible to have a native build depend on another native build in spksrc?

**Comment by Diaoul** [comment]
@maxrogers: I don't see why this wouldn't be possible. If that's not possible we'll make it so it is :)

**Comment by Dr-Bean** [comment]
Seeing as the issue was handled and solved on the Sonarr side, let's close the issue.
