### ISSUE TITLE
PILL issue (Python 2.7.8-11) on DS413

### ISSUE THREAD

**Issue by mderksen** [SynoCommunity/spksrc#1474]
When i try to use PILL with the SynoCommunity Python i get a segmentation fault. Can anyone confirm PILL works in the package for DS413? This is what i tried on my Synology DS413 (PPC arch):

nas> cd /usr/local/python/bin
nas> python2.7
Python 2.7.9 (default, Jan  7 2015, 14:23:54)
[GCC 4.3.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image, ImageFilter
>>> img = Image.open("/volume1/downloads/test.jpg")
>>> img = img.resize((1000, 1000), Image.NEAREST)
Segmentation fault (core dumped)

**Comment by Dr-Bean** [comment]
Can't reproduce on 88f6281 or bromolow at least. It's either a PPC specific thing (which would be weird), or maybe an issue with the image somehow?

**Comment by mderksen** [comment]
Thank you for testing on 88f6281 and bromolow. I hope someone can test this also on PPC. I can't easily uninstall and reinstall Python because i have to uninstall Autosub, PlexConnect, CouchPotato, SickBeard and SABnzbd also before i can uninstall Python :)

**Comment by mderksen** [comment]
I uninstalled and reinstalled the python package from scratch. Still got the same problem :(

**Comment by Dr-Bean** [comment]
Coming back to this: You seem to have a Python version installed that we don't offer: Python 2.7.9 is not available on the SynoCommunity repository.
Can you start the Python console like this: `/usr/local/python/bin/python`, run your commands, and see if that works?

**Comment by mderksen** [comment]
Ok, i will give it a try but i have installed Python from the SynoCommunity repository (2.7.8-11). 

I will let you know asap after i start Python with /usr/local/python/bin/python

**Comment by Dr-Bean** [comment]
Well, what's strange is the version shown in your Python console: 
> Python 2.7.9 (default, Jan 7 2015, 14:23:54)

That leads me to believe there's a different version of Python installed, and it's on PATH too. You can check where it's located with `which python2.7` 
If you use the full path, then at least we know that the correct Python is used.

**Comment by mderksen** [comment]
Well, that absolute path didn't gave me an error :-) So there is nothing wrong with my package installed? Could it be something in PlexConnect which isn't using Python and PILL without the full path? 

I have only have Python 2.7.8-11 (from SynoCommunity) installed and Python Module 0002 from Synology.

nas> cd /usr/local/python/bin
nas> ll

shows this:
lrwxrwxrwx    1 root     root             7 Dec 12 22:40 python -> python2
lrwxrwxrwx    1 root     root             9 Dec 12 22:40 python2 -> python2.7
-rwxr-xr-x    1 root     root          3824 Dec 12 23:01 python2.7

nas> ls -d -1 $PWD/*.*

shows this:
/usr/local/python/bin/easy_install-2.7
/usr/local/python/bin/pip2.7
/usr/local/python/bin/python2.7
/usr/local/python/bin/smtpd.py
/usr/local/python/bin/virtualenv-2.7

**Comment by Dr-Bean** [comment]
Ok, so there's nothing wrong with the SynoCommunity package. The problem lies somewhere else.
First off, you have two Python packages installed:
- Our package, located in `/usr/local/python` (which is a symlink to `/volume1/@appstore/python`)
- Some version of Python 2.7.9, located somewhere else. As I said, use `which python2.7` to figure out its location.

The next thing to note is that the second Python is located on the system PATH. This means you can call `python2.7` from any location, and it'll start that version. That is what happened when you did this:
>nas> cd /usr/local/python/bin      < correct dir for our package
nas> python2.7          < not the correct command, you should call `./python2.7` here. The `./` ensures you start an executable located inside the current working directory, and is equivalent to using `/usr/local/python/bin/python2.7`

So, how to solve this? 
Well, the best option is to always call executables with their full path. This prevents issues where executables with the same name are found on $PATH and take precedence over the executable you actually want. As you mentioned, maybe it's possible to change the path to Python in PlexConnect (no idea, never seen it)
If that's not possible, put the correct Python location first on PATH. One way is to start PlexConnect like this: `PATH=/usr/local/python/bin:${PATH} /path/to/PlexConnect`.
Then, although it probably won't solve this issue directly, remove the other Python if you don't need it. It'll only cause confusion if you're not too familiar with the system.

**Comment by mderksen** [comment]
Thank you so much. I'm going to try this tonight (change system PATH or remove 2.7.9 or start PlexConnect in a different way). 

Strange thing is, i didn't install 2.7.9 but i will use which python2.7 to figure out it's location. I will give you an update asap.

**Comment by mderksen** [comment]
which python2.7:
/usr/bin/python2.7

which python:
/usr/bin/python

**Comment by Dr-Bean** [comment]
Those changes should work fine. Just remember that in case of package upgrades, those changes might be reverted.

As for replacing the symlink, it's possible, but I would not recommend it. I'm assuming the current symlink points to the regular Synology Python, and you might break Synology functionality that relies on that particular version.

Anyway, glad to be of assistance :)
