### ISSUE TITLE
Docker support coming to dsm 5.2

### ISSUE THREAD

**Issue by jabbera** [SynoCommunity/spksrc#1493]
I wish it was a full blown hyper visor but better then nothing.

DSM 5.2 beta brings exciting features for all users. The lightweight virtualization package Docker is aimed at creating, managing, and shipping server applications in a few clicks.

https://www.synology.com/en-global/events/2015_CeBIT_event

**Comment by bru7us** [comment]
Interesting! That has the potential to totally flip our (spksrc) delivery method in the future and could make cross-platform compilation almost redundant.

**Comment by jabbera** [comment]
Cross compilation will always be needed. The packaging though will be very different.

**Comment by fbartels** [comment]
I've heard that this will sadly not be available to all devices, but rather only for the fast 64bit intel machines (415+ and up). Which makes sense, as there are already plenty of docker templates for this architecture.

**Comment by dsebastien** [comment]
It makes sense to have it for intel machines since most Docker images on the Docker hub are compatible. Arm based devices require specific images (which is why I'm not interested in running Docker on my Raspberry Pi ;-)

That's be a good start. There are so many use cases for Docker even at home and certainly on Synology NASes ^^

**Comment by Diaoul** [comment]
Nothing will change for spksrc as Docker is only available for intel based devices and still require more resources than a cross compiled application.
That's an alternative to a chroot.
