### ISSUE TITLE
Sabnzbd https issue

### ISSUE THREAD

**Issue by flitschbirne** [SynoCommunity/spksrc#1535]
Hi guys.

I freshly installed sabnzbd on DSM 5.1-5022 Update 2. I click through the 1st setup and I get to the web interface. When I want to switch to https (port 9090) and I restart the service I no longer can get to the web interface. In the DSM system control under packages the service is stopped and I cannot start it again.

Any thoughts?

**Comment by Dr-Bean** [comment]
When you turn on https, http on port 8080 should still work too, and there's nothing that should keep SAB from starting, afaik. Just tested, works for me on the same version.
So, couple questions:
- Is there something else running on port 9090 maybe? Check with `netstat -tulpn | grep 9090`, I'd expect a Python process if SAB is running on that port, otherwise nothing.
- Did you change anything at all in or outside the package to get it running in the first place? Changed permissions, users, anything in particular in the SAB config?
- Try running `/var/packages/sabnzbd/scripts/start-stop-status start`, see if that gives some insight.

**Comment by flitschbirne** [comment]
Hi.
netstat -tulpn | grep 9090 returns:

tcp        0      0 0.0.0.0:9090            0.0.0.0:*               LISTEN      20148/perl

I did not change anything. Crazy thing is: It worked totally fine with https and port 9090. Then I rebooted the system and then the SAB service would not start. So I uninstalled the package and reinstalled it. Then some minutes later i realized that the problem is somehow connected to activating that https option.

I tried a different port now (8081) and now https works. So something is wrong with port 9090...

**Comment by Dr-Bean** [comment]
No, there's nothing wrong with it. As I suggested, there's already a process running on that port according to your output. Specifically, a Perl process.
By executing `ps -www | grep 20148`, you might get some insight in what it is. You probably have some other package installed (Synology or third party), based on Perl, which uses port 9090.

Your current solution to use a different port for SAB is fine. Alternatively, you can fix that other package to run on a different port: that's up to you :)

**Comment by flitschbirne** [comment]
Ah. There you go. Thanks for the commands.

```ps -www | grep 20148´´´ showed
```20148 admin     100m S    /usr/bin/perl /volume2/@appstore/SqueezeCenter/slimserver.pl --daemon --pidfile /volume2/@appstore/SqueezeCenter/Cache/slimserver.pid --cachedir /volume2/@appstore/SqueezeCenter/Cache --logdir /volume2/@appstore/SqueezeCenter/Logs --prefsdir /volume2/@appstore/SqueezeCenter/prefs --httpport 9002´´´

Strange. But this service runs on port 9002?!?

**Comment by Dr-Bean** [comment]
Well, it happens to say `9002` in the startup argument...it doesn't seem to be true, does it? ;)

I don't know the package at all, but I could imagine a couple of scenarios why it's running on port 9090. 
E.g. it might be running on two ports simultaneously for whatever reason, or the startup argument is ignored because a config file says otherwise.

**Comment by flitschbirne** [comment]
Well I will dig into that. Thanks for your help!

**Comment by Dr-Bean** [comment]
Sure. At least you have SAB running via SSL, so you've got the time to sort the other issue out :)
