### ISSUE TITLE
NZBGet V15

### ISSUE THREAD

**Issue by TeaPot91** [SynoCommunity/spksrc#1539]
Can NZBget V15 be added to the synology nzbget testing package? It has been compiled and pull request outstanding for over a month here:

https://github.com/SynoCommunity/spksrc/pull/1471

Thanks

**Comment by Dr-Bean** [comment]
If there's already an open PR, we'll get to it when we can. Opening a new issue for the same thing won't speed it up, we're doing this in our spare time. 

Note that the reason that PR wasn't merged earlier, was because the PR didn't merge cleanly...and it still doesn't, so it needs a bit of manual work.

If it's urgent, you can clone the repo, and build the package yourself.
