### ISSUE TITLE
Transmission 2.84 (14307)

### ISSUE THREAD

**Issue by Zenda-lee** [SynoCommunity/spksrc#1553]
I recently installed Transmission 2.84 (14307) on my DS415+ with DSM 5.1 on it. 

I tried to use the guide here: http://forum.synology.com/wiki/index.php/Transmission_HowTo

However, upon installing Transmission appears to be in the folder: 
volume1/downloads
as opposed to
volume1/transmission/download
as is suggested in that wiki

The program runs fine. I was able to add previously downloaded files to seed. I was also able to download new files but only when adding the .torrent file manually. I was not able to get an auto-dl situation to happen.

I have tried adding the .torrent file to the volume1/transmission/incoming folder as the wiki states, but that does not work. I have also tried creating the folder volume1/downloads/incoming and adding the .torrent file there too, but that also does not trigger an auto-dl. I also just tried adding the .torrent file to the volume1/downloads folder to see if that might trigger an auto-dl situation but again no luck.

So, how do I get this to work the way it was advertised? Is there a different install process I should be following than laid out in that wiki, it is from 2012 and I can easily see how the procedure may have changed in the interim, especially since it appears from my non-linux gui based skill set to be installed in a different location than in that wiki.

**Comment by Dr-Bean** [comment]
That tutorial is outdated, yes, and not fit for the package you see on our repository.

May I suggest to read what's shown during the installation wizard, because that would probably answer your questions :)
The wizard specifically asks you to enter a location where to store the downloads in (default: `/volume1/downloads`), and also asks you to enter a directory to watch for incoming torrent files. Leaving that field blank disables the functionality, otherwise, I'd suggest using something like `/volume1/watchfolder`.

Note that the directories you want to use should exist upfront, before package installation. So, first off, make one (or two, for the watch folder) shared folders, in the same vein as the suggested `downloads` folder. With that done, you can start the installation of the package.

**Comment by Zenda-lee** [comment]
Thank you Dr. Bean, I will try a re-install, with the proper folders and not the ones from the wiki. :)

**Comment by Dr-Bean** [comment]
Apologies if my post came across as harsh, it wasn't meant like that :) 
See if my suggestions work for you, and if not, we should be able to help you out.

**Comment by Zenda-lee** [comment]
No, it wasn't harsh, just the scenario of a conflicting years old wiki with a version much newer confused me. Today I had the time to do a re-install and set it all up again. It worked perfectly. I created the folders ahead of time, then installed. Then transferred previously downloaded content into the downloads folder, then added the ,torrent files to the incoming folder and it auto-loaded them all. It then forcechecked them and started seeding them. I also downloaded a file off the net to that folder and it auto-download. It is perfect! Now I just need to work on being able to download to that folder on the NAS from my phone... Thanks for the help Dr. Bean. :D

**Comment by Dr-Bean** [comment]
Great :)

As for the download via phone, there might be other ways, but I know some people use Dropbox (or BTSync, Owncloud, SyncThing etc, depending on the availability of a client for your mobile phone's OS) to sync between their phone and Synology.

With that approach, you can set up a sync between a particular folder on your phone and the watchfolder on your Synology. Then you can save the torrent file on your phone, and put it in a folder that syncs with the watchfolder on your Synology.
