### ISSUE TITLE
SABNZBD issues after updating python

### ISSUE THREAD

**Issue by grimrod42** [SynoCommunity/spksrc#1600]
Hi

I installed the new python on Sunday, and I started to get an error on my sickbeard script about cannot open url due to certificate issue. I then installed the latest python fix on Monday, however I still get that error and now the nzb fetch does not work.

Is there anyway I can revert to the old python or will this be fixed soon.

**Comment by Dr-Bean** [comment]
Your problem is more than likely caused by a certificate that cannot be verified against a root certificate, or because it is invalid. We cannot fix that. Take a look at #1575, I've put some suggestions in there on how to handle it.
As for Sickbeard, they seem to have a fix in their development branch which might help in solving your problem, but that fix is not in their master branch yet. See [SB-issue 2551](https://code.google.com/p/sickbeard/issues/detail?can=2&q=2551&colspec=ID%20Type%20Status%20Priority%20Milestone%20Owner%20Summary%20Stars&id=2551) and https://github.com/midgetspy/Sick-Beard/commit/79cb8f207bef8613db9e47eb392666af059df3d0

**Comment by grimrod42** [comment]
Thanks
However, Everything  was working perfectly before the update this week of python...

Pat

**Comment by Dr-Bean** [comment]
Yes, I don't disagree with that. However, the other issue I linked to includes a link to the rationale of the change. In short, prior to Python 2.7.9, a gaping security hole existed by not verifying certificates were valid.
The Python developers felt justified (and we can only agree with that), that breaking previously working behavior was justified if that meant that that security issue was fixed. Note that this was heavily discussed last year in the Python community, implemented in Python in November, and over three months later, we have only just released the updated Python package.

So, yes, things might be broken. It is up to the application developers and -maintainers, site managers and all others involved, to fix their code, fix their certificates or whatever might be needed. From what I can see, they are doing just that.

As for what you can do yourself, that depends on where exactly your issue lies. A couple examples:
- If you are using untrusted/unverifiable/invalid certificates internally, then you can probably fix that yourself in a number of ways: replace the certificate with a valid one, check you're actually using the hostname on the certificate or even turn off HTTP for internal traffic.
- If it's an external site (e.g. news provider or web/API interface of an indexer), ask the site manager to fix their certificates.
- Check with the application maintainers if a fix is on the way.

**Comment by grimrod42** [comment]
ok thanks I will try some of your suggestions
thx for the details on the change

Pat

**Comment by tppinheiro** [comment]
Hello, I'm having the same problem (SAB and Sickbeard failing SSL verification). Any chances on getting the link to rollback to the previous version of python until the application maintainers fix the problem?

Thanks!

**Comment by Dr-Bean** [comment]
No, we won't be providing older versions of the Python package. If you want an older version of Python, please compile it yourself. See the README for the details.

The reason why was explained in my previous comment. The older version of Python _did not check_ for valid certificates. In other words, if you run into issues internally with Python 2.7.9-13 (so, issues connecting from Sickbeard to Sab or v.v.), you might as well just turn off SSL, because it didn't do much for you anyway. The current behavior of Python 2.7.9 is correct in that it disables access to applications with invalid certificates.

For external use of SSL, please take a look at using a reverse proxy such as HAProxy. That arguably does a better job of implementing SSL than the built-in capabilities of Sickbeard or other related packages.

Seeing as there's not much else to add, I'm going to close this issue.
