### ISSUE TITLE
New version of Domoticz?

### ISSUE THREAD

**Issue by czechmark** [SynoCommunity/spksrc#1620]
It would be greatly appreciated if a more recent version of Domoticz could be distributed.

Thanks tons,
  Mark

**Comment by wind-rider** [comment]
I think it is already committed, but not yet published..

See https://github.com/SynoCommunity/spksrc/pull/1604

**Comment by czechmark** [comment]
Darn.  I searched, but I guess the search matches full words not partials.  Sorry.  I will patiently wait for the publication.  Thanks

**Comment by gkroone** [comment]
I have made some local changes to the openzwave branch of decypher in order to compile the latest revision of Domoticz, but I am new to programming and github. I'd like some guidance on how to publish my changes as what I read on github manuals it states to always branch off the master repository, but I actually started off from the openzwave branch due to the changes in there needed to compile later revisions of domoticz. I mainly need the latest revisions for the RFLink functionalilty so I compiled my own. up to r2362 the openzwave branch needed almost no adjustments other than updating the revision numbers in the MakeFiles, and I now managed to compile r2383 with python adjustments, and also added a udev rule file to set permissions on /dev/ttyACM* to 666.
