### ISSUE TITLE
Debian chroot not starting

### ISSUE THREAD

**Issue by Dannermax** [SynoCommunity/spksrc#1626]
Hello.

I really want this package to work on my synology. I have installed python from synocommunity version 2.7.9-13 and when i install debian chroot 4.7-4 the package is listed as stopped. Is this normal? When i try to start the package, it tells me that it failed to start. I am running DSM v. 5.1-5022

Thanks in advance.

**Comment by cytec** [comment]
Debian needs an update because of some things changed in python: see https://github.com/SynoCommunity/spksrc/issues/1595

**Comment by davparker** [comment]
FYI,
I can't get to the point to install Debian chroot because Python 2.7.9-13 fails to install "unkown publisher", on a new DS713+ running DSM 5.1 update 4. Python and Debian chroot had both broken before, when I was on a DS213j, after upgrading to DSM 5.1 update4. I finally uninstalled them both, then tried again after the DS713+ arrived.

**Comment by Dannermax** [comment]
After python had been updated, i reinstalled Debian chroot, and it worked, just as it should! :)
