### ISSUE TITLE
Sabnzb continiously stops working

### ISSUE THREAD

**Issue by SurpremeNemwbie** [SynoCommunity/spksrc#1634]
I have sabnzb on my Synology NAS (213+) and it just stops working after a few minutes. It sstopped before, but very randomly and whenever selected 'RUN' via the package center it would work fine for long periods of time. But now it just got worse.

I use  DSM 5.1-5022 Update 4 and 0.7.20-13 of Sabnzb. Python version is 2.7.9-13.
The logs don't show anything for the last 4 days or so.
Status page gives no warnings.
As said, I have used Sabnzb on my NAS for a long time now and have set it up with categories etc. Would there be a way to reinstall that without losing these settings if needed?

I hope you can help.

Thanks!

**Comment by Dr-Bean** [comment]
Seeing you have random issues, and you are the only one reporting this, I'd suggest a clean install: remove the package, install the package (you might need to wait a bit before installing because the port might still be in use)

To prevent issues where your configuration actually causes the issues, maybe it's best to set those up again via the interface instead of restoring the old settings directly.
Anyway, to backup the old settings, create a backup of `/usr/local/sabnzbd/var` before uninstalling. The `config.ini` files contains your configuration obviously, but there might be more in that dir you want to keep around.

Last thing: Make sure the folders you use have read/write permissions for the `users` group.

**Comment by SurpremeNemwbie** [comment]
Thanks! Just made the backup and reinstalled sabnzb. Downloaded a test file of approx 10GB, no hangups. Same when checking and extracting.
All looks well. Will give it a another good go tonight and report back.

Thank you so far!
