### ISSUE TITLE
[Request] YunoHost

### ISSUE THREAD

**Issue by romu70** [SynoCommunity/spksrc#1639]
Don't if this is a big deal, but having YunoHost would be great.

**Comment by Dr-Bean** [comment]
Adding some more details on the subject would be great too: what, why, etc.. I assume you mean this: https://yunohost.org?

This link: https://yunohost.org/#/whatsyunohost tells me that YunoHost is a complete distro, forked/based off of Debian, comprised out of separate packages that are already available on DSM: NginX<>WebServer, Postfix+Amavis+Dovecot<>MailServer, Bind<>DNSServer, OpenLDAP<>Directory Server.

Wrong link, or am I missing something?

**Comment by romu70** [comment]
That's it. Yuno is a self hosting solution. The first and main package is a LDAP directory, and then, based on that module, they package a lot of open source software for different purposes. A bit like SynoCommunity does. The difference is all applications are packages to work integrated with the directory. And the list of packaged applications is pretty huge.

**Comment by Dr-Bean** [comment]
Because YunoHost is a complete distro, it's essentially a DSM replacement. As you mentioned, LDAP support is one of the their USP's. For software where that's not implemented, it looks like they add it in themselves by forking the upstream source and adding in an LDAP auth mechanism, and packaging the resulting code.

Most SynoCommunity packages don't support LDAP, simply because the upstream sources don't include it. A limited set (e.g. Horde, Owncloud and some others) do support LDAP, although it'll never be turned on by default.
Imo, adding LDAP support can best be done upstream. Maintaining forks for a load of packages to add in LDAP support is not going to be feasible for us.

**Comment by romu70** [comment]
I think there is some misunderstanding here. Let's say Yuno is integrated within SynoCommunity packages. Then, there is no need to integrate all applications Yuno supports, there are managed directly from the Yuno interface.

It's similar to what OwnCloud does. SynoCommunity doesn't manage all OwnCloud applications, just the core packages.

And Yuno is nothing more a web app, the provide an ISO because it's then easiest to install.

**Comment by Dr-Bean** [comment]
I think you're missing my point. The whole of YunoHost is a distro, not a single piece of software. One of their USPs is SSO (Single Sign On), provided by integration of LDAP (which in itself isn't unique, but that's beside the point).

Here are the actual installation scripts: https://github.com/YunoHost/install_script. You can see that it's far more then just a web app: it changes quite a lot on the system to prepare for the whole LDAP integration.
Then, as I explained above, they repackage upstream sources, add LDAP support where the sources don't provide it, and provide those packages along with the distro via an additional package source (this part here: https://github.com/YunoHost/install_script/blob/master/install_yunohostv2#L106). 
To provide access to those packages via SSO, they provide a slick looking frontend (which you call the web app): sign in once, have access to those packages.

Back to our Synology then, see what we can do: 
Hm. We won't be able to use the Yuno installation scripts, because those don't work on DSM (and if they did, it'd break quite a lot I imagine. I would't recommend it unless it's a test device)

Okay, maybe just use the Yuno web app and their packages then, and rewrite the scripts to work with Synology's Directory Service package? Well, we can't use their packages, because we need to cross-compile the software so that it works on a Synology device. That functionality is provided by the spksrc framework.

So, let's say we'd want to use their package sources instead of upstream (because those add LDAP support) and use that to cross-compile with spksrc? Nope: That would cause problems because when
Yuno added LDAP support, they broke non-LDAP usage (those packages are tailored specifically to Yuno's needs)
In addition, because they forked the software, we'd be relying on them to keep up-to-date with upstream.

Lastly, what about just using the Yuno webapp then? Well, then we're back to square one: most packages we provide don't provide LDAP support. Best place to get that added in is upstream, that's better than having to maintain our own fork.

**Comment by Dr-Bean** [comment]
Forgot to mention this: Owncloud is (just) one application that uses plugins to add functionality. That's distinctly different from using a frontend which provides access to different applications: it might look similar, but it's not the same :)

**Comment by romu70** [comment]
Yes you're right, I missed a lot of points here, thanks for the time you took to wrote all of these explanations, pretty kind.

Let's see if I manage to run it through Docker on my Syno, I'm not really successful for the time being.

**Comment by Dr-Bean** [comment]
You might want to try Debian-Chroot.

**Comment by cytec** [comment]
@romu70 i don't get whats the benefit from running it on a DS at all... all apps are already available as seperate SPK's :/

**Comment by romu70** [comment]
To me, benefits are obvious:
 - Yuno provides a LDAP ready core, this means you get a central users directory
 - All applications they provide have been tweaked to use this repository, so you get an easy single-sign-on feature
 - When I see the list of apps already included, and some to be (https://yunohost.org/#/apps_in_progress_en) I don't feel they are all provided as SPK's, and no SPK's chase, you just deal with Yuno.

**Comment by Dr-Bean** [comment]
The LDAP part only works as a means to provide the SSO functionality though. As far as I can tell, they don't add usermanagement to the applications they provide.
In other words, you can log in to Yuno's frontend with various accounts, and open Transmission, and you'll always end up in the same environment, with the same active torrents, same files, same settings.

As for the list of apps, you do realize a lot of those are forked/patched/maintained by people that want to have a certain application provided on the YunoHost platform, right?
You yourself might only see the YunoHost team, as they are the ones that accept an application and put it up on their repo, but that's not true at all...hey, where have I seen that before?

**Comment by romu70** [comment]
You've seen this before in some other places for sure, maybe even for SynoCommunity :-)

I'm deeping into self hosting for some time for my own purpose, and Yuno seems the be the most mature in my opinion. I've taken a look at OwnCloud, CozyCloud and Yuno.

I really think the first 2 chose the best path (building a framework for a complete hosting ecosystem) but right now, those ecosystems are far from being completes and stables. They miss some important applications a lot are buggy or not maintained, etc.

So the Yuno's approach, integrating mature apps into an core mainly made of a LDAP directory, seems pretty interesting, at least to me.

**Comment by cytec** [comment]
@romu70 yeah seems pretty intereseting if you are looking for a "one click" solution but still don't know what and why someone want to run in on a DS...

I get the SSO (which is/can be nice) but like @Dr-Bean said, most apps don't support this by default and you have to hope that they keep their fork in sync with upstream. I would prefer to ask upstream for LDAP support or open a PR and get it included so anyone can profit and you don't have to worry that you are stuck on an outdated version ;)

**Comment by Dr-Bean** [comment]
Again, you can't compare Owncloud and Cozycloud with Yuno. You're comparing one application (with _plugins_, even though Owncloud calls them Apps) with a distro: those are not mutually exclusive.  

Stability or maturity don't even come into play, because YunoHost are as dependent on their upstream sources as you are when you install an the same source directly on a Debian server (or on a Synology for that matter): literally the only difference is that Yuno adds an LDAP authentication mechanism to those sources, and even that has it's limitations as I mentioned previously.

My point is, yes, of course you should investigate, test, play around with all kinds of different setups and environments, as long as it's for the right reasons. In the end, you might end up with a different setup than a Synology, because the platform Synology chose closes off certain avenues, especially if you're not willing to put in the work yourself to change that.

**Comment by romu70** [comment]
@cytec : to be run on DS because I consider my syno as a mini-PC with raid capabilities. This may be not the best choice, but it's mine.

@Dr-Bean your points are comparison are true and wrong at the same time. On a pure technical point of view, you're 100% right, differences and philosophy of those projects make them incomparable. But if you turn yourself with just the end user point of view and think only in terms of features, they all follow the same goal : to offer a self hosting solution.

And we all have only 24 hrs days. Some can invest their time in such projects, some can't. That's life.

**Comment by Dr-Bean** [comment]
Well, that might be, but objectively, you need to compare YunoHost with DSM (either with just Synology's packages, or taking all the 3rd party packages into account)
Where YunoHost has a single focus on SSO, DSM has a different focus...whatever that is, because Synology's vision is probably different than SynoCommunity's.

**Comment by Dr-Bean** [comment]
Closing. To get this to work, either use Docker (if available) or Debian Chroot. Installing this directly on DSM is not going to be feasible.
