### ISSUE TITLE
Getting "Invalid location" for a DS512+

### ISSUE THREAD

**Issue by kcgthb** [SynoCommunity/spksrc#1651]
Hi,

I'm not sure if they're something wrong with the repo right now, but when I try to add "http://packages.synocommunity.com/" as the location for a new packages repository in DSM, I get an "Invalid location" error. It worked perfectly fine before, on the same NAS.

**Comment by Dr-Bean** [comment]
Got to be a local issue in your network or Synology device, because the repo is up and running. 
If it still doesn't work, restart the device and restart your router. 

If all else fails, try my instruction in the following comment: https://github.com/SynoCommunity/spksrc/issues/1476#issuecomment-73899963 (ignore the rest of that issue, that no longer applies)

**Comment by kcgthb** [comment]
Right, must have been a temporary blip in name resolution or something because it works fine again now.
Thanks!
