### ISSUE TITLE
What is the reason that PyYaml is a module?

### ISSUE THREAD

**Issue by wind-rider** [SynoCommunity/spksrc#1653]
I see that some months ago, PyYaml was converted by @Diaoul from a wheel to a module in e097f66.

I need PyYaml as a wheel or module in python3 for my package now (see #1654) - is there a specific reason that it was converted to a module?

The software that I'm trying to package is trying to reference it as a wheel in its requirements.txt.

**Comment by Diaoul** [comment]
The python package is multi purpose and  should be packaged with pre
compiled modules.
If you need it in your virtualenv, you can use --system-site-packages
option. Or package it as a wheel in a other directory like cross/pyyaml-whl
and use that.

**Comment by wind-rider** [comment]
Ok, clear. I packaged it in a separate folder as you proposed - see https://github.com/SynoCommunity/spksrc/compare/master...wind-rider:homeassistant.

I still have one Makefile that doesn't behave (see issue https://github.com/SynoCommunity/spksrc/issues/1654) but this issue about PyYaml can be closed.

**Comment by Dr-Bean** [comment]
Well, maybe it's me, but if there's already a PyYAML module you can use, why not use it? You can simply remove the reference to PyYAML from `WHEELS` (either by removing the entry itself, or by removing the reference in your requirements.txt, depending on the approach you use).

During installation, first, you create the virtualenv with the --system-site-packages argument, after which you install the wheels (see the various packages, it's the same approach all over)
When the application is installed, it should pick up the available system-site PyYAML module by itself because it's referenced in setup.py or whatever approach is used.

**Comment by wind-rider** [comment]
Yes, it's true that duplication is undesirable. However I hoped to keep the requirements.txt equal to upstream. That's why I decided to make a wheel out of it.

Is there any guideline when to package a module as a wheel and when not to do that?

**Comment by Dr-Bean** [comment]
Keeping the requirements.txt equal might be something to aim for, but not if it duplicates code in spksrc imo. I'd say keep it simple: if removing one reference in a requirements.txt makes more sense than adding a whole cross package, do that. 
The requirements.txt should fit your (our) environment, not the other way around :)

**Comment by wind-rider** [comment]
I see. To come back to the original question - I'm still wondering why the PyYaml wheel was converted to a module. Didn't it work well as a wheel? (I read something about it on https://github.com/SynoCommunity/spksrc/wiki/Using-wheels-to-distribute-Python-solutions but I don't know how up-to-date that page is)

**Comment by Dr-Bean** [comment]
Yes it did, it was in use for another package (search for it). But, if the module is used for multiple packages, ultimately, it makes sense to add it to the Python package. There are several reasons why that's preferred (up to a point): 
- Cross-compiling a wheel takes a long time, because it basically forces Python to be compiled for each package, for each arch.
- It takes up quite a lot of additional disk space (shouldn't be a concern, but still)
- If one package just needs one cross-compiled wheel/module, and can otherwise be converted to a pure-python package (so: noarch), then that would be an additional reason to add that module to the Python package.

On the other hand, there are good reasons to start off with a wheel first. The Python package shouldn't be a dumping ground when cross-compiling is needed for a module. Also, some packages use quite specific modules (e.g. the Mercurial module comes to mind), which won't be used by other packages: it's best to keep those self-contained in their own packages.

I probably will re-add some form of wheel caching back into spksrc when the spec has been updated. That should speed things up, because instead of having to rebuild the wheels each time you start compiling, it can grab it out of the cache after it has been built once.
