### ISSUE TITLE
Updating CouchPotato Server required package Git, no package Git available though

### ISSUE THREAD

**Issue by hagabla** [SynoCommunity/spksrc#1689]
When updating Couchpotato i get the following message:
"Please install the following package(s) before installing this package:
Git

Unfortunately there is no package Called "Git" in the repository.

**Comment by Dr-Bean** [comment]
Sure there is: https://synocommunity.com/package/git
If you're using the search bar in Package Center, then use the drop-down arrow to select `Community`. Otherwise, just select the `Community` link in the left menu and scroll down a bit.

If the Git package doesn't show up, try the `Refresh` button. Note that it's not instantaneous, so it might take a bit before packages show up.

**Comment by hagabla** [comment]
Thanks!
Using the search bar (all) does not work.(weird)
Found it as you described, all good now.

**Comment by Dr-Bean** [comment]
That `all` just means it searches all Synology packages, but it excludes third-party packages. You could report it to Synology, maybe it'll get fixed ;)
