### ISSUE TITLE
Python v2.7.9 for DSM 4.2

### ISSUE THREAD

**Issue by Amelandbor** [SynoCommunity/spksrc#1700]
Still on a DS409 here which won't get an update to DSM 5. Is it possible to get the newest Python for this? A lot of SSL errors in CP because of this older python version.

**Comment by cytec** [comment]
well if it's not in the repo you can always compile it yourself ;)

**Comment by Amelandbor** [comment]
Will see what I can do. Can I install it manually as an update then, so I won't have to uninstall the related packages?

**Comment by cytec** [comment]
yup should be no problem when you manually install it

**Comment by Diaoul** [comment]
I didn't upload DSM4.x versions of the Python package. Maybe we can do something about that. @Dr-Bean: didn't you publish those versions some time ago?

**Comment by Dr-Bean** [comment]
@Diaoul No, I noticed it, but didn't get to uploading. I might get to it in a couple days/weekend.

**Comment by Amelandbor** [comment]
@Dr-Bean any updates maybe?

I could build them myself, but I don't know if update ability is lost then? And can I build a package for 4.2 with the toolchain of 4.3?

**Comment by Dr-Bean** [comment]
Working on it (slowly ;)): Python 2.7.10 was released recently, so I'm updating the package and dependencies while I'm at it (also fyi @Diaoul).

If you want to build it yourself, you can still update to newer package versions. The 4.3 TC is backwards compatible, so no problems there either.

**Comment by Amelandbor** [comment]
Ok, thanks for the info. Learning every day :)

**Comment by Diaoul** [comment]
@Dr-Bean: you added uwsgi as wheel and updated dependencies as well? Try `make dependency-tree` in the SPK to print out all the dependencies of Python if you didn't know that already :)

**Comment by Dr-Bean** [comment]
Yep. Need to sort out a compile issue....must've made a typo when updating the patches, but I don't see it :/

**Comment by Dr-Bean** [comment]
Status update: checked and updated all deps. 25 updated packages, give or take.
Two things: 
- The newest version of `libgpg-error` fails on 4.3TC's, so I'm sticking with the current version for now.
- To upgrade pyOpenSSL to 0.15.1, we'll need some additional modules in the Python SPK. `pip install pyopenssl` returns this:
`cryptography>=0.7, idna, pyasn1, enum34, ipaddress, cffi>=0.8`

Some are available as pure-python wheels (or we'll probably be able to build them ourselves)
Strangely enough, `cffi` tries to download, build and fails due to missing a compiler, even though it should already be available. Not sure what that's about, but I'll continue the work tomorrow.

**Comment by Dr-Bean** [comment]
Updated Python to 2.7.10 with https://github.com/SynoCommunity/spksrc/commit/298ccfcb4eb374484e3366424223cc1d38d09ae8.
Building now...

**Comment by Amelandbor** [comment]
Thanks, build 2.7.9-13 yesterday and it's working, so let's see if update works as expected :)

**Comment by Dr-Bean** [comment]
Published Python 2.7.10-14.
I skipped `powerpc-4.0` and `ppc824x-4.2`. First fails on OpenSSL of all the things to fail on, second fails on uwsgi iirc...I didn't have the patience to figure that one out.

**Comment by Dr-Bean** [comment]
Should be solved, so I'm closing this one. @Amelandbor If you run into issues, you know where to find us ;)

**Comment by Amelandbor** [comment]
Updating worked, thanks again @Dr-Bean
