### ISSUE TITLE
Can't delete Firefox Sync Server 1.5

### ISSUE THREAD

**Issue by IntGen** [SynoCommunity/spksrc#1717]
How I can delete Firefox Sync Server 1.5?
When I try, I get Incorrect MySQL root password. And packet can't be deleted.
When I install Firefox Sync Server 1.5 I use blank password for MySQL. Because I don't know it.
P.S. Documents for Firefox Sync Server 1.5 incomplete. I don't see any materials how to install that package.

**Comment by Dr-Bean** [comment]
If your MySQL/MariaDB root password is blank, then simply don't fill in a password when the root password is asked. Works the same for installation and uninstallation of the package.
For security reasons, I would recommend setting a root password though. You can do that via the MariaDB link in the menu.

About the documents, can you explain what you're missing? The package basically works after the installation completes and the package has the status 'running', so unless you want to change more advanced options, there's nothing else you need to do.
You will need to change your Firefox client(s) to connect them to your sync server instead of the default Mozilla servers: we can't arrange that from the package.

**Comment by Diaoul** [comment]
Any updates @IntGen ?

**Comment by sebw** [comment]
I have the same problem. I'm not sure which Mysql are we talking about here? I don't have a Mysql instance on my Synology. When installing ffsync, it only complained about Python dep missing. I proceeded with the installation and let the password field blank. It proceeded and got installed successfully, but FF sync wasn't starting, because of connection refused to the (seemingly) non existant mysql.

I changed the configuration of ffsync manually to fall back to sqlite. It started and I could get stuff to sync.

I now want to uninstall and it keeps failing at the mysql password question. Simple, there is no mysql running on that NAS, so of course it fails.

**Comment by Dr-Bean** [comment]
@sebw You don't have MariaDB installed then? It's a Synology package. 
...I should probably add that to `SPK_DEPENDS` then (or include the somewhat buggy `CONF_DIR`)

**Comment by sebw** [comment]
Indeed @Dr-Bean I don't have any sql server running on my Syno. It didn't complain for the broken dependency, and this is why uninstall won't work without editing installer.sh.

**Comment by Diaoul** [comment]
@Dr-Bean: Is it possible to allow sqlite db in wizard? Maybe grey out the unavailable options (if MariaDB isn't installed)

**Comment by Dr-Bean** [comment]
@Diaoul I more or less tried that with FFsync 1.1, but I wasn't happy with it (aside from the fact that sqlite probably isn't supported in this version, but that's a detail).

The main issue is the install wizard doesn't have access to the system: you can't influence/adapt the install wizard before running the installer, other than via user input.
So, what you could do is add a radiobutton: `use sqlite` and `use mysql/mariadb`.
During PREINSTALL, rewrite INFO, write `PKG_DEPS`, maybe adapt the uninstall sequence and update or remove uninstall wizard to fit the used database.
I _think_ that writing PKG_DEPS during PREINSTALL still triggers that there's a dependency (assuming that PKG_DEPS itself is checked in INSTALL), but I need to confirm that.

**Comment by Dr-Bean** [comment]
Well, that last thing I mentioned doesn't work. `PKG_DEPS` is read during `install`, and that's a problem here:
You can't create a `PKG_DEPS` file during `preinstall`, because `/var/packages/{PACKAGE}` isn't created yet (assuming it's not read from the tmp dir), and if you write it during `postinstall`, it's too late.

So, it's either: 
- Not defining the dependency, which causes the issue that @sebw and presumably @IntGen ran into;
- Define the dependency upfront, as part of the package (meaning: define `support_conf_folder="yes"` in INFO, adding `/conf/PKG_DEPS` into the package, and specify the correct dependency in it.

**Comment by Diaoul** [comment]
Is there anything wrong using sqlite by default and not MySQL? How is the performance? The simpler the better I think.

**Comment by Dr-Bean** [comment]
Probably nothing wrong with it, although if that's a thing, why don't we challenge it for every package using a database? ;)
I don't have performance numbers though, but it obviously depends a lot on the amount of clients and accounts that sync. My installed base is too small to say anything worthwhile (currently using it in a home env, not a business env.)

**Comment by Diaoul** [comment]
Good point. Let's just choose a solution and stick with it :) Forget the configurable wizard.

**Comment by Dr-Bean** [comment]
Fixed with https://github.com/SynoCommunity/spksrc/commit/faf84898186f8d89cb4287b4368d2721d43f389e

Note that this does not fix a broken package (i.e. ffsync installed without MariaDB). People who ran into this should remove the old package and reinstall.
People who installed ffsync while MariaDB/MySQL was already installed won't notice any changes at all.

@IntGen: If you need help with uninstalling, let me know: it involves commenting out some code in `/var/packages/ffsync/scripts/installer`.
@sebw : if you prefer to run with sqlite, that's possible (unless upstream removes the option, but I don't think that's a risk on short/mid term. Apart from that, I think you just about figured out how to correct the issue yourself.

**Comment by Dr-Bean** [comment]
...and closing again. See previous issue.

**Comment by fritzo69** [comment]
since dsm 7 doesn't support anymore mariadb5 and ran out of patience, I used a very brutal method : 
1. sudo mkdir ffsync_delete
2. sudo mv ffsync ffsync_delete
3. sudo mkdir MariaDB_delete
4. sudo mv MariaDB MariaDB_delete

then DSM accepts to move on with the upgrade... I am not especially proud, but it it did the job :)
