### ISSUE TITLE
My Tweak - is this useful?

### ISSUE THREAD

**Issue by nineteenuk** [SynoCommunity/spksrc#1745]
Enjoying flexget on my synology DS214
One tweak I like to make and it's a little fiddly, is to direct the var folder to a shared folder (/volume1/homes/me/flexget), so that I can access the config.yml and log files from finder and windows explorer.
I also have to change the permissions for user flexget, but that's it.
- And I have to remember to back up the folder before any reinstall, as it vanishes!

Have I missed a trick here?

Tim

**Comment by Dr-Bean** [comment]
What do you mean exactly with `direct the var folder to a shared folder`?

**Comment by nineteenuk** [comment]
I replace the /var/packages/flexget/target/var folder with a symbolic link to my target folder

**Comment by Dr-Bean** [comment]
I can see why that would cause problems...Take a look at https://github.com/SynoCommunity/spksrc/blob/master/spk/flexget/src/installer.sh#L101-L118 to see what happens during a package upgrade.

Maybe a symlink from /usr/local/flexget/var to /any/path/ would work better, instead of actually moving the dir?

**Comment by nineteenuk** [comment]
OK, so symlink from /usr/local/flexget/var instead of symlink from /var/packages/flexget/target/var
I think I tried that (no notes) without success.
I'll try again sometime

**Comment by Dr-Bean** [comment]
`var/packages/package/target` and `/usr/local/package` point to the same location, that's not the point ;) 

What I was trying to say: leave the package data intact. Don't move it around, that will only cause issues similar to what you're seeing, or worse: you might lose your configuration if something isn't setup correctly.
Instead of moving the package data, create a symlink _to_ the package data, in a location you can access. You might run into permissions issues with that too (probably on every package upgrade), but then again, it's not a supported configuration either way.

**Comment by nineteenuk** [comment]
Yes, I've tried that too. If I create a symlink in one of the shared
folders, it does not behave as a symlink in finder (I don't think i checked
it from windows explorer).
As I say, it works well enough for me to edit the config.yml (series,
schedules etc) and check the flexget.log files without phaffing around with
terminal, putty or winscp. Of course what I really need is a web interface
;-)

**Comment by Dr-Bean** [comment]
As I said, it's not a supported configuration either way. Best bet is to stick with CLI (or WinSCP/equivalent if you prefer GUI), but that's up to you. If you're okay with your current approach, with the shortcomings and risks, sure.

As for the web interface: that's a subject for the Flexget bug tracker. There's nothing we can do about that from here.

**Comment by nineteenuk** [comment]
It really isn't a problem. I've been using  older versions of flexget for
many years now, and moved to this installation a few months ago for the
improved scheduling.

Keep up the good work.
