### ISSUE TITLE
[Request] Package for OpenFire

### ISSUE THREAD

**Issue by Zorgonaute84** [SynoCommunity/spksrc#1788]
Hello,

At the beginning of the year, MissileHunger decided to shut down their repository. Unfortunetly, it looks to be the only repository with OpenFire. Do you think it's possible to add OpenFire to the SynoCommunity repo ?

OpenFire website : http://www.igniterealtime.org/projects/openfire/

Thanks and have a nice day.
##

**Comment by nurtext** [comment]
Why not use ejabberd from SynoCommunity? MissileHunger strongly depends on Java VM and as we all know, Java isn't the fastest piece of software, at least not on this planet. So dump all the Java stuff and be happy with ejabberd. Btw: Running Java-based applications on low powered machines like NAS devices isn't recommended ;)

**Comment by cytec** [comment]
afaik there is a (old) Package for ejabberd...

**Comment by sebionofrei** [comment]
Hello guys,

I am also very sad that openfire is down. Indeed Java is not the fastest of technologies, but for my family it is important, especially because I'm using it for about 3 years now, lots of logs are already in the system, settings, etc :)

Doesn't anyone have contacts or something with missilehuger so to get the sourcecode for the SPK make tool, so we could make the updates easier?

Regards.
