### ISSUE TITLE
ruTorrent  - AutoTools not adding .torrent files [$20]

### ISSUE THREAD

**Issue by Pyronious** [SynoCommunity/spksrc#1805]
I've been running ruTorrent/Autotools on my Synology DS1512+ for a few years now. Normally I install it using the steps described at http://forum.synology.com/wiki/index.php/RTorrent_ruTorrent_HowTo. Unfortunately with the most recent DSM update, the steps to compile XMLRPC-C are failing, so I had to go looking for another solution, which led me here.

I installed the package from the community package center and ruTorrent is working fine. However, the AutoTools plugin is not picking up torrent files in the watch folders like it normally does.

So far my troubleshooting steps have included:
- Re-synced plugins folder from GoogleCode to make sure I have the latest version
- Set permissions on ruTorrent folder to be very liberal (777)
- Disabled the standard rTorrent watch folder
- Enabled autodebug_enable in AutoTools conf.php to generate log files. However it doesn't ever seem to produce a log file (looked for /tmp/errors.log and searched elsewhere)
- Set register_argc_argv = On in /etc/php/php.ini
- Other plugins are installed and working fine
- Tried un-installing and re-installing the ruTorrent package

Any thoughts / ideas / suggestions? I'm totally stuck at this point.

Thanks!
##

**Comment by OBenned** [comment]
I had the same issue, i also tried CHMOD 777 but in some weird way it started working when i set it to 755 and after a restart of the synology box i was a happy panda

**Comment by Pyronious** [comment]
Yeah, I ended up at 755 as well for my ruTorrent folder. Unfortunately even at 755 my watch folders aren't working. Maybe there are other directories I need to check the permissions on?

**Comment by A----** [comment]
It might not be related to your issue _at all_ since we're now one year later.

Anyway, to anyone which might have the same issue and read this:
* check the user/group rights: meaning you should be able to do `sudo -u rutorrent /volume/to/your/torrents/and/data` and `sudo -u http /volume/to/your/torrents/and/data`. Change the rights in the control panel accordingly if necessary
* also, there's a 5 min delay before rutorrent starts picking up anything new. This delay can be changed in `/usr/local/rutorrent/plugins/autotools/conf.php` but I guess that it'll be overridden when the package is upgraded (contrary to the `var/.rtorrent.rc` which has a preupdate backup mechanism)

**Comment by Safihre** [comment]
Updates (like proper DSM6 support) will be handled in #2215 and maybe PR #3175.
