### ISSUE TITLE
[FFSYNC] Failed to launch package repair

### ISSUE THREAD

**Issue by lennvilardi** [SynoCommunity/spksrc#1840]
Hello,
I tried unsucessfully to install FFSYNC 1.5.
Maria DB is installed. The root password is fine.
But when I tried to launch FFSYNC it always come with a message error : failed to launch package repair (reparation ?)

![2015-09-12 13_13_27-synology diskstation - midgard](https://cloud.githubusercontent.com/assets/10863269/9831273/2c21cc96-5950-11e5-9e57-9a38bc8e83d5.png)

**Comment by lennvilardi** [comment]
I finally find what was missing : the python package.

**Comment by lennvilardi** [comment]
I have no more error messages but the status show running only a few second and then show stop :(

**Comment by Dr-Bean** [comment]
Python is indeed a requirement, but Package Center doesn't recognize it as such (because CONF, when used, overrides `install_dep_packages`. CONF currently contains MariaDB, but not Python)

As for the issue with the AtttibuteError, that's because the package is already running. 
For some reason, Package Center tries to run it again, or so it seems. There's no obvious reason that should happen, so I'll need to look into that.

If you're okay with command line, you should be able to look up the process with `ps -w | grep ffsync`, and kill the process that pops up with `kill <processid>`. A reboot of the device might work too.
After that, you should be able to stop/start it correctly via Package Center.

**Comment by Dr-Bean** [comment]
Should both be fixed with https://github.com/SynoCommunity/spksrc/commit/00ade09e9b4526f3966f82f75e75245fb8126c0c. Fresh packages will be published soon.

**Comment by Dr-Bean** [comment]
Ffsync_1.5.2-3 has been published on the repo. That should solve the issues you ran into.

**Comment by lennvilardi** [comment]
Thanks Dr-Bean, late days were very busy.
I will try your package when I came back at home in 2 weeks.

**Comment by lennvilardi** [comment]
Thanks Dr-Bean it finally works tricking the host file because my box doesn't provide loopback.
I was very surprise that I've to create an account on Firefox servers to use ffsync.
Is there a way to backup ffsync, I mean where the files are stored on the synology ?

**Comment by Dr-Bean** [comment]
I'd use a DNS server, but a hosts file entry should do the job too ;)

Yes, you do need to create an account on Mozilla's servers. The accountname, password and a hashed sync key are the only items stored on Mozilla's servers. The important stuff is stored on the NAS.

The data is stored in a MariaDB database. You can create a backup of the database via e.g. mysqldump or use phpMyAdmin.
