### ISSUE TITLE
[Enhancement] Darkstat selection of network interface

### ISSUE THREAD

**Issue by MMD70** [SynoCommunity/spksrc#1850]
https://github.com/SynoCommunity/spksrc/issues/770

Many thanks in advance :-)

**Comment by Dr-Bean** [comment]
Seems the following patch works, as discussed [here](http://www.synology-forum.nl/3rd-party-packages/darkstat-laat-geen-grafieken-zien/). It chooses the default interface, so people running two/more interfaces in bond don't have to change the start-stop script.

People who want to use a different interface than that will have to continue to do so manually, because there's no appropriate way to select an interface (other than a GUI, and I'm not adding one for this package)

@MMD70 Does this cover your request?
```
--- /spksrc/spk/darkstat/src/dsm-control.sh.org
+++ /spksrc/spk/darkstat/src/dsm-control.sh
@@ -11,9 +11,11 @@
 DARKSTAT="${INSTALL_DIR}/sbin/darkstat"
 PID_FILE="${INSTALL_DIR}/var/darkstat.pid"
 
+PORT=`ip r | awk '/^default/{print $5}'`
+
 start_daemon ()
 {
-    su ${USER} -c "PATH=${PATH} ${DARKSTAT} -i eth0 --chroot ${INSTALL_DIR}/var --pidfile darkstat.pid --import darkstat.data --export darkstat.data"
+    su ${USER} -c "PATH=${PATH} ${DARKSTAT} -i ${PORT} --chroot ${INSTALL_DIR}/var --pidfile darkstat.pid --import darkstat.data --export darkstat.data"
 }
 
 stop_daemon ()
```

**Comment by MMD70** [comment]
Yes it did/does :-)
Thanks

**Comment by Dr-Bean** [comment]
Done with 5835fe2f772ba3038bf299a8d9fdc66e04c1cabc

**Comment by Dr-Bean** [comment]
Darkstat-3.0.719-4 has been published on the repository.
