### ISSUE TITLE
[Request] Teleinfo to Mqtt [$5]

### ISSUE THREAD

**Issue by CondormanFr** [SynoCommunity/spksrc#1862]
I'm looking some help to add a very small C program in the cross folder of spksrc.

The program allows to listen serial port for Teleinfo data (Teleinformation is a protocol used by a French power provider ) and send the data to a MQTT broker.
This program is available on Github here : 

https://github.com/destroyedlolo/TeleInfod

On the Github page, the author gives the way to compil. It seems very simple :

gcc -std=c99 -DUSE_MOSQUITTO -lpthread -lmosquitto -Wall TeleInfod.c -o TeleInfod

There is a dependencies with mosquitto  and mosquitto is already working on spksrc...

I have no skill  with C compilation and spksrc repository rules too. I don't undestand exactly what I have to put in the make file to get the Teleinfod source project and compil it correctly.

But if the program does compil in cross folder, then I think I will be able to create the spk part of this projet.

I think the folder projet name could be "TeleinfoMqtt".

Thanks for the Help.

**Comment by Dr-Bean** [comment]
This is how I'd go about it. Completely untested:
- Add a cross package for `Teleinfod`. You might want to start from another [cross package which uses a Git download method](https://github.com/SynoCommunity/spksrc/blob/master/cross/gateone/Makefile), because it doesn't look like there are source tarballs available for Teleinfod.
- Add `cross/mosquitto` to the DEPENDS.
- To compile the project, override `CONFIGURE_TARGET` like [this](https://github.com/SynoCommunity/spksrc/blob/master/cross/gateone/Makefile#L15`) and probably the same with `INSTALL_TARGET` (at least for now, because you only want a cross package)
- Then, override the compile target by setting `COMPILE_TARGET = myCompile`, similar to [this](https://github.com/SynoCommunity/spksrc/blob/master/cross/gateone/Makefile#L17), and add a `.PHONY: myCompile` target. The content should be `$(RUN) $(MAKE) -std=c99 -DUSE_MOSQUITTO -lpthread -lmosquitto -Wall TeleInfod.c -o TeleInfod`

**Comment by CondormanFr** [comment]
Thanks to give me some hints.
I created a new Makefile (https://github.com/CondormanFr/spksrc/blob/teleinfomqtt/cross/teleinfomqtt/Makefile)

Downloads and compilation of dependencie works but process failed on trying to compil my .C file 

![compil](https://cloud.githubusercontent.com/assets/2799574/10371109/07eb9432-6de2-11e5-8aac-3fe849547f99.png)

How to set properly the compil params ?

**Comment by CondormanFr** [comment]
It look likes that a Makefile is missing...

**Comment by destroyedlolo** [comment]
Hi all,

1/ If it can help, I'll create a tarball this evening : please confirm :)

2/ I may also create a Makefile, but as per the comment above, I'm quite sure you'll have to customize it to suite you're packaging system.
I think the better this is to continue with your own make file : the compilation is failing only because you're launching the compilation with **make** instead of **cc**.
Then I would suggest to modify your myconfig target
```
$(RUN) ~~~$(MAKE)~~~~ -std=c99 -DUSE_MOSQUITTO -lpthread -lmosquitto -Wall TeleInfod.c -o TeleInfod
```
as
```
$(RUN) **$(CC)** -std=c99 -DUSE_MOSQUITTO -lpthread -lmosquitto -Wall TeleInfod.c -o TeleInfod
```
Bye

**Comment by Dr-Bean** [comment]
Typo on my part, of course I meant $(CC). However, I actually tested it now, and there are some other changes needed. The following should produce a working binary (although note that some paths etc on the target device might need work, e.g. location of .conf needs changing).
```
$(RUN) $(TC_PATH)$(TC_PREFIX)gcc -I$(STAGING_INSTALL_PREFIX)/include \
          -std=c99 -DUSE_MOSQUITTO -Wall TeleInfod.c -o TeleInfod \
          -L$(STAGING_INSTALL_PREFIX)/lib -Wl,--rpath-link,$(STAGING_INSTALL_PREFIX)/lib \
          -Wl,--rpath,/usr/local/lib -lpthread -lmosquitto
```
@destroyedlolo Thanks for the comment. You might want to take a look at this line: https://github.com/destroyedlolo/TeleInfod/blob/master/TeleInfod.c#L520. I believe `mosquitto_destatexitroy(cfg.mosq);` should be changed to `mosquitto_destroy(cfg.mosq);`.

As an aside, I don't know that this will be included in spksrc. It has a very specific target audience from what I can see, but correct me if I'm wrong.

**Comment by CondormanFr** [comment]
Thanks @Dr-Bean !
With your last post, I successfully build the daemon. I will now try to make it working and finalize the process to build the spk.

Teleinformation data can be used is France and many people playing with Home Automation loves to get this Data. Thru the MQTT protocol, it's very easy to get the data for OpenHAB, domoticz software...  (present on spksrc)
If it is not included in spksrc, I think I will try to share it with my own copy of spkrepo.

But the syntax for the Makefile you gave (with $(RUN) $(TC_PATH)$(TC_PREFIX)gcc ....) can help people in the same case in the future. (I tried to look by my own at the other Makefile but I didn't find the answer myself)

I think, you can get the bounty !

**Comment by destroyedlolo** [comment]
@Dr-Bean 
Yes, you're correct : a bad copy/past :)
I'll correct tonight.

@CondormanFr : cool to see you've been able to compile it :)
Don't hesitate to tell me if you made some improvement (for example, to support more contract, as said, I've focused on my own as I don't have others' frames to tests with).

**Comment by destroyedlolo** [comment]
The source code is corrected :)

**Comment by Dr-Bean** [comment]
@CondormanFr I assume this can be closed? Feel free to open a PR with your changes, in case it can be merged after all (maybe @Diaoul has a different opinion than me, or maybe I can change my mind)

**Comment by CondormanFr** [comment]
Yes, it can be close. I 'm waiting some enhancement from @destroyedlolo to open the PR.
