### ISSUE TITLE
DS216play/Monaco support

### ISSUE THREAD

**Issue by Emptaze** [SynoCommunity/spksrc#1876]
After installing a new Synology (DS216play) I tried to add the location of the database (http://packages.synocommunity.com/) but it came up as invalid location.

**Comment by funnybutrandom** [comment]
I am getting the same issue (on the same device) I'm wondering if the server has had issues with DSM6.0 coming out today as well?

**Comment by piwi82** [comment]
The DS216play uses a new architecture (monaco).
No package will be provided as Synology has not released the toolchains.

**Comment by funnybutrandom** [comment]
Ah ok, thanks for letting us know

**Comment by Yanouch** [comment]
God this is bad news.... just installed my new DS216 and can't even install a single program on it, not even Sabnzdb... my NAS is useless ! :'(

**Comment by Emptaze** [comment]
Yeah, I am awaiting the packages eagerly as well! Want to use Sonarr badly. Just have to wait.

**Comment by Yanouch** [comment]
Still not working for me... rebooted my NAS but no difference... Do i have to make something special ?

**Comment by Diaoul** [comment]
I added the architecture to the repository so you can add it. However you won't see any arch-specific packages until we have a toolchain.

**Comment by PoloSwelsen** [comment]
I still can't install any package like SickRage or CouchPotato. When I press the 'Install' button, it does nothing.

**Comment by funnybutrandom** [comment]
You won't be able to until the tool chain is released

**Comment by Yanouch** [comment]
Will there be an update on this thread when the toolchain will be available ?

Thanks

**Comment by funnybutrandom** [comment]
Dsm 6 for ds216play is coming out in January, so plan to wait a while

**Comment by Dr-Bean** [comment]
The Monaco toolchain and kernel have been released yesterday. Both seem to work as intended with a quick check, so things are coming along.

@Diaoul, @piwi82 Just to be sure, can you confirm we won't run into issues with disk space on the repo? ;)

**Comment by Emptaze** [comment]
Does this mean we might get the packages prior to DSM6.0?

**Comment by sandeman684** [comment]
I can now see a bunch of packages in my DSM 5 on the ds216play, but they don't install (nothing happens when pressing the install button).

**Comment by Emptaze** [comment]
This has been the case for a while. No installing yet (except for Full Text RSS or whatever it's called).

**Comment by PoloSwelsen** [comment]
So when can we expect Phyton to run on the ds216play? :smiley:

**Comment by Dr-Bean** [comment]
All packages should be available. If you haven't done so already, follow these instructions to add the SynoCommunity repository to Package Center: https://synocommunity.com/#easy-install 

Take a look, let us know if you run into issues. If you get a `Failed to download` error, that is probably caused by a higher server load than usual. Please retry at a later time.

If you experience problems with running packages, please report them in a separate issue, not in here. Use [this link to open a new issue](https://github.com/SynoCommunity/spksrc/issues/new).
In the issue, tell us what you did up to that point, what you expected to happen, and what actually happened. Provide logging if available.

Have fun ;)
