### ISSUE TITLE
[request] Plex Requests

### ISSUE THREAD

**Issue by G1zm0** [SynoCommunity/spksrc#1881]
Website: http://plexrequests.8bits.ca/
Prerequisites: 
- Meteor https://www.meteor.com/ 
- Node.js
- npm
- MongoDB
- .....

Build method: https://github.com/meteor/meteor#slow-start-for-developers
Sourcecode: https://github.com/lokenx/plexrequests
License: MIT license

------copy/paste from website-------
Simple automated way for users to request new content for Plex

Are people constantly asking you to add new content to your Plex Server? Frequent late night texts asking for a new release that's not out yet? Wouldn't it be easier to just send them to a website where they could submit their requests? Enter Plex Requests!

Features:
Users can easily search the TheMovieDB for content to request
Easily accessible list of requested movies and TV series
Simple and easy user authentication lets only those you want in
Couch Potato integration for automatic downloads of movies
SickRage and Sonarr integrationed for automatic TV Series downloads
PushBullet or PushOver notifications to keep up to date with requests

---end copy/paste from website ----

This integrates nice with CP/Sonarr/SickBeard/Sickrage
also nice for Emby
##

**Comment by baz1860** [comment]
As a heads up, the Django version of this app linked to has already basically been deprecated by the author; he's moved over to a meteor deployment for current/future releases. For any future upgrade path (i.e. when things break because of PMS upgrades), the source code would have to be 'de-meteorised' before it could be packaged on Synology.

Its not that its a bad idea, in fact, it looks like quite a good (if niche) app - but its going to be a PITA to support in the long-term.

**Comment by G1zm0** [comment]
Opened a new Package Request [2601](https://github.com/SynoCommunity/spksrc/issues/2601l)
