### ISSUE TITLE
Sickbeard-custom - sc-media

### ISSUE THREAD

**Issue by Martijn085** [SynoCommunity/spksrc#1893]
The sickbeard-custom package does not add the sickbeard-custom user to the sc-media group.
##

**Comment by Dr-Bean** [comment]
The package hasn't been updated with those changes (yet, I guess. Should be done at some point).
Use the `users` group in the mean time.

**Comment by Martijn085** [comment]
You can also edit the file "/etc/groups" and add the sickbeard-custom user to the sc-media group.

**Comment by Dr-Bean** [comment]
Might as well provide a current status list. Starting off from here: https://github.com/SynoCommunity/spksrc/pull/1649:

### sc-media:

couchpotatoserver
couchpotatoserver-custom
~~flexget~~
~~headphones~~
~~headphones-custom~~
lazylibrarian (unmaintained)
sickbeard (unmaintained)
sickbeard-custom
~~sonarr~~

### sc-download:

deluge
~~nzbget~~
~~nzbget-testing~~
~~pyload~~
transmission
sabnzb
~~sabnzbd-testing~~
rutorrent

**Comment by Dr-Bean** [comment]
@Martijn085 The Sickbeard-Custom package has been updated, and should now work with the `sc-media` group.

Just a couple more packages to go...

**Comment by Martijn085** [comment]
Thank you @Dr-Bean

**Comment by KaHooli** [comment]
Just came across this, as I've been trying to work out why CP didn't have permission to rename/move a file with this CP package installed under DSM 5.2.
The fix is 
1. SSH using root on DSM 5.2.
2. vi /etc/group
3. Add couchpotatoserver to the end of the sc-media line
4. save & quit vi
5. reboot server
and then everything worked perfectly, as sc-media group had rw access to the folder :grinning:

**Comment by Safihre** [comment]
Closing due to age. Test-packages for DSM6.1 and new architectures available here: #3138.
Those will later be published to the real package rep.
In these new packages all users for download packages and download-related packages will be transitioned to `sc-download`. There will be backwards compatibility with `sc-media`.
