### ISSUE TITLE
Problems with SABnzbd

### ISSUE THREAD

**Issue by ihaveworms** [SynoCommunity/spksrc#1895]
I am having some issues with installing and running SABnzbd on my DS1515+. I just got this NAS yesterday and have been working on installing sabnzbd on it. When I intially tried installing it, it would fail saying it could not create the directory for downloads during the installation step. After manually creating this directory and then setting the path to that, the installation finished.

But I am getting lots of errors with it being unable to create the complete and incomplete folder. I manually created and changed the ownership to these folders as 'user' and gave it full access with all permissions. But it still is failing.

I am not sure what the problem is. This is running on DSM 5.2-5592
 
For example, this is the kind of lines I am seeing in the sabnzbd log.

2015-10-24 17:16:01,175	ERROR:	Cannot create directory /volume1/Media/usenet/incomplete

But if I look at this folder's permissions, it looks to be fine:
<img width="421" alt="capture" src="https://cloud.githubusercontent.com/assets/15304822/10713451/cf772342-7a8d-11e5-8cdd-da42615f002e.PNG">

Also, my folder isn't being listed in the folder settings within sabnzbd
<img width="493" alt="capture2" src="https://cloud.githubusercontent.com/assets/15304822/10713447/a8e40b5a-7a8d-11e5-8a9c-e0d2faa6bde6.PNG">

**Comment by ihaveworms** [comment]
I went to the control panel->groups and selected user and went to the permission tab. There I set read/write to the shared folder and now sabnzbd appears to be seeing the folder correctly.

Now my question is, why is it that I had to check this r/w checkbox for the share when I expicitly set these permissions on the downloads folder within the share?

**Comment by Dr-Bean** [comment]
That's _because_ you explicitly set the permissions on the downloads folder within the shared folder ;)
Permissions only apply top-down, not bottom-up. You can't set permissions on parent dirs, only on child dirs (optionally, with a recursive switch). All operating systems work that way.

For the record, `Traverse folders/execute` permissions on the shared folder is technically sufficient. However, you're probably setting permissions for the `users` group, and because every user on the NAS is a member of that group, just `traverse/execute` may not be enough.

**Comment by ihaveworms** [comment]
So you are saying you must have permissions on a parent level before you can have permissions on a child level?

If so, why when I do the permission inspector for 'user', it has several of those permissions? I would think the permission inspector would show what derived permissions a group would have.

**Comment by Dr-Bean** [comment]
> So you are saying you must have permissions on a parent level before you can have permissions on a child level?

I'm assuming you mean that a user must have _access_, not _permissions_? If not, please rephrase your question.
The answer is: it depends. If a user needs to traverse directories to get to a certain child dir, then yes, you need to allow traverse directories for that user. Otherwise, you don't. In this case, it's necessary...as you've seen already ;)

>If so, why when I do the permission inspector for 'user', it has several of those permissions? I would think the permission inspector would show what derived permissions a group would have.

Again, not sure what you mean here. Permissions themselves are either inherited from a parent dir, or they are set directly on the dir/file. You can set permissions for users or groups.
If you are checking the permissions for a specific user, the permissions inspector will show the combined permissions for that user, which includes the groups the user is member of.
If I'm misunderstanding what you're asking, please explain in more detail.
