### ISSUE TITLE
NZBGet won't install on DSM6 beta

### ISSUE THREAD

**Issue by HellDiverUK** [SynoCommunity/spksrc#1897]
Hi folks.

DS1815+, brand new install of DSM 6b.  

Went to install the usual apps, and NZBGet won't install.  I get the error "Failed to run the package service".  Logs are pretty useless as far as I can see:

Information
System
2015/10/26 10:06:08
Administrator
Package [NZBGet] has been successfully installed.

Also, there doesn't seem to be s shortcut generated for Sonarr on the "Start menu" in DSM - Sonarr works fine otherwise.

**Comment by Dr-Bean** [comment]
Missing shortcut: check Application Privileges. Seems you're not logged in as admin, so you have to tell DSM to show the shortcut.

As for your NZBGet problem, you probably mean: it doesn't _start_, correct? Are you running with btrfs as file system? See https://github.com/SynoCommunity/spksrc/issues/1880 then, that may have some information. In any case, try to start nzbget manually, and provide the output you get:
```
su nzbget -c "PATH=/usr/local/nzbget/bin:${PATH} /usr/local/nzbget/bin/nzbget -c /usr/local/nzbget/var/nzbget.conf -D"
```

**Comment by HellDiverUK** [comment]
Of course, logged in with the wrong user, got it, thanks.  No appearing OK when logged in as admin.

Ran NZBGet command as suggested and got: 
"su: user nzbget does not exist"

So, created a nzbget user, assigned it to the sc-download group, reinstalled and everything is working!

Thanks, I think you can close this problem. :+1:

**Comment by Dr-Bean** [comment]
Hm. I guess you can expect weird behavior with beta's :) We'll take a further look at it when DSM6 is a bit more mature.

**Comment by talisto** [comment]
I got Transmission working on a fresh install of DSM 6.0b.  Here's how I did it.

First of all, the installation of the package didn't create a Transmission user account.  I'm not sure if that is supposed to happen as part of the installer or not.  Regardless, I created a "transmission" user through the control panel.

Once the user was created, I SSHed into the NAS as root, and attempted to run the startup script manually, like so:

```
/var/packages/transmission/scripts/start-stop-status start
```

Then I got this error:

```
Starting Transmission ...
su: failed to execute /sbin/nologin: No such file or directory
```

The default shell for new users is `/sbin/nologin`, and running `su transmission` in the startup script initiates that shell in this line:

```
su ${USER} -c "PATH=${PATH} ${TRANSMISSION} -g ${INSTALL_DIR}/var/ -x ${PID_FILE}"
```

...so I took a hint from the Plex startup script and changed it to this:

```
su ${USER} -s /bin/sh -c "PATH=${PATH} ${TRANSMISSION} -g ${INSTALL_DIR}/var/ -x ${PID_FILE}"
```

...which forces it to use the GNU shell instead of `/sbin/nologin`. 

Once I fixed the startup script, Transmission would run, but the Package Center wouldn't recognize it as running, and the `/var/log/messages` had a bunch of entries like this:

```
transmission-daemon[26813]: Couldn't save temporary file "/volume1/@appstore/transmission/var/settings.json.tmp.JGPvF5": Permission denied (variant.c:1227)
transmission-daemon[26813]: Unable to save pidfile "/usr/local/transmission/var/transmission.pid": Permission denied (daemon.c:573)
transmission-daemon[26386]: Couldn't save temporary file "/volume1/@appstore/transmission/var/settings.json.tmp.R8ioFW": Permission denied (variant.c:1227)
transmission-daemon[26813]: Couldn't save temporary file "/volume1/@appstore/transmission/var/settings.json.tmp.yEqk96": Permission denied (variant.c:1227)
transmission-daemon[27357]: Couldn't create "/usr/local/transmission/var//resume": Permission denied (utils.c:424)
transmission-daemon[27357]: Couldn't create "/usr/local/transmission/var//torrents": Permission denied (utils.c:424)
transmission-daemon[27357]: Couldn't create "/usr/local/transmission/var//blocklists": Permission denied (utils.c:424)
```

so I then chowned the transmission directory to the 'transmission' user, like so:

```
chown -hRL transmission /usr/local/transmission
```

..and then Transmission fired up just fine from the Package Center and everything works great.  I used the exact same method to fix SABnzbd as well.

I hope that helps!

**Comment by GroteVriendelijkeReus** [comment]
For anyone puzzling, why NZBget doesnt start, after installing it
> su nzbget -c "PATH=/usr/local/nzbget/bin:${PATH} /usr/local/nzbget/bin/nzbget -c /usr/local/nzbget/var/nzbget.conf -D"
With the error :   **su: permission denied**

This is the error i received and finally after checking numerous logfiles and config files, i noticed, the nzbget user isn't inserted in the /etc/shadow file. 
After inserting this, the script works and all starts well. 
I hope this helps others.
