### ISSUE TITLE
Help me. I don't know how to install Flexget plugin.

### ISSUE THREAD

**Issue by iruyanka** [SynoCommunity/spksrc#1917]
https://github.com/Flexget/Flexget/pull/628
https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/output/send_telegram.py

I want to install send_telegram Plugin in Flexget.

Please tell me know-how. Thanks.
##

**Comment by Dr-Bean** [comment]
You need to update Flexget, maybe you need to fix a couple of issues with the new version. Then follow the instructions that the Flexget devs provide you with to use the plugin.

**Comment by iruyanka** [comment]
Oh.
Need to update Flexget? Can I update Flexget?
I'm using SynoCommunity version 20150606-5. How to update?

**Comment by Mirgolth** [comment]
You are not the only one interested in upgrading the Flexget version from the Synocommunity package.

**Comment by Dr-Bean** [comment]
Closing. Flexget was updated via https://github.com/SynoCommunity/spksrc/issues/2551 and https://github.com/SynoCommunity/spksrc/pull/2626.

For future reference: while `/usr/local/flexget/env/bin/pip install --upgrade flexget` probably works, doing that means you're no longer using the SynoCommunity package. We can't provide support for that, because we can't check or control what has happened on your system.
