### ISSUE TITLE
Deluge package

### ISSUE THREAD

**Issue by akafester** [SynoCommunity/spksrc#1922]
The package doesn't seem to include the normal plugins? 
I have tried to reinstall the package.

**Comment by Dr-Bean** [comment]
Right, my bad I guess. Since I'm not a user of Deluge, I didn't notice the built-in plugins were missing.
I'll set up a fix tomorrow. Not sure when the packages will be updated though, those take a while to build.

To make sure I don't forget, here's the gist of it. L79 in the installer:
```
PYTHON_EGG_CACHE=${INSTALL_DIR}/env/cache && cd ${INSTALL_DIR}/share/deluge/ && ${INSTALL_DIR}/env/bin/python setup.py build && ${INSTALL_DIR}/env/bin/python setup.py install
```
export the same env var in start-stop-status, and export it in `start_daemon()`
`PYTHON_EGG_CACHE=${INSTALL_DIR}/env/cache`

**Comment by Dr-Bean** [comment]
Fixed with https://github.com/SynoCommunity/spksrc/commit/fe93108c00dd89a2b645b8121420189e79ae4b97.
deluge 1.3.12-3 has been published on the repository.

Thanks for reporting :)
