### ISSUE TITLE
packages.synocommunity.com is down ?

### ISSUE THREAD

**Issue by quentinus95** [SynoCommunity/spksrc#1957]
Hi !

I can't add http://packages.synocommunity.com on my DS (incorrect location).

Is the service down ?

Thanks !

**Comment by Dr-Bean** [comment]
The repo isn't down, although the service may have been unavailable just as you were trying. 
Other causes could be that your model is not supported yet (DS716+? See https://github.com/SynoCommunity/spksrc/issues/1944) or you have a DNS issue (see https://github.com/SynoCommunity/spksrc/issues/1538).

 @Diaoul The service returns a 502 every once in a while (Just about twenty occurrences since this morning, with a duration of 1~2 minutes per). That seems quite high...Could be related to https://github.com/Diaoul/spkrepo/issues/3 as well.

**Comment by quentinus95** [comment]
Thanks for the answer. I have a DS716+, let's wait then.

Thanks !
