### ISSUE TITLE
nzbget-testing update

### ISSUE THREAD

**Issue by baz1860** [SynoCommunity/spksrc#1958]
Currently, the nzbget-testing package is based on the pre-release package r1439 from Sept 17th

Much work has been done since, with 4 stable releases put out (16.0, 16.1, 16.2, 16.3) placing the testing package behind 'stable'. I understand that there was an issue with the auto-upgrade function released in v15 (iirc) which was disabled as part of the spksrc packaging process.

As nzbget has moved over to the github model, with a master and develop branch, and it appears that no further pre-release packages will be put out, is it possible to have the testing package updated to follow the develop branch and auto upgrade reinstated? Or were there other reasons which led to the disabling of the auto-upgrade function which would prevent this?

**Comment by Dr-Bean** [comment]
NZBGet-stable was updated a couple of times after an issue was discovered with 16.0. There was a bit of back and forth over the cause, which is why the latest stable is at 16.3. From what I've read, ultimately it was something external, related to a specific indexer.

The latest -testing version is still `16.0-testing-r1439`, even when using the auto update function.
Afaik, hugbug will continue releasing new testing versions, but hasn't seen a need to do so yet.
See also https://github.com/nzbget/nzbget/wiki/Packaging#branches-and-releases.

As for using the auto-update function: we prefer to build our own packages from source. There are several reasons for that, including optimization for 'our' arches, better control over packages, and less reliance on external resources.
It's definitely interesting for people who don't want to or can't use (our) packages though.

**Comment by Diaoul** [comment]
We'd need to compile it for auto-update to work, so it's the same effort as publishing a package. You can rely on package auto update instead of nzbget auto update.
It's not a matter of just "enabling" the option, it requires some work as described here: https://github.com/nzbget/nzbget/wiki/Packaging#automatic-updates

**Comment by Dr-Bean** [comment]
Right, that's the other option. I didn't include that in my explanation, because it definitely has no advantages over updating the package on the repo.
The option which I assumed @baz1860 asked about, is to use the update service of nzbget itself. It probably has most, if not all, of the arches that we provide packages for. That's what my explanation focused on.
Either way, there's no compelling reason for us to use it :)

**Comment by baz1860** [comment]
Thanks for the explanation, I see why the method currently used is preferable.
