### ISSUE TITLE
Unzip binary is missing (replaced by 7zip in DSM 6.0)

### ISSUE THREAD

**Issue by Chahk** [SynoCommunity/spksrc#1975]
SABnzbd v0.7.20 gives the following warning:
`WARNING: unzip binary... NOT found!`

According to [this post](https://forum.synology.com/enu/viewtopic.php?p=400791#p400791) on Synology forum, Unzip has been replaced with 7zip in 6.0 Beta.

**Comment by Dr-Bean** [comment]
The sabnzbd-testing package should have support for 7zip. Try that, and let us know if it works.

**Comment by Dr-Bean** [comment]
@Chahk Have you been able to test this?

**Comment by 3muzel** [comment]
Have this issue been fixed? I'm running the stable version "0.7.2" and I got the same message.

**Comment by Wild4fire** [comment]
@ Dr-Bean -- SABnzbd testing 1.0.0 RC5 doesn't fix anything, as a matter of fact it won't even start on DSM 6.0...

**Comment by techabyte** [comment]
Is there an update on this? Just updated I thought plex was my only issue but now I cannot run sab :(

**Comment by charlesjohnson** [comment]
I'm bit by this too. +1 for SAB 1.0.0 moving to stable.

**Comment by Dr-Bean** [comment]
Please note that releasing the SABnzbd 1.0.0 package as-is won't solve anything for DSM6...there are at least two reasons why the package does not work, and all of the issues need to be fixed before a working package can be released.

**Comment by mparents2007** [comment]
I am also having this issue, it isn't seeming to cause a problem on most downloads but I have noticed it has paused some due to this.

I also see another issue that I haven't had until upgrading to DSM 6.0 and that is: 2016-04-02 15:44:59,820	ERROR:	Cannot change permissions of /volume1/downloads/incomplete

All my permissions are set for RWX for ALL users and has always worked previously.

I hope we have a fix for this soon and keep up the good work

**Comment by techabyte** [comment]
NZBGet works perfect on 6.0. Using that for now for those that are still waiting for sab update. Might test out sab 1.0.0 if its worth the jump back when it gets pushed.

**Comment by Wild4fire** [comment]
@ techabyte: NZBGet, like most SynoCommunity packages, works fine [b]IF[/b] you already had it installed prior to upgrading. If not, it won't work as it cannot start.

**Comment by techabyte** [comment]
@Wild4fire that's weird because this is my first time using NZBGet. At first my problem it not starting was because like many packages I needed to edit the start-stop script and run it as root. But I have had issues in the past with permissions on sonarr/sickbeard so I eventually followed a guide ages ago https://couchpota.to/forum/viewtopic.php?t=1477 to fix my permission problem and that just works fine perhaps why I had no issues installing fresh copy of NZBGet on DSM6

**Comment by Wild4fire** [comment]
I've seen many people reporting that fresh (first) installs from SynoCommunity packages will succeed, but the packages themselves cannot start.

In my opinion we should not have to resort to editting files or making other changes. The packages should be able to start directly after installing.

So it seems we'll have to wait for the packages to be updated to reflect the changes in DSM 6.0.

**Comment by theCheek** [comment]
Just started getting this message this morning. Afaik my DSM has not updated since yesterday, but it has been running 6.0 for a while now, as it installed 6.0-7321 on the 3rd of March and sab was running perfectly until now.

Any ideas how to fix it? I've got over 3.6tb queued and really don't want to lose it, so I'm holding off on reinstalling for now.

**Comment by charlesjohnson** [comment]
I copied the unzip binary from an Ubuntu 14.04 instance to the Synology's path and it worked, fwiw.

**Comment by theCheek** [comment]
@charlesjohnson any chance of a quick guide on how to do this?

**Comment by charlesjohnson** [comment]
Will try to write it up tomorrow, but mostly I started an Ubuntu 14.04 VM, copied the unzip file off to the Sunology, and it worked.

Probably only works if you've got an x86 Synology.

**Comment by Wild4fire** [comment]
I don't think that's necessary. Sinds I upgraded to DSM 6.0, SABnzbd worked fine even though it's saying the unzip binary is missing. A bit strange, I think, but everything SABnzbd downloads ends up unzipped at the right place. :)

**Comment by Dr-Bean** [comment]
The missing unzip is a warning, not a error. You're probably not running into issues because zipfiles aren't used all that much nowadays.

**Comment by theCheek** [comment]
@Dr-Bean thanks, I spent some time finding the unzip binary from an oracle link (https://oss.oracle.com/el4/unzip/unzip.html) and placed it into my synology's PATH, changed its permissions to 777 and the error went away. 

But then yes, I also realised this wasn't my problem as I don't have any zips in the queue! Turns out downloads had stalled due to an issue with my usenet provider. Pebcak error...move along :)

**Comment by Wild4fire** [comment]
@ Dr-Bean: geez, I'm an idiot. Never before did I realize that I didn't run into any unzip issues simply because most stuff nowadays are RAR volumes. :)

One is never too old to realize he's a fool. :P

**Comment by charlesjohnson** [comment]
I'm not going to have time to write this up properly, but essentially I just found the unzip file on another linux host at roughly the same version for the environment, and then copied it over to the Synology, and it worked.

**Comment by edraven** [comment]
could synocommunity make a package for unzip and mark it as a dependency for sabnzbd 1.0.0?

**Comment by benkirton** [comment]
Many months on, is anyone working on getting SABnzb to work?

**Comment by Dr-Bean** [comment]
Done via https://github.com/SynoCommunity/spksrc/pull/2365
