### ISSUE TITLE
SickRage, SABNZDB, CouchPotato - Keeps On Stopping On Synology

### ISSUE THREAD

**Issue by Vodka2014** [SynoCommunity/spksrc#2002]
Hi All,

SickRage, SABNZDB, CouchPotato keeps on stopping them selves for some odd reason. If there a bug in the version or Python 2.7.10-14 ?

Running DSM 5.2-5592 Update 4

If this is the wrong please apologies.

Thanks

**Comment by Dr-Bean** [comment]
You're the only person reporting issues with multiple packages. So, I'd say no bugs, but something is/went wrong with your setup. Do the log files say anything in particular?
Have you made any changes to the users which run packages etc and associated permissions?

**Comment by Vodka2014** [comment]
Hi There

Here is the forms where peoplw have issues - https://sickrage.tv/forums/forum/help-support/synology/31236-sickrage-stopped-for-no-reason/page2?_=1450129403344

Seems Python is the cause but not confirmed

**Comment by Dr-Bean** [comment]
I'm sorry, but most of what I'm reading there looks like plain old guesswork to me, combining issues on several platforms which have nothing to do with each other.

What actually happened: The SR dev introduced a bug which caused SR to use all system resources. Naturally, that will affect other services on the system. The bug has since been resolved, as far as my info goes, but that does mean SR should be updated to latest (and I can't tell whether or not other bugs are still around). If need be, reinstall SR on your NAS.
