### ISSUE TITLE
UDPXY for DS215j

### ISSUE THREAD

**Issue by Dancoman** [SynoCommunity/spksrc#2038]
Please make UDPXY work on DS215j
http://sourceforge.net/projects/udpxy/
Tnx
##

**Comment by Dr-Bean** [comment]
The last release of udpxy was in 2012, which is a long time ago. Is the software still maintained?

**Comment by Dancoman** [comment]
I dunno how to make it work on my NAS DS215j

**Comment by Dancoman** [comment]
@Dr-Bean Can u help me install and configure udpxy on DS215j?
Thanks

**Comment by Dr-Bean** [comment]
Read the README that is provided in the UDPXY source files. It explains that you need to compile the software by running `make`. 

So, you can do just that with spksrc: create a cross-package for udpxy, set `CONFIGURE_TARGET` and `COMPILE_TARGET` to `nop`, and run `make arch-whatever`. The framework takes care of most of the details for cross-compiling. You should end up with something that you can conceivably _run_ on a Synology device. 

Next step is to create an actual SPK package to install and control the software. Take a look at, for example, the Transmission package for inspiration.

**Comment by Dancoman** [comment]
Tried to compile it with make, but did not work.
Tried to do like this: http://blog.dabasinskas.net/installing-udpxy-on-synology-ds411/

**Comment by Dr-Bean** [comment]
That blog is of no use.
Start reading the [spksrc README](https://github.com/SynoCommunity/spksrc/blob/master/README.rst). Follow the instructions to set up a virtual machine (or set up the spksrc Docker container, might be easier), then walk through the usage and example on Transmission. If you have succeeded in building that package, then continue with reading the Contribute section, and try to apply it to udpxy.

If you have concrete questions, feel free to ask. Please be specific. Tell or show us exactly what you have done, and what you expected to happen. 'It doesn't work' is no good, because we have no idea _what_ doesn't work.

**Comment by Dancoman** [comment]
So there is no app that can be installed on NAS?  I dunno how to do that.

**Comment by Dr-Bean** [comment]
No, that's the whole point of spksrc. A package for Synology NAS devices currently doesn't exist, so someone has to put in the time and effort to package it. That someone could be you. 
If not, then it looks like you expect someone else to do the work. Seeing as every single contributor is a volunteer, you might be waiting for a long time.
