### ISSUE TITLE
DS216 - invalid location issue

### ISSUE THREAD

**Issue by brgale** [SynoCommunity/spksrc#2057]
I've done a search and read as much as I can find about the invalid location error when trying to add synocommunity to the package sources on my nas and I've corrected my DNS addresses.  I'm starting to find some references to newer nas devices not being supported.  I have a new DS216.  Can I not use synocommunity yet?  

And if not is there another way of installing 3rd party packages?

**Comment by Dr-Bean** [comment]
See #2033. The 216 is a new architecture, and we're waiting for Synology to release a useable toolchain.

**Comment by brgale** [comment]
Is there somewhere I can check that will tell me when it's ready to go? I see many toolchains on synology's sourceforge page, but I don't really know what I'm looking at.  Does SynoCommunity maintain a list of supported Nas's?

**Comment by PJClapp** [comment]
Sorry for adding to the closed conversation, but I'm a complete noob here. Just bought a new DS416j and was unpleasantly surprised to not be able to install SynoCommunity packages on it (which was 95% of what my old 212j NAS was doing).

As I understand it, you are now waiting for Synology to release something that will allow you guys at SynoCommunity to be able to add support for the new architecture? Is there any way of knowing if, and if so, when Synology will do this? Days or maybe weeks I can wait, but otherwise I would much rather return my now useless NAS and go back to using my old one.

**Comment by Dr-Bean** [comment]
I referred you to #2033 to keep the discussion in one place. Please put future questions there.

@brgale SynoCommunity's list of supported toolchains can be found here: https://github.com/SynoCommunity/spksrc/tree/master/toolchains. You can match up the toolchains with a particular model via this link: https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model.

@PJClapp Synology does not release any public information about toolchains and associated tooling, and generally state that it can take up to several months before those are made available.

In this particular case, there is a toolchain, but we can't use it as-is. I haven't received a proper response yet, so I have nothing further to say at this point. The choice is yours to make.

**Comment by bigcheek** [comment]
Hello,

I just bought a DS416j and found that unfortunately no community packages are available :(

Is there anything we can do on our side (user's side) to help you get what you need to migrate the packages to this new NAS (open a ticket with Synology asking them to give you the sources you need for example) ?

Can this help you (Armada38x sources) ?
http://sourceforge.net/projects/dsgpl/

Thanks in advance; your work is greatly appreciated.
