### ISSUE TITLE
Static vs shared library

### ISSUE THREAD

**Issue by vkostas** [SynoCommunity/spksrc#2058]
Many packages have 4 options for static/shared libraries 
`--enable-static --enable-shared --disable-static --disable-shared`.
Which of the *static / shared* are we supposed to "prefer"?

It would be nice if some *tips and tricks* were put together in a guideline. 
- DO and DO-NOT.
- Available variables, modes (pre/configure, compile, install). 
- PLIST (prefixes, which files to remove and which to keep)
- Maybe some recurring build errors?

I learned all those in the hard way. So let save some time to the new contributors.

**Comment by Dr-Bean** [comment]
There is no right answer for your first question. If anything, the answer would be `it depends`, so that's not helping. There may be a dependent cross package that statically compiles a library itself, so you can't rule out that you need both of them. 
If both libs are built by default, that's fine. You can clean up what will be included in the resulting package via the PLIST, because we obviously don't need static libraries on the device, but we usually _do_ want shared libs.
So, simply don't specify either.

As for the other suggestions: sure. Feel free to open an issue with concrete suggestions or better yet,  set up the documentation for the knowledge you have gathered so far. There's an old open issue somewhere on documentation as well, that may be a good place to gather the information.

PLIST has a wiki article already, see if that works for you, and correct it if it's wrong.
Recurring build errors? Please open issues (or PR's with a fix) for those. SynoCommunity is in constant flux with package additions and code changes, so breakage is somewhat expected.

**Comment by vkostas** [comment]
@Dr-Bean 
>If both libs are built by default, that's fine. You can clean up what will be included in the resulting package via the PLIST, because we obviously don't need static libraries on the device, but we usually do want shared libs.
>So, simply don't specify either.

From the 20 or so new sub-packages I am working on I have seen all (default options) combinations:
- Shared on + static on
- Shared on + static off
- Shared off + static on

A few of them do not have at all shared/static option (maybe I am wrong).
**I have activated shared library and disable static one when possible.**
Of course those options can be reviewed/amended during PR.
Thanks again.

**Comment by Dr-Bean** [comment]
Generally speaking, shared libs are more popular than static, so provided that the resulting SPK works as expected, you won't hear complaints from me ;)
