### ISSUE TITLE
Jackett Fork SPK

### ISSUE THREAD

**Issue by komarto2** [SynoCommunity/spksrc#2061]
Hi,

There is a fork of the jackett project before they removed public trackers:
https://github.com/raspdealer/Jackett/

Can you please create a Jackett custom fork spk?

Thanks,
Komar

**Comment by Dr-Bean** [comment]
First off: There's an open issue over on the Jackett tracker discussing public trackers: https://github.com/Jackett/Jackett/issues/157. If nothing else, make sure you have shown your support there.

Then to the request itself. Jackett needs to be compiled in order to work. Upstream provides those binaries, but those are tied to a specific version.
Setting up the package for custom forks means that you, as the user, would have the enter the correct download link manually, and imo, that's just not a feasible option.

As an alternative, you can download and overwrite the files yourself (`/usr/local/jackett/share/jackett` iirc, will be reverted with package updates), or fork spskrc and create the package from scratch using the source you want.

**Comment by JigSawFr** [comment]
But somes providers are down (not updated since deleting of public's, so it's normal), as T411 for example.

**Comment by raspdealer** [comment]
It's better to fork version 0.6.45 than to use my fork.
My fork has some tweak to create and use an other config folder to be able to run easily 2 instances of jackett on the same debian.

**Comment by Dr-Bean** [comment]
To be clear, at this point, this issue is a WONTFIX. The implementation of allowing forked versions in combination with Jackett in particular isn't fit for Synology devices.

If https://github.com/Jackett/Jackett/issues/157 is implemented, then there's no need for forks.
If not, someone can fork the code and keep maintaining the public trackers.
According to @raspdealer, his fork shouldn't be considered, so it's up to someone else to do that. If that fork gains enough traction, we can reconsider the approach for SynoCommunity. 
Until then, back to my earlier suggestion: build the binaries, and either replace the current code or rebuild the package.

**Comment by raspdealer** [comment]
Exactly!
You can the package the version 0.6.45 and use it, It will contains T411.

**Comment by solspire** [comment]
hello,
I have instal jackett package on my nas synology but I don't have t411 !!
Please help me, I need that for work with mylar...

**Comment by Dr-Bean** [comment]
@solspire See my previous comment. This is not the right place for your question. The Jackett maintainers at https://github.com/Jackett/Jackett have chosen to not include public indexers, and T411 is a public indexer. As a result, our package does not include it.

Either maintain your own fork of Jackett, include that indexer yourself, and maintain your own package, or see if there's another product that fullfills your need. There's nothing for us to do here.
