### ISSUE TITLE
Boost does not support all archs.

### ISSUE THREAD

**Issue by vkostas** [SynoCommunity/spksrc#2064]
Boost 1.59.0 does not compile for **88f6281-5.2**.
I tried Boost 1.53.0 for this arch but I have some strange error
`./boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory`.
"Missing file" is located in **./install/usr/local/python2.7**.
File `user_config.jam` has this dir inside `using python : 2.7 : : ./spksrc/cross/boost/work-88f6281-5.2/install/usr/local/include/python2.7 ;`.
Anyone has this issue? Maybe smth is wrong with my (virtual) OS?
Thanks.

**Comment by Dr-Bean** [comment]
Boost isn't meant to be compiled directly via the cross package. You should have less issues when you build boost as part of an SPK.

If the issue is with including `python-cc.mk`, restarting the build process works. 
It could also be that an arch doesn't support a boost component/library. Restarting won't work then: you'll have to set the correct libraries in the depending cross package. See https://github.com/SynoCommunity/spksrc/blob/master/cross/libtorrent/Makefile#L27 for example.

**Comment by vkostas** [comment]
@Dr-Bean
That's good news. Boost is a hell of slooooow process. Thx.
