### ISSUE TITLE
Compile all archs of a DSM version

### ISSUE THREAD

**Issue by vkostas** [SynoCommunity/spksrc#2068]
Is it possible to dynamically build all archs of a DSM version (something like `make archs-5.2`)?
Using `make all-archs` we build all DSM versions but it is wise to try first all archs of latest DSM version (currently 5.2) and then go further with older DSM.
Of course it can be done manually by searching toolchain folder (`syno-*-<my DSM version>`) but a manual step can lead many times to mistakes.
##

**Comment by Dr-Bean** [comment]
We may not have much in way of documentation (other than looking at the actual code, which can be quite helpful), but we do have an article on that subject. See https://github.com/SynoCommunity/spksrc/wiki/Compile-and-build-rules.

Note that a lot of the rules apply only to building SPK's, not cross-packages. It should be sufficient to compile with one or two toolchains (_not_ x86-based!), then move on.
For example, my routine would be to set up a cross package, test that with 88f628x until it works, repeat as needed with other cross packages, then set up the SPK and run a `make all-supported` to see if any particular toolchain is broken. If so, fix whatever is broken, rinse and repeat.
You'll notice soon enough if a cross package is finicky with particular arches (ARM, PPC, X86 as major flavors), and if need be, focus on those by building manually.

**Comment by Diaoul** [comment]
I noticed I can't use multithreading with `make all-supported` (using `-j4`)
I think rules can use a clean-up. Since the last changes `make smart-clean` doesn't work anymore and was quite helpful to debug.
Something like `supported` instead of `all-supported`, `88f628x` instead of `arch-88f628x` and so on.

**Comment by Dr-Bean** [comment]
I don't see how `make smart-clean` ever worked for anything other than `noarch`? The default value for `$(WORK_DIR)` is `work`. I would expect a for-loop over all `work-*` dirs if you don't want to specify an arch there.

As for multithreading, I warned about that when I created the PR: the kernel-required check prevents that from working. As far as I know, there's no way around that. 
If you add a rule to ignore kernel-required, you lose the (size and build-time) advantage of x64 packages, but it'd solve the multithreading issue.

**Comment by vkostas** [comment]
No need to spend time on it.
I thought it was already possible.
By checking the `mk` includes didn't help me, that's why I started this thread.
I have more urgent issues to solve btw (e.g. building ICU in ARM alpine).
I admit it would be nice to have it but listing all archs I need in a simple script works fine.
Thx a lot anyway. Thumbs up.

**Comment by Dr-Bean** [comment]
For the record, if you're able to compile the latest available toolchain, you're good (SPK: `make all-supported`). Anything older is nice to have, but not mandatory at this point.
If you want to compile a package for all arches with a specific toolchain version, SPK: `make all-toolchain-%` is what you want (e.g. `make all-toolchain-4.3`).

**Comment by Dr-Bean** [comment]
@Diaoul Did you want to change the behavior of `smart-clean` still?
As for the other comments: renaming from `make all-supported` to `make supported` is fine with me, same with `legacy`.

I don't see how reworking `make arch-$(ARCH)` to `make $(ARCH)` would work though. Seems to me that will break because of the wildcard (`%`) (and probably permanently disable bash-autocomplete...see also #1919 for a proof of concept)

**Comment by Diaoul** [comment]
I used spksrc with `make ARCH=88f6281` and not `make arch-88f6281` so I could use `make ARCH=88f6281 smart-clean` and it would clean up the current cross but not the dependencies which speeds things up quite a bit.
But when you introduced the new toolchain thing it broke, I think it's still possible to use `smart-clean` but I have to setup the environment and it's a bit longer. Something like `make ARCH=88f6281 TCVERSION=5.2 smart-clean` if memory serves.

You're probably right, about the shortening, it wouldn't work properly without side effects. I don't use bash completion anyway so I don't mind that part.

**Comment by Dr-Bean** [comment]
I see what you mean. Hm. If you use ARCH=88f6281, then you're overriding the automatic addition of TCVERSION which is added when you'd use the traditional `arch-88f6281`.

I don't know if there's a way to get around that within the rule. Maybe an easy way is to clean up all `work-88f6281-*`, so it works for all TCVERSIONs?

**Comment by Diaoul** [comment]
Yes it worked with `=`, it sets the ARCH variable properly which is the same as done in `arch-%`. Since the change to support multiple versions of toolchain it doesn't work anymore. Not a big deal though but it was a clean way to call other rules while still benefiting from the ARCH variable being set.
