### ISSUE TITLE
How to set up ownCloud on synology

### ISSUE THREAD

**Issue by RockScience** [SynoCommunity/spksrc#2072]
Hello,

I have successfully installed owncloud 8 from synoCommunity on my synology NAS.
I have one issue and one question:

1) issue: When logging on http://192.168.0.3/owncloud/, I was being told that the owncloud data folder I have chosen is not writable by owncloud: "Can't create or write into the data directory /volume1/owncloud". So I edited the properties of the folder using the file station so that the http group has full read and write access. It works now I could finish the owncloud setup. BUT I can't see the folder anymore from my synology user account. This is very dangerous as I can't back it up in case I need.... Is it normal and can I revert back what I did?

2) question: So far I can only access to owncloud using the local IP http://192.168.0.3/owncloud/, but ultimately I need to access the owncloud remotely. Is it possible to use the quickconnect ID?

Thank you
##

**Comment by Dr-Bean** [comment]
1) Make sure that the `users` group has access to the shared folder (and if you're currently have `deny` set, don't). Otherwise, at the very least, set r/w permissions for your user.
Maybe Synology changed the group/permissions behavior once again, because I can't think of another reason why that wouldn't work anymore.

2) Try it. I have no idea.

**Comment by RockScience** [comment]
1) ok thank you I managed to tweak the permissions settings.
2) I have  tried and it doesn't work.. This is disappointing as my initial plan is to use owncloud from anywhere in the world, not only on my local network.

**Comment by Dr-Bean** [comment]
1) Confirmed that the `http` group needs access, instead of the `http` user. That will need to be fixed, tagging as `bug`.

2) That's what a domain name is for (or alternatively, use DDNS). You should then be able to access owncloud via http://ddns-domain.name:80. 
In case you hadn't considered it yet, I'd strongly urge to look into securing the connection by allowing only `https` from external locations or securing the connection via VPN (arguably the better option, but maybe less user-friendly.
