### ISSUE TITLE
App "Documents" not available in synoCommunity owncloud 8.1 

### ISSUE THREAD

**Issue by RockScience** [SynoCommunity/spksrc#2076]
I have just installed ownCloud 8.1 from synoCommunity reposetory, on my synology NAS. I can't find the "Documents" app..
That's weird because it seems people just have to "enable" it usually. 
Is the synoCommunity package different?

**Comment by Dr-Bean** [comment]
Our package is nothing special really, it's just a convenient, automated way to install Owncloud instead of doing it manually.

The `Documents` app is no longer available with Owncloud 8.x, see https://github.com/owncloud/core/issues/21597. Documentation seems to be outdated though (e.g. https://doc.owncloud.org/server/8.1/user_manual/documents.html seems to indicate it's still included).
It should show up in the appstore (or whatever its called) in Owncloud, but it doesn't seem to be right now. You should probably report that upstream, that could be a bug.

Anyway, you can work around this by downloading and extracting the app yourself. Get it from here: https://apps.owncloud.com/content/show.php?content=168711&forumpage=2 (pick the correct version), extract it, and put it in `/volume1/web/owncloud/apps` (you should end up with a new dir, called `documents`, and the contents of the zip file). I think it should be doable from FileStation, once you have the file downloaded.
