### ISSUE TITLE
How far away is Docker for ARM?

### ISSUE THREAD

**Issue by zhuchun** [SynoCommunity/spksrc#2080]
Noticed Docker isn't on my 216play since it's ARM chipset :(
Any route map to support that? Thanks.
##

**Comment by Dr-Bean** [comment]
You might want to ask Synology that question, they provide the Docker package for Intel-based devices: https://www.synology.com/en-global/form/inquiry/feedback.

**Comment by zhuchun** [comment]
Sure, let me try :+1:

**Comment by zhuchun** [comment]
@Dr-Bean They reply my inquiry, in short: No plan. :(

**Comment by peterstory** [comment]
I wonder how challenging it would be to install docker on an ARM-based device. Having a GUI isn't really important to me.

**Comment by vgonisanz** [comment]
Already exists a docker version for ARM, working on raspberri pi, [Here a tutorial](https://blog.hypriot.com/getting-started-with-docker-on-your-arm-device/), so the problem is not docker cant work in arm architecture. If someone know how to install manually via SSH/terminal docker and its dependencies, the problem is solved.

**Comment by berdugorn** [comment]
could it be possible to run through the debian chroot?

**Comment by ourcubk** [comment]
https://stackoverflow.com/questions/52520008/can-i-install-docker-on-arm8-based-synology-nas/58690946#58690946

Please follow this steps to install docker in ARM DSM.

**Comment by hgy59** [comment]
Docker for ARM64 comes with DSM 7.2 (see #5667)
