### ISSUE TITLE
Standalone vs dependent Package: Different behaviour 

### ISSUE THREAD

**Issue by vkostas** [SynoCommunity/spksrc#2082]
I have noticed (probably you already know this) a cross/package can behave differently when it is compiled standalone or as a dependent cross/package of another cross/package.
Some values are blank and you are puzzled what you have done wrong.
That's because the values are calculated inside the `include ../../mk/spksrc.cross-cc.mk`.
Personally I faced a real issue with at least two packages. A package would compile as standalone and never as dependent one. But in most of the cases, a package would compile as dependent and never as standalone.
Since most of the SPKSRC cross/packages are dependent ones it is wise to compile them (during standalone testing) in a _dependent_ mode.
I solve this by using an empty main cross/package `testpkg`.
This way we can safely use variables so far are not available or randomly available (`ARM_ARCHES`, `PPC_ARCHES`, etc).

> # This is a dummy package used to test other package. Add your package to DEPENDS variable.
> # e.g. DEPENDS = cross/ffmpeg
> DEPENDS = 
> 
> GNU_CONFIGURE = 1
> # Disable Checksum
> PRE_CHECKSUM_TARGET = none
> CHECKSUM_TARGET = none
> # Disable Download
> PRE_DOWNLOAD_TARGET = none
> DOWNLOAD_TARGET = none
> # Disable Extract
> PRE_EXTRACT_TARGET = none
> EXTRACT_TARGET = none
> # Disable Patch
> PRE_PATCH_TARGET = none
> PATCH_TARGET = none
> # Disable Configure
> PRE_CONFIGURE_TARGET = none
> CONFIGURE_TARGET = none
> # Disable Compile
> PRE_COMPILE_TARGET = none
> COMPILE_TARGET = none
> 
> include ../../mk/spksrc.cross-cc.mk

Thank you.
##

**Comment by Dr-Bean** [comment]
> Since most of the SPKSRC cross/packages are dependent ones it is wise to compile them (during standalone testing) in a dependent mode.

_All_ of cross packages are dependencies on another package: the spk itself. There are no exceptions: we can't install _just_ a cross package on a Synology.
Consider this approach: Create spk/package, and add the cross package to DEPENDS. When you build the SPK you are doing the exact same thing as with your proposed change, with the added benefit that you can test the resulting SPK immediately (provided that you set up spk/Makefile and other components of the SPK: install scripts etc).

Being able to compile a cross package by itself (while including it's dependencies) is the norm. In the majority of cases, there is no difference between building as a dependency of another package or standalone.

There are a couple exceptions (e.g. busybox and boost come to mind) where there's an actual difference, and that's because there's information in the 'parent' package that is not available for the cross package when that's built as standalone.

The other exception is if the cross package isn't setup correctly. Think CONFIGURE_ARGS, patches to fix cross-compile errors, maybe a specific arch needs a specific fix, maybe a package isn't compatible with a certain arch, and so on.. 
If you encounter those types of errors, then that simply something that needs to be fixed. Not always easy to do obviously, but that's part of the fun.

**Comment by vkostas** [comment]
@Dr-Bean 
I understand and fully agree with you.
My point is to avoid some (rare but existent) false errors.
As per documentation, it is not a good practice to advance directly to SPK build. We should first check if cross/package builds correctly (standalone first, then the main cross/package). 
It is there I noticed some cases which can make you spend a lot of time. :-)
I had a couple of cases I was going crazy because everything looked OK until I started digging the source code.
Believe me, a standalone cross/package builds correctly on its own but fails as dependent package of another one can kill your time.
