### ISSUE TITLE
Installation of latest Sickrage version 6 failed (using gui)

### ISSUE THREAD

**Issue by reyman** [SynoCommunity/spksrc#2087]
Hi,
The sickrage develop branch contain a new version of sickrage which solve the MAX CONNECTION error. But the manual install using synocommunity package failed.

You can find some information here:
https://sickrage.tv/forums/forum/main-category/latest-news/32593-sickrage-version-6-0-is-out-and-the-install-just-got-easier/page3?_=1452942463287&_=1452945015709&_=1453019272%

I try to finish install using command line with root : 

```
11:09:41 ERROR::MAIN::git version returned : /bin/sh: git: command not found, treat as error for now
None
```

I change the `git_path` option in `config.ini` with : `/volume1/@appstore/git/bin/git`

Then i start without problem sickrage with this command : 

```
/volume1/@appstore/python/bin/python SiCKRAGE.py
```
##

**Comment by bigmillz** [comment]
Same here.

**Comment by Vodka2014** [comment]
Same

**Comment by xmenxmen** [comment]
Same

**Comment by cytec** [comment]
@reyman better use `/usr/local/git/bin/git/` which points to your @appstore version...

**Comment by Dr-Bean** [comment]
@cytec There's a potentially bigger issue here, and that's that the changes upstream are backwards incompatible (from a package maintainers perpective anyway).

This update has replaced the vendored-in libraries to a `requirements.txt`. I'm all for that idea, but it looks like upstream didn't know or care that it would cause issues with packages...

On top of that, to solve it, people such as @reyman are directly installing into the system wide Python installation instead of using the virtualenv (as evidenced by `/volume1/@appstore/python/bin/python` vs `/usr/local/sickrage/env/bin/python`). This will cause issues when Python is updated: the complete SR installation will be removed.

So...Wheels should be created for the requirements.txt and should be installed via the package. Not sure, but we might even need to turn off auto-update.

**Comment by Vodka2014** [comment]
This does work if you use the other Repo SickRage. This is only happening to SickRageTV. I do not care about there politics just a good and stable Version i can support

**Comment by reyman** [comment]
Ok, i understand my error @Dr-Bean , i remove the package and make a fresh install when it works with synopackage way. I'm not sure to understand, which sickrage repository we need to clone if we want regular upgrade. [Sickrage.tv](https://github.com/sickragetv/sickrage) is the old repo, and sickrage is the new forked repo [here](https://github.com/SickRage/SickRage) ?

**Comment by Dr-Bean** [comment]
@Vodka2014 Then you're free to install that version. We're not keeping you from making your own choice.

As far as I understood, the SR "Community" edition prefers you to use the `Sickbeard-Custom` package, and you can change the fork to their repository.
There's a FAQ article here: https://github.com/SickRage/sickrage-issues/wiki/Switching-your-Synology's-Sickrage-to-the-new-repository#install-sickrage, although that still refers to the SickRage package.

@reyman Again, which SR repository to use is up to you. As far as I know, the "community" edition uses the 'old style', but I'm reasonably sure they will move to a similar structure at some point.
Once this issue is sorted, maybe auto-updates can be enabled, maybe not. Packaging for Synology is different from packaging for regular distros, and having some level of control of what is installed is quite important for us.

**Comment by Dr-Bean** [comment]
The SickRage package is currently deactivated. In its current state, it won't work for installations of the 'old' version of SickRage.

Users of the SickRage 'Community' edition can switch over to using the Sickbeard-Custom package. See the link I provided in my previous comment for further instructions.

**Comment by Vodka2014** [comment]
@Dr-Bean. Yes i am just using it since it is working right now and yes there are features in both that differ. GIT just updated on my NAS so i am going to use the SickBeard Custom now to see if this works.

**Comment by neoatomic** [comment]
The last Mohicans. :P

**Comment by Paradoxx2015** [comment]
Ooo. Whats happening here.! @reyman you do refer to miigotu´s clone of sickrage (with lack of security). The original (not old repo) sickrage git address: is https://github.com/SiCKRAGETV/SickRage (sickrage.tv). @reyman why do you mention that miigotu`s clone og sickrage is the new fork, when the original (and still developed) sickrage that "echel0n" and the team is the real deal? (Im smelling som kind opportunity to steal users and get access to data.)..

**Comment by adaur** [comment]
@Paradoxx2015 : every user can choose its repository, depending if they want a broken installation (SRTV) or a working one (SR)

**Comment by fonix232** [comment]
@adaur so just to confirm: the SynoCommunity SickRage package always used https://github.com/SickRage/SickRage and not https://github.com/SiCKRAGETV/SickRage right?

**Comment by duramato** [comment]
@Paradoxx2015 what are you on about? echle0n went MIA for more than year , leaving the team on SR doing all the work. When he returned he just caused trouble , so the team left an contiuned the work elsewhere.
```(Im smelling som kind opportunity to steal users and get access to data.)``` Are you new to github and Open Source projects? mmm if not dont know what you are on about...
And like @adaur said everyone is entitled to their own opinion and choise. But as far as oficial goes , it isnt the echle0n one without the original team

**Comment by labrys** [comment]
@Paradoxx2015 echel0n has no team.  The entire team except echelOn is at https://github.com/SickRage/sickrage.  However you are free to choose whichever you prefer.  And what "lack of security" are you referring to?

**Comment by Dr-Bean** [comment]
People, please continue your discussion somewhere else. It does not belong here. Thank you.

**Comment by labrys** [comment]
@Dr-Bean agreed.

**Comment by Paradoxx2015** [comment]
agreed, just had some questions. :)

**Comment by lucianot54** [comment]
I tried bugfix the problem and i have some problems for create SPK file. 
Who can share me the spk file?

**Comment by lucianot54** [comment]
I tried to bugfix but i need a valid spk file. I created sickrage_noarch-all_20160121-1.spk file with docker. I can import SPK file but i can't install correctly. I have an error :s.

Anyone can share me a good spk file?

**Comment by roeiegans** [comment]
Any news on this? Will there be a new sickrage package and will it work with DSM 6.0 (for both repo's don't work with DSM 6.0 in combination with sickbeard-custom). Seems to be a permission issue, the package won't start at all.

**Comment by pedro2d10** [comment]
is there a way to have again the sickrage package available? I use sickbeard custom and I don't want to remove the gitinside it.

**Comment by Vodka2014** [comment]
Is this going to get added back now since v7.0.22 seems to work ?

**Comment by labrys** [comment]
@roeiegans there are some work arounds in the https://github.com/SickRage/SickRage-issues issue tracker for DSM 6.0.

**Comment by Safihre** [comment]
DSM6 compatible version of the package is expected to be released soon. It can already be installed by downloading it from here #3138.
After the official release on SynoCommunity, the package will auto-update from the official release.
