### ISSUE TITLE
Synology: Firefox Sync can not be uninstalled (Incorrect MySQL root password)

### ISSUE THREAD

**Issue by rbieb** [SynoCommunity/spksrc#2093]
Version is 1.5.2-3

MariaDB was installed before installing Firefox Sync since it came as a dependency. No matter what password I enter, ffsync always complains it's wrong, therefore preventing me from uninstalling the package.
##

**Comment by nickbroon** [comment]
This is also a problem with installing tt-rss. See https://github.com/SynoCommunity/spksrc/pull/2056#issuecomment-173900759

**Comment by Dr-Bean** [comment]
Please look at [CONTRIBUTING](https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#issue-content). Could you add the missing information please, in particular the DSM version?

If DSM6 Beta: I assume you already know this, but otherwise: it's a beta. Synology seems to have a habit of breaking backwards compatibility with new DSM versions, and breaking our packages in the process.

It could be related to the `root` user changes, but that's not clear to me atm. If you have shell access, you can try to play around with the following command, and see if you can get access or not: https://github.com/SynoCommunity/spksrc/blob/master/spk/ffsync/src/installer.sh#L41.

This will probably affect all packages that use MariaDB...

**Comment by Hubfront** [comment]
I dont think its related to root user changes. I can log in Maria DB as root in beta 2. The root user acount was not changed in MariaDB. There is also an user ffsync in the table mysql. Maybe u used a different password for that user? You could install phpmyadmin and look if the hashes are the same.

**Comment by Hubfront** [comment]
I can confirm that the root user account still works with beta 2 with old password. The users in MariaDB seems to be not affected. There is root user and ffsync user in my mysql table.

**Comment by Sprinkle-Master** [comment]
@nickbroon 
Just use MariaDB from community development fork.  One click resets root password back to blank.  Then, simply use the same app to "change password" by leaving the "current password" field blank and set the new root password to whatever you want.

**Comment by Sprinkle-Master** [comment]
@Hubfront 
Could you be in the same boat with a blank password?  I am still a nub but...  If root pass is blank, would shell let you in with anything you give it?  Just a thought but it would make for a decent explanation.

**Comment by Hubfront** [comment]
Yeah before i wrote herein i blanked out the root password in the mariadb database. The problem with the uninstaller persisted.

**Comment by Dr-Bean** [comment]
Copied mostly from #2217: 
We can use `/usr/bin/mysql` when the buildnumber is associated with DSM6. The approach will probably be similar to [this](https://github.com/SynoCommunity/spksrc/blob/master/spk/tt-rss/src/installer.sh#L11). 

PR's welcome, but please note that this affects all packages using MariaDB, so the PR should take all those packages into account. 
Secondly, after merging a PR/change to fix this particular issue, it does not mean the affected packages will immediately work after upgrading. There are several reasons why packages on DSM6 are broken, this is just one of them. Some packages will be affected by multiple changes in DSM6.

**Comment by Dr-Bean** [comment]
Done in part with d6900764830d2500a382cbd9a27fb84cdaf1dc3a. This solves the mysql location, but it does not solve the issue with creation of users (#2216), and we'll also need to have the DSM6-final toolchains (not yet released)

**Comment by mettix** [comment]
Hello!

I'm also stuck with the uninstall of Owncloud.

-> Tried resetting MariaDB root password from the MariaDB GUI
-> Tried resetting password from SSH 

Both shots didnt work out, still throws error; MySQL incorrect root password.

Any other thoughts?

**Comment by gnacho** [comment]
What worked for me:

```
mkdir /usr/syno/mysql
mkdir /usr/syno/mysql/bin 
ln -s /usr/bin/mysql /usr/syno/mysql/bin/mysql
```

source: https://github.com/SynoCommunity/spksrc/issues/2217

**Comment by qu1gl3s** [comment]
Any progress on this issue.

Has Synology released the toolchains?

**Comment by calvinleea** [comment]
@gnacho 

> What worked for me:

mkdir /usr/syno/mysql
mkdir /usr/syno/mysql/bin 
ln -s /usr/bin/mysql /usr/syno/mysql/bin/mysql
source: #2217


That really works for me when installing the fengoffice to my dsm6.0

thanks

**Comment by Sigawan** [comment]
Years later.. most packages still will not install throwing error : incorrect mysql root password.
Should these packages all be marked DSM 5.xx only?

**Comment by ymartin59** [comment]
Yes. That is explained in FAQ. Upgrades and DSM 6.x support is in progress, package by package.

**Comment by mreid-tt** [comment]
The original Firefox Sync Server, as indicated in its [source repository](https://github.com/mozilla-services/syncserver), is no longer actively maintained. Instead, it has been redeveloped in Rust and is now hosted in a new repository called [Syncstorage-rs](https://github.com/mozilla-services/syncstorage-rs). The upcoming release, associated with the Pull Request [5942](https://github.com/SynoCommunity/spksrc/pull/5942) in the SynoCommunity/spksrc repository, will soon replace all prior versions of the package due to their deprecated functionality.

We invite interested individuals to explore the Checks tab at [this link](https://github.com/SynoCommunity/spksrc/pull/5942/checks) for the opportunity to download a pre-release version for testing purposes. Your valuable feedback is highly appreciated and encouraged before the final release.
