### ISSUE TITLE
I can't add SynoCommunity on my DS416j DSM6

### ISSUE THREAD

**Issue by aurel71** [SynoCommunity/spksrc#2143]
Hello, i can't add SynoCommunityon my DS416j DSM 6.0-7274.

it say "invalid location"

yet I am as described at https://synocommunity.com/.

and I tested several dns.

Can you help me ?

**Comment by NidalM** [comment]
This is because 416j has a processor for which there is currently no toolchain in spksrc repo. You can clone the repo and add it yourself by following the instructions in this thread: https://github.com/SynoCommunity/spksrc/issues/2118

If you're not familiar or uncomfortable with doing this, you will need to wait for someone to add the toolchain and push it to the repo.

**Comment by Dr-Bean** [comment]
I'm going to close this one as a duplicate. Support for Armada38x models is handled via #2033. 
#2118 contains several unrelated issues, so that's not the best place to look.
