### ISSUE TITLE
[Request] Update HAProxy to 1.6.x

### ISSUE THREAD

**Issue by Vilican** [SynoCommunity/spksrc#2175]
Hi,

Could you please update HAProxy from 1.5.14 to 1.6.3?
It should be also compiled against the new DSM 6.0-RC.

Thanks
##

**Comment by Dr-Bean** [comment]
You can compile against the beta toolchains yourself, it seems unlikely those will be added to spksrc at this point.
I'll edit the title to reflect this is a request to update HAProxy to latest.

**Comment by Vilican** [comment]
Can you please point me to some guide how to compile it? Though I am developer, I have no experience in that. Thanks

**Comment by Dr-Bean** [comment]
How to compile HAProxy in general? Take a look at the README, setup a development environment, and build a package with `make arch-88f6281` etc.
If you're specifically referring to using the DSM6 toolchains: I'd suggest to check if the DSM5.2 toolchains work on DSM6 first, otherwise it's a lot of unnecessary work. 
To add new toolchains/kernels, look at some of the previous commits to add a toolchain, e.g. this one: https://github.com/SynoCommunity/spksrc/commit/4f2759e1013f4edeffaf929fa6c1156ab3ef9a3b#diff-50484c19f1afdaf3841a0d821ed393d2
