### ISSUE TITLE
disk util

### ISSUE THREAD

**Issue by burghy86** [SynoCommunity/spksrc#2197]
hi, i have install disk util on your repo for using screen
i tried to type a command screen in putty but:
-ash: screen: not found

the packet is stopped but i don't see a start command.

please help me. where are a documentation?

**Comment by Dr-Bean** [comment]
See the FAQ: https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#im-trying-to-use-a-command-line-only-package-but-im-seeing--ash-command--not-found-help.

Screen is just a binary. No starting/stopping required, just you running it.

**Comment by burghy86** [comment]
great..thank you so much dr.bean.
i have create new file called: "screen"  in: /usr/local/bin
inside i have write:
-------------------------------------
#!/bin/sh

LC_ALL=en_US.UTF8 /usr/local/diskutils/bin/screen "$@"
-------------------------------------
mod chmod in 777

and screen work prefectly

**Comment by Dr-Bean** [comment]
Because we don't put every binary in our packages on PATH. For example, if Synology adds the same command (or even another package, for that matter), this will cause unexpected results.

Besides, it's fairly standard practice on *nix environments. As a user, you can create a symlink, a wrapper script as you used, using the full path to the binary, or by editing your .profile to add the path to PATH. Whatever method you prefer, you are in charge of what happens on your system.
