### ISSUE TITLE
Debian-chroot web interface not working on DSM 6

### ISSUE THREAD

**Issue by r1sknt** [SynoCommunity/spksrc#2222]
Debian-chroot web interface not working on DSM 6 it just freezes on loading status and if I add service it's it won't start and got deleted after refreshing the page like I didn't add it
**DS415+
tried after upgrade and on a fresh install

**Comment by mcondarelli** [comment]
I have the exact same issue, so it doesn't seem to be a sporadic case.

The chroot seems to be working right (I can ssh into it and it behaves normally), so the problem seems to be confined to the GUI, but it' crippling nonetheless.

*Additional Info*:
- I installed on a brand-new DS216j.
- No other packages installed (beside the required `Python`, of course).
- I installed it exactly to test if I can upgrade to DSM6 on my main machines.

**Comment by jattym** [comment]
Same issue here on DS215j.  Chroot working and services already configured running on reboot but no web functionality to add/monitor services.

**Comment by Dr-Bean** [comment]
https://github.com/SynoCommunity/spksrc/issues/1910

**Comment by elRadix** [comment]
will the GUI be fixed now with the new toolchain ?

**Comment by Dr-Bean** [comment]
@elRadix Stop spamming please. There's one issue dealing with the GUI problems of Debian-Chroot, and that is linked in my previous comment.

**Comment by belkone** [comment]
I fixed this issue, look: https://github.com/SynoCommunity/spksrc/issues/1910#issuecomment-253990371
