### ISSUE TITLE
Request: Manual Download of spk's

### ISSUE THREAD

**Issue by raymondtrueman** [SynoCommunity/spksrc#2225]
Hi,

I migrated from a DS413 (ppc) to a DS415+ (x86) on DSM 6. In order to get my couchpotato and headphones packages running again without losing config, I need to update to the x86 version of the package. I managed to do this with other non-syno community packages. But I need to download the spk files manually. Can anybody provide the download paths? I cant seem to find them myself. 

Thanks

**Comment by sn0wblind4r** [comment]
There is a Log Button in the "Package-Center" in the installed Apps list.... :)

**Comment by sn0wblind4r** [comment]
Wrong thread. Sorry.

**Comment by Dr-Bean** [comment]
We don't provide manual downloads. Please see the README for details on how to build your own package.

**Comment by raymondtrueman** [comment]
@Dr-Bean Thank you, I managed to get the spksrc docker container running in Synology with the Docker package. Now that it is running, how do I compile an spk?

**Comment by raymondtrueman** [comment]
@Dr-Bean Nevermind after hours of googling I figured it out. You might want to add the make command to actually create the spk to the README

**Comment by Dr-Bean** [comment]
I don't disagree that the documentation still needs work, but what you needed is linked from the README. We can't put it all in there, because it would become too long.

For future reference: 
README refers to [Pull Requests section of CONTRIBUTING](https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#pull-requests). 
That section, amongst other things, points to [spksrc example wiki page](https://github.com/SynoCommunity/spksrc/wiki/spksrc-example). 

Along with that, if you open the [wiki](https://github.com/SynoCommunity/spksrc/wiki), you're linked to the [Developers HOW-TO](https://github.com/SynoCommunity/spksrc/wiki/Developers-HOW-TO), which contains the same links, but also links to [Compile and build rules](https://github.com/SynoCommunity/spksrc/wiki/Compile-and-build-rules), which explains more in depth which build rules there are.
