### ISSUE TITLE
Headphone SSL_ERROR_RX_RECORD_TOO_LONG issue

### ISSUE THREAD

**Issue by BjornTra** [SynoCommunity/spksrc#2289]
Hello!
I have an issue with headphone, when i try to launch him with firefox or chrome, i have the error "SSL_ERROR_RX_RECORD_TOO_LONG". I have this issue only with Headphone. 
Someone have an idea ? 

Can i uninstall headphone, suppress headphone files and install a clear headphone ? how can i suppress those files ? 

I have reinstall my Synology. My certificat is from Let's Encrypt.
DS 414
dsm 6.0-7321 Update 3

Thanks
Vitria

**Comment by Dr-Bean** [comment]
This is not a package issue, so you might be better off asking upstream, e.g. the Headphones bugtracker.
Anyway, I would say you haven't configured SSL correctly. Turn it off, and start over. If you can't access the GUI, you can edit the config (after stopping the package) at `/usr/local/headphones/var/config.ini`.

I wouldn't recommend a uninstall/install at this time, due to issues where clean installations of packages on DSM6 result in broken packages. Search the tracker, you'll see plenty of issues related to DSM6.
