### ISSUE TITLE
Reevaluate qoriq packages with availibility of gcc493

### ISSUE THREAD

**Issue by piejanssens** [SynoCommunity/spksrc#2319]
The DSM 6.0 toolchains contain a newer gcc version supporting newer features such as C11 or C14.
I believe because in the past qoriq toolchains were trailing behind with an outdated gcc that some packages have not been updated or haven't been available for qoriq devices. Correct?

Could we list these packages here and reevaluate them?

**Comment by Dr-Bean** [comment]
PPC/Qoriq's issue wasn't an outdated GCC version. The issue is that the arch is considered exotic, and a number of instructions are not implemented. A lot of developers haven't implemented workarounds for PPC32 and don't plan to, especially since the architecture as a whole seems to be EOL, and is being replaced with PPC64.

C11/C14 is a different matter, and is not related to PPC specifically. It more or less has a similar outcome though: software that uses instructions that are introduced with the new standards won't compile. Most, if not all, the older Synology arches will be affected by this at some point.
