### ISSUE TITLE
NZBGet 16.4-22 update on DSM 5

### ISSUE THREAD

**Issue by Cartman25** [SynoCommunity/spksrc#2376]
### Setup
_Package Name:_ NZBGet
_Package Version:_ 16.4-22

_NAS Model:_ Xpenology
_NAS Architecture:_ x86
_DSM version:_ DSM 5.2-5644 Update 1

### Expected behavior
After updating NZBGet, it can't start the package

### Actual behavior
NZBGet is not started.

### Other info :
SynoNAS> ./nzbget -v
nzbget version: 16.4

SynoNAS> ./start-stop-status start
Starting NZBGet ...
su: can't chdir to home directory '/usr/local/nzbget/var'
nzbget.conf(0): Could not open file /usr/local/nzbget/var/nzbget.conf
SynoNAS> cd /usr/local/nzbget/var
-ash: cd: can't cd to /usr/local/nzbget/var

SynoNAS> cd /usr/local/nzbget
SynoNAS> ll
-rw-r--r--    1 nzbget   root       10.6K Jun 12 14:47 openssl.cnf
drwxr-xr-x    5 nzbget   root        4.0K Jun 12 14:48 share
drwxr-xr-x    4 nzbget   root        4.0K Jun 12 14:48 lib
drwxr-xr-x    4 nzbget   root        4.0K Jun 12 14:48 app
drwxr-xr-x    2 nzbget   root        4.0K Jun 13 13:54 bin

#### Package log
No log

#### Other logs
/var/log/messages :
Jun 13 14:14:19 SynoNAS entry.cgi_SYNO.Core.Package.Control[1].start[6607]: pkgstartstop.cpp:187 Failed to start package nzbget, [1], No such file or directory
Jun 13 14:14:19 SynoNAS entry.cgi_SYNO.Core.Package.Control[1].start[6607]: pkgstartstop.cpp:196 Failed to start package nzbget, [1]

/var/log/synopkg.log
2016/06/13 14:14:19     start nzbget: begin to start version 16.4-22
2016/06/13 14:14:19     stop nzbget: begin to stop version 16.4-22
2016/06/13 14:14:19     stop nzbget: stop version 16.4-22 successfully, result 0
2016/06/13 14:14:19     start nzbget: start version 16.4-22 failed, result 263

**Comment by Dr-Bean** [comment]
This has got to be a one-off. The upgrade method hasn't changed since the package was introduced, and there's no reason for this to happen at all.

@Cartman25 For some reason, the `var` directory backup or -restore has failed for reasons unknown (with the notable exception of manual changes to the package/user/package permissions at some point in the past).
Unfortunately, that directory stores the configuration and other important stuff. You'll have to remove and reinstall the package, and start from scratch.

**Comment by Cartman25** [comment]
Thanks for the news.
I tried yesterday to make a link to /var, it loaded the demon but the web interface did not work.

--> So yes i made a clean delete et setup again the package and conf.
