### ISSUE TITLE
adduser: user: 'sabznbd' in use + fails to start

### ISSUE THREAD

**Issue by madvtak** [SynoCommunity/spksrc#2378]
![user in use](https://cloud.githubusercontent.com/assets/18261123/16040989/eeed8254-31e7-11e6-89f4-6917f937fa72.jpg)
### Setup

Package Name:_SABnzbd
Package Version:_1.0.3-16

_NAS Model: DS1515+
_NAS Architecture:_
_DSM version: DSM 6.0.1-7393

I tried to create this user before to see if that would work, it didnt work, so i deleted the user. Now when i try to create the user DSM says the account exists or reserved for the system. I checked the logs for SABnzbd and it also said sabnzbd is in use. Sorry i don't know how to copy and paste in MC.

**Comment by Dr-Bean** [comment]
As mentioned before, currently, a lot of the packages don't work with DSM6. That won't change unless some things are figured out, e.g. #2216.

On top of that, you now have some type of ghost user that may or may not still exist in some form. A reboot _might_ help with that, because of the way users are managed on a Synology. Still, the previous point will apply then.

**Comment by Dr-Bean** [comment]
Closing. DSM6 compatibility for SABnzbd is tracked in 2416, and the meta issue wrt user creation is tracked in #2216.
