### ISSUE TITLE
Midnight Commander does not start in 

### ISSUE THREAD

**Issue by citytrader** [SynoCommunity/spksrc#2385]
_For new Package Requests, see the guidelines_  
### Setup

_Package Name: Midnight Commander
_Package Version: 4.8.15.-3

_NAS Model: DS713+
_NAS Architecture: INTEL Atom D2700
_DSM version:  6.0.1-7393
### Expected behavior

MC should start
### Actual behavior

After the installation I click run and after 10 seconds it say "stopped"
### Steps to reproduce

_1. Install MC
_2. Run MC
_3._
#### Package log

_Check Package Center or `/usr/local/{package}/var/`_

```
Insert the package log here
Log is empty

```

**Comment by ajboelen** [comment]
I, unfortunately, have the same issue...

**Comment by ajboelen** [comment]
Midnight Commander does not run from the DSM environment. It runs in a terminal window using the command "mc". The stopped status in the package manager is not a valid statement of the way this app should be used. I would like to advise the developer to make the program start a terminal window where MC starts. Or state a clear instruction in the remarks field of the app. The current text obviously leads to many misunderstandings.

**Comment by citytrader** [comment]
It is obviouse that it don't runs from DSM, after the DSM upgrade it does not work anymore from ssh, can be solved this please?... its very handy MC

**Comment by JoopNL** [comment]
Well, what happens when you start it from SSH? When logging on using SSH, do you get a warning that your home directory path can't be found perhaps?

**Comment by Dr-Bean** [comment]
MC is purely CLI-based, it's not supposed to be started via Package Center. Because it doesn't run, the status is `stopped`. This is the default for all of our CLI-based packages.

A specific key, `startable=no` is set in the package's INFO file, to prevent Package Center from thinking it can be started. It looks like that that behavior has been broken, probably with the introduction of DSM6 due to changes in the way packages are managed. I've entered a bug report for that (308566)

In the meantime, I'll close this, as it's not a package issue.
