### ISSUE TITLE
ownCloud 8.1.1-7 on DSM 6 - downloading shared files

### ISSUE THREAD

**Issue by fatmaddin2000** [SynoCommunity/spksrc#2409]
### Setup

_Package Name:_ owncloud
_Package Version:_ 8.1.1-7 

_NAS Model:_ DS715
_NAS Architecture:_ NAS behind Router via port forwarding
_DSM version:_DSM 6.0.1-7393 Update 1
### Expected behavior

Downloading files from ownCloud via browser
### Actual behavior

When I click on download I got "file not exist"
### Steps to reproduce

_1._updated from DSM 5 to DSM 6
_2._updated PHP settings i open_basedir with "/dev/urandom:/volume1/owncloud"
_3._share a link
_4._click on link, enter password, getting on owncloud site with file file displayed, clicking on download
--> file not exist
#### Package log

"no data"

In DSM 5 it was easy to readjust /etc/httpd/conf/extra/mod_xsendfile.conf-user and to make it work. This file is not existing on DSM 6. Is there a workaround for DSM 6?

**Comment by mreid-tt** [comment]
Hey @fatmaddin2000, I'm not sure if you are still having this issue. There could be a permissions issue which should show up in the logs. Alternatively, I've been working on a new release of ownCloud v10.11 (#5619). You can perhaps try to download from one of the artefacts if you'd like to help with testing. Please note that this version is not upgradeable from the v8.1.1 in the repository so you'll need to manually backup your user data and repopulate the new deployment.

**Comment by mreid-tt** [comment]
Hi there! It looks like this issue has been open for some time without any recent updates. Since then, a new version of ownCloud (v10.12-9) has been released which may have resolved this issue. Can you please test with the latest version and let us know if the issue persists? If we don't hear back from you in a few days, we'll assume the issue has been resolved and close this ticket. Thank you!
