### ISSUE TITLE
[Deluge] Compile error

### ISSUE THREAD

**Issue by schumi2004** [SynoCommunity/spksrc#2496]
When i tried to compile Deluge 1.3.13 it generates error during compilation.
http://pastebin.com/D8LVTku1

I'm trying to compile it for Alpine using 5.2 toolchain but for some reason it switches to x86_64 during setuptools.

copying setuptools/script (dev).tmpl -> build/lib/setuptools
copying setuptools/script.tmpl -> build/lib/setuptools
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
copying build/lib/easy_install.py -> build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pkg_resources
creating build/bdist.linux-x86_64/egg/pkg_resources/_vendor
copying build/lib/pkg_resources/_vendor/pyparsing.py -> build/bdist.linux-x86_64/egg/pkg_resources/_vendor
copying build/lib/pkg_resources/_vendor/appdirs.py -> build/bdist.linux-x86_64/egg/pkg_resources/_vendor

**Comment by cytec** [comment]
This happens because you need to build `native/python` try runn `make clean` on Deluge, then switch to `native/python` run `make clean && make` there and switch back to Deluge and try to build it again!

Sometimes there goes something wrong when automaticaly compiling `native` components from inside a spk/cross folder

**Comment by KaraokeStu** [comment]
Not an issue per-se
