### ISSUE TITLE
Mosquitto broker on 416slim Start/Stops

### ISSUE THREAD

**Issue by amanzimdwini** [SynoCommunity/spksrc#2512]
I have the same problem as others - my package will start and them stop
"Failed to run the package service." is what I get...

I did add SynoCommunity to my Package Sources; I set the Trust Level.
I made a user mosquitto  and I chown mosquitto mosquitto.conf (dont even have password file yet)
Logged in as mosquitto - same problem.

Sorry - feeling dense. Any help would be most appreciated.

Karl

**Comment by keiser1080** [comment]
Hi, 
same problem using dsm 6.0.2-8451 update 2.
mosquitto fail to start using the web interface.

But i can start mosquitto manualy

`/usr//local/mosquitto/sbin/mosquitto -c /usr/local/mosquitto/var/mosquitto.conf 
1479244871: mosquitto version 1.4.9 (build date 2016-09-22 10:20:30+0100) starting
1479244871: Config loaded from /usr/local/mosquitto/var/mosquitto.conf.
1479244871: Opening ipv4 listen socket on port 1883.
1479244871: Opening ipv6 listen socket on port 1883.
^C1479244877: mosquitto version 1.4.9 terminating
`

**Comment by amanzimdwini** [comment]
My eventual solution:
uninstall package
make a new user MOSQUITTO - give Admin privileges (use VERY tough password)
log in AS MOSQUITTO
Install package
(runs)
Log off as Mosquitto
(package continues to run)

I have NOT YET tested what happens upon reboot...

**Comment by jacobstim** [comment]
The problem is that the "su" command used in the `start-stop-status` script fails to change the user to the "mosquitto" user. That is because the "adduser" command from the installer script does not seem to add an entry for the mosquitto user in the `/etc/shadow` file -- I think this is due to a recent change in DSM and other packages suffer similar problems. Solve that by executing:

`echo "mosquitto:*:10933:0:99999:7:::" >> /etc/shadow`

in an SSH session as root, and then the package will start/stop just fine.
