### ISSUE TITLE
homeassistant requires python 3.4.2 and additional modules

### ISSUE THREAD

**Issue by joshlawless** [SynoCommunity/spksrc#2525]
I eventually solved my challenges getting homeassistant to build with the current spksrc git by updating the versions of the Makefiles of psutil pyephem and netifaces.  But unforunately, the package can not run.  Some of the required python modules for the newer version of homeassistant (e.g., aiohttp) require the python version to be at least 3.4.2, but the spksrc python version (and the synocommunity python3 package) are version 3.4.1.  Is it safe to update the version numbers for the /spksrc/cross/python3 and /spksrc/native/python3 Makefiles to 3.4.5 and build a package that way?  I don't know enough to know whether, if that were to succeed in making a package, it would be safe to install on the Synology (e.g., without causing trouble for other python3-dependent packages).

**Comment by Diaoul** [comment]
You can even bump it to 3.5 without consequences I think.

**Comment by joshlawless** [comment]
I'm no longer sure that the dependency on Python 3.4.2 is even the issue I'm running into.  I built a spksrc package for Python3 by indexing the Python version to 3.4.4 and manually installed it over my Synocommunity installation (3.4.1).  I still get the same unusual error when trying to run my homeassistant package, though.  There's no output from the start script (which uses the start-stop-daemon command), but if I parse it down to the python command `env PATH=/usr/local/homeassistant/bin:/usr/local/homeassistant/env/bin:/usr/local/python3/bin:${PATH} PYTHONPATH=/usr/local/homeassistant/share/homeassistant /usr/local/homeassistant/env/bin/python3 -m homeassistant -c /usr/local/homeassistant/var --open-ui
` it spits out this error:
```
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/python3/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/homeassistant/share/homeassistant/homeassistant/__main__.py", line 11, in <module>
    from typing import Optional, List
ImportError: No module named 'typing'
```

If i go to the /usr/local/python3/bin folder and run `./python3 -m pip install typing`, I can get past this error, but it quickly runs into another:
```
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/python3/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/homeassistant/share/homeassistant/homeassistant/__main__.py", line 388, in <module>
    sys.exit(main())
  File "/usr/local/homeassistant/share/homeassistant/homeassistant/__main__.py", line 363, in main
    args = get_arguments()
  File "/usr/local/homeassistant/share/homeassistant/homeassistant/__main__.py", line 121, in get_arguments
    import homeassistant.config as config_util
  File "/usr/local/homeassistant/share/homeassistant/homeassistant/config.py", line 11, in <module>
    import voluptuous as vol
ImportError: No module named 'voluptuous'
```

Did I do something wrong in building the homeassistant package, such that it doesn't seem to see any of the modules that it's supposed to rely upon?

**Comment by Dr-Bean** [comment]
Well, that makes sense. If you want to update Homeassistant to latest then you'll have to integrate the changes since made to Homeassistant into the package.

The Python modules that Homeassistant uses can be found at https://github.com/home-assistant/home-assistant/blob/master/requirements_all.txt. 
All the mandatory modules in there at least need to be included in the SPK (along with their dependencies if they exist).
Some of those modules might need to be cross-compiled, you'll have to check if that's the case. Those will need a similar setup as pyephem, netifaces etc: a cross package, along with a mention in requirements.txt. Pure-python modules just need to be added to requirements.txt for creation and inclusion into the package.

**Comment by joshlawless** [comment]
@Dr-Bean, I'm very happy to keep plugging away at this via trial-and-error, but if you have any guidance on how I could check which modules would need to be cross-compiled, I'd be grateful.  Is that an issue of whether or not they're "pure python"?  I'm interpreting that to mean whether or not they're listed on pypi.python.org - is that a fair way to tell?

**Comment by Dr-Bean** [comment]
No, PyPI includes both pure-python modules and modules with (optional) C-code.

Either look at the source code for the modules, or simply try it. For a larger list of requirements, just dump them all in a requirements.txt, set up a virtualenv, and run the list through pip, it's more or less the same approach the installer for the homeassistant package uses.
Also see the (somewhat outdated) wiki article here https://github.com/SynoCommunity/spksrc/wiki/Using-wheels-to-distribute-Python-solutions

**Comment by joshlawless** [comment]
So, my trial-and-error approach has taken me to my first sticking point.

I set up a virtualenv and ran the entire requirements.txt list from the homeassistant git through pip.  No trouble installing any of them, so I replaced the spk/homeassistant/src/requirements.txt file with that from the homeassistant git.  Without adding any new subfolders to spksrc/cross/ (but with my previous changes to version numbers of netifaces, psutil, pyephem, and python3), I got it to compile all the way with no new errors (none of the additional requirements broke the `make` command, the way that the wheels for netifaces psutil and pyephem used to).  But the package wouldn't run successfully -- the traceback on my Synology terminal indicated that the module pytz couldn't be found.  

I assumed that by adding pytz to the cross/ folder, and referencing it on the same line of the spk/homeassistant/Makefile as the other cross dependent wheels (e.g., as `BUILD_DEPENDS += cross/pyephem cross/netifaces cross/psutil cross/pytz`), it would build the wheel that way (which appears to have happened, looking at the terminal output from making the new package).  But running this second package still caused a traceback complaint that pytz wasn't found. 

Should the cross/pytz dependency be specified somewhere else?  (E.g., DEPENDS instead of BUILD_DEPENDS)?  It doesn't appear to have any dependencies of its own (I can create a virtualenv and install it without it trying to install anything else).  

Any assistant to get to the next step would be welcomed.  Also, if there's a faster way to trial-and-error than building the whole spk each time, that would be great to know about.

**Comment by Dr-Bean** [comment]
pytz is pure-python as far as I'm aware, so no need to cross-compile.

If pytz is not directly included in the upstream requirements file, then it's likely to be a dependency of one of the modules that _is_ listed in there. 
Either way, pytz _must_ then be listed in the SPKs requirements file. As for how to detect those dependencies, if you instruct pip to install modules from a requirements file, be sure to _not_ use `--no-deps`. That way, pip will attempt to install all the dependencies of the listed modules as part of the process. 
Use `pip freeze` or `pip list`, pip that to a new requirements file, that you can then use as basis for the SPK.

Sidenote: The reason that upstream may not have listed that module is because they might only want to list 'top-level' modules, and leave the dependency handling up to their chosen install process. For spksrc packaging, we can't do that. We need to explicitly include each dependency, which is why also we use `--no-deps` during install.

As for speeding up the process: I'm guessing you're running a `make clean` between each step. There's no need for that in this particular case. 
You might have noticed that the build process creates cookies/checkfiles along the way, called e.g. `.depend_done`, `.wheel_done` and so on. Those files are used to verify where the build process will be restarted when you reissue the same `make` command.
Remove the all the cookie files starting from the step from which you want to restart forwards. Say that you want to restart building dependencies,then remove `.depend_done`, `.wheel_done`, `.copy_done`, `.strip_done`, reissue the `make` command, and go from there.

**Comment by Diaoul** [comment]
Home Assistant dynamically install python modules depending on the features of HA you use. This is not a problem for pure python modules.

The dependencies are listed each components, for example for the `enocean` component: https://github.com/Diaoul/home-assistant/blob/dev/homeassistant/components/light/enocean.py#L24

I think you need to make a script that collects all those dependencies and creates a requirements.txt

**Comment by Dr-Bean** [comment]
Enocean is listed though: https://github.com/Diaoul/home-assistant/blob/dev/requirements_all.txt#L92. As it should be, imo. If HA starts to dynamically install modules after being installed via pip, that would cause breakage if HA isn't allowed/able to access i'net.

**Comment by Dr-Bean** [comment]
...having said that, even pytz is listed, so I'm not sure what the original issue was...https://github.com/Diaoul/home-assistant/blob/dev/requirements_all.txt#L4

**Comment by Diaoul** [comment]
You're right @Dr-Bean, it seems requirements_all.txt contains all the requirements gathered from every component. No need to create a script to do that then.

**Comment by joshlawless** [comment]
Inspecting the installed package, there is definitely a `pytz-2016.7-py2.py3-none-any.whl` file in the share/wheelhouse/ folder, so I'm a little lost on why it claims that it can't find pytz.

**Comment by Dr-Bean** [comment]
Time to start troubleshooting. Is the wheel installed via pip during package installation? Check with `pip freeze`. If not, tell the installer to pipe the `pip wheel` output to a logfile instead of `/dev/null`, install the package and see if pip skips it/the install fails/whatever.
If pytz did get installed, can it be imported? Start the Python interpreter in the venv, and run `import pytz`, see what it returns. If nothing, then the import succeeded.

**Comment by Dr-Bean** [comment]
FYI, Python3 has been updated to 3.5.2, and the approach of creating wheels has changed a bit. There should be less need to create cross packages (and adding via DEPENDS), and more chance to get the wheels working when (cross) compiled directly from a requirements.txt.

**Comment by schumi2004** [comment]
How hard is it to add module pytz to Python 2.7?
It seems i need this module for some epg script.

**Comment by ymartin59** [comment]
Please refer to #3115

**Comment by ymartin59** [comment]
To anyone interested in Home Assistant, what are components you are interested ? Please comment in #3115
