### ISSUE TITLE
NZBget won't start after upgrading to DSM 6.0.2-8451 Update 4

### ISSUE THREAD

**Issue by 3muzel** [SynoCommunity/spksrc#2526]
Hi there,

I'm running NZBget 16.4-22 on Synology 1815+. It's been running great until yesterday I upgraded to 6.0.2-8451 Update 4. After the restart the package won't start.

When I run start-stop-status in root I get the following:
`/usr/local/nzbget/bin/nzbget: /lib/libstdc++.so.6: no version information available (required by /usr/local/nzbget/bin/nzbget)

/usr/local/nzbget/bin/nzbget: /lib/libstdc++.so.6: no version information available (required by /usr/local/nzbget/bin/nzbget)

/usr/local/nzbget/bin/nzbget: /lib/libstdc++.so.6: no version information available (required by /usr/local/nzbget/bin/nzbget)`

Anyone else having the same issue?
Thanks
Ageel

**Comment by Ric1234Fr** [comment]
Hello,
Same here:
# ./nzbget
./nzbget: /lib/libstdc++.so.6: no version information available (required by ./nzbget)
./nzbget: /lib/libstdc++.so.6: no version information available (required by ./nzbget)
./nzbget: /lib/libstdc++.so.6: no version information available (required by ./nzbget)

I hope this can be fixed soon. 
Thanks a lot to the authors in advance.
Cheers
Ric

**Comment by noshali** [comment]
Just got 1815+ and updated to DSM 6.0.2-8451 Update 4. Was able to install mono and Sonarr but none of the other packages run. I get the "failed to run the package service" This is for Sabnzbd, nzbget, transmission. I looked through the forums and tried all solutions but nothing worked. Hopefully someone can fix this...thanks in advance

**Comment by AirRailey** [comment]
The following steps helped me:

- if SABnzbd or Python are still installed -> first uninstall again
- then reinstall, but do not run
- Restart the DS
- now SABnzbd went with me problem-free

Hope it helps you too.

**Comment by Dr-Bean** [comment]
If installing a DSM update broke it, please report it to Synology. It's possible (theoretically, I guess) that we need the DSM6.x toolchains, but that seems unlikely at this point.
Is it only nzbget, or are there other packages (either official or 3rd party)?

**Comment by noshali** [comment]
All official packages are ok. It is nzbget, transmission, sabnzbd and
sonarr.

-- 
Ali Raza

On December 1, 2016 at 7:50:27 PM, Dr-Bean (notifications@github.com) wrote:

If installing a DSM update broke it, please report it to Synology. It's
possible (theoretically, I guess) that we need the DSM6.x toolchains, but
that seems unlikely at this point.
Is it only nzbget, or are there other packages (either official or 3rd
party)?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/SynoCommunity/spksrc/issues/2526#issuecomment-264192179>,
or mute the thread

**Comment by Ric1234Fr** [comment]
Hi,
I just sent the below support request to synology.
I will keep you posted if I receive a reply.

====
Hi,

Following the upgrade in DSM 6.0.2-8451 Update 4 or 6 the package "NZBGet 16.4-22" from synocommunity.com fails at startup.

More precisely, the following error occurs under ssh:

root@DS416:~# /usr/local/nzbget/bin/nzbget
/usr/local/nzbget/bin/nzbget: /lib/libstdc++.so.6: no version information available (required by /usr/local/nzbget/bin/nzbget)
/usr/local/nzbget/bin/nzbget: /lib/libstdc++.so.6: no version information available (required by /usr/local/nzbget/bin/nzbget)
/usr/local/nzbget/bin/nzbget: /lib/libstdc++.so.6: no version information available (required by /usr/local/nzbget/bin/nzbget)

This problem is reported in the synocommunity bugtracker
There was no update of the NZBGet package

The author asks to report this issue to the synology support for more help in solving this.

Thanks in advance for your actions,
Regards,

**Comment by Ric1234Fr** [comment]
Hi, 
Just got the reply from Synology support... does not help much in fact.
Here is what they wrote:
"A user reported that each user must receive allowance to start the packages in the user settings. We are not sure if it works for you and we do not have further detail.
If this hint does not help, we apologize for any inconvenience.
Unfortunately NZBget are third party packages not developed by Synology. 
For technical support regarding these packages, please kindly contact the package's developers for more information."

Anyway, I searched again and managed to make nzbget work!

The answer comes from this page: [https://www.bountysource.com/issues/32220873-dsm-6-0-released-report-success-issues-with-packages-here](https://www.bountysource.com/issues/32220873-dsm-6-0-released-report-success-issues-with-packages-here)

Here is what I did and the results:
- nzbget is run by user "nzbget" 
- assigned the user nzbget to the newly created user group "sc-download"
- gave read&write permissions for my download to sc-download group for nzbget 
- chown -R nzbget:sc-download /volume1/@appstore/nzbget
- same chown procedure for /usr/local/nzbget

=> at this stage, nzbget would not start

- added nzbget:*:10933:0:99999:7::: at the end of /etc/shadow

=> bingo! nzbget now starts from the Package center

**Comment by Hubfront** [comment]
I wonder if this package is still installing and running on DSM 5? I plan to downgrade to DSM 5.2.

**Comment by Hubfront** [comment]
This, how i got it resolved without console, after reading the helpful comment above from user Ric1234Fr .
After reinstall DSM 6.1.1 for a fresh start, before installing nzbget i did

- create a user nzbget manually with the Usermanager of the DSM System Tools. 
- set the passwort to be different as the default "nzbget". 
- add user nzbget to the default system group for downloads: "sc-download" 
- add rw permissions to working folders (e.g. /volume1/downloads)

After that i installed the synoncommunity package nzbget and updated the pw to the one, i did choose when i created the user nzbget above. The default pw would be "nzbget" otherwise and that wasnt allowed by the DSM usermanager, as the pw has to be different to the username and i needed to create the user manually.

As the user and the necessary permissions were created before installing the package, it started right away after installation.

**Comment by Safihre** [comment]
Test package for new-style NZBGet has been released: #3138.
We no longer compile it here on the repo, but fetch the latest official installer from NZBGet.
During package installation you can choose if you want the latest stable or testing release. After this you can use NZBGet's internal update system to do updates. It also includes updates to user-management.
We hope to soon publish this on the official repo.
