### ISSUE TITLE
Use predefined ARCHES before spksrc include

### ISSUE THREAD

**Issue by vkostas** [SynoCommunity/spksrc#2530]
See also this topic [https://github.com/SynoCommunity/spksrc/pull/1662](url)... (Dr-Bean's comment: We should do something about the XYZ_ARCHES in common.mk, that's not working as intended imo. It's strange that it only works after the include, but not before.)

Random example based on a real spksrc cross packages.
`include ../../mk/spksrc.cross-cc.mk`
`ifeq ($(findstring $(ARCH), $(XYZ_ARCHES)),$(ARCH))`
`DEPENDS += ........`
`ENV += .........`
`CMAKE_ARGS += ...........`
`endif`
Any change of DEPENDS value after spksrc.cross-cc.mk is useless since all related code is "executed" in the latter.
I think the solution is to put common.mk before any reference to XYZ_ARCHES and then user the "normal" include spksrc.cross-cc.mk. (Yeah, that means common.mk is executed twice, but it has no other impact).
`include ../../mk/spksrc.common.mk`
`ifeq ($(findstring $(ARCH), $(XYZ_ARCHES)),$(ARCH))`
`......`
`endif`
`include ../../mk/spksrc.cross-cc.mk`

Any ideas?

**Comment by Dr-Bean** [comment]
My original thought there was that include directives were read before further processing the rest of a Makefile, so $(ARCH) would have the proper value. That's not the case unfortunately...as we've seen, it actually matters where the include is located in the Makefile.

So, we might as well keep the approach of that random example you have there. Especially if adding the second include for common.mk is just to replace the other include as far as location is concerned. The location of the include obviously is less important than the functionality ;)

**Comment by vkostas** [comment]
Thumbs up.
Then it would be wise to amend somehow the instructions (somewhere) so other people do not have to re-invent the wheel ;-)

**Comment by Dr-Bean** [comment]
Cool. Feel free to open a PR to sync all the packages that use the approach to have the same layout, we could even keep this issue open for it to serve as a reminder.

Not sure how to describe it in terms of a instruction/wiki though...https://github.com/SynoCommunity/spksrc/wiki/Makefile-variables would probably fit the best, but it doesn't use any type of order that we care about as far as I can tell. Maybe add the include directive for the cross packages stuff, and put it in there?

**Comment by hgy59** [comment]
The usage of $(XYZ_ARCHES) in **cross**/.../Makefile works as expected, since cross modules are built by dependencies of spk modules. The cross environment is setup in spksrc.spk.mk where the include of spksrc.common.mk is done before including spksrc.cross.mk.
If the XYZ_ARCHES variables are used in a **spk**/.../Makefile before the include of spksrc.spk.mk, then the spksrc.common.mk must be included prior.
I used this approach in #3099 for spk/lirc/Makefile where the XYZ_ARCHES variables are used to evaluate the version of the cross module to use.
It took me some time to sort this out and I would appreciate the difference between spk and cross makefiles is noticed in the docs.
Since cross modules work as expected, I propose to close the PR #2534.

**Comment by ymartin59** [comment]
I have added a short note at the end of https://github.com/SynoCommunity/spksrc/wiki/Compile-and-build-rules
