### ISSUE TITLE
Avoton: error "no version information available"

### ISSUE THREAD

**Issue by vkostas** [SynoCommunity/spksrc#2540]
_NAS Model:_ DS415+
_NAS Architecture:_ Avoton
_DSM version:_ 6.0

### Actual behavior
I face error **no version information available** on several syno **/usr/lib** libraries (**libssp**, **libstdc++**, etc) when running a new build Package in my NAS (avoton).
Is it me doing something wrong in the build or Toolchin itself has broken links?
Maybe it's due to missing access **/usr/local/\<pkg\>/\<pkg\>** vs **/usr/lib**?
I could of course include all those "hidden" libraries to my SPK but that's not the way to go IMO.

**Comment by Dr-Bean** [comment]
More info needed. What new package? Which toolchain? Which _specific_ DSM version? Anything change on the system lately, e.g. installed a new DSM patch? Do existing packages still work?

**Comment by Dr-Bean** [comment]
#2526 might be related?

**Comment by vkostas** [comment]
Hi.
It looks like the DSM does not include those libraries (?!?!?) even they exist in 5.2/6.0 **avoton** toolchains.
I connected with **SSH** to my NAS.
No **libssp0\*** at all and only **libstdc++.so.6** available (this one without its links).
Thx for the tip. I will contact Synology regarding the "missing" libraries.

One thing it puzzles me is the list of messages (are they really warning ones ???), e.g.:
` /lib/libstdc++.so.6: no version information available (required by bin/mpd)`
`/lib/libgomp.so.1: no version information available (required by /usr/local/mpd/lib/libsoxr.so.0)`.
Please note the **/lib** (shouldn't it be **/usr/lib/...** or just **lib/...** ???).
I will investigate further and post here my findings. It could be useful for others.

I noticed **start-stop-daemon** is not present in my NAS DSM 6.0!!! I guess that's part of DSM. Is it a known issue or I better re-install DSM just in case?

**Comment by Dr-Bean** [comment]
`/lib` is a symlink to `/usr/lib` on more conventional distros. I do think Synology might have changed things up vs DSM5, because they were (still) working with `/lib` and `/lib64` back then, but have since switched to complete x64 (hence the changes we needed to make to spksrc at the time). Maybe they forgot to actually create the symlink.
Have you checked if any of the libs are available in `/usr/lib`, or if there's still a `/usr/lib64` around? If so, create the symlink, and see what happens.

The `no version information` indicates that either the files cannot be found or that the library versions are outdated. Maybe a similar message is generated if the libraries are too _new_, don't know, but that would mean building a package with DSM6 toolchains, I suppose.

`start-stop-daemon` isn't available on any DSM version. We include it in our packages if it's needed, i.e. when the software-to-package doesn't include a useable daemon. No reason to reinstall DSM for that.

**Comment by vkostas** [comment]
It's getting (more) clear now.
All symlinks look good:
- `/lib` -> `/usr/lib`
- `/lib32` -> `/usr/lib32`
- `/lib64` -> `/usr/lib64`
- `/usr/lib64` -> `/usr/lib`

I compile with Toolchain DSM 5 but I install in DSM6. That (rather) explains the message.

At first sight I though `start-stop-daemon` would be generated from `busybox` (via `daemon` option added to `BUSYBOX_CONFIG` in spk `Makefile`) but since it didn't (now I have to investigate further why ???) I thought it is DSM itself containing it.
