### ISSUE TITLE
Copy utilities

### ISSUE THREAD

**Issue by juanjoGL** [SynoCommunity/spksrc#2550]
Just a simple question. Other NAS offer copy utilities that allow to créate a job to copy from a device to another device being not neccesary a 3rd (typically a PC) device controlling the process. I mean the following: You have 2 NAS and you créate a job (on NAS 1 or NAS 2) that copies files from NAS 1 to NAS 2 and you only need to have NAS 1 and NAS 2 working being not neccesary that a PC is working, and even more, it is NOT powered on. Is there any application to do that with Synology NAS?

**Comment by Dr-Bean** [comment]
Sure. `rsync` is a native Linux command that's able to do what you want. Otherwise, you might want to check out various packages on our repository at https://synocommunity.com/packages, such as [Duplicity](https://synocommunity.com/package/duplicity) or [rdiff-backup](https://synocommunity.com/package/rdiff-backup). I suppose [Sshfs](https://synocommunity.com/package/sshfs) might be worth investigating and even [syncthing](https://synocommunity.com/package/syncthing) could cover your needs. It all depends on what you need exactly, how comfortable you are with command line and what you want to do exactly.

Besides our packages, I believe that the official Synology repository might have some options for you as well.

**Comment by juanjoGL** [comment]
Thank you very much Mr. Bean. I will check what you suggest, however as I am a basic user wiith scarce knowledge on IT I was really looking for a more "straight forward" simpler solution. I have 2 Syno NAS (DS214se and DS212j) and as well I have 2 Lenovo/Iomega iX2. I use them for several purposes: Movies, Music, backups, Documents, etc. and from time to time I need to move files from one NAS to another. The moving of files is handled by Lenovo/Iomega NASes as they have a ustility that is describbed as:
"Data Replication / Device to Device Copy Jobs Easily copy files to and from attached USB drives or any network share including LenovoEMC™ Personal Cloud locations using the rsync or CIFS protocol. Define your Copy Job to copy/synchronize files to and from connected drives and/or any other shared storage on your network. "
This is a utility to handle copy Jobs to one unit to another one on the network and when executing runs in backgroung allowing me to copya big amount of files i.e. during the night. After termination of the copy process you only need to delete the files from the source (it is not a "move" utility.
While DSM appears as a powerfull system for different tasks and with a significant amount of utilities and applications, an application like the one I mention is missing and I'd like to have it on Syno NASes instead on having it on Lenovo/Iomega NASes only. Another useful utility is i.e.: Copying files from a PC or portable from/to a NAS without using the Windows Explorer. I mean a simple copy and not a backup.

**Comment by BenjV** [comment]
You can do that with File Station.
Just mout a remote folder on the other NAS and all copy (move) operations can be done as if it was a local copy.

**Comment by juanjoGL** [comment]
Hello,

Thank you very much. I have been playing around with the remote folder mounting and I have been able to mount a remote folder that points to a folder in another NAS. I see the files/folder of the other NAS in the remote folder created. I have not chequed yet but it appears copy options could be done in the way I need. A great idea, thank you again.

**Comment by Dr-Bean** [comment]
Closing, seems to be answered.
