### ISSUE TITLE
Issue - Python Upgrade + SABNZDB Errors

### ISSUE THREAD

**Issue by HPMSGEN8** [SynoCommunity/spksrc#2567]
### Setup
_Package Name:_ Python
_Package Version:_ 2.7.13

_Package Name:_ SAB
_Package Version:_ 1.1.11-19

_NAS Model:_ Synology
_NAS Architecture:_ Synology
_DSM version:_ 6.0

There was an update to Python today and i updated it and now SAB keeps on giving me the below error:

Exit(1) You need to install python requests library 

I have tried to install this on my NAS and i get this back after i install the modules

1. python get-pip.py
2. cd /volumex/@appstore/python/lib/python2.7/site-packages
3. pip2.7 install requests
4. Successfully installed requests-2.12.4

I do not know what to do next as it keeps on giving the same error ever after restarts.

Thanks

**Comment by Dr-Bean** [comment]
Please complete the issue template instead of deleting part of it, because now it's not clear where the error comes from...it may not seem important to you, but there's a reason we ask. Thanks :)

The requests library should not be needed for Sabnzbd afaik. Do you have additional userscripts installed maybe?
You can install the library in the virtualenv where Sab is installed: `/usr/local/sabnzbd/env`. Use `pip` to install: `/usr/local/sabnzbd/env/bin/pip install requests`

**Comment by HPMSGEN8** [comment]
Apologies for that.

So after doing some digging again this seems to have solve the issue:

cd /usr/local/python/bin
./pip install requests

Thanks

**Comment by Dr-Bean** [comment]
Sure, but note that you'll see the issue return when the Python package is updated again.
Of course, if you install it in Sab's virtualenv, you'll see the issue return with each Sab package upgrade, but it's the more correct location in terms of what the library is used for.

Anyway, solved, so closing.
