### ISSUE TITLE
Failed to load SABnzbd and Sickbeard.

### ISSUE THREAD

**Issue by Noordmeep** [SynoCommunity/spksrc#2571]
I just updated my python and both packages faild to start.
After this I updated my DS412+ to DSM 6

Now both apps won't start and can't find any information on how to fix it.

SABnzbd is version :1.1.1-19
Sickbeard is version: 20151220-4

First I found that the start stop script had wrong path for python.
So changed the path to /usr/local/python/bin/python
So the script would run (after first fault)
Now the error is that I need to install the cheetah module for python.
How can I install cheetah or fix the problem I have.

My current DSM version is: DSM 6.0.2-8451 Update 6
On a DS412+

Regards,

Hans

**Comment by BenjV** [comment]
You do not have the Python from the SynoCommunity installed, but the old one from Synology (or Python 3.0 from Synology)
That's why it seems that the path is wron and that you are missing the cheetah module.

Just install Python 2.7 from the Synocommunity and undoe you'r changes in the start-stop script.

**Comment by Noordmeep** [comment]
Hello BenjV,

Thanks for your sollution. It worked.
Got the wrong Python installed.

Hans
