### ISSUE TITLE
Unable to Start Mosquitto MQTT Broker Package

### ISSUE THREAD

**Issue by GitHubDelphi** [SynoCommunity/spksrc#2581]
Package Name: Mosquitto
Package Version: 1.4.9.5

NAS Model: DS1815+
DSM version: DSM 6.0.2-8451 Update 7

Mosquitto package status is "Stopped", even after I try to "Run" the package.
I am looking for MQTT WebSockets protocol support.
I will use the Paho JavaScript Client.

My mosquitto.conf looks like:

listener 1883
listener 9001

protocol websockets

Any help appreciated.

**Comment by GitHubDelphi** [comment]
I have tried also with the following conf file, without a blank line between listener and protocol.

My mosquitto.conf looks like:

listener 1883
listener 9001
protocol websockets

Do I perhaps need to run under a specific user? If so, how should this user be set up?

**Comment by GitHubDelphi** [comment]
May I please request a fix for the Mosquitto package; there is a bug that the service does not start.
Without the fix the package does not work.

Thank you.

**Comment by Dr-Bean** [comment]
See #2216.

**Comment by GitHubDelphi** [comment]
I do appreciate your trying to help.  However, #2216 just does not help me solve problem I am facing.

I would appreciate if you could please describe *exactly* what needs to be done to make the Mosquitto package start.

Thank you.

**Comment by Dr-Bean** [comment]
There is no fix as of right now...this is a very open issue, very much in progress. Subscribe to #2216 to keep informed.

**Comment by GitHubDelphi** [comment]
Ok, thanks for your feedback.

**Comment by EddyBin** [comment]
Is there already an solution ?

I found a workaround but not sure if this would work.  Can someone with a little more experience test this
As root you can start it from console with: 
sudo su mosquitto -s /bin/sh -
> -c "PATH=/usr/local/mosquitto/bin:${PATH} /usr/local/mosquitto/sbin/mosquitto -d -c /usr/local/mosquitto/var/mosquitto.conf" <- that's one command, no line breaks

[https://www.bountysource.com/issues/32220873-dsm-6-0-released-report-success-issues-with-packages-here](url)

**Comment by GitHubDelphi** [comment]
@EddyBin your link is broken

**Comment by EddyBin** [comment]
The correct [link](https://www.bountysource.com/issues/32220873-dsm-6-0-released-report-success-issues-with-packages-here)

The actual item is approximately 25% of the long list by tedstriker

tedstriker  commented on this issue 9 months ago.

 @ernorv unfortunately this doesn't work with the current DSM 6.0 version.
 As root you can start it from console with: 
sudo su mosquitto -s /bin/sh -c "PATH=/usr/local/mosquitto/bin:${PATH} /usr/local/mosquitto/sbin/mosquitto -d -c /usr/local/mosquitto/var/mosquitto.conf" <- that's one command, no line breaks.

**Comment by trlafleur** [comment]
Have issue with Mosquitto after upgrade to DSM 6.1-15022 Update 1... program will not install...

**Comment by EddyBin** [comment]
Will the issue be solved with the update to dsm 6.1 ?

**Comment by edsenabr** [comment]
Hi, I had the same issue. In order to solve it, I had to add, via Web UI, the user "mosquitto", and edit the start-stop script (/var/packages/mosquitto/scripts/start-stop-status) to keep it from execute mosquitto inside of su session. 

If you login as mosquitto and try to execute the bin directly (/usr/local/mosquitto/sbin/mosquitto), you'll notice that it starts fine ONLY if you don't add the -d flag. If you try to run it as a daemon, under the mosquitto user, the process will silently exit, w/o any kind of extra information. 

If you login as root and execute it with the daemon flag, it runs w/o any issue. So, in addition to that, I changed the config file (/usr/local/mosquitto/var/mosquitto.conf) to add the option "user mosquitto", so it would automatically drop its privileges, to avoid running it as root. 

After that, I was able to start/stop it using the web UI:

![image](https://cloud.githubusercontent.com/assets/15689137/24388735/1803914a-1353-11e7-842f-7feea7994d38.png)

Best Regards,
Ed.

**Comment by robmarkcole** [comment]
Also having this issue, DSM 6.1.1-15101 Update 2 on DS216+II

**Comment by ymartin59** [comment]
In progress #3025 #3028 #3022

**Comment by ymartin59** [comment]
Update has been published. Please create new specific issue to report any trouble
