### ISSUE TITLE
meta: creation of synobugs project for tracking Synology bugs

### ISSUE THREAD

**Issue by ssbarnea** [SynoCommunity/spksrc#2619]
If you could open a new project under SynoCommunity called `synobugs` (or similar) it would be great. 

I would like to use this project for tracking Synology bugs because, as we all know, Synology keeps their issue tracker private and it is clear nightmare to follow bugs on multiple forums and websites.

You can assign me as a maintainer and I will try to help dealing with them. Who knows, maybe in the end we will manage to persuade them to open their tracker.

**Comment by Dr-Bean** [comment]
I don't disagree that tracking Synology bugs is a pain in the neck, but I'm not at all convinced that SynoCommunity's Github repo is the right place for it myself.
For one, we're not affiliated with Synology, other than being users of their platform. We've seen new users reporting issues with Synology packages on our tracker on more than one occasion, and imo, we shouldn't make it more confusing by suggesting that there's a close(r) relationship between us and Synology.

In my opinion, an (official) forum would be the correct place to set up something like this, especially if you ever expect Synology to interact and contribute.
So, from my point of view, a better approach would be to convince Synology that it's in their best interest to develop a keen interest in what's going on on their forums, and start actively participating, as they did way back in the day. Maybe start by setting up a separate forumgroup for reported/accepted bugs, assign moderators, and generally get the forums back to being _managed_...

I've actually considered opening a request to ask for that a while back, but I don't think I went through with it...requests seem to have a habit of disappearing in a large black hole...and now we've come full circle ;)

**Comment by ssbarnea** [comment]
Indeed. I am really surprised how poor is the relation between Synology and its user community (both issue tracking, unmaintained and outdated forums and lack of transparency.

How about starting a petition instead? (sarcasm)

**Comment by Dr-Bean** [comment]
It was better in the past, as it always is ;)

Anyway, if the petition doesn't work, my suggestion would be to start off with a thread on the global forum: Synology <> community interaction, or something like that. 
Use your comment above as starting point, but put a positive spin on it :P. You want to gather input on improving the forums...like a 'starting over with a fresh slate' kind of idea, because the forums aren't as effective a tool as they could be, for both the community and Synology.
Some ideas could be assigning a Synology community manager, assigning (community) moderators per subforum, closing old/outdated threads, interaction with Synology support, a feedback loop between mods and Synology support, you name it.
If the community responds positively, open a FR and link to that thread...then maybe Synology responds positively as well ;)

**Comment by Safihre** [comment]
Closing due to age. Seems nothing really changed over the years.
