### ISSUE TITLE
Unable to See Radarr within Synology Community.

### ISSUE THREAD

**Issue by jaycapo1** [SynoCommunity/spksrc#2705]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_
_Package Version:_

_NAS Model:_
_NAS Architecture:_
_DSM version:_

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by jaycapo1** [comment]
[https://dl.dropboxusercontent.com/u/5443786/syno..JPG](url)

**Comment by juxtaposed** [comment]
@jaycapo1 1) You didn't fill out any of the fields they ask you to. Remember, it's a volunteer effort, e.g. they don't get paid, so give them as much information as you can.

And 2), the reason you're not seeing Radarr is because it's still a Beta package. If you want to install it, even though it's in beta, you need to go to Package Center -> Settings -> Beta tab -> check the "Yes, I want to see beta versions!"

Don't forget: it's **BETA**.

**Comment by KaraokeStu** [comment]
Closing as @juxtaposed has given the information required to sort the issue - thanks!
