### ISSUE TITLE
[Package Request] Nano compiled for broadwell (x86_64)

### ISSUE THREAD

**Issue by olamaekle** [SynoCommunity/spksrc#2716]
It would be nice if someone could compile Nano for the broadwell I have in my DS3617xs. Isn't the braswell the same instruction set as the broadwell (x86_64)?

GNU nano
[https://www.nano-editor.org/](https://www.nano-editor.org/)

**Comment by ymartin59** [comment]
nano package already exists. But compilation toolchain is not available for your platform yet #2509 

Same troubles for #2718 ... be patient.

**Comment by ymartin59** [comment]
I have prepared toolchain for broadwell 6.1 and build nano package. Here is it packed in a zip file because of GitHub. May you please test it and report if it seems to work well.
[nano_broadwell-6.1_2.5.1-2.spk.zip](https://github.com/SynoCommunity/spksrc/files/888578/nano_broadwell-6.1_2.5.1-2.spk.zip)

**Comment by olamaekle** [comment]
@ymartin59 The package works fine on my DS3617xs. Thanks
