### ISSUE TITLE
Synology DS3617, Missing packages

### ISSUE THREAD

**Issue by MACE-Zer0** [SynoCommunity/spksrc#2718]
Hello , dont know if its the right place , but i dont see many of the packages of https://packages.synocommunity.com/ , in my new ds3617 , i have a similar one here the ds3615 , and i see all the packages ,  do i need to do something or is the ds3617 not compatible with these packages , hope not because i need a few of those , 

if im not in the right place i apologise

A few i see missing :
chromaprint 
mediainfo 
disktutils
git 
gitserver
ZNC
Zshell,

many more

Thanks

**Comment by MACE-Zer0** [comment]
Can anyone help me out , have the nas on hold , because i need a lot of missing packages that are only missing in ds3617xs , have tired reinstalling nas  , changed dns servers , but still nothing , in other nas i have  all the packages ..... help !!!!

**Comment by MACE-Zer0** [comment]
The only packages i see 

![image](https://cloud.githubusercontent.com/assets/9946471/24331431/45f20b36-122c-11e7-8a51-2aa1a15cd0ad.png)


![image](https://cloud.githubusercontent.com/assets/9946471/24331434/517e1dfa-122c-11e7-9826-5cb1ed3e7a0f.png)

**Comment by ymartin59** [comment]
What is your DSM version on new NAS ? It is possible missing packages are only available for DSM 5.2 - supposing packages you are interested in on your previous NAS when running DSM 5.2. Is my hypothesis relevant/right ?

**Comment by MACE-Zer0** [comment]
Both nas has the most recent version , 6.1-15047, and  iv always had all the packages no mather the version installed , this has something to do with the DS3617 because its very recent model of synology , but i need help from someone in synocommunity , because iv tried all that i can remember

**Comment by ymartin59** [comment]
Almost no package for DSM 6 is available because of #2216 . Compilation toolchain is not available for your platform yet #2509 

Sorry but nothing can be done for the moment, and there is no other reason that packages are not available for your sytem. Do not spend more time trying to "fix" it... except if you are interested in helping testing packages for instance.

**Comment by MACE-Zer0** [comment]
@ymartin59  , thanks for the info , havent seen those issues , guess only have to wait !!!

**Comment by ymartin59** [comment]
@MACE-Zer0 Toolchain for your system is available but I have no idea when packages may be published to package repository. As your system supports Docker, it may be possible for you to build packages you are interested in directly on your Synology. If interested, I may provide details about this process.

**Comment by nicky1038** [comment]
I guess I have a similar problem. Just installed Dr-Dean's Mercurial 4.0.1-4 to my DS216j (DSM 6.1-15047 Update 2), and I can't see its icon in the main menu.

**Comment by gierran** [comment]
DS3617xs here - just showing my interest for the missing packages. Docker works as a stopgap, but struggling with the permissions changes in DSM 6. Thanks for the great work bringing these apps to synology. :)

**Comment by aamri111** [comment]
@ymartin59 Can you guide me how to modify packages so I can make it supporting DS3617xs?

**Comment by ymartin59** [comment]
To get most of these packages for DSM 6.1 and , you have to built them from sources with `make arch-broadwell-6.1`. As my pull request #2727 with DSM 6.1 toolchains is not included yet, I propose you use my branch with a `git clone -b dsm6-toolchains-6.1 https://github.com/ymartin59/spksrc.git`

Then follow instructions to get and start SynoCommunity Docker container https://github.com/SynoCommunity/spksrc/blob/master/README.rst so that you can build packages (produced in `packages/` folder) for your own platform. 

```
cd /spksrc/spk/mediainfo
make arch-broadwell-6.1
```

**Comment by koljaschluetter** [comment]
I have the exact same issue on a DS3617 - I can only see a fraction of the packages (same as the screenshot above). I migrated from a DS216play - same DSM version as I'm running now. I don't understand what should be the issue from DSM 6.1 - all missing packages ran flawlessly on the DS216play on the same DSM version. Can you enlighten me or post a more detailed version on how to build the correct version for this branch(?)?

Thanks very much.

**Comment by justme-1968** [comment]
i have just migrated from a ds1813+ to a ds3617xs and dsm shows debian chroot, git, python and sabnzbd as defect and says i should reinstall. but the packages are not visible in the repository.

but: if i start the packages manualy with the start-stop script they just work. so i think just adding broadwell to the the package description should be enough to get them installable.

**Comment by justme-1968** [comment]
changing arch in the package INFO file from x86 to x86_64 fixes the error for sabnzb, debian-chroot, python and git.

then everything works on a ds3617xs.

**Comment by justme-1968** [comment]
same for the mediainfo package. which is not installable from package center.

i just copied the installation over from a ds710+, changed the arch in the INFO file and it works.

**Comment by ymartin59** [comment]
Correct. Recent package published for "braswell" have been aliased to "x86" arch instead of "x86_64"

**Comment by ymartin59** [comment]
I have just republished mediainfo and ffmpeg. May you please test them from repository ?

**Comment by justme-1968** [comment]
i still don't see both packages in packet center or you you mean building from source?

**Comment by mayson14** [comment]
DSM 6.1.3-15152 Update 4.  Same Issue.

![image](https://user-images.githubusercontent.com/8452532/30393316-81ae4fb2-9874-11e7-9988-4e28313d2877.png)

**Comment by ymartin59** [comment]
Sorry I missed my target. I have published "mediainfo" 0.7.99 for broadwell (even if built with dsm 5.2 toolchains). If correct now - visible and installable, I have a way to publish other packages, if not constrained by DSM 6.x support.

**Comment by justme-1968** [comment]
the mediainfo package ist now visible, installable and working. there are some warnings related to missing library version info but that is due to dsm5.2 vs dsm6.x and has been like this 'forever'.

the other packages i mentioned above (sabnzb, debian-chroot, python and git) all work flawless since i got the ds3617xs and 'fixed' manually.

**Comment by aamri111** [comment]
@justme-1968 do you have the modified spks so we can install it manually?

**Comment by justme-1968** [comment]
unfortunately no. i still had the installed packets in the file system.

**Comment by aamri111** [comment]
Thanks. I hope if someone can help us to get the spk files so we can manually install it for ds3617xs

**Comment by justme-1968** [comment]
are there any news about this? mediainfo has again disappeared from the package center, the others are still not available.

**Comment by ZeekWorld** [comment]
Any updates, same issue with latest Synology DSM 6.1.3-15152

**Comment by Drakuhl** [comment]
I assume this issue is just not high enough in the priority change. It would be nice if this could be made to work for those of us with a cleanly installed DS3617xs.

**Comment by justme-1968** [comment]
is there anything we can do to help getting this simple config change into all packages ?

**Comment by benjaminwood** [comment]
Same boat here. This is all I see:

![image](https://user-images.githubusercontent.com/1232531/33598742-b0452222-d958-11e7-9b5c-982edb75dded.png)

**Comment by Metalkaz** [comment]
Exactly the same issue on my new DS218play , and i see all the packages with my old DS413j

**Comment by hamishsw** [comment]
Same issue for me, looking to get Transmission/Sonarr onto my DS918+ running DSM 6.1.4-15217 Update 2 and only see a very much reduced number of packages vs. https://synocommunity.com/packages

**Comment by smeijer** [comment]
I have the same packages visible as @benjaminwood , worth mentioning; the packages that I see, cannot be installed due to the unavailable `git` and `python` packages, which are required by a lot of them.

**Comment by Noppes** [comment]
![image](https://user-images.githubusercontent.com/1127987/34640521-4e3810d4-f2f4-11e7-86c4-87e7c96a7773.png)
Same issue DS218+ DSM 6.1.4-15217 Update 5

**Comment by d3smo** [comment]
Same issue here impossible to install any package dependent of git or python from synocommunity, or from a local copy of a Sickrage Fork. My hardware is a DS418 freshly migrated from a DS213J

**Comment by d1000pt** [comment]
+1 installing DS918+ only a few packages available and no git, python or sonarr.

**Comment by d3smo** [comment]
@d1000pt you can certainly find python compiled for your hardware here https://github.com/Safihre/spksrc/releases/

**Comment by d1000pt** [comment]
@d3smo thanks but actually none of the versions still install git. Every single version say invalid file format.

I tought was doing an upgrade to my DS916+ going to DS918+ and now I can't install any of my favorite apps (couchpotato, sonarr, sabnzbd, etc). Anyone now the timmings for resolution?

Cheers everyone

**Comment by dcasbonne** [comment]
@d3smo thank you, your python successfully installed on DS718+ using python_apollolake-6.1_2.7.14-17.spk

But when I try to install SickRage for example it says "python and git are not available on the package repository" so I could not install anything...

Could you explain me how to compile using spksrc and docker on my DS718+ ? I'm an application developer and I'm not stranger to terminal commands but I can't succeed... When I clone the official docker image, the folder spksrc is empty. I tried to clone a git repo and then do a "make arc-apollolake" but nothing works...

Thank you for your help !

**Comment by d3smo** [comment]
@dcasbonne sorry but i just find these package already compile for the RTD1296, and i don't know how to proceed, maybe asked to the owner of the repository where they are.

**Comment by dcasbonne** [comment]
@d3smo sorry, I thought that it is your repo!

**Comment by Safihre** [comment]
**New packages converted for generic service account, DSM6 compatibility and new architecture compatibility. [All are still in testing](https://github.com/SynoCommunity/spksrc/pulls)!**

If you experience problems (not requests for other packages), please send me logs at safihre@sabnzbd.org

- [NZBGet](https://github.com/Safihre/spksrc/releases/tag/nzbget-dsm61-new-all)
- [Python](https://github.com/Safihre/spksrc/releases/tag/python-dsm61-new-all) _(Updated since last post! Please update to this one)_
- [SABnzbd](https://github.com/Safihre/spksrc/releases/tag/sabnzbd-dsm61-new-all) _(Updated since last post! Please update to this one)_
- [Git](https://github.com/Safihre/spksrc/releases/tag/git-dsm61-new-all)
- [CouchPotato](https://github.com/Safihre/spksrc/releases/tag/cp-dsm61-new-all)
- [Sickrage](https://github.com/Safihre/spksrc/releases/tag/sickrage-dsm61-new-all)
- [Syncthing](https://github.com/Safihre/spksrc/releases/tag/syncthing-dsm61-new-all)

**Comment by dcasbonne** [comment]
Hi @Safihre ! Thank you for your work I'll try this asap but on your python-dsm61-new-all I'm not able to find any compiled packages, only sources... What I'm missing ?

**Comment by Safihre** [comment]
Python package is recompiling with the [UTF8 fix](https://github.com/SynoCommunity/spksrc/issues/2945#issuecomment-357216168), give it ~30 min 🕦

**Comment by dcasbonne** [comment]
Oups, too fast :) Thank you again, I'll let you know if it works

**Comment by m4tt075** [comment]
@Safihre Could you please add `ffmpeg` to the list (compiled off master)? Here the [link](https://github.com/m4tt075/spksrc/releases/tag/ffmpeg-3.3.3)

And an idea: Would it make sense to open a new issue, just for your list, that you keep updated and where you lock conversations? You would just have one list to maintain, we could keep the package-specific discussions in "their" issue threads and simply refer to the list across different issues and PRs whenever needed...

**Comment by silentmiles** [comment]
Hi All,

First off, thank you @Safihre and @m4tt075 for creating these packages! I've successfully installed Git, Python, Mono and Jackett on my DS918+ (apollolake), and they work fine.

Two questions:

1. Will these eventually appear in the standard Synology Community repo? And a related question, why is that repo so slow to update? I know the DS918+ has been out for only about 4 or 5 months, but it's still not supported, and I'd think this would be long enough?

2. Does anyone know if/how I can get Sonarr and Radarr compiled for apollolake?

Thanks!

**Comment by Safihre** [comment]
Well.. Too much work, not enough volunteers. 
This is not a Synology supported effort, it's all based on people volunteering to do work for other people.. 

Working on Sonarr, turned out to have a few more unexpected bumps. But once that's done, Radarr will be easy ported.

**Comment by silentmiles** [comment]
Fair enough! Thanks for you efforts.

**Comment by m4tt075** [comment]
@silentmiles 

What @Safihre said. And I want to add some points to your first questions and share a little bit of history. There have been two major(!) problems with the spksrc framework since DSM 6.0 was introduced: 

Firstly, Synology changed the permission management completely and it took months to figure out what they did. One of the key developers for a very long time (@Dr-Bean ) made significant advancements, but suddenly left. I very much hope he is well. But even then, there was a challenge to create packages which are compatible with DSM5 and 6 at the same time. Only pretty recently @ymartin59 was able to solve this issue and introduced scripts to facilitate building DSM 5+6 packages. We are only able to build good packages again, because @ymartin59 eventually solved the underlying issues and we can use his generic scripts. With DSM6 compatibility, the addition of new architectures is typically not much of an issue (the new rtd1296 platform is an exception). 

Secondly, the repository you have been mentioning has neither been built for DSM6+, nor is it able to handle volume and traffic appropriately anymore. It is again @ymartin59 , who took a time-out from working on the packages, to look into these more fundamental problems together with @Diaoul .

Just wanted to clarify this, as this is not about "a new Syno model" or "quick fixes". It will take as long as it takes. But I also want to ensure that @ymartin59 's significant contributions to the recent advancements are understood and appreciated.

**Comment by Safihre** [comment]
Indeed!
Does make me wonder why Synology is not supporting this project more. It's by far the largest community effort, yet it seems (correct me if I'm wrong) they have no contact here at all.. 
But getting off topic now 😊

**Comment by Safihre** [comment]
New package list here (just added Sonarr/Radarr): https://github.com/SynoCommunity/spksrc/issues/2945#issuecomment-357008518

**Comment by justme-1968** [comment]
could you please try to add python to the new builds?

pyplex and some other packages depend on it.

thanks !

**Comment by Safihre** [comment]
Did you click the link? 🤔 Python is already there for a long time..

**Comment by Drakuhl** [comment]
Python indeed works and many packages now work with it, however Mylar still seems to be able to recognize it. When trying to install Mylar, it still lists Python as missing.

**Comment by justme-1968** [comment]
missed python in the link. updated to this version and my old packages still work. 

but plexpy ist still not installable. it says python is missing.

**Comment by tnaseem** [comment]
Any idea if/when deluge would be available on the 918+? (DSM 6.1.5-15254).

**Comment by Safihre** [comment]
Deluge test-package available in #3138.
In case of problems, please post:
`/volume1/@appstore/deluge/var/delug.log` and
`/volume1/@appstore/deluge/var/delug_install.log`

**Comment by ymartin59** [comment]
DS3617 architecture is now supported and packages are coming. I decide to close this issue. Please follow package specific "update issue" according to your interests.

**Comment by myca5a** [comment]
Hello,
I have the same bug with my DS420+.
I need wait ?

thank's
