### ISSUE TITLE
Missing Input in the wizard while installing the packages for 'Firefox Sync Server 1.5 BETA'

### ISSUE THREAD

**Issue by ghost** [SynoCommunity/spksrc#2748]
### Setup
_Package Name:_ffsync
_Package Version:_1.5.2_3

_NAS Model:_DS213+
_NAS Architecture:_MARVELL Kirkwood 88F6282
_DSM version:_DSM 6.1-15047 Update 2

### Expected behavior
I would like to have an extra input in the wizard to specify another database user.

### Actual behavior
The current database user is 'root'

### Steps to reproduce
_1._Go in the package center (included synocommunity packages on http://packages.synocommunity.com
_2._Click on install packages "Firefox Sync Server 1.5 BETA"
_3._See the first wizard window

**Comment by ymartin59** [comment]
If implemented as DSM 6.x resource according to #2747 , database connection will use a hard-coded package specific user account in MariaDB. I do not expect database user account can be provided from a wizard.

**Comment by mreid-tt** [comment]
The original Firefox Sync Server, as indicated in its [source repository](https://github.com/mozilla-services/syncserver), is no longer actively maintained. Instead, it has been redeveloped in Rust and is now hosted in a new repository called [Syncstorage-rs](https://github.com/mozilla-services/syncstorage-rs). The upcoming release, associated with the Pull Request [5942](https://github.com/SynoCommunity/spksrc/pull/5942) in the SynoCommunity/spksrc repository, will soon replace all prior versions of the package due to their deprecated functionality.

We invite interested individuals to explore the Checks tab at [this link](https://github.com/SynoCommunity/spksrc/pull/5942/checks) for the opportunity to download a pre-release version for testing purposes. Your valuable feedback is highly appreciated and encouraged before the final release.
