### ISSUE TITLE
Tvheadend desktop link point to wrong URL

### ISSUE THREAD

**Issue by DjMomo** [SynoCommunity/spksrc#2764]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Tvheadend
_Package Version:_ 3.4.27-6

_NAS Model:_ DS1511+
_NAS Architecture:_ Intel
_DSM version:_ DSM 6.1.1-15101 Update 1

### Expected behavior
Tvheadend desktop link have to point to http://IP:9981

### Actual behavior
Tvheadend desktop link point to wrong URL. This link open URL http://IP/3rdparty/tvheadend/tvheadend.cgi

**Comment by mastacheata** [comment]
This is definitely fixed in the latest update to the tvheadend package (4.2.2) by m4tt075 
His packages are just waiting to be deployed on the synocommunity package server.

Apparently you can build the package in a virtual machine (at least m4tt075 succeeded in that, I couldn't test the VM approach yet) and install the spk just fine.

**Comment by ymartin59** [comment]
@mastacheata @m4tt075 Is this issue still relevant now ?

**Comment by m4tt075** [comment]
@ymartin59: I have never noticed to be honest. I have just PRed #2841 for a possible fix. 
@mastacheata and @DjMomo : Can you test and confirm the fix?

**Comment by mastacheata** [comment]
I'll try to check this tomorrow.
No idea if the problems with building openSSL are fixed by updating to the newer version, though...

**Comment by m4tt075** [comment]
This has been confirmed as fixed by a user on another forum. Guess it can be closed now.

**Comment by ymartin59** [comment]
@KaraokeStu May you please close this issue. Thanks

**Comment by m4tt075** [comment]
@ymartin59 Can you close this, please (if possible)?
