### ISSUE TITLE
Missing Packages

### ISSUE THREAD

**Issue by TheOriginalSkunk** [SynoCommunity/spksrc#2776]
Im running DSM 6.1.1 and I have installed the package and ticked beta builds but I'm missing a lot of apps such as Sonarr, Radarr and NZBget

**Comment by JoelOnGithub** [comment]
I am having the same issue.

I have a synology DS216+II, with DSM 6.1.1-15101 Update 2. Here I see Bittorrent Sync as a package.

I also have a synology DS114, with DSM 6.1.1-15101 Update 4, and here I do not see Bittorrent Sync as a package!

**Comment by joost14** [comment]
I am also having the same issue. 

Im running dsm 6.1. Packes like transmission, Sonarr etc.

**Comment by ymartin59** [comment]
At the moment, DSM 6.1 packages are not available in online repository. Only DSM 5.2 are available and some are still running well on recent versions.

To get most of these packages for DSM 6.1 and , you have to built them from sources. As my pull request #2727 with DSM 6.1 toolchains is not included yet, I propose you use my branch with a `git clone -b dsm6-toolchains-6.1 https://github.com/ymartin59/spksrc.git`

Then follow instructions https://github.com/SynoCommunity/spksrc/blob/master/README.rst to get and start SynoCommunity Docker container so that you can build packages - produced in `packages/` folder - for your own platform, select your arch from https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model and listed in `toolchains/` folder.

```
cd /spksrc/spk/mediainfo
make arch-ARCH-6.1
```

**Comment by ymartin59** [comment]
Related to #2718

**Comment by Safihre** [comment]
@KaraokeStu @Dr-Bean the path to full DSM 6 support is still very long?

**Comment by koljaschluetter** [comment]
Push. Same issue here.

**Comment by xadonxander** [comment]
Tried to build my own and some of the packages in the list are not found in the apt repository. it's too complicated I just want it to work that is why I use synology and not freenas.

**Comment by gravelld** [comment]
In the absence of any other overall meta issue for DSM 6.x (that I have the rights to contribute to) I just wanted to feed this back...

I came to this project because I was interested in the Chromaprint package and was initially willing to build it myself. When I reviewed the SynoCommunity site and these GitHub pages I was initially very confused as to why everything still seemed to revolve around DSM 5.x... DSM 6.x has been out for a long time now and is surely by far the most commonly used version (I have no citations for that, just my expectation), and the toolchain has been available at least since early this year... February was it?

I think everyone does a great job here, but I just wanted to communicate my initial experiences. KUTGW!

**Comment by ymartin59** [comment]
For information, the package repository, code running to provide online https://synocommunity.com/packages has to be updated to support DSM 6.x (and probably SRM 1.x too)

PR has been submitted by @Dr-Bean but still requires testing before turning it ON to production hosted by community founder @Diaoul

**Comment by gravelld** [comment]
Thanks - I made an attempt to edit the Wiki: https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions/492805ea22789e32853183cbd00b9ed1b09e9920

**Comment by ymartin59** [comment]
Good idea. Thanks

**Comment by ymartin59** [comment]
I close this "me too" issue, now explained in FAQ
