### ISSUE TITLE
Firefox Sync Server not working with latest MariaDB update

### ISSUE THREAD

**Issue by Protarios** [SynoCommunity/spksrc#2816]
Firefox Sync Server (1.5.2-3) is not working anymore with latest update of MariaDB.

Synology updated MariaDB lately, renaming the existing install of MariaDB to "MariaDB 5" and introducing a parallel installed "MariaDB 10" version.
This update broke Firefox Sync server. Maybe because of the rename?

After deinstalling Sync Server and trying to reinstall it, it won't install, telling me the MySQL root password is wrong (which isn't, I even tried resetting it)

**Comment by eddieirvine** [comment]
I'm facing the same issue.
Since the MariaDB update Firefox Sync is not working any longer.

**Comment by ollrich** [comment]
Same here, doesn't work anymore...

@Protarios to get rid of the root passwort error, you have to login with your admin credentials via ssh, then
`sudo -i`

to become root and then create the directory /usr/syno/mysql/bin/
(/usr/syno/ already exists) - when you made this folder, setup the symlink 

`ln -s /volume1/@appstore/MariaDB/usr/bin/mysql /usr/syno/mysql/bin/mysql`

and you shouldn't get the error anymore.

**Comment by ollrich** [comment]
Ok, after re-install, it seems pretty well again. Maybe the mentioned symlink is the solution.

**Comment by eddieirvine** [comment]
Thanks, ollrich!
The symlink did the trick!
Sync between my Windows PCs is working again.

But Fx on Android still doesn't sync.
No synchroniyed devices are shown and if I tab on "Synchronized devices", it says "Login to synchronize your bookmarks etc." although I'm already  logged in.
Maybe there's an issue with Fx on Android...

Does it work for you on Android?

**Comment by ollrich** [comment]
I also got issues with Android, long before MariaDB10 came. My initial setup worked really fine, just 2 month ago. Seems to be an issue because of one of the lasts Fx updates

Did you setup your sync-server in the identity.sync.tokenserver.uri entry? Than you should see your Android device at least in the fx sync account settings.

I guess Fx on Android can't work with the Reverse Proxy settings anymore but I didn't figured out how to get rid of that yet.

**Comment by eddieirvine** [comment]
I dropped my mobile into a river and had to switch to my old phone :(
There Fx 54.0.1 syncs perfectly...

**Comment by eddieirvine** [comment]
Still not working properly...
Got a new mobile. Logon works and I can also see the tabs opened on others PCs.
But no passwords are synced etc.

**Comment by ollrich** [comment]
Sounds strange! Shouldn't be an issue of the device since Firefox as an app should do the same job on every Android device.

I didn't try to sync in my home network yet. Got no time to get deeper in it in the last days.

Are you using your SSL on your Diskstation and did you configure the reverse proxy then?

**Comment by eddieirvine** [comment]
Yes, i'm using reverse proxy on my DS.
I point from 'https://ffsync.mydomain.com' to 'http://localhost:8132'.

If I copy/paste the value 'https://ffsync.mydomain.com/token/1.0/sync/1.5' of preference 'identity.sync.tokenserver.uri' to the address bar, then I still see 
'{"status": "error", "errors": [{"location": "body", "name": "", "description": "Unauthorized"}]}'.

This was always the case and has worked so far.

**Comment by ollrich** [comment]
You didn't set a port for the external url? My first (working) configuration was like:
`https://sync.domain.com:8133/token/1.0/sync/1.5`

In reverse proxy I did a redirection from the extern URL with 8133 to the localhost with 8132. Like you did but with the :8133 in the external URL. Both ports (I guess, at least the 8133) has to be opened in the modem/ router to be reachable from the internet.

And in the ffsync.ini is a change necessary:
`force_wsgi_environ = true`

I know that the desktop version of Fx is better in handling with the url when the wsgi is set true and guessing that this part is responsible for the (new) trouble with Android.

Will try to get deeper into it this weekend.

**Comment by eddieirvine** [comment]
Yes, I use port 443, because my employer only allows 80 and 443.
But in the end our configs should be equal, no matter if you use port 8133 or 443,

I think that I've set

> force_wsgi_environ = false

, but it always was...
I just changed 

> public_url = https://ffsync.mydomain.com/

**Comment by ymartin59** [comment]
Related to #2828

**Comment by stealz0ne** [comment]
after finding an error message cocerning mysqldump on a fresh install of the addon, I took olrichs advice but made two links:
```
ln -s /volume1/@appstore/MariaDB/usr/bin/mysql /usr/syno/mysql/bin/mysql
ln -s /volume1/@appstore/MariaDB/usr/bin/mysqldump /usr/syno/mysql/bin/mysqldump

```
after that it worked. 
Just thought I'd share.

**Comment by mreid-tt** [comment]
The original Firefox Sync Server, as indicated in its [source repository](https://github.com/mozilla-services/syncserver), is no longer actively maintained. Instead, it has been redeveloped in Rust and is now hosted in a new repository called [Syncstorage-rs](https://github.com/mozilla-services/syncstorage-rs). The upcoming release, associated with the Pull Request [5942](https://github.com/SynoCommunity/spksrc/pull/5942) in the SynoCommunity/spksrc repository, will soon replace all prior versions of the package due to their deprecated functionality.

We invite interested individuals to explore the Checks tab at [this link](https://github.com/SynoCommunity/spksrc/pull/5942/checks) for the opportunity to download a pre-release version for testing purposes. Your valuable feedback is highly appreciated and encouraged before the final release.
