### ISSUE TITLE
Compile ffsync

### ISSUE THREAD

**Issue by Martijn085** [SynoCommunity/spksrc#2828]
I can't compile ffsync anymore.

I run this command from the folder: **/spksrc/spk/ffsync** : **make arch=x86-6.0.2**

This is the error message i get:

`===>  Compiling for bzip2
cd /spksrc/spk/ffsync/work/bzip2-1.0.6 && env PKG_CONFIG_LIBDIR=/spksrc/spk/ffsync/work/install//usr/local/ffsync/lib/pkgconfig WORK_DIR=/spksrc/spk/ffsync/work INSTALL_PREFIX=/usr/local/ffsync make bzip2 bzip2recover PREFIX=/spksrc/spk/ffsync/work/install/usr/local/ffsync
make[3]: Map '/spksrc/spk/ffsync/work/bzip2-1.0.6' wordt binnengegaan
make[3]: 'bzip2' is up-to-date.
make[3]: 'bzip2recover' is up-to-date.
make[3]: Map '/spksrc/spk/ffsync/work/bzip2-1.0.6' wordt verlaten
cd /spksrc/spk/ffsync/work/bzip2-1.0.6 && env PKG_CONFIG_LIBDIR=/spksrc/spk/ffsync/work/install//usr/local/ffsync/lib/pkgconfig WORK_DIR=/spksrc/spk/ffsync/work INSTALL_PREFIX=/usr/local/ffsync make -f Makefile-libbz2_so PREFIX=/spksrc/spk/ffsync/work/install/usr/local/ffsync
make[3]: Map '/spksrc/spk/ffsync/work/bzip2-1.0.6' wordt binnengegaan
cc -shared -Wl,-soname -Wl,libbz2.so.1.0 -o libbz2.so.1.0.6 blocksort.o huffman.o crctable.o randtable.o compress.o decompress.o bzlib.o
/usr/bin/ld: blocksort.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
blocksort.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile-libbz2_so:32: recept voor doel 'all' is mislukt
make[3]: *** [all] Fout 1
make[3]: Map '/spksrc/spk/ffsync/work/bzip2-1.0.6' wordt verlaten
Makefile:24: recept voor doel 'myCompile' is mislukt
make[2]: *** [myCompile] Fout 2
make[2]: Map '/spksrc/cross/bzip2' wordt verlaten
../../mk/spksrc.depend.mk:44: recept voor doel 'depend_target' is mislukt
make[1]: *** [depend_target] Fout 2
make[1]: Map '/spksrc/cross/python' wordt verlaten
../../mk/spksrc.depend.mk:44: recept voor doel 'depend_target' is mislukt
make: *** [depend_target] Fout 2`

Anyone can help me out to fix this?

**Comment by ymartin59** [comment]
I suppose you build from `dsm6` branch. May you please try again invoking `make arch-x64-6.0.2` ?

**Comment by ymartin59** [comment]
I have other troubles because of an "invalid source location" concerning `libev`:

```
===>  Downloading files for libev
wget http://dist.schmorp.de/libev/libev-4.22.tar.gz
http://dist.schmorp.de/libev/libev-4.22.tar.gz:
2017-07-24 07:43:35 ERROR 404: Not Found.
```

Readme clearly states to hard-code Attic, so we will do: http://dist.schmorp.de/libev/README

**Comment by ymartin59** [comment]
From my point of view `ffsync` requires a full update and review to be packaged again.

**Comment by MysteryWoMan** [comment]
> I have other troubles because of an "invalid source location" concerning libev:
Had the same. Just change the version of libev in the requirements from 4.22 to (at this moment) 4.24
I also remembered I had to update cd SHA1 , SHA256 and MD5 checksum to that of 4.24

**Comment by mreid-tt** [comment]
The original Firefox Sync Server, as indicated in its [source repository](https://github.com/mozilla-services/syncserver), is no longer actively maintained. Instead, it has been redeveloped in Rust and is now hosted in a new repository called [Syncstorage-rs](https://github.com/mozilla-services/syncstorage-rs). The upcoming release, associated with the Pull Request [5942](https://github.com/SynoCommunity/spksrc/pull/5942) in the SynoCommunity/spksrc repository, will soon replace all prior versions of the package due to their deprecated functionality.

We invite interested individuals to explore the Checks tab at [this link](https://github.com/SynoCommunity/spksrc/pull/5942/checks) for the opportunity to download a pre-release version for testing purposes. Your valuable feedback is highly appreciated and encouraged before the final release.
