### ISSUE TITLE
Request for adding the Requests module tot the pyhon package

### ISSUE THREAD

**Issue by BenjV** [SynoCommunity/spksrc#2857]
### Setup
_Package Name: Python
_Package Version: 2.7.13-16

_NAS Model:_ALL
_NAS Architecture: NO-ARCH
_DSM version: DSM 6

The python request package is used in many applications.
It would be nice to have it included in the python distribution of the SynoCommunity.

Request can be found here:
https://github.com/requests/requests

```

**Comment by Diaoul** [comment]
You can use pip to install it (have to redo it after package update) or better, create a virtualenv and install it from here.

The Python SPK only contains packages that have a C-extension because they require compilation and cannot be easily installed by pip.
The requests package is pure-python and thus doesn't require compilation.
