### ISSUE TITLE
Can't uninstall ffsync

### ISSUE THREAD

**Issue by ghost** [SynoCommunity/spksrc#2873]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Firefox sync Server 1.5
_Package Version:_

_NAS Model:_ ds414
_NAS Architecture:_
_DSM version:_6.1.3 update 1

### Expected behavior
Can't unistall firefox sync server , can't make run firefox sync server. When try unistalling say error mysql passoword. i try reset it in mariadb,  try make it new one ... problem persist.
 I try look online for problem but some post don't solve me.
Thank's

**Comment by ymartin59** [comment]
Known issue with some DSM 5.2 packages after upgrade of DSM to 6.x
From my point of view, this will wait package updates to both DSM 5.2 and DSM 6.1 when available to do so.

**Comment by ioio123** [comment]
Thank's for answer,

so i have to wait?, little annoying have service that use resource of nas and can't unistall.

Thankl's.


??
??
??
??
Questo messaggio e-mail ?? riservato unicamente al/ai soggetto/i destinatario/i e pu?? contenere informazioni riservate e/o coperte da segreto professionale utilizzabili esclusivamente dal/i destinatario/i sopraindicato/i. Il ricevente, se diverso dal destinatario, ?? avvertito che qualsiasi utilizzazione, divulgazione o copia di questa comunicazione, nonch?? di eventuali suoi allegati, comporta la violazione delle disposizioni di Legge sulla tutela dei dati personali (D.Lgs 196/2003). Qualora il messaggio fosse ricevuto per errore, si prega di cancellarlo e distruggere eventuali copie o stampe e di darne informazione immediata al mittente. Grazie.


________________________________
Da: Yves Martin <notifications@github.com>
Inviato: martedì 15 agosto 2017 18:49
A: SynoCommunity/spksrc
Cc: ioio123; Author
Oggetto: Re: [SynoCommunity/spksrc] Can't unistall (#2873)


Known issue with some DSM 5.2 packages after upgrade of DSM to 6.x
From my point of view, this will wait package updates to both DSM 5.2 and DSM 6.1 when available to do so.

**Comment by eddieirvine** [comment]
I just bought a RasPi and will install the sync server there.
I'm fed up of waiting for a package update.

Fx Sync server in the Synology package is out of date for Android devices:
https://bugzilla.mozilla.org/show_bug.cgi?id=1382666

**Comment by ymartin59** [comment]
@eddieirvine as you want, by the way, you may have invest your time in updating package, why not ?

@ioio123 from my point of view, there is no resource consumed. Service is not started and package may wait maximum  30 MiB... on a NAS, sounds like affordable.

**Comment by ioio123** [comment]
how can update package by myself?


??
??
??
??
Questo messaggio e-mail ?? riservato unicamente al/ai soggetto/i destinatario/i e pu?? contenere informazioni riservate e/o coperte da segreto professionale utilizzabili esclusivamente dal/i destinatario/i sopraindicato/i. Il ricevente, se diverso dal destinatario, ?? avvertito che qualsiasi utilizzazione, divulgazione o copia di questa comunicazione, nonch?? di eventuali suoi allegati, comporta la violazione delle disposizioni di Legge sulla tutela dei dati personali (D.Lgs 196/2003). Qualora il messaggio fosse ricevuto per errore, si prega di cancellarlo e distruggere eventuali copie o stampe e di darne informazione immediata al mittente. Grazie.


________________________________
Da: Yves Martin <notifications@github.com>
Inviato: giovedì 17 agosto 2017 19:03
A: SynoCommunity/spksrc
Cc: ioio123; Mention
Oggetto: Re: [SynoCommunity/spksrc] Can't unistall (#2873)


@eddieirvine<https://github.com/eddieirvine> as you want, by the way, you may have invest your time in updating package, why not ?

@ioio123<https://github.com/ioio123> from my point of view, there is no resource consumed. Service is not started and package may wait maximum 30 MiB... on a NAS, sounds like affordable.

**Comment by eddieirvine** [comment]
@ymartin: Yes, I could maybe help.
But I'm not a Linux specialist...

And actually I prefer to keep my NAS inside my network and access it through VPN.
Then only the RasPi must be accessible from outside.

**Comment by ymartin59** [comment]
OK so why complaining about outdated package, you seem to be able to install/deploy on a RasPi. I do not consider more difficult to manually deploy Fx Sync on Synology where Python is available, compared to a Linux distro install on RasPi to get same application running there.
By the way, I add this update Fx Sync to my todo list

**Comment by ymartin59** [comment]
Related to #2828

**Comment by elalmago** [comment]
Package Name: Firefox sync Server 1.5

NAS Model: ds1513+
DSM version: DSM 6.2.4-25556

I am also unable to uninstall Firefox sync Server 1.5. When I try to do so, it asks for MySQL Password and afterwards it says the password is wrong. 

Since I am able to login to MariaDB 5 and/or connect to the databases using MyPHPAdmin using the same password, this must be an issue woth the package itself. Can samobody help?

Maybe there is a way to uninstall it manually via Telnet/SSH Session? If yes, can somebody provide how to achive that?

Thank you

[SynoProb.pdf](https://github.com/SynoCommunity/spksrc/files/6792469/SynoProb.pdf)

**Comment by hgy59** [comment]
To uninstall:

1. remove the firewall rules for ffsync
2. remove the `/var/packages/ffsync` folder
```
servicetool --remove-configure-file --package ffsync.sc

rm -rf /var/packages/ffsync
```

You need administrator privileges, so login with ssh into your diskstation with an administrator account or use `sudo` to execute the commands above.

**Comment by elalmago** [comment]
Thank you hgy59, it seems I was able to get rid of ffsync following the instructions provided by you. 👍

**Comment by mreid-tt** [comment]
The original Firefox Sync Server, as indicated in its [source repository](https://github.com/mozilla-services/syncserver), is no longer actively maintained. Instead, it has been redeveloped in Rust and is now hosted in a new repository called [Syncstorage-rs](https://github.com/mozilla-services/syncstorage-rs). The upcoming release, associated with the Pull Request [5942](https://github.com/SynoCommunity/spksrc/pull/5942) in the SynoCommunity/spksrc repository, will soon replace all prior versions of the package due to their deprecated functionality.

We invite interested individuals to explore the Checks tab at [this link](https://github.com/SynoCommunity/spksrc/pull/5942/checks) for the opportunity to download a pre-release version for testing purposes. Your valuable feedback is highly appreciated and encouraged before the final release.
