### ISSUE TITLE
I can't connect to the new Firefox Sync Server on my Synology

### ISSUE THREAD

**Issue by Catskan-zz** [SynoCommunity/spksrc#2885]
Hi,

I installed and setting up the Firefox Sync Server Package on my Synology, but I can't connect to with my Firefox 55.

In my about:config : 
![image](https://user-images.githubusercontent.com/17289964/29488562-e822c61c-850d-11e7-8f59-e8da745a2464.png)

And when I click on "Create account" : 
![image](https://user-images.githubusercontent.com/17289964/29488558-d85dedb0-850d-11e7-9653-c21167b8916f.png)

My Firefox sync log : 

[error-sync-1503102467875.txt](https://github.com/SynoCommunity/spksrc/files/1236505/error-sync-1503102467875.txt)

In tried many possibilities to add my server, and I have always the same error.

Thanks you in advance for your help !

Regards

### Setup
_Package Name:_ Firefox Sync Server
_Package Version:_ 1.5.2-3

_NAS Model:_ 716+II
_NAS Architecture:_ x64
_DSM version:_ DSM 6.1.3-15152 Update 3

**Comment by ymartin59** [comment]
Related to #2828 #2816 #2748 #2747 #2093

**Comment by mreid-tt** [comment]
The original Firefox Sync Server, as indicated in its [source repository](https://github.com/mozilla-services/syncserver), is no longer actively maintained. Instead, it has been redeveloped in Rust and is now hosted in a new repository called [Syncstorage-rs](https://github.com/mozilla-services/syncstorage-rs). The upcoming release, associated with the Pull Request [5942](https://github.com/SynoCommunity/spksrc/pull/5942) in the SynoCommunity/spksrc repository, will soon replace all prior versions of the package due to their deprecated functionality.

We invite interested individuals to explore the Checks tab at [this link](https://github.com/SynoCommunity/spksrc/pull/5942/checks) for the opportunity to download a pre-release version for testing purposes. Your valuable feedback is highly appreciated and encouraged before the final release.
