### ISSUE TITLE
Sabnzbd update 2.30

### ISSUE THREAD

**Issue by JySzE** [SynoCommunity/spksrc#2926]
When will the new Sabnzbd 2.30 update be pushed to the community? 

Thanks.

**Comment by ymartin59** [comment]
@Safihre I wonder if `BUILD_DEPENDS` with Python, pip and wheels are really required with new `WHEELS` support... Pure Python application package like `beets` does not declare such `BUILD_DEPENDS`. May it be possible to avoid building Python when packaging Sabnzbd ?

**Comment by ymartin59** [comment]
Building after merged PR #2924

**Comment by Safihre** [comment]
@ymartin59 Good question, probably not needed? As long as it gets a recent python (2.7.12+) and it can compile the `sabyenc` C-extension, that's all we need.

**Comment by ymartin59** [comment]
@Safihre I propose to check for possible options at next update. For instance include some native wheels in Python package itself, as it is requested for update too...

**Comment by ymartin59** [comment]
@JySzE Packages have been published: https://synocommunity.com/package/sabnzbd

**Comment by Safihre** [comment]
@ymartin59 Yes let's do that next update.
Could you also publish the update to the `sabnzbd-testing` [package](https://synocommunity.com/package/sabnzbd-testing)? Thanks!

**Comment by Safihre** [comment]
There used to be long gaps between releases with long testing phases before a final release, this has changed for SABnzbd with more incremental releases (because I personally like to get new stuff out to users quickly). So for SABnzbd it's not really required anymore I think. Can you see how many users there are on that package?

NZBGet usually has at least 4 months between releases, so getting new features could be a long wait. I am not sure why SynoCommunity compiles NZBGet from sources? I think most platforms should be able to use the `bin-linux.run` package, which would also allow in-app updates. 
The self-compiled version does not offer in-app updates and keeps users stuck on the original version. Maybe it's worth to take a look into that for supported platforms? Then you would never have to update NZBGet anymore on SynoCommunity.

**Comment by Safihre** [comment]
Actually I see that NZBGet linux installer only covers ["Linux kernel 2.6 and later, x86 (32 or 64 Bit), ARM, MIPS, PowerPC"](https://nzbget.net/download), so probably still quite some unsupported platforms for Synology.

I think for these packages in particular a Travis workflow with auto-publishing would make it very easy, only update of the digests and they would be good to go without any work for SynoCommunity maintainers.

**Comment by ymartin59** [comment]
From my point of view, the package flag `beta` should be used to provide "mixed" versions of the same package, so that users really have same package and future stable replace beta one. Moreover two packages requires more storage in repository. I really think we should propose users a migration path from testing to regular packages to get rid of that duplication/split.

**Comment by Safihre** [comment]
Sounds good to me!
