### ISSUE TITLE
[Request] Support RT2600AC router

### ISSUE THREAD

**Issue by thermoska** [SynoCommunity/spksrc#2951]
Hello

Would it be possible to support router RT2600ac by synocomunity ?
This router has a bump up in specs from previous version

I have seen some standalone recompiling here:
https://synopackages.wordpress.com/2016/02/21/synocommunity-packages-for-rsm/

and small thread here:

https://forum.synology.com/enu/viewtopic.php?t=114206

Thanks in advance

PS: I do have a root access to OS there. If it will help the community to support and migrate packages to SRM. I can provide information from this OS.

**Comment by CoskunSunali** [comment]
I would also like and wish to see the support for the RT2600ac which has higher specs than RT1900ac, including but not limited to CPU and memory.

> I have seen some standalone recompiling here:
https://synopackages.wordpress.com/2016/02/21/synocommunity-packages-for-rsm/

The newer versions of those packages (for RT2600ac) are here:
https://synopackages.wordpress.com/2017/04/23/synocommunity-packages-for-srm-1-1/

**Comment by ymartin59** [comment]
@publicarray According to https://www.synology.com/en-global/knowledgebase/SRM/help/SRM/PkgManApp/configure it is also possible to register a package source to SRM.

I have published Nano 2.9.5 for `ipq806x` in SynoCommunity repository with a firmware version `1.1-6931`.
I have no idea if SRM can grab it. May anyone please test it and report feedback?

**Comment by publicarray** [comment]
Sigh, the documentation is wrong. There is no "Package Sources" tab: 
![screen shot](https://user-images.githubusercontent.com/5497998/38782789-fef9b3b0-413b-11e8-8759-d9bf06ad7af5.png)

**Comment by ymartin59** [comment]
@publicarray Is it worth to search Synology forums or submit a support request to Synology about it? ... for instance in case it is an experimental feature that may be enabled? (I doubt they may release an update only for that reason...)

**Comment by publicarray** [comment]
I imagine they already know, but just in case I've send an email with a reference to this issue.

**Comment by publicarray** [comment]
Their reply:

> Sorry for the confusion.
>
>For SRM there's no "package source" tab, and it is wrong information on our website.
>
>Thank you for bringing it to our attention, and we've informed related department.
>
>Sorry for the inconvenience.

**Comment by ymartin59** [comment]
Sounds relevant to publish SRM packages too in repository, so a manual download is required: https://github.com/SynoCommunity/spkrepo/issues/13

**Comment by ymartin59** [comment]
CC @jlmkerr @piwi82 @ScoobyJD @publicarray
I have published zsh packages for SRM architectures in repository. Sounds like OK: https://synocommunity.com/package/zsh

According to https://synopackages.wordpress.com/2018/05/20/synocommunity-packages-for-srm-update-2018-05/
Nelek follows our PR and publish packages. I will invite him to follow our process and do testing on SRM.

@Safihre I have updated publish process to mention them: https://github.com/SynoCommunity/spksrc/wiki/Update-Policy

**Comment by Safihre** [comment]
Which packages should we compile now for those platforms? Same list as on Nelek website?

**Comment by publicarray** [comment]
@nelek I don't know how to contact you (I hope the GitHub username is the same person) but I've read the blog post. I can help host the packages if you like. 
currently I publish my builds here https://seby.io/download/synology-rt2600ac/

**Comment by nelek** [comment]
Indeed the routers do not support repositories. The package sources tab was present in SRM 1.0 but was removed in 1.1. I'm not holding my breath for it to return anytime soon.

Indeed one has to question what packages make sense on SRM. Some packages might work well. For some packages it will depend on the usage (light usage might be OK) - it's too different from DSM in this regard. Other packages do not make sense because of missing dependencies/libraries. Compiled applications tend to work adequately on SRM.

@ymartin59 I actually have both devices. Is there a possibility to communicate about my involvement? The #synocommunity IRC channel on freenode has been dead for ages.

@publicarray I can use a hand with hosting. Make a comment on my blog and I'll get in touch.

**Comment by Safihre** [comment]
@nelek @publicarray We can host them on SynoCommunity? Just have to get the build, which is quite easy using Travis/CircleCI.
You can submit PR's for things to change and let us know which packages should be compiled for the platform.

**Comment by publicarray** [comment]
@Safihre Yes I'd rather have them hosted at SynoCommunity too. Unfortunately the current selection is quite small, but that is improving thanks to @ymartin59. I'm not sure what people would want to install on their router. I only use dnscrypt-proxy, nano, nmap and nethogs. I know the router can do more but I'd rather keep the router to just to provide the internet. (It's important not to have downtime in my household. I have learnt my lesson after I coursed a few hours of internet outages/slowness)

Maybe offering the majority of packages makes SynoCommunity the new place to find packages for the router. At the moment nelek's blog is probably the most common way for router owners to get their package fix.

I'm also happy to build packages via CircleCI if needed, however discovery is still a problem. 

@nelek GitHub is probably the best place to have discussions at the moment.

**Comment by nelek** [comment]
@Safihre : I'd like to have a bit more hands-on approach myself when it comes to this. Especially for the packages I'm making from scratch... Is this possible? Can we discuss this somewhere?

**Comment by publicarray** [comment]
@nelek This is an open source community. If you want to publish your packages here the code needs to be open source. Also I don't think SynoCommunity should publish unknown binaries for security reasons.

**Comment by nelek** [comment]
@publicarray I'm familiar with what open source is about. I have no issues with publishing my works,  there is nothing in my packages which can't be verified and read anyway.

What I want is to have some control over the publishing process for the packages I'm making and releasing myself. My time to do them is extremely limited, so I'd rather spend my time getting things done and getting them out there so that people can use them instead of having to poke various people and having to wait for them to release them for me.

**Comment by publicarray** [comment]
Ah Sorry, I miss understood what you meant by a hands on approach.

**Comment by Safihre** [comment]
@nelek we do use our framework so that it will work on both DSM5 and 6, so we would need the new packages also to use it so we can easily update things if Synology does. It takes care of all the install/uninstall/upgrade stuff. Or do you already use it?
In terms of publishing speed: I have no problems releasing things for you (always checking my email!) and if all works well we can give you access directly to the repo here and the publishing. That's also how I started 👍

**Comment by nelek** [comment]
@Saphire do you mean spksrc?

**Comment by Safihre** [comment]
Yes.

**Comment by nelek** [comment]
@safhire I have been using it for SRM builds from pretty early on, and have been building my packages with it since SRM 1.0. However, I'm using my own makefiles as the ones in spksrc mainline do not have architecture optimizations.

**Comment by ymartin59** [comment]
@nelek I am interested to know what kind of optimizations you have implemented, to get them included into framework toolchains and avoid (as much as possible) architecture specific settings in package Makefile.
As an exercise, we may try for instance dnscrypt-proxy, as @publicarray has recently submitted PRs: https://github.com/SynoCommunity/spksrc/pulls?utf8=%E2%9C%93&q=is%3Apr+dnscrypt-proxy

**Comment by nelek** [comment]
@ymartin59 The optimizations in question are related to the specific SoC's used. I'll be on a holiday for the next couple of weeks, I'll have look into doing a fork with my changes after I get back.

**Comment by ymartin59** [comment]
As far as I know, we are OK with SRM support. Packages are downloadable from architecture list to be manually installed. Re-open if I am wrong.
