### ISSUE TITLE
Firefox Sync Server 1.5 - MariaDB10

### ISSUE THREAD

**Issue by Delor3an91** [SynoCommunity/spksrc#2979]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_Firefox Sync Server 1.5
_Package Version:_1.5.2-3

_NAS Model:_DS1813+
_NAS Architecture:_cedarview
_DSM version:_6.1.3

### Expected behavior
Dependency MariaDB5 or MariaDB10

### Actual behavior
Dependency MariaDB5

**Comment by mreid-tt** [comment]
The original Firefox Sync Server, as indicated in its [source repository](https://github.com/mozilla-services/syncserver), is no longer actively maintained. Instead, it has been redeveloped in Rust and is now hosted in a new repository called [Syncstorage-rs](https://github.com/mozilla-services/syncstorage-rs). The upcoming release, associated with the Pull Request [5942](https://github.com/SynoCommunity/spksrc/pull/5942) in the SynoCommunity/spksrc repository, will soon replace all prior versions of the package due to their deprecated functionality.

We invite interested individuals to explore the Checks tab at [this link](https://github.com/SynoCommunity/spksrc/pull/5942/checks) for the opportunity to download a pre-release version for testing purposes. Your valuable feedback is highly appreciated and encouraged before the final release.
