### ISSUE TITLE
Firefox Sync Server 1.5 do not work with Firefox Mobile anymore

### ISSUE THREAD

**Issue by 3qdev** [SynoCommunity/spksrc#2985]
### Setup
_Package Name:_ Firefox Sync Server 1.5
_Package Version:_ 1.5.2-3

_NAS Model:_ 213
_NAS Architecture:_
_DSM version:_ newest

### Expected behavior
Sync between all Firefox installations

### Actual behavior
Firefox Sync do not work on Android (6, 8) with newest Firefox Mobile since September 2017 

### Steps to reproduce
_1._ Install and configure Firefox Sync Server 1.5
_2._ Install and configure Firefox on Android
_3._ Try to sync

Sync between Firefox on Desktop is still working

**Comment by 3qdev** [comment]
Can somebody reproduce that issue?
Is the package still maintained?

**Comment by mskyaxl** [comment]
I have a similar behavior with FF59 on android 6. After updating services.sync.tokenServerURI on the Android side, the phone connects but nothing is synchronized.

**Comment by Dr-Cool** [comment]
> I have a similar behavior with FF59 on android 6. After updating services.sync.tokenServerURI on the Android side, the phone connects but nothing is synchronized.

I can confirm this misbehavior with ffsync version 1.5.2-3, a DiskStation DS111 with DSM 6.2.1-23824 Update 4, reverse proxy installed or not, HSTS enabled or not, HTTP/2 enabled or not. Desktop Firefox 65.0 64 bits syncs fine with the hosted server, but Android Firefox 64.0.2, although showing the correct sync server address in the tab, after changed in about:config and resigning in, will never sync.

The sync engine can be accessed though on Android Firefox through the URL bar and gives the expected feedback message, so the problem isn't with the server setup, it's some bad interaction between Android Firefox and the ffsync package.

**Comment by mreid-tt** [comment]
The original Firefox Sync Server, as indicated in its [source repository](https://github.com/mozilla-services/syncserver), is no longer actively maintained. Instead, it has been redeveloped in Rust and is now hosted in a new repository called [Syncstorage-rs](https://github.com/mozilla-services/syncstorage-rs). The upcoming release, associated with the Pull Request [5942](https://github.com/SynoCommunity/spksrc/pull/5942) in the SynoCommunity/spksrc repository, will soon replace all prior versions of the package due to their deprecated functionality.

We invite interested individuals to explore the Checks tab at [this link](https://github.com/SynoCommunity/spksrc/pull/5942/checks) for the opportunity to download a pre-release version for testing purposes. Your valuable feedback is highly appreciated and encouraged before the final release.
