### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by jelmerj** [SynoCommunity/spksrc#2990]
Hi,

Out of personal interest I have been looking at continuous integration, and I've been trying to apply it to (my fork of) the synocommunity repository. Currently I've got a basic integration workflow working that builds just the transmission package (intentional restriction). I have chosen to work with Travis CI. I haven't done a lot of research into which solution is best, but it looks pretty neat to me, it's free, it's open and it won't require me provide a buildserver (although I could). 
I am wondering of there is any interest in this from the current development team. The idea is that for every commit/pull request there would be a fully automated check if it breaks the compilation of packages, and it would also be possible to fully automate the building and releasing of packages.
If you guys are interested I would love to continue work on this, but I would also like to discuss the correct approach for some stuff.

**Comment by ymartin59** [comment]
Hello

Thanks for ideas and proposal of help. First Travis build for a package was published for Gog PR #2533, 
others have followed: https://github.com/SynoCommunity/spksrc/pulls?q=is%3Apr+travis+is%3Aclosed

At the moment, a travis configuration cannot be published as is because it would change for each PR/package, so I keep it on my private branches - like other submitters previously: https://github.com/ymartin59/spksrc/blob/master-travis/.travis.yml

What is interested from my point of view, is a set of configuration and scripts that process commits added by PR and impacted packages ("spk" and ideally users of dependencies in "cross"). I found following references as ideas:
- https://graysonkoonce.com/getting-the-current-branch-name-during-a-pull-request-in-travis-ci/
- https://github.com/DefinitelyTyped/DefinitelyTyped/issues/1314

Personally I love task automation and agree for building... but releasing is another part. First publishing too fast and easy put testing in risk and may break users applications; second, credentials to publish package should be left in cloud services.

A solution may be to deploy a "staging" package repository for testing, and an additional promotion feature to copy tested packages from "staging" to "production" environment.

But on step at a time. If you want to help with Travis support, do not hesitate to follow links I submitted here with initial configuration you may improve. I propose you publish a PR with your work in progress so that we can review even if draft so that you get early feedback and get confident you are on the right path.

Kind Regards
Yves Martin

**Comment by jelmerj** [comment]
Ah, good to see that others are doing more or less the same thing already!

I've tried the Docker approach, and it worked, but pulling the docker image each time took such a long time (and it timed out once) that I decided to try and go with the Trusty container and installing the additional packages. This turned out to be much faster.

Placing a travis config that will do a "make all-supported" for all packages will be far too time consuming. I was thinking to call a bash script which will inspect the changed files in the commit/pr which triggered the build, and it would search dependencies and build a list of affected packages and only build those.

**Comment by ymartin59** [comment]
OK for me. I look forward for your PR !

**Comment by Safihre** [comment]
I changed the `travis.yml` to no longer rely on `docker` and to use the `sudo: false`, which both launches faster on Travis and seems to compile also faster.
https://github.com/Safihre/spksrc/blob/sabnzbd-fix-travis/.travis.yml

**Comment by Safihre** [comment]
Today, after having spend way too much time on getting `spk/python` to work I finally found that the `apt`-based version is actually slightly different from the docker one.
Specifically it has a version of `ncursesw` installed, which on `x86` toolchains automatically gets included, resulting in all kinds of build failures. The docker system only has `ncurses`. Maybe this is due to the docker being based on Debian while Travis is based on Ubuntu.
I am sure there is a way around this, but for now I reverted back to the docker.

**Comment by Safihre** [comment]
As an update:
The `docker` is annoyingly unreliable, I had so many failures of docker timeouts and also the total time varies so much, because the `docker pull` can be 90 seconds or even 1200 seconds.
![image](https://user-images.githubusercontent.com/5703454/34831242-adf98c64-f6e6-11e7-9087-7e7070819c82.png)

Therefore, I included a patch in the Python PR so that it also compiles fine on the `sudo: false` Travis-system for the future. Did not have problems related to non-docker setup with other packages yet.

**Comment by Safihre** [comment]
I have a new proposal for automated publishing, [after reading carefully the Travis documentation](https://docs.travis-ci.com/user/triggering-builds/). It allows you to trigger builds by calling the API, and during this trigger you can update existing `travis.yml` settings to specify what should be build.

### So I propose the following:
- We make a basic `travis.yml` that includes the pulling of the docker and the basic command to compile and publish here on the repo.
- The API-key is stored in Travis [as an encrypted variable](https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml). 
This is used by _thousands_ of repo's and companies, it's safe and not exposed.
- We create a new `make travis-publish-all-supported` rule, this will:
  - Use the regular rules in the `Makefile` to determine which arch's are supported and should be build
  - Then sends the API-call to only trigger those builds (by adding `SYNOARCH` to the `matrix`) and does the publishing.
  - Can be extended to also include  `make travis-publish-*` (all other options)
  - It is triggered locally by admins, so we have full control which packages should be published and only the building is automated.

I can make this, if you agree?
@Diaoul @ymartin59 What do you think?

**Comment by Diaoul** [comment]
I think this is awesome. The trick is to only trigger build for the package
that changed but it seems you have that part covered !

**Comment by ymartin59** [comment]
@Safihre Idea sounds really interesting. It covers publication process which is quite heavy, even if I will always check myself produced package on xpenology and my evansport system.

By the way, some packages depending on libstdc++ require to be build for both DSM 5.2 and DSM 6.x toolchains. Then some architectures are included in `x64`, so there is no need to build them all. My current process often consists in running - for example when `ffmpeg` is concerned because of libstdc++:

```
make publish-arch-qoriq-5.2 publish-arch-x64-5.2 publish-arch-evansport-5.2 publish-arch-88f6281-5.0 publish-arch-alpine-5.2 publish-arch-armada370-5.2 publish-arch-armada375-5.2 publish-arch-armadaxp-5.2 publish-arch-comcerto2k-5.2 publish-arch-monaco-5.2 publish-arch-ppc853x-5.2 publish-arch-dockerx64-6.1 publish-arch-rtd1296-6.1

make publish-arch-qoriq-6.1 publish-arch-x64-6.1 publish-arch-evansport-6.1 publish-arch-88f6281-6.1 publish-arch-alpine-6.1 publish-arch-armada370-6.1 publish-arch-armada375-6.1 publish-arch-armadaxp-6.1 publish-arch-comcerto2k-6.1 publish-arch-monaco-6.1 publish-arch-ppc853x-6.1
```

For on-the-fly PR validation process, my previous comment contains some references/ideas: https://github.com/SynoCommunity/spksrc/issues/2990#issuecomment-342617044

**Comment by Safihre** [comment]
@ymartin59 So you wouldn't like this? 
The idea is indeed to test locally first, but when publishing comes it can be much faster and doesn't need to be run locally. At least on my PC, the building is much slower than Travis is.
Your commands would then translate into:
``` 
make dsm-5.2
make travis-publish-all-supported
make dsm-6.2
make travis-publish-all-supported
```
`all-supported` already ignores duplicate `x64` archs via `ARCHS_DUPES` in `spksrc.common.mk` so after this, Travis does the rest.

**Comment by Diaoul** [comment]
I believe Travis can cache some stuff, could've great to avoid
redownloading. Sorry i'm on a phone I cannot check if this is already
implemented, if so, please just ignore my comment :)

**Comment by ymartin59** [comment]
@Safihre In my mind I have discarded DSM 6.0.x as I consider SC never published packages for that versions... and probably all hardware delivered with DSM 6.0.x is now updated to DSM 6.1. I guess `make dsm-6.2` is a "mistake".
If it would be possible to add a marker variable in `spk` package `Makefile` to notice that it depends on DSM 5/6 runtime/toolchains, then a single target can produce packages for both without additional tricks.

**Comment by Safihre** [comment]
@ymartin59 I mostly wanted to know if you think I should implement this system of using Travis for publishing, otherwise I don't spend my time coding it :)

**Comment by ymartin59** [comment]
@Safihre I would say it is not a top priority, compared to DSM 6 service support, but I really think it is worth having such an automated process.

**Comment by ymartin59** [comment]
I am reviewing current status of Travis integration... Knowing that circleci has been tested by @publicarray too https://github.com/publicarray/spksrc/blob/master/.circleci/config.yml

As new stretch Docker image is far lighter that previous one, there is a chance Travis appreciate better.

@Safihre @m4tt075 As far as I remember, the may trouble of spksrc build process is its verbosity... too many logs, so use >/dev/null and then Travis considers process is stuck. We should find a way to generate regularly light volume logging...

**Comment by Safihre** [comment]
Is there a way to maybe show the output procuded by the SynoCommunity scripts, but not the output of the commands they run? So that you still see the statuses like getting the package, checking it, building started, creating spk, etc. 
Capature the rest of the output and only display last X lines in case of failure. That would be a nice bonus feature to have some debugging info.

**Comment by ymartin59** [comment]
@Safihre That is not so obvious, as some compilation may last longer than "ci timeout"... My idea would to replace process output by a "dot-progress" watchdog.

**Comment by publicarray** [comment]
Since we switched to GitHub Actions, this can be closed.
