### ISSUE TITLE
synocommunity.com down ?

### ISSUE THREAD

**Issue by Echupk** [SynoCommunity/spksrc#2995]
Is synocommunity.com ? 
no packages showing in NAS
the web page tells that's a snapshot version of the site taken by cloudfare.

I needed to reinstal jackett but can't for now du to this.

Any update on when it will be live again ? 

thx

**Comment by Johnito** [comment]
Same issue here on two different NAS at different locations. Source location http://packages.synocommunity.com cannot be added anymore in package center, and packages are no more refreshed.

**Comment by Echupk** [comment]
Yep, seems we have to wait, or install manually during the down time

**Comment by tchirou** [comment]
OVH servers are down this morning in France so that must be that

Le 9 nov. 2017 à 10:21, Echupk <notifications@github.com> a écrit :

Yep, seems we have to wait, or install manually during the down time

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/SynoCommunity/spksrc/issues/2995#issuecomment-343095242>,
or mute the thread

**Comment by ymartin59** [comment]
Services back online.
