### ISSUE TITLE
ADD [Debian Chroot] IN PACKAGES FOR DS118

### ISSUE THREAD

**Issue by suil1128** [SynoCommunity/spksrc#3031]
ADD [Debian Chroot] IN PACKAGES FOR DS118, THANKS VERY MUCH!

### Setup
_Package Name:_
_Package Version:_

_NAS Model:_
_NAS Architecture:_
_DSM version:_

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by ymartin59** [comment]
Complex and dangerous package... Not sure it will ever come back

**Comment by christophe-lyon** [comment]
I did manage to build it on my side (for DS218play), but couldn't install it because DSM says there's a dependency on python, which I wasn't able to build so far because pip complains:
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
(Which is probably a problem on my side)

@ymartin59 what do you mean by dangerous?

**Comment by ymartin59** [comment]
See #2758 - according to many issues registered around debian-chroot, there is risk you face an unstable DSM, and uninstall package lead to corrupt DSM up to a full re-install is required
