### ISSUE TITLE
why package center cancel the debian chroot today?

### ISSUE THREAD

**Issue by DrDoa** [SynoCommunity/spksrc#3055]
I am surprised that I cannot find debian chroot in package center any more, but why you cancel it? It works well.

**Comment by jeancaffou** [comment]
+1

**Comment by spiceyux** [comment]
+1

**Comment by VadVoci** [comment]
I've downgraded xpenolgy from DSM 6.1.4 to DSM 5.2-5644 , DS3615xs today . Debian Chroot still missing in community repo!

Please! Does anyone have the Debian-Chroot 8.4-7 offline spk package?

I need urgently.

**Comment by ymartin59** [comment]
I am sorry to say it does not work so well... typically try to uninstall that package may brick your DSM system completely. Because of some complaints I decided to stop package distribution.
OK, I set it back... but really consider it as unsupported

**Comment by jeancaffou** [comment]
Thank you, in that case please consider having an "unsupported" category with offline installs, warnings on the synocommunity page.

I see the chroot package now.

**Comment by VadVoci** [comment]
@ymartin59 Thank you very much!  I saved the spk pack for offline use.
@jeancaffou  A good idea

**Comment by Daopr** [comment]
@VadVoci Could you provide me the offline spk? I can still not find it.

**Comment by Daopr** [comment]
OK, I found Synology Community gives it back now. It was weird.

**Comment by Daopr** [comment]
although  I found  I cannot launch it...  So I decide to give it up. Thanks Diaoul anyway.

**Comment by VadVoci** [comment]
@Daopr 
Debian Chroot v7.4-4 (from spk.synologyitalia.com) > In DSM5.2, the application does not start! In DSM6.1 neither!

Debian Chroot v8.4-7 (from packages.synocommunity.com) > In DSM5.2, the application runs perfectly! 
 
In DSM6.0 the Debian Chroot application needs some tweaks. You can not start the debian services from the application, but from the DSM task scheduler .

**Comment by Daopr** [comment]
Thanks a lot. I have ever run debian chroot on esxi dsm 6.1, it works well. But this is the first time I run it on the real Synology, So I met this problem. 
Thanks for your clue, I found this issue to solve my problem 
[#1910](https://github.com/SynoCommunity/spksrc/issues/1910)

**Comment by ymartin59** [comment]
Hard to believe debian-chroot really works well according to reported issues like #3059 and many others

**Comment by VadVoci** [comment]
@ymartin59 
[quote=ymartin59]typically try to uninstall that package may brick your DSM system completely. Because of some complaints I decided to stop package distribution.
[/quote]
Uninstalling the DebianChroot app without stopping it first, and implicitly without umount-ing shared folders and files between that two environments, 
i think it will remove folders and files used by the synology OS and Debian together. 

..issues like #3059 .., This issue with 'locale' has always existed after fresh installation of Debian Chroot.
It's easy to solve this issue with a few steps in the command line.
apt-get update
apt-get upgrade
apt-get install locales
dpkg-reconfigure locales
dpkg-reconfigure tzdata
And then edit this files:
/volume1/@appstore/debian-chroot/var/chroottarget/etc/default/locale
/volume1/@appstore/debian-chroot/var/chroottarget/etc/environment
where insert this line:  LANG=en_US.UTF-8

sudo locale-gen en_US en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
sudo locale-gen en_US.UTF-8
sudo dpkg-reconfigure locales
choose.. en_US.UTF-8 UTF-8  .. and then ENTER
sudo localedef -i en_US -f UTF-8 en_US.UTF-8
Edit:
/volume1/@appstore/debian-chroot/var/chroottarget/etc/locale.gen
And remove this character '#' from the beginning of the line:  en_US.UTF-8 UTF-8

sudo locale-gen en_US en_US.UTF-8

**Comment by Safihre** [comment]
Since the package is back, closing this. Still needs conversion to DSM6, but there's plenty of other issues for that..

**Comment by wabee** [comment]
Does anyone know how to remove the package safely from DSM 6.2??

**Comment by ymartin59** [comment]
Probably nobody... we will investigate that situation when upgrading package to run on DSM 6.x

**Comment by wabee** [comment]
I read up on Debian Chroot in general and it seems the most important thing is to make sure that nothing referring to the Chroot environment is mounted.
I stopped Chroot and rebooted the NAS, after that nothing chroot related was mounted. I "believe" it would be safe to remove the chroot dirs after this manually but have yet to try. Must make sure all important data is backed up first.

**Comment by Lovski** [comment]
Is it correct Debian Chroot has been pulled again? It was working perfectly for me on DSM 6.2, however I wanted to remove it and reinstall it because of an issue with a package that I installed through Chroot. However, after removing it, I cannot find it anymore in the SynoCommunity via Package Center. It is also no longer listed on https://synocommunity.com/packages.

**Comment by Louike** [comment]
i noticed the same thing, been using it for Pi-hole. Can someone explain to me how to build your own package using the download zip file?

**Comment by 3clypse** [comment]
@Louike The easy way is to run it using Docker. 
Moar info: https://hub.docker.com/r/pihole/pihole/

**Comment by hadesome1** [comment]
can anyone give me the link to download Debian-Chroot 8.4-7 offline spk package? i can't find it on Synology Community any more.

**Comment by zejjnt** [comment]
I would also like to get this again. I have it on one of my devices though and it works fine with the latest version of DSM so if anyone can tell me how to pull the package from another device that would work too.

**Comment by zejjnt** [comment]
I see now that the package is not listed, but download links still work; https://synocommunity.com/package/debian-chroot

And to find which package you need go to https://www.synology.com/en-global/knowledgebase/DSM/tutorial/General/What_kind_of_CPU_does_my_NAS_have

**Comment by phineco** [comment]
@hadesome1 you can build the package in a docker environment.

**Comment by hgw77** [comment]
+1 

I also noticed today that debian chroot was removed from the package list. For me the debian chroot runs (after some small tweaks) very well. So I do not understand why it was removed. Please bring it back :-) So I have the possibility to reinstall it if necessary......

**Comment by HEYGUL** [comment]
The package is not available, and as a ds418 user, docker is not available too ...
Wanted to install pihole but seems it is not easily possible for the moment...

**Comment by tenhow** [comment]
I have compiled a spk for ds3615(bromolow), and works  on DSM 6.1.

**Comment by Tao87-04** [comment]
maybe dropbox or mega?

**Comment by Tao87-04** [comment]
Nice, thanks:)

**Comment by VadVoci** [comment]
@tenhow    I need that packet compiled by you.  Can you give me a download link? Please

**Comment by VadVoci** [comment]
I cannot edit my previous post ..
@xnaas
"the package was deemed super unreliable and could brick systems if it was uninstalled" because o this trick: https://github.com/SynoCommunity/spksrc/issues/1910  @Toka69 commented..
[
CHROOT=/usr/local/debian-chroot/var/chroottarget
mount -o bind /dev $CHROOT/dev
mount -o bind /proc $CHROOT/proc
mount -o bind /dev/pts $CHROOT/dev/pts
mount -o bind /sys $CHROOT/sys
mount -o bind /volume1 $CHROOT/volume1
mount -o bind /volume2 $CHROOT/volume2
cp /etc/resolv.conf $CHROOT/etc/resolv.conf
cp /etc/hosts $CHROOT/etc/hosts
#below, an example to launch ssh previously installed
chroot $CHROOT /etc/init.d/ssh start
]
Some stuff(files,folders and etc..) was mounted. But it's not exist a simple and fast option to unmount them before uninstalling the debian chroot app.
You should first delete that script from the shedulled task, then a restart of the synology machine and only then uninstall debian chroot app. This is safe way. (Because there is no stop and umount command) Otherwise .. there is a risk of deleting files from the synology system
After all, the only problem with the application is the gui interface. Everything else works very well, I could say even perfectly.
The application only needs a developer to fix its gui interface. That's the only issue to solve.
I apologize to my poor English..

**Comment by tenhow** [comment]
@VadVoci  you can download here. [DSM.debian-chroot.spk](https://github.com/OKit-Scripts-Projects/DSM.debian-chroot.spk/blob/master/README.md)

**Comment by schumi2004** [comment]
There is no package for Alpine (DS715) architecture right ?
