### ISSUE TITLE
Update BicBucStriim

### ISSUE THREAD

**Issue by gpuberos** [SynoCommunity/spksrc#3089]
### Setup
_Package Name:_ BicBucStriim
_Package Version:_ 1.3.6-5

_NAS Model:_ DS1815+
_NAS Architecture:_ Intel Atom
_DSM version:_ 6.1.4

### Expected behavior
Could you update the BicBuctriim Package to the last version BicBucStriim 1.4.1, this version fix more bug from 1.3.x
https://github.com/rvolz/BicBucStriim

**Comment by Safihre** [comment]
I tried to update it but even the current version shows me a 500 Server Error page.
Did I setup something wrong? 

Also the package need to be updated to force dependencies on Web Station being installed. Otherwise it won't work at all. If possible.

**Comment by bkqc** [comment]
The package should also install / configure the following:

- Apache HTTP Server 2.2 require
- php 5.3+ required
- sqllite3 module for php required
- gd module for PHP is required
- mcrypt module for PHP is recommended
- intl module for PHP is recommended

**Comment by mreid-tt** [comment]
We have received several requests to upgrade the BicBucStriim version in the repository. This task has been pending for a while due to the package not being updated for the latest DSM versions. A new release is currently in draft, featured as part of PR #5952. We welcome individuals who are interested in contributing to the testing and feedback process for the upcoming release. Early builds can be downloaded at [this link](https://github.com/SynoCommunity/spksrc/pull/5952/checks). Your assistance in testing and providing feedback would be greatly appreciated.
