### ISSUE TITLE
Splitting up SickRage

### ISSUE THREAD

**Issue by guusdk** [SynoCommunity/spksrc#3204]
There are two software projects that identify themselves as "SickRage":
* https://git.sickrage.ca/SiCKRAGE/sickrage
* https://sickrage.github.io/

Both have, at some point, been available through this community _under the same identifier_. This has lead to a (frankly immature) battle for the dominance, resulting in weird version numbering, but also setup corruption and much annoyance for end-users.

Kindly clear things up for end-users by offering not one, but two SickRage packages:

* SickRage (sickrage.ca)
* SickRage (github.io)

**Comment by Safihre** [comment]
The packages allow you to specify the git url to use during new installations, specifically for this reason. Isn't that good enough?

**Comment by guusdk** [comment]
No, it's utterly confusing - not in the least because at least one of them recently changed it's primary git URL. Also, many people are not even aware that there are two incompatible packages out there. I strongly feel that all of this complexity can (and should) be easily hidden from end-users. Offering two, instead of one, packages, unambiguously sets the record straight.

**Comment by Safihre** [comment]
The new package that's yet to be published will contain the new updated url.
Honestly I feel people that use this software are not basic  users, they know their stuff and how to use it and are perfectly able to change a Git URL if they'd prefer that.

**Comment by guusdk** [comment]
Well, as someone who today had to reconfig for the third time, I disagree. 😏

**Comment by cytec** [comment]
we had this several times already... use SickRage to install sickrage.ca which is the official Repo/App and needs to be handled differently then SickRage fork on github... Use SickBeard Custom to install the second one ;)

See https://github.com/SynoCommunity/spksrc/issues/1989 for the Discussion about that

**Comment by guusdk** [comment]
#1989 is demonstrating the amount of confusion there is related to this. You guys can clear this all up by simply having two properly named packages. There's no downside to that.

**Comment by cytec** [comment]
As already stated in https://github.com/SynoCommunity/spksrc/issues/1989 the confusion is mainly because the guys who moved refuse to change the name of their fork... the "original" SickRage repo is still there and maintained by echel0n (git.sickrage.ca/SiCKRAGE/sickrage)

Everything already was discussed in the issue i linked... Check out the Doku on how to install SickRage from github on Synology Devices and it will tell you to use the SB-Custom SPK: https://github.com/SickRage/SickRage/wiki/Switching-your-Synology's-Sickrage-to-the-new-repository#install-sickrage

I also stated that i'd retire the SickRage SPK completely and also use SB-Custom for that (after all it's still a SB fork) but that'll be way to complex to maintain since the original SR has some major differences that would have to be catched on install time.
