### ISSUE TITLE
Pyload on DS218+

### ISSUE THREAD

**Issue by Piero87** [SynoCommunity/spksrc#3210]
Hi, when Pyload will be available for DS218+?

**Comment by Safihre** [comment]
When someone converts it to Generic Service approach.

**Comment by Piero87** [comment]
@Safihre Thanks, i hope someone fix it

**Comment by Safihre** [comment]
We have a blocking issue with Python, after that's fixed we can release all python related tools.
PyLoad won't be forgotten, for example via #2259.

**Comment by Piero87** [comment]
@Safihre ok thank you very much

**Comment by Piero87** [comment]
@Safihre You know if there is something else to use similar to pyLoad?

**Comment by etaletovic** [comment]
@Piero87 Synology’s Download Station works for me and it looks like it is based on pyload (based on references to pyload on my filesystem although I haven’t installed anything pyload related and the fact it uses pyload plugins such as Real Debrid)
The only reason I still need pyload is because I cannot access Download Station from my iOS device and pyload has web ui.
