### ISSUE TITLE
Tiny Tiny RSS (tt-rss) is not available for ds918+

### ISSUE THREAD

**Issue by Mowd** [SynoCommunity/spksrc#3220]
I just transfer some packages from my ds1515+ to new ds918+, and found out that tt-rss is not display on package center.

**Comment by Tweaqer** [comment]
Use Docker. that one works well

**Comment by LawrenceAusten** [comment]
Any suggestions on which Docker image to use, as there are a lot of images that show up under TT-RSS in the registry.  Alternatively, can anyone give an indication of roughly how much work it would be for an experience developer to recompile TT-RSS to run on the ds1819+ (Denverton archicture)?

**Comment by Tweaqer** [comment]
Do as @Mowd says or use this docker: https://hub.docker.com/r/linuxserver/tt-rss/

**Comment by LawrenceAusten** [comment]
For anyone trying to migrate tt-rss to a machine without a SynoCommunity package available, here's what I ended up doing, based on Mowd's suggestion:

1. ssh into your existing nas and backup your existing data using "mysqldump -u root -p --opt ttrss > ttrss.sql".  Note that PhpAdmin showed I had both MariaDB 5 and 10 running, but the above command "did the right thing".
2. move the backup to your new machine using "scp ttrss.sql user@local_ip_address:." 
3. tar + gzip your existing /var/services/web/ttr-rss directory using "tar cvzf tt-rss.tar.gz /var/services/web/tt-rss"
4. scp the tar.gz file over to your new server "scp tt-rss.tar.gz user@local_ip_address:."
5. use PhpAdmin on your new machine to create a database in MariaDB 5 called ttrss.  You need to create the database without anything in it before importing the backup to work around well know bug in MariaDB.
6. ssh to your new machine and import the database backup using "mysql -u root -p ttrss < ttrss.sql".  This took about 10 minutes on my machine.
7. untar the tar.gz file "cd /var/services/web ; tar xfvz ~/tt-rss.tar.gz" or some such.
8. Follow the excellent instructions at https://tt-rss.org/oldforum/viewtopic.php?t=3736 to get the feed updating working.
9. Voila, with a bit of luck tt-rss will be running on your new machine.

FWIW, I tried to update the SynoCommunity tt-rss package to the Denverton architecture but I couldn't get it working.  Only real issue was the download url for tt-rss has changed and I got a clean compile, but the package wouldn't install on my machine, giving the following two errors in the log.  If anyone has any suggestions, please let me know.

2019-07-01T08:59:25+02:00 nas4 synopkg: pkginstall.cpp:481 Failed to run preinst script for tt-rss, 1
2019-07-01T08:59:25+02:00 nas4 synopkg: pkginstall.cpp:341 Failed to install package: tt-rss_denverton-6.1_19.2-11.spk, [263]

**Comment by hgy59** [comment]
solved with v20200829-12
