### ISSUE TITLE
Improve Python usage and packaging documentation

### ISSUE THREAD

**Issue by hgy59** [SynoCommunity/spksrc#3229]
Is there any reason why the [wiki](https://github.com/SynoCommunity/spksrc/wiki) is restricted for editing?

As I am still getting into the developping process here, I miss some themes in the wiki.
At least I miss a structured side-board giving a better overview of the wiki's pages.
I would like to add a wiki page regarding the Docker image.

While testing an updated docker image I am wondering what the real reason of native packages is. I can build python and it is running on my DS918+ (apollolake) but the python3 does not.
(python3 compiles after update to 3.5.5 and openssl to 1.1.0g but it does not execute on the DS).

I am missing wiki pages about python/python3 spk: what is included and what is the update policy (use pip, wheel or spk for updates?).
As I build native python it depends on the host system (docker image) whether the sqlite, tkinter and other modules are built into python...
What modules should be included?
Shall the documentation and code samples be included in the spk? (I would like to build spks without documentation and code samples, since I expect more a runtime than a development environment on the diskstation)
May be the python spks are only for other SynoCommunity spks that need a python environment?

A lot of questions that could be answered on wiki pages ;-)

**Comment by ymartin59** [comment]
@hgy59 I have un-restricted push access to wiki repository... Thanks in advance for your effort to document. If you have no answer yet, at least organize and post your questions.

**Comment by hgy59** [comment]
@BenjV and what is the spk/python3 (cross/python3, native/python3) package here for?

**Comment by Safihre** [comment]
Indeed the python compilation would partly  use the system python instead of using the `native` one. I fixed this for Python 2 package, but now that one is having other problems.

It would be great to have a list of why packages are included in the main Python package. I wondered the same for the Python 2 package.. 
But I realized for most of them it's to make as many other packages `noarch` by including the compiled parts inside Python package. 
There does seem to be no difference in the way it gets compiled when using the `requirements.txt` or as `cross/x` package.

**Comment by BenjV** [comment]
Some background information:

In the past there was a need voor extra binaries and modules in the python 2 release of Synology.
That is why the SynoCommunity added the python 2 package with extra binaries and widely used modules.
The problem with extra modules that are not of the formal python distribution, is the support of new versions and potential backwards compatibility.
So at that point (by DrBean and Diaoul I think) it was decided to stop adding extra modules (like requests) and use a virtual environment for packages that needed extra pure python modules.

Because if you have a package that works with for example version A of the requests library and not with version B, and another package that only works with version B there is a problem when that library becomes a part of the python distribution.

After that, only binaries who needed compiling were added to the python release.
Following this line it was not needed anymore to release a python 3 distribution, because Synology distributes the Python 3 release itself.

**Comment by ymartin59** [comment]
Am I wrong or a good reason to rebuild is that Synology Python 2.x and 3.x packages do not provide either "pip" or "virtualenv" commands ? I searched for them few minutes in `/var/packages/py3k` and `/var/packages/PythonModule/target/` and have found none... Anyone to cross-check that statement, please ?

About wiki restriction... I really wonder why GitHub does not provide same fork/PR mechanism for wiki Git repository as for code repository. It would be a far better process than the single all-or-nothing permission switch.

**Comment by ymartin59** [comment]
@hgy59 Thanks for your sidebar ! By the way, I just learned how to include images few days ago... That wiki seems to be on the right path.

**Comment by BenjV** [comment]
Python 2 is not an official package of Synology.
It is just included because Synology themselves used python and it is a very bare minimum python version.

Python 3 is a package you can install from the package centre and it includes pip en venv
/volume1/@appstore/py3k/usr/local/bin/pip
/volume1/@appstore/py3k/usr/local/lib/python3.5/venv

**Comment by ymartin59** [comment]
Synology "PythonModules" is available to "extend" system minimum python 2.x

I agree. Found `/var/packages/py3k/target/usr/local/lib/python3.4/venv` and also `/var/packages/py3k/target/usr/local/lib/python3.4/ensurepip/_bundled/pip-1.5.6-py2.py3-none-any.whl`, so `pip` should be available when creating a virtual env.

As a result, I propose to switch packages to Synology "Python 3" package and make our own obsolete.

Just by curiosity, I just find out that Synology "Python3" module has a specific "auto-update" check box in Package Center. Anyone know more about it? Would it be available for SynoCommunity packages too?

**Comment by ymartin59** [comment]
@hgy59 Here is a starting point to answer your Python questions... I only wrote one Python package myself: `beets`.

**Comment by Safihre** [comment]
I don't agree to switch to Synology Python. 
As you show they include 3.4, which has been one on those not very happy python versions with many rough edges that were only smoothed out later. 
The hug benefit of our own version is that we can push newer releases whenever we want.

**Comment by ymartin59** [comment]
@Safihre You're right... They do not update often, other "beta" packages of their own are quite old too. By the way, we know why already.
