### ISSUE TITLE
Issues when Install COPS

### ISSUE THREAD

**Issue by podor** [SynoCommunity/spksrc#3324]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ COPS
_Package Version:_ 1.0.1-5

_NAS Model:_ DS415+
_NAS Architecture:_
_DSM version:_ 6.2 Beta

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._ Click Install
![2018-05-15](https://user-images.githubusercontent.com/23508005/40085518-09039378-589b-11e8-97be-8968c311ab7f.png)

_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by ymartin59** [comment]
COPS package has not been updated to run on DSM 6.x

**Comment by mreid-tt** [comment]
Hi @podor, it looks like this issue has been open for some time without any recent updates. Since then, a new version of COPS (v1.4.2-7) has been released which may have resolved this issue. Can you please test with the latest version and let us know if the issue persists? If we don't hear back from you in a few days, we'll assume the issue has been resolved and close this ticket. Thank you!
