### ISSUE TITLE
Improve start-stop-status status

### ISSUE THREAD

**Issue by publicarray** [SynoCommunity/spksrc#3387]
Specificity the following exit status codes should be used when running `start-stop-status status`

> 0: package is running.
> 1: program of package is dead and /var/run pid file exists.
> 2: program of package is dead and /var/lock lock file exists
> 3: package is not running
> 4: package status is unknown
> 150: package is broken and should be reinstalled. Please note, broken status (150) is only supported by DSM 4.2 and later.

https://developer.synology.com/developer-guide/synology_package/scripts.html

Currently we exit with 0 (package is running) or 1 (package is not running)

**Comment by BenjV** [comment]
Actually the return code should be 0 or 3

Status 1: does not occur, because the start-stop-status script removes the pidfile when the process is no longer running because various applications do not start if a (old)pidfile is already there.
Status 2: does not exists, no lockfile is used.
Status 4: does not exists it is either running(0) or not running(3).
Status 150: is not possible to determine in the start-stop-status script.

**Comment by publicarray** [comment]
Agreed but that’s not what I think our current script does

**Comment by ymartin59** [comment]
Thanks for reviewing documentation. I will fix generic scripts:
- `spksrc.service.start-stop-status`
- `spksrc.service.start-stop-daemon`
- `spksrc.service.non-startable`
