### ISSUE TITLE
ps3netsrv: error message /lib/libstdc++.so.6: no version information available

### ISSUE THREAD

**Issue by Anonym-tsk** [SynoCommunity/spksrc#3404]
From /volume1/@appstore/ps3netsrv/var/ps3netsrv.log
`/volume1/@appstore/ps3netsrv/bin/ps3netsrv: /lib/libstdc++.so.6: no version information available (required by /volume1/@appstore/ps3netsrv/bin/ps3netsrv)`

When i compiled ps3netsrv with docker and installed it, i don't see this error.

**Comment by ymartin59** [comment]
There is a chance because I built with DSM 5.x toolchain (except for architecture with only DSM 6.x toolchain). It is the first package for which I see such version information error - usually binary with heavy C++ usage just crash: https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#compatibility-issue

**Comment by ymartin59** [comment]
I have to check if building for DSM 6 fixes this warning... Not urgent from my point of view if binary runs.

**Comment by hgy59** [comment]
fixed, at least with #4984
