### ISSUE TITLE
[Package Request] Comskip Update (for Armada38x and other platforms)

### ISSUE THREAD

**Issue by rEFulaYL** [SynoCommunity/spksrc#3410]
Name: Comskip
Description:Comskip is a free mpeg commercial detector.
Website:https://github.com/SynoCommunity/spksrc/wiki/Comskip
Software documentation:http://www.kaashoek.com/files/manual.htm
Build/Installation documentation:http://www.kaashoek.com/files/tuning.htm
Source Code:
License:

**Comment by m4tt075** [comment]
@ymartin59 I have just tried to compile the existing `comskip` beta package for `armada38x`. The `digests` files are outdated, but otherwise it works fine. No idea, why this specific architecture isn't published. Anyways, the package is quite simple. Am updating to latest release 0.82.003 now. Will do some testing and PR the update.

**Comment by m4tt075** [comment]
@rEFulaYL 
You will find a test-build for your platform here: https://github.com/m4tt075/spksrc/releases/tag/comskip-0.82.003
I have not yet had a chance to test. Please give it a try and report back.

**Comment by rEFulaYL** [comment]
@m4tt075 
Thanks for looking into this. I've tested the build and it works fine and as expected.

**Comment by m4tt075** [comment]
@rEFulaYL Great. Thanks for the quick report.

@ymartin59 Please keep this issue and my PR open for a while. Maybe we can attract some more testers and feedback. I will watch the github release download counts as well.

Everyone, please keep testing the test-builds above and provide feedback here. Good or bad, all welcome...

**Comment by ymartin59** [comment]
Package updated and published with ffmpeg dependency
