### ISSUE TITLE
BicBucStriim upgrade to 1.4.1 please

### ISSUE THREAD

**Issue by ruderl** [SynoCommunity/spksrc#3421]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_BicBucStriim
_Package Version:_1.4.1

_NAS Model:_DS716+
_NAS Architecture:_
_DSM version:_6.2

### Expected behavior
Current version of BicBucStriim which is packaged on synocommunity 1.3.6 has been superceded by newer version 1.4.1 https://projekte.textmulch.de/bicbucstriim/downloads/  which remedies a number of bugs. New packaging would be nice. thanks. 
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by hgy59** [comment]
Made an update to version 1.5.0 but unfortunatly there is no migration of the user db. An existing user db is recreated instead of leaving it and migrate it when migration is required.
The update is as easy as changing the versions in the makefiles and call `make digests` in cross/bicbucstriim.
But someone has to dig into the code to prevent the recreation of the user database on update.

**Comment by mreid-tt** [comment]
We have received several requests to upgrade the BicBucStriim version in the repository. This task has been pending for a while due to the package not being updated for the latest DSM versions. A new release is currently in draft, featured as part of PR #5952. We welcome individuals who are interested in contributing to the testing and feedback process for the upcoming release. Early builds can be downloaded at [this link](https://github.com/SynoCommunity/spksrc/pull/5952/checks). Your assistance in testing and providing feedback would be greatly appreciated.
