### ISSUE TITLE
Error extracting toolchain for armada38x

### ISSUE THREAD

**Issue by obourdon** [SynoCommunity/spksrc#3523]
### Setup
_Package Name:_ ALL
_Package Version:_ ANY

_NAS Model:_ DS218j
_NAS Architecture:_ armada38x
_DSM version:_ 6.1/6.2

### Expected behavior
tmux/git/... should build using make arch-armada38x

### Actual behavior
Error due to bad extraction of toolchain

### Steps to reproduce
_1._ use the official docker dev container 
_2._ follow instructions to setup and build any package
_3._ try building git for instance

#### Other logs
_E.g. `command output`_
```
===>    Extracting for syno-armada38x
tar -xpf /spksrc/toolchains/syno-armada38x-6.1/../../distrib/toolchains/6.1/armada38x-gcc493_glibc220_hard-GPL.txz -C /spksrc/toolchains/syno-armada38x-6.1/work 
tar: arm-unknown-linux-gnueabi/share: Cannot mkdir: Permission denied
tar: arm-unknown-linux-gnueabi/share: Cannot mkdir: Permission denied
tar: arm-unknown-linux-gnueabi/share/locale: Cannot mkdir: No such file or directory
...
# find /spksrc/toolchains/syno-armada38x-6.1/work -ls
42733955    0 drwxr-xr-x   5 root     root          170 Nov 21 23:29 /spksrc/toolchains/syno-armada38x-6.1/work
42733960    0 -rw-r--r--   1 root     root            0 Nov 21 23:29 /spksrc/toolchains/syno-armada38x-6.1/work/.syno-armada38x-checksum_done
42733956    0 -rw-r--r--   1 root     root            0 Nov 21 23:28 /spksrc/toolchains/syno-armada38x-6.1/work/.syno-armada38x-download_done
42733961    0 dr-xr-xr-x   2 1000     1000           68 Jun 24  2016 /spksrc/toolchains/syno-armada38x-6.1/work/arm-unknown-linux-gnueabi
```

**Comment by BenjV** [comment]
You should fix the permissions yourself.
The user which you are using does not have enough permissions to create folders.

**Comment by obourdon** [comment]
@BenjV nope, you can try this by yourself in the docker container, there is no way root user can extract properly when dirs are not writable. The only other option is to fix the toolchain archive but as this kind of issue can occur for any kind of archive the fix proposed in [Pull request #3524 ](https://github.com/SynoCommunity/spksrc/pull/3524) is generic enough to cope with most situations I have tested.

**Comment by BenjV** [comment]
If you cannot create a folder then this is a Docker problem and not spkrsc
In my opinion is Docker not a very usefull environment, but that's my opinion

**Comment by obourdon** [comment]
Docker is very useful because everything is self contained and way lighter than virtual machines. Furthermore it is faster to get started with and restarted from clean state. Even though this might be a docker related issue it does not mean that a workaround should not be implemented so that everybody can use spkrsc without any issue whatever the dev env chosen. You can also consider this as an issue related to toolchain and how the corresponding tar was created but again the workaround works and allows spksrc users to build what they need

**Comment by ymartin59** [comment]
toolchain comes from Synology. Files are packed with uid:gid couple 1000:1000
On Linux, I have cloned project with my own non-priviledged user and run docker image with 
  docker run -it -v `pwd`:/spksrc synocommunity/spksrc /bin/bash

According to "_done" files, docker process expectedly runs as root.

My only hypothesis to explain why "myFix" toolchain target with "chmod u+w" has not been processed (based on your report "dr-xr-xr-x" is that:
- process has been interrupted in the middle of tar extraction
- and retry later (just an educated guess: after freeing disk space...)

Proposal: go to "toolchains/syno-armda38x-6.1" and try "make clean " first and if failing, "rm -rf work" at same place.
With enough disk space and no Ctrl-C interruption, toolchain will be re-created from archive when building any package.

**Comment by obourdon** [comment]
@ymartin59 just tried again from brand new git repo + docker image and it failed again without any previous cancellation, error, retry, ...
Please note that I am running docker on MacOSX Sierra
Will try this on my Linux workstation to see if it behaves any differently

**Comment by obourdon** [comment]
Indeed, seems to be MacOSX + Docker related. Works like a charm on Linux under exact same conditions

**Comment by BenjV** [comment]
Docker is a useless environment as I stated before.
It just add problems and does not solve anything.

**Comment by obourdon** [comment]
@BenjV this is your own an personal opinion which I respect and you perfectly have right to think so for your own use and applications. However seems like quite a lot of people tend to think the opposite and have their entire businesses, CI/CD and bunch of other stuff build on it ...

**Comment by BenjV** [comment]
That's their opinion.
Docker is a system that adds a complete operating system to every application you put in in docker container.
I don't see anything usefull except eating resources from a Nas which by design has as little resources as needed.
Only Synology is happy with Docker, because it creates a whole new demand for more powerfull devices and so more expensive devices.

And I see lots and lots of problems with Docker which do not exists with normal package based environments.

**Comment by BenjV** [comment]
Sure that make sense but the problem is that you introduce all kinds of Docker related issues which are only present in a Docker environment and you post it as a problem without saying that you use a problematic environment like Docker.

**Comment by obourdon** [comment]
This is exactly why I also posted a fix for this and I did mention Docker in the reproducible steps.
I am not reporting issue as my pleasure, nor fixing them by the way.
If I had time I am pretty sure I would be able to reproduce this issue on non-docker environment (playing with selinux+acls+perms).
In my experience I have encountered cases where bugs which were hidden until a new/flaky/problematic environment made them obvious to everybody.
YOU find docker problematic but again not everybody does. May be you would say the same thing about some other very common computer env running some well known operating systems ;-)

**Comment by BenjV** [comment]
I could.
Apple devices are also problematic.

Common and well known are not the same as "good quality, mature, and open"

**Comment by obourdon** [comment]
I was definitely not talking about Apple (devil)
Good quality implies fixes bugs and reporting issues, therefore my work here

**Comment by ymartin59** [comment]
Problem is that there is already far enough to do here, to include spksrc Docker support on macOS. And I am reluctant to change anything in spksrc without understanding exactly why there are permissions issue on macOS...

**Comment by pr0d1r2** [comment]
A solution is here: https://github.com/pr0d1r2/spksrc-macos-build

**Comment by pbevin** [comment]
The tar file has mode 0555 on the top-level directory: it doesn't have write permission for any user. If `tar` followed the instructions naively, it would do this:
```
mkdir -m 0555 x86_64-pc-linux-gnu
mkdir -m 0555 x86_64-pc-linux-gnu/share
```
and the second command would fail with `mkdir: cannot create directory ‘x86_64-pc-linux-gnu/share’: Permission denied`.  So GNU tar creates the directory with write permission enabled, and then goes back later and changes it.

Now that slows things down a little, but more importantly, it's a bad thing for the root user to do (for various security reasons). And in fact, it's not even necessary: a quirk of Unix is that [directory write permissions don't apply to root](https://unix.stackexchange.com/q/412234/120182).  So GNU tar creates a directory in two different ways, depending on whether it's running as root:
* If it's a non-root user, it creates the directory with write permission enabled so that the user can create the tree underneath; it then goes back and removes write permission with `chmod` once it's safe to do so.
* If it's root, it creates the directory with its final permission, since the subsequent operations will be possible.

Unfortunately, the root permission assumption doesn't hold in some file systems. That's not exclusive to Docker or Apple: you can see it for yourself if you mount a directory over NFS and then run the two `mkdir` commands above as root.  In the case of Docker on Mac, the host-mounted volume is handled by a process that runs as the Mac-side user running the container. The container believes it's running with root permissions on the file system, but in fact, the permissions are limited to what your Mac user can do locally.

The easiest recourse is simply to run docker with `sudo`:

```
git clone https://github.com/SynoCommunity/spksrc.git
sudo docker run -it --rm -v $(pwd)/spksrc:/spksrc -w /spksrc \
    synocommunity/spksrc:latest /bin/bash -c 'make spk-transmission-88f6281-6.1'
```

Another would be to mount the `work` directory as a named volume, so that it's mounted as a Linux filesystem in Docker Engine:

```
git clone https://github.com/SynoCommunity/spksrc.git
docker run -it --rm -v $(pwd)/spksrc:/spksrc -v volume_name:/spksrc/toolchains/syno-x64-6.1/work -w /spksrc synocommunity/spksrc:latest /bin/bash -c 'make spk-transmission-x64-6.1'
```
