### ISSUE TITLE
Best practice: new package that already provides binaries

### ISSUE THREAD

**Issue by alexanderharm** [SynoCommunity/spksrc#3550]
I wanted to create a `minio` (<https://minio.io/>) package for SynoCommunity. While I understand the the process is very much based on compiling a package from source, I was wondering what would be the best way forward if the project already provides ready compiled binaries. I tested them on several Synology models and they work just fine out of the box.

**Comment by BenjV** [comment]
Do like for example the applications that are written in python, they run from source and don't need to be compiled to binaries.

**Comment by alexanderharm** [comment]
I will check them out. However, there is one issue: checksums are available per binary and architecture. So there isn't one checksum one could test...

**Comment by ymartin59** [comment]
Even there is already examples where package downloads binary online: https://github.com/SynoCommunity/spksrc/blob/master/spk/nzbget/src/service-setup.sh#L17
my opinion is to compile for sources because:
- upstream team may not provide binaries for all expected architectures for DSM, typically: armv7, armv8, x86, ppc32 
- as synocommunity team cannot test on each platform, compiling from sources with DSM toolkit is "known" to work - when a binary built for Linux distribution may fail to run in DSM
- package cannot be installed "offline" (ok, rare usage)

**Comment by alexanderharm** [comment]
OK, thanks for all your feedback. I will try to go along the example of Syncthing and others and compile from source.




On 20. December 2018 at 08:45:25, Yves Martin (notifications@github.com) wrote:

Even there is already examples where package downloads binary online: https://github.com/SynoCommunity/spksrc/blob/master/spk/nzbget/src/service-setup.sh#L17
my opinion is to compile for sources because:

upstream team may not provide binaries for all expected architectures for DSM, typically: armv7, armv8, x86, ppc32
as synocommunity team cannot test on each platform, compiling from sources with DSM toolkit is "known" to work - when a binary built for Linux distribution may fail to run in DSM
package cannot be installed "offline" (ok, rare usage)

**Comment by hgy59** [comment]
closing this issue as minio package is available now and the question of @alexanderharm is answered.
