### ISSUE TITLE
Transmission creating test.file????

### ISSUE THREAD

**Issue by ilatix** [SynoCommunity/spksrc#3626]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ TRANSMISSION
_Package Version:_ 2.93-13

_NAS Model:_ 916+
_NAS Architecture:_ Intel
_DSM version:_ 6.2

### Expected behavior
Tell us what should happen

### Actual behavior
I can see test.file files being generated everyday and I would like to know what they are.
test_1
test_2
test_3
test_4
etc

### Steps to reproduce
_1._ A couple of files a created a day.
_2._
_3._

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by ilatix** [comment]
Does anybody have any idea.  These files are in the Recycle bin.

**Comment by BenjV** [comment]
This kind of questions should be asked in an Transmission forum not here.
My guess is that transmission does some testing and then delete those files.

**Comment by mreid-tt** [comment]
Hi @ilatix, it looks like this issue has been open for some time without any recent updates. Since then, a new version of Transmission (v4.0.3-22) has been released which may have resolved this issue. Can you please test with the latest version and let us know if the issue persists? If we don't hear back from you in a few days, we'll assume the issue has been resolved and close this ticket. Thank you!
