### ISSUE TITLE
Python 2.7 EOL

### ISSUE THREAD

**Issue by hgy59** [SynoCommunity/spksrc#3633]
When creating the new docker image for the build pipeline I got a lot of warnings telling the End of Life of python 2.x at the end of this year (2019)!.

Therefore this issue should initiate a discussion about the timeline and need to remove python 2.7 from the synocommunity build environment and the kick out of all packages depending on python 2.

I know that python 2.7 is the base of a lot of packages here, but let give me some facts:

- I suppose that synology will drop python 2 from the current DSM version this year
- Or may be that synology will introduce a new DSM version with python 3.x only
- Any diskstation running with python 2.x are considered to be vulnerable as of January 1, 2020

Therefore
- We need a schedule to migrate all packages depending on python 2.x to python 3.x
- All the existing packages depending on python 2.x (and python 2.7 itself) should be removed from the repository by end of 2019

let the discussion begin...

**Comment by ymartin59** [comment]
I would even say it question the need to re-publish 2.7.15 and all python2-based packages... Really a large effort which sounds useless if we decide to invest on moving applications to python3 - when supported upstream already.

**Comment by BenjV** [comment]
I very much disagree with this proposal to remove Python 2.
The fact that development  of Python 2 is stopped, does not mean that it is absolute.
Development of python 2 has been stopped already from the day they release the first 2.7 version and that contained only backports from Python 3 to make migration easier.
There are thousands of python scripts that depend on python 2 so it will be around for many, many more years.

And converting all python based package from python 2 to python 3 is not something the SynoCommunity should even try.
It is not an easy task and would require al lot of effort, especially in testing the application.
That can only be done by the developers of the application.

Synology itself stopped distributing the python 2 packages as of DSM 6 but still distribute Python 2 with DSM because DSM 6 uses a lot of python 2 scripts.

Instead of this poorly thought out proposol, I propose to remove the Python 3 package from the SynoCommunity.
Python 3 is distributed by Synology themselves and two Python 3 packages are only creating confusion.
So lets change the packages that use the python 3 of the SynoCommunity to use the Synology version and remove the python 3 package of the SynoCommunity.
We could also create a package that could easily add site-packages to the Synology distribution from the PyPi website so no application should need to distribute those site-packages themselves.

**Comment by hgy59** [comment]
python 2.x usage will be a risk from January 1, 2020 an will stop working some time later.

The message when building the current docker image for this repo ist definite:

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. **A future version of pip will drop support for Python 2.7**.

And python.org release notes for 2.4.7 declares:
Python 2.7.14 is the latest bug fix release in the Python 2.7.x series.

And python.org release schedule for 2.4.7 is:
Being the last of the 2.x series, 2.7 will have an extended period of maintenance. Specifically, 2.7 will receive bugfix support until January 1, 2020. After the last release, 2.7 will receive no support.

So 2.7.x is already on the extended period of maintenance.

So the EOL (=death) of Python 2.x is set and we have some remaining time to decide how to get rid of it.

**Comment by hgy59** [comment]
Did some scanning with `make dependency-tree` for all cross and spk targets and found just a few packages depending on python 2.7

**SPK**
- deluge			(bit torrent client)
- mercurial		(distributed source control system)
- domoticz			(lightweigt home automation system, not found in [packages](https://synocommunity.com/packages))
- python			(python 2.7.14)
- rdiff-backup	(remote incremental backup, beta)
- duplicity		(backup based on rsync, beta)
- octoprint		(3D printer software, beta)
- sabnzbd			(usenet client)
- ffsync			(firefox sync server, beta)

**CROSS**
- boost (dependency of libtorrent, domoticz)

and most of the packages are declared "beta"...

just analyzed `domoticz` so far and regarding its CMakeList.txt it depends on python3 only.

**Comment by BenjV** [comment]
Nonsense Python 2 is not dead, not at risk and will not stop working.
The Python developers did not state any of that an it is of course an absurd statement.
Only new development and bug fixes will stop for pyhon 2, it will not disappear.

Of course everybody should port their application to python 3, but it make no sense to remove the python 2 package with as a result would made multiply packages instant useless.

And if a future version of pip will drop support of python 2 (which is not even announced and most likely will never happen) then you can simple use the current version of pip and pip is not even used for packages of the SynoCommunity.

Python 2 will be around for may years.
You are making a mouse into an elephant.

**Comment by hgy59** [comment]
https://pythonclock.org/

**Comment by BenjV** [comment]
You did not read the text there?
Nothing about, not working, dead, no pip support!
Just end of new development.

**Comment by Safihre** [comment]
I agree with @BenjV, just acting like 1st of January 2020 suddenly there's no need for Python 2 is nowhere near realistic. There is so much actively used Python 2.7 scripts out there.

We are now also switching SABnzbd to Python 3, which should be finished on time.

**Comment by Safihre** [comment]
2.7.16 is coming, they just had RC1. https://github.com/python/cpython/blob/2.7/Misc/NEWS.d/2.7.16rc1.rst

**Comment by hugovk** [comment]
PEP 373 -- Python 2.7 Release Schedule says:

> # Maintenance releases
>
> Being the last of the 2.x series, 2.7 will have an extended period of maintenance. Specifically, 2.7 will receive bugfix support until January 1, 2020. After the last release, 2.7 will receive no support.

https://www.python.org/dev/peps/pep-0373/#maintenance-releases

> # Possible features for 2.7
>
> Nothing here. [Note that a moratorium on core language changes is in effect.]

https://www.python.org/dev/peps/pep-0373/#possible-features-for-2-7

* So Python 2.7 is getting no new features.

* It is getting some bug and security fixes until 2020-01-01.

* After that 2020-01-01, there will be no more Python 2.7 bug fixes, security updates or releases.

**Comment by Safihre** [comment]
We know what it says. Now what do you want to add?
Or what's the plan? Just cold turkey remove it 1st of January 2020? For what purpose other than principles? With no known security issues etc.

**Comment by hgy59** [comment]
I recommend to kick off the python 2.7 spk and all spks that require python 2.7 from this repository.
It is not worth to spend any time on such packages.

**Comment by chickenandpork** [comment]
Seems a bit capricious.  I would rather flag them unsupported, build them for interest’s sake (ie get breakage data) but not merge-blocking on commits, and in cases of complete failure, a user can step up and migrate a package to python3 without a huge resurrection effort.

This would reduce our effort to merely flagging a status for each and removing the unsupported from any list of packages.  

Anyone still stuck on a package using python2 may accidentally get updates but nothing promised.

If we had a way to canary releases in a federated manner, we could keep rolling updates as a side-effect.

**Comment by BenjV** [comment]
Stupid proposal to kick out something which has been around for very long time with no arguments at all.
I propose to ban people with this kind of stupid ideas from this Community.

I predict that python 2.7 will be used for many more years including Synology themselfves.

**Comment by m4tt075** [comment]
Please take it easy. No need to take this further. I believe all perspectives are on the table. I'd like to  propose @ymartin59 looks at it (when he has time), decides how to proceed and then we move on...

**Comment by ymartin59** [comment]
Just some facts:
- Task to upgrade from Python 3.5 to 3.6 tooks lot of effort over more than 5 weeks and finally failed at publishment, and it requires all dependent application packages - only two for the moment: borgbackup and homeassistant
- 2.7.15 PR has been merged but 2.7.16 is already there and all dependent application packages have to be checked to validate it still runs on new version - or else requires itself its own update to python 2.7.15...
My opinion about all these recent events: endless full time job

A way to avoid such continuous workload (which consumes resources and prevents to work on application packages): restrict to only one yearly python3 update
And so, no longer update python 2.7 is another way to spare time. Then come the question how we should handle any security issues that may be noticed: update in urgency, plan for a "regular" update or simply ignore
CC @chickenandpork

**Comment by BenjV** [comment]
My suggestion wout be to update Python 2 juist one more time when 2.7.16 is released and leave of at that version, that will save time.
Testing package that use python 2, is not neccesary because if the minor version does not change it is completly backward  compatible and that is alreeds a long time on 2.7

**Comment by rogervdf** [comment]
So I fiddled with a few packages here and there testing things. Every single issue I had always came down to python issues. 

When a product is EOL usually the sane thing is to clean cut it out as soon as possible, the pain will only become bigger and bigger if it's postponed and weird constructions need to be designed to keep legacy running. One ends up with spaghetti that no-one understands and nobody is willing to support.

**Comment by BenjV** [comment]
Don't confuse problems with packages written in python with problems stemming from python itself.
And chancing over from writing software in python 3 instead of python 2 is of course a very good idea.

But removing python 2 is a very bad idea because there is a lot of very usefull code and even simple scripts out there that needs python 2 which would be suddenly useless if the SynoCommunity would remove the python 2 package.

And speaking of spaghetti, I can assure you that code written for python 2 that is converted to python 3 will not improve in quality and readability.

**Comment by rogervdf** [comment]
There are useful COBOL/BASIC/LOGO scripts out there. Why stop at python2? Maybe there should be support for code punched into cards, or we should be able to control the NAS by turning transistor bulbs. Possibly there should be support for that pre-AD Greek computer found at the bottom of the ocean.

We don't do this because it's heavy, mostly unproductive baggage. It detracts from the goal and consumes energy and time. The way forward is supporting the modern, the popular, the state of the art.

**Comment by BenjV** [comment]
Cobol is still the langue with the biggest in production code in the world.
You are a victim of the current time were new is better is fashionable.
And if you follow the problems of building and maintaining the latest version of python 3 then you should understand that the latest is not always better.

By the way, there was a time that writing code for interpreters like python was a stupid idea, because everything should be compiled.
Nowadays that idea is also outdated.

But I don't see why there is so much fuss about this, just leave python 2 alone if you don't want to use it.
Nobody is forcing you to use it.

**Comment by rogervdf** [comment]
COBOL indeed still has a large production base and it's the reason traditional banks are losing market share fast to FinTechs: Fast, cheap, and flexible transactions instead of tech from the 80s that keeps old programmers from retiring. Now they have to at gunpoint because that generation is dying rapidly and are stuck with the spaghetti.

New languages/packages/libraries come about due to a perceived need. Otherwise no-one would spend the time. Python2 no doubt has its uses but time and energy being limited resources I'll focus on current wants and needs.

**Comment by BenjV** [comment]
Still not an answer why bothering to remove python 2
It is there, does not do any harm, does not need maintenance so why remove it?
Tell your  banking examples to remove all their Cobol programs and see if you can leave the building unharmed.

**Comment by rogervdf** [comment]
Thank you for pointing out the weakness in not phasing out python2: Keeping around legacy creates weak foundations and structural integrity.

**Comment by BenjV** [comment]
You are entitle of you own misconceptions.
