### ISSUE TITLE
[Request] Move fritzctl out of synocli-net to own spk

### ISSUE THREAD

**Issue by hgy59** [SynoCommunity/spksrc#3651]
SynoCli-Net is very welcome, but far from the target to be a set of ***small*** utilities.

The largest tool in synocli-net ist nmap followed by fritzctl.

I did not analyze the amount of shared resources of nmap with other tools, so there may be reasons to keep it in the package.

Otherwise ***fritzctl*** is built by go, and there are no shared resources with other tools, since go apps are selfcontained.
And fritzctl depends on a brand and therefore too, I suggest to make a dedicated spk.

The size of the synocli-net package is > 50MB.
The part of fritzctl is 7.2MB and the part of nmap is about 40MB (including shared libs)

@ymartin59 what are the limits for ***small*** tools? 

_But it's not a matter of size only. While working on the update of go, I run `make all-supported` for synocli-net to validate the build of fritzctl. This takes almost 4 hours (on my debian system with 2 core Pentium G3220 @ 3.00GHz). The build of all cross/fritzctl takes 90 seconds only, but this is without the spk generation._

**Comment by BenjV** [comment]
What is the importance of a little  diskspace more or less.?
These tool only use system memory when used, not when then are juist installed.

**Comment by cytec** [comment]
I'll get the part that it sucks that you'll have to build it for go test purposes but i'd rather split nmap to a Seperate package since it's way bigger and imho more qualified to get it's own package...

fritzctl in fact IS a small tool, considering that it only *explicity* supports 3 boxes and the overall userbase most likely is relatively small...

TL;DL: I'd rather move nmap to its own SPK 

\cc @SynoCommunity/developers
