### ISSUE TITLE
Jackett crash many times per day

### ISSUE THREAD

**Issue by iFredOS** [SynoCommunity/spksrc#3693]
### Setup
_Package Name:_ Jackett
_Package Version:_ 0.11.43-8

_NAS Model:_ DS918+
_DSM version:_ DSM 6.2.1.23824-6

### Expected behavior
Jackett should run forever.

### Actual behavior
Jackett crash nearly every hour.

### Steps to reproduce
_1._ Install Jackett package
_2._ Run Jackett
_3._ Wait a few minutes or hours and check back in Installed Package Center. Instead of seeing 'Installed' you will see a 'Run' button.

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_

[`jackett.log`](https://github.com/SynoCommunity/spksrc/files/3104786/jackett.log)

#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_

[`synopkg.log`](https://github.com/SynoCommunity/spksrc/files/3104949/synopkg.log)

**Comment by ymartin59** [comment]
@m4tt075 Hello. May I ask for help. Thank you in advance

**Comment by m4tt075** [comment]
Cannot judge without logs. @iFredOS Can you provide those? You need to `ssh` into your NAS to get them.

**Comment by iFredOS** [comment]
I did what you ask for when I created the issue report. I attached both log.

**Comment by mreid-tt** [comment]
@iFredOS... checking on some older issues... is this still an ongoing concern or can this ticket be closed?

**Comment by iFredOS** [comment]
Still an issue. Cannot figures why it crashes randomly. Less often then a year ago but still happening from time to time. Once per month or two.

**Comment by mreid-tt** [comment]
okay, looking at your jackett.log, this seems like a normal application startup from 16:14:14 to just after 16:14:32. Then a few more entries at 16:27:51 for normal operations but nothing about a crash. The synopkg.log shows the same app startup at 16:14:11 for a successful startup on 2019/04/22 but nothing after that.

Perhaps we can get some fresh data and move from there... let's get a sense of where we are at now:

1. Are you still on DSM 6.2.1.23824-6 or have you upgraded since then?
2. Are you still on the Jackett 0.11.43-8 or are you on the current 0.20.1171-15 in the repository?

I'd like to see some new logs for:
1. Install Log -- /var/log/packages/jackett.log
2. Service Log -- /var/packages/jackett/var/jackett.log

If you had a recent crash perhaps you can include an approximate date when Jackett was launched and an approximate date/time when it crashed to help narrow down the review of the logs.

Also, when you do get a crash, do you receive any specific message or error? Is the package just not in a running state in the Package Manager?

I know the above may be a bit much but I'm hoping that with an updated and more complete picture we can have a better sense of what is happening.

**Comment by mreid-tt** [comment]
Hi there! It looks like this issue has been open for some time without any recent updates. Since then, a new version of Jackett (v0.20.3521-16) has been released which may have resolved this issue. Can you please test with the latest version and let us know if the issue persists? If we don't hear back from you in a few days, we'll assume the issue has been resolved and close this ticket. Thank you!
