### ISSUE TITLE
rutorrent .spk installed, but gibberish in browser

### ISSUE THREAD

**Issue by collyp** [SynoCommunity/spksrc#3699]
_Package Name:_ ruTorrent
_Package Version:_ v3.7-8 and 3.8-1

_NAS Model:_ DS413j
CPU: MARVELL Kirkwood 88F6282
_DSM version:_ DSM 6.2.1-23824 Update 6

### Expected behavior
When I browse nasip:rutorrentport/rutorrent I expect to be met with rutorrent

But I am met with 5-10 lines of random gibberish, like ›\ùCÜÄÌ

I tried rutorrent.v8.f4458[88f628x].spk then unistalled it and installed  rutorrent.v1.f4458[88f628x].spk but the same symptom occured.

I have previously installed Deluge (and Python 2.7 for it), which worked to access in browser.

**Comment by ymartin59** [comment]
The binary packages you grab are for DSM 5. There is no package for DSM 6 yet.

**Comment by collyp** [comment]
Ah, thanks. Is it planned to be released for DSM 6?

Since "The DSM version is not downgradable", Will I would lose my torrent list and info what volume and folder they are in that I so far have in Deluge?

**Comment by BenjV** [comment]
I have installed this package on my Test Nas (DS116) with DSM 6.2 and could not reproduce this problem.
So I don't think it has anything to do with DSM 5 versus DSM 6 package.
Your problem has something to do with language settings or sysencoding because it looks like your interface is trying to display windows style codepage on an utf-8 system (which Linux is).

**Comment by th0ma7** [comment]
New and update to `rutorrent` version 3.10 uploaded on https://synocommunity.com/package/rutorrent
