### ISSUE TITLE
Home Assistant update?

### ISSUE THREAD

**Issue by rriessen** [SynoCommunity/spksrc#3740]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name: Home Assistant
_Package Version: 0.82.1-2

_NAS Model: Synology NVR1218
_NAS Architecture:_ 
_DSM version: 6.2

When will there be an update of the Home Assistant version to 0.96?

**Comment by chickenandpork** [comment]
This is a complex issue right now: python-3.6 requires both natively-built "wheels" involving some compiled code, and post install wheels pulled on-demand by a system lacking a toolchain yet needing to build C code.

Home Assistant update is being researched in #3643
Python-3.6 issues are being resolved as part of #3726; Python-3.7 would logically build on this, see #3737 

For a narrow set of architecture, @fredrike is working on getting the hass.io manager working, so that Synology users can enjoy the Raspbian-based Hass experience including bolt-on extensions.

**Comment by rriessen** [comment]
So reading this all, it looks like Home Assistant is better of on a Raspberry PI than on a native app for Synology NAS?

Thanks

**Comment by fredrike** [comment]
@rriessen it has it pros and cons. On Raspberry PI you don't have ability for good storage of data and might have performance issue. On Synology there might be some compatibility issues. 

I would say that you are better off getting a RPI 3 or 4 if you can't run hass.io on your Synology (i.e. are not running a x64 arch NAS) and storing the config on a shared volume on your Synology. RPI is the official supported arch https://www.home-assistant.io/hassio/installation/.

**Comment by joaoleveiga** [comment]
Hello! From my understanding of this discussion, this means that upgrading Home Assistant is impossible for (for example DS218play)?

From reading #3673 it seems Python 3.6 should be available for installation, which this somehow can be fixed?

I'm recent to this world of NAS, and Home Assistant, so apologies if I'm missing something obvious :sweat_smile: .

If there's some issue/PR where help is needed to solve this, I'd be glad to take a look and try it out.

**Comment by hgy59** [comment]
@joaoleveiga by updating python3 to 3.7.7 you can update Home Assistant to 0.114.2-7 (but currently you need at least 300MB free in /tmp - #4205)
The first version working with python 3.7.7 is HomeAssistant version 0.87.1-5.
