### ISSUE TITLE
[Update Request] Beets 1.4.9

### ISSUE THREAD

**Issue by SpaceAgeHero** [SynoCommunity/spksrc#3743]
Motivation: Upgrade beets to the latest available version
https://github.com/beetbox/beets/releases/tag/v1.4.9
Linked issues: #2572

**Comment by hgy59** [comment]
done with #3906

**Comment by sirjaymz** [comment]
For beets to work, you must have Control Panel >>> User >>Advanced >>> User Home - "Enable user home service" checked/enabled., otherwise python will exception fault when trying to run $ beet. Specifically, I logged in with any user directly via ssh, admin, root, etc, with zero success. Enabling this resolves the issue, as beet saves the library.db file in the home directory of the user running it.

**Comment by ymartin59** [comment]
@sirjaymz Thanks for the hint. Add as FAQ: https://github.com/SynoCommunity/spksrc/wiki/FAQ-beets
