### ISSUE TITLE
Mono doesn´t work

### ISSUE THREAD

**Issue by Durschti** [SynoCommunity/spksrc#3755]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Mono
_Package Version:_ 5.18.0.240-12

_NAS Model:_ 918+
_NAS Architecture:_ apollolake (x64)
_DSM version:_ 6.2.2-24922 Update 2

Current Behavior

Mono doesn´t work on my NAS ( "Mono required, but it's not installed."

**Comment by BenjV** [comment]
Maybe you should do what is says and install mono?

**Comment by Durschti** [comment]
mono is installed over the package centre. 
the beta from synology 4.6.2 works with http errors.
But this version is not recognized.

**Comment by BenjV** [comment]
For problems with packages from Synology you should  ask Synology and not the SynoCommunity.

By the way the version from the SynoCommunity is much recenter then the beta from Synology.
For which application do you need mono?

**Comment by Durschti** [comment]
WebGrab+Plus. But he does not recognize the installation from mono 5.18. 
What can I do? In which path it is installed ?

**Comment by BenjV** [comment]
WebGrab+ is not a package from the SynoCommunity.
Any package on a Synology Nas that uses another package should be made in such a way that it knows where to find that other package.
It should also have a dependency that makes sure mono is installed in DSM in the correct place.

Because that is most likely is not the case, you either installed it not via a package or it is a faulty package.
Application not installed via the package center don't work very wel on DSM.

But you can try to tell webgraph+ where it can find mono and that location is:
/var/packages/mono/target/bin

**Comment by hgy59** [comment]
@Durschti 
regarding the guide on the WebGrab+ page [Installation on Synology NAS](http://www.webgrabplus.com/documentation/installation/synology-nas) they recommend to install mono of synocommunity.com.

If you install the official Mono (beta) from **synology.com** you will get the following output on **step1** of the guide:
```bash
$ mono -V
Mono JIT compiler version 4.6.2 (Stable 4.6.2.16/ac9e222 Fri Oct 27 17:00:53 CST 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  amd64
        Disabled:      profiler,logging,debug,soft_debug
        Misc:
        LLVM:          supported, not enabled.
        GC:            sgen
```
with this, the installation of WebGrab+ works as expected.

**Alternativ installation of Mono from synocommunity.com**
Since this package does not create a symbolic link to the installed target (anymore?) you have to create the link yourself like this:
`ln -s /var/packages/mono/target/bin/mono /usr/local/bin/mono `

With the link, mono is found in the PATH:
```bash
$ mono -V
Mono JIT compiler version 5.18.0.240 (tarball Tue Mar 19 06:36:09 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       preemptive
        GC:            sgen (concurrent by default)
```

### Remarks:
- to avoid the creation of the symbolic link, you can modify the **`run.sh`** script to run WebGrab+
  a) remove the check of installed mono
  b) use mono with qualified path: `/var/packages/mono/target/bin/mono` to start the application
- on DSM (or Mono) updates, manually created links may be removed and need to be created again.
- there is a lightly different target path for **Mono** from synology vs. **mono** from synocommunity:
synology.com:
`/var/packages/Mono/target/usr/local/bin/mono`
synocommunity.com
`/var/packages/mono/target/bin/mono`
So it is even possible to install both mono packages and use the synology version from PATH and the synocommunity version by qualified path.
- I got WebGrab+ working with both versions of mono on a DS-218+ (same ARCH as DS918+)

**Comment by hgy59** [comment]
Still voting for creation of symlinks into /usr/local/bin for the cli and library packages (not for services, web apps) as proposed in #3687, as it is used by synology for there Mono package.

**Comment by ymartin59** [comment]
Mono is a "beast" to compile and publish... and lack support for recent ARMv8 architectures.
I prefer to document such "symlink issue" in a dedicated FAQ in wiki, as there is chance Mono package will no longer receive updates.
Our effort will go to dotnet core support.
