### ISSUE TITLE
[Package Request] Selfoss for apollolake (x64) - DS218+

### ISSUE THREAD

**Issue by ElDuderino79** [SynoCommunity/spksrc#3786]
Name: Selfoss
Description: web based rss reader
Website: https://selfoss.aditu.de
Software documentation: https://selfoss.aditu.de/#documentation
Build/Installation documentation: https://selfoss.aditu.de/#documentation
Source Code: https://github.com/SSilence/selfoss/releases/download/2.18/selfoss-2.18.zip
License: https://www.gnu.org/licenses/gpl-3.0.html 

SynoCommunity already supports this software for various architectures (https://synocommunity.com/package/selfoss), unfortunatly, the apollolake (x64) one is not available yet. I'd highly appreciate if someone could have a look.

**Comment by digitalbox94** [comment]
You can build directly via spksrc if it's not available ?
I've checked and the spk package is compiling fine for apollolake

**Comment by martinkath** [comment]
I have to admit I have no idea how to do that. Can you provide a HowTo?

**Comment by digitalbox94** [comment]
Quite simple. 

Under an Ubuntu VM for instance :
git clone https://github.com/SynoCommunity/spksrc.git
cd spksrc/
make setup
cd spk/selfoss
make arch-apollolake

=> The spk package for your NAS will be available in the spksrc/packages/ directory :)

**Comment by ymartin59** [comment]
Current package has been designed for DSM 5.2 and have never been tested or migrated to DSM 6.x
It is highly expected it may not work as-is.

**Comment by mreid-tt** [comment]
Given the comment https://github.com/SynoCommunity/spksrc/issues/4524#issuecomment-1750996277, is there demand for a modernised deployment? I can try my hand as I did with ownCloud but it will take some time.

**Comment by hgy59** [comment]
@mreid-tt we sould probably use sqlite instead of mysql/mariadb for selfoss, as you did with OwnCloud.
There is nobody here who solved the integration of packages to use mysql/mariadb.

**Comment by mreid-tt** [comment]
> @mreid-tt we sould probably use sqlite instead of mysql/mariadb for selfoss, as you did with OwnCloud. There is nobody here who solved the integration of packages to use mysql/mariadb.

That was going to be my direction anyway but not because of integration. I did get ownCloud to work with MariaDB however there were a few concerns:
1. The setup of MariaDB in my test machine was so slow the installation seemed to be stuck. The orders of magnitude longer than SQLite was unacceptable as older NAS units would likely timeout in the installation script
2. The credential configuration in the config file was sometimes flaky to link to the DB and was not encrypted at rest which was a security problem
3. The software developer recommended SQLite for home deployments and recommended MySQL/MariaDB for enterprise deployments

As such, taken together it was clear I should be using SQLite.

**Comment by mreid-tt** [comment]
@ElDuderino79, I did a build for this and it would be great if you could test it for me to see if it meets your need. Check out the Artifacts under https://github.com/SynoCommunity/spksrc/pull/5916/checks and let me know if you are able to manually install it.
