### ISSUE TITLE
Synology Ds218play (rtd1296) DSM 6.2.2 no Jackett available

### ISSUE THREAD

**Issue by Hrabac** [SynoCommunity/spksrc#3793]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Jackett 
_Package Version:_ 0.11.43-8 beta

_NAS Model:_ DS218Play 
_NAS Architecture:_ Rtd1296 
_DSM version:_ 6.2.2 24922 update 3

## Expected behavior
Jackett package should be available in Synocommunity repo 

### Actual behavior
Jackett does not appear in the synocommunity repo and neither manual install is possible using 6.1 rtd1296 package most likely due to, jackett not supporting DSM 6.2.xxx versions as of now? 

### Steps to reproduce
_1._  Setup synocommunity repo  or try manual install of Jackett on DS218Play or possibly any other DSM 6.2.xxx NAS 
_2._ Jackett is not available (package is not supported error message during manual spk installation) 
_3._ Any way to fix this or is it simply due to the fact, that Jackett is not yet supported on 6.2.xxx DSM versions? 
 
Please let me know if there is anything that I am missing. 

Thank you in advance

**Comment by hgy59** [comment]
To see Jackett in the Package Center of your diskstation, you have to enable "Beta Packages" since Jackett is declared as beta.
Jackett depends on Mono>=5.4 (from SynoCommunity) so you have to install mono first.
Please provide the exact _error message during installation_.

**Comment by ymartin59** [comment]
Notice Mono does not work properly on ARMv8 64bits "aarch64" architectures like rtd1296...
Refer to #3666 #3715

**Comment by Hrabac** [comment]
I was able to get Mono working and using Sonarr and Radarr which depend on Mono, so that should not be an issue on my end. My main point is that Radarr and Sonarr are not able to use other than English language for searching torrents which makes them useless for me, so I wanted to setup, jackett to take care of the rss syncing as I see that trackers I am using are actively supported by jackett, however due to this issue I am most likely going to use a spare Rpi 3B+ that I have with raspbian and Jackett configured to parse torrents to the nas, where sonarr and radarr are running.

**Comment by hgy59** [comment]
I am still requesting the detailed error message. With mono installed there should not be such an error. At least not by installation from the synocommunity package center.
Maybe you manually installed a spk for an unmatching arch?
I suppose the error is not related to mono. The problems of mono with 64 bit arm archs are at runtime and not at installation.

**Comment by Hrabac** [comment]
Hello hgy59, I am actually trying to install it manually, package has been downloaded from SynoCommunity, however my issue is that the available package is rtd1296 6.1, whereas my nas has DSM 6.2.2 24922 (update 3) installed (architecture of Ds218play is rtd1296).

So the only error message I will get is during manual installation (which is the only way to even try installing Jackett) of the package stating, that "this package is not supported by current DSM version". Unfortunately, I have left my country and I am not currently able to access the NAS due to my security settings which are blocking access from other countries (due to those "bruteforce" attacks coming from everywhere. So I currently cannot provide any log until Friday.

I am not sure, whether the log will help, but I can provide it on Friday if still needed (given the issue).

Thanks for your help so far :)

**Comment by hgy59** [comment]
IMO this is related to arch and not version.
@ymartin59 may be it is time to introduce armv8 arch?
On https://usdl.synology.com/download/Package/spk/ on a quick look I can't see any rtd1296 arch but there are armv5, armv7 and armv8 packages.

As a reference I looked at a package released 02/2019:
https://usdl.synology.com/download/Package/spk/DNSServer/2.2.1-5014/

Synology deploys the following archs:
- armada38x
- armada370
- armada375
- armadaxp
- armv5
- armv7
- armv8
- comcerto2k
- i686
- monaco
- ppc
- x86_64

make all-supported generates the following archs:
- 88f6281  (may be synology armv5)
- aarch64  (may be synology armv8)
- alpine  (may be synology armv7)
- armada38x
- armada370
- armada375
- armadaxp
- comcerto2k
- evansport (same as i686)
- hi3535  (SRM)
- ipq806x  (SRM, only few synology packages like DNSServer 1.2)
- monaco
- northstarplus  (SRM, only few synology packages like DNSServer 1.2)
- ppc853x
- qoriq   (may be synology ppc)
- x64 (same as x86_64)

**Or may be it is related to os_min_ver vs firmware:**

The synology VideoStation spk has archs rtd1296 and armada37xx instead of armv8 and has "firmware="6.0.8451" declared in INFO file.

Our jackett spk for "rtd1296 armada37xx aarch64" has os_min_ver="6.1-15047" and no firmware defined in INFO file.

As a first try I propose to add "armv8" to our jackett spk and (optionally) set os_min_ver="6.0-7473"

**Comment by Hrabac** [comment]
I have actually managed to install Jackett manually via the version 0.10.589-7 available in SynoCommunity website (rtd1296) and then update Jackett to the latest version through package center. Still not sure, why the latest version could not be installed directly. Anyway, thanks for all inputs guys. Currently I need to setup, jackett in Radarr correctly as for some reason, it is not grabbing movies even though manual Jackett search works like a charm. But this will be another issue and if needed, I will turn to Radarr github directly.
