### ISSUE TITLE
pyopenssl Issues

### ISSUE THREAD

**Issue by HPMSGEN8** [SynoCommunity/spksrc#3806]
Hi, 

For some odd reason i am getting the below error with medusa via docker:

pyopenssl module missing, please install for https access.

I have Python 2 and 3 installed as well as the Modules. I have tried to install this but no luck.

Any help on this please

Thanks

**Comment by BenjV** [comment]
Adding module by yourself does not has any us, Medusa uses a virtual environment for all non standard modules so self installed modules cannot be used.
But I think the problem is something else, please read this thread.
https://github.com/pymedusa/Medusa/issues/7350

By the way this kind of issue do not belong here you should post them on the Medusa GitHub.
