### ISSUE TITLE
Syncthing on qorig

### ISSUE THREAD

**Issue by ErinVoid** [SynoCommunity/spksrc#3810]
### Setup
Syncthing
1.2.2 and uodates

DS213+
qorig
6.2 updated

Please can qorig be readded to the arch list of  Syncthing. It was a previous issue (#3460), was added but seemingly dropped for1 x.x.

Many thanks,

**Comment by hgy59** [comment]
There was never a working version of syncthing for qoriq processors.
Since goland does not support ppc32 arch (and syncthing is written in golang) it is not possible to build syncthing for DS213+.
The issue you mentioned was resolved by disabling qoriq.
All you can do is to vote for ppc32 support [here](https://github.com/golang/go/issues/22885)

**Comment by ErinVoid** [comment]
Thanks you @hgy59. My DS is becoming an expensive paperweight due to the processor!
