### ISSUE TITLE
ffmpeg does not play eac3 or H264 1080p content in matroska,webm container.

### ISSUE THREAD

**Issue by YerBabiE** [SynoCommunity/spksrc#3848]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ 
_Package Version:_  4.1-11

_NAS Model:_ DS1817+
_NAS Architecture:_ 
_DSM version:_ DSM 6.2.2-24922 Update 4

### Expected behavior
eac3 / h264 1080P does not play from a matroska,webm container.

### Actual behavior
It does not play.

### Steps to reproduce
_1._ 
_2._ 
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by th0ma7** [comment]
I believe you have found a solution based on https://github.com/SynoCommunity/spksrc/issues/2952#issuecomment-572415925 which is using solution provided from https://github.com/SynoCommunity/spksrc/pull/3822 using testing packages ?

As "official" packages are to become avalaible and your issue is solved can we close this issue?

**Comment by YerBabiE** [comment]
Problem / Solution covered in other ticket as mentioned.
