### ISSUE TITLE
（transmission）Anomaly in Synology causes  to crash

### ISSUE THREAD

**Issue by BH1NBN** [SynoCommunity/spksrc#3886]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Transmission
_Package Version:_ 2.94-16

_NAS Model:_ sysnology
_NAS Architecture:_ x86 x64
_DSM version:_ 6.15

1. When the downloaded file name exceeds a certain value, according to the online data, 255 characters will be displayed. The file name is too long and the transfer failed. 
myfilename:
/volumeUSB3/usbshare/PT/M-Team/伊東ちなみ Chinami Ito/MDVR-025 【VR】伊東ちなみがじ～っ (3)
(Error: file name is too long)

2. If the download path does not exist, the transfer will crash

Hope to update as soon as possible, many people around me are already talking about this situation

**Comment by chickenandpork** [comment]
SynoCommunity bug fixes are probably best resolved in upstream before repackaged for Syno.  Has this been resolved in upstream Transmission?

If not, the patching and fixing of an issue often requires that we can test and confirm on hardware we don’t personally have.  I see non-english characters, there might be (Unlikely) a multibyte issue related to that.

**Comment by BH1NBN** [comment]
> SynoCommunity bug fixes are probably best resolved in upstream before repackaged for Syno. Has this been resolved in upstream Transmission?
> 
> If not, the patching and fixing of an issue often requires that we can test and confirm on hardware we don’t personally have. I see non-english characters, there might be (Unlikely) a multibyte issue related to that.

This problem has been solved in the download station of sysnology because he evolved from transmission. I think you can refer to it? I don't know much about programming, but how can I help you?

**Comment by chickenandpork** [comment]
> I think you can refer to [ source code for Download Station]?

We're a community group, we're not the Synology company, so we cannot see non-open source.

SynoCommunity Transmission was updated to version 2.94 with #3303

The most straightforward update -- and the one that allows the complex part of fixing this issue be used by all users of Transmission on or off Synology -- would be to see the fix in the opensource Transmission.

It might be transmission/transmission#122 (pushed to 3.0 release) (attempted to be fixed by https://github.com/transmission/transmission/commit/bb47410 ) but it's been suggested that multibyte plus a deep set of folders might exacerbate the 255 limit to cause an issue.  bb47410 moved filenames to hashes, but a deep folder would still cause an issue with a 255 max and path length.

Note also https://github.com/transmission/transmission/issues/772#issuecomment-571151448 --> "old libevent cannot handle newer openssl" so there might be other issues.

3.0 is the branded version since 2019-07-21 so there's some signs of a new release perhaps coming.  Last official release is still 2.94 which was packaged by #3303.  Unless a contributor is using the package, it's difficult to build something we're not personally using without some structure to remove the obstacles to collecting signal and user feedback on betas.

**Comment by BH1NBN** [comment]
Thank you for your answer
