### ISSUE TITLE
[Update Request] borg

### ISSUE THREAD

**Issue by askarsabyrov** [SynoCommunity/spksrc#3934]
Update Request for borg package due to important bug fixes, that causes data corruption.
https://borgbackup.readthedocs.io/en/stable/changes.html

**Comment by noplanman** [comment]
I'd really love to see an update of borg too, the latest version (1.1.7) for Syno is from August 2018 :scream: 

Many important fixes and features have come along, so it would be great to be able to take advantage of them.

@ymartin59 @yuroller Maybe do your thing like last time? :innocent:
#3471

**Comment by noplanman** [comment]
Well, what's working for me so far with the latest version 1.1.11, which I hadn't tried in a while, is to just use one of my prebuilt binaries: https://borg.bauerj.eu/

**Comment by yuroller** [comment]
Rebuilding current borgbackup 1.1.9 package on arch-88f6281 with new pyhton3 package works after applying pull request #3928 , but it fails to run.
When I try to run it, there is a failure probably due do inability to load libssl library (installed python3 package).
`admin@Blackbox:~$ borg
Traceback (most recent call last):
  File "/volume1/@appstore/borgbackup/env/lib/python3.6/site-packages/borg/archiver.py", line 38, in <module>
    from . import helpers
  File "/volume1/@appstore/borgbackup/env/lib/python3.6/site-packages/borg/helpers.py", line 75, in <module>
    import borg.crypto.low_level
ModuleNotFoundError: No module named 'borg.crypto.low_level
`
the compiled low_level.*.so module is present but I think it is unable to load it because it is missing some dependencies (libssl.so?).

Any hint about what the python3 or openssl updates could have changed?
