### ISSUE TITLE
DS216j  with  DSM 6.2.2-24922   jackett not updated

### ISSUE THREAD

**Issue by giospud** [SynoCommunity/spksrc#3948]
Dear all,
I have a DS216j with DSM 6.2.2-24922 and I am running jackett version 0.11.43.8 which is distributed through the SynoCommunity site. Actually opening jackett on the NAS it tells me that it is not updated and that v0.14.541 is available. I was wondering if there is any plan to give the release of the updated jackett through the synocommunity or if it would be necessary to install it directly on the NAS via ssh terminal (not really easy and straightforward)...
It would be really great if you could prepare the updated version of jackett because the current one is not almost working any more

**Comment by ymartin59** [comment]
The reason is that I have temporarily disabled updates (after having them published for one day) because of a blocker bug.
Knowing it only concerns ARM64 architectures, I have enabled again updates, so you should be able to install from Package Center as expected.
Another option is to use "Manual Installation" from Package Center with files downloaded from web pages: https://synocommunity.com/packages

**Comment by ymartin59** [comment]
@giospud Please close this issue when you have been able to update your packages. If not please provide feedback.

**Comment by giospud** [comment]
Dear @ymartin59 
I installed the updated version and it is working properly. Thanks for the effort and for the valuable work you are doing for the SynoCommunity
