### ISSUE TITLE
TVHeadend: Huge CPU usage after upgrade

### ISSUE THREAD

**Issue by dav1170** [SynoCommunity/spksrc#3971]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ TVHeadend
_Package Version:_ 4.3.2

_NAS Model:_ DS918+
_NAS Architecture:_ INTEL Celeron J3455
_DSM version:_ DSM 6.2.2-24922 Update 4

### Expected behavior
Upgrade goes fast

### Actual behavior
This is the case for this upgrade and the previous one: after upgrading package, the upgrade process tell me that I have to update permissions.
And then, for hours, a bzip task will use almost 100% of my CPU. during this period, unable to access to tvheadend.

### Steps to reproduce
_1._ 
_2._ 
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Wed Apr 22 12:35:52 NZST 2020
===> Step preupgrade. USER=tvheadend GROUP=sc-media SHARE_PATH=
Invoke service_preupgrade
Save potential recordings from package root directory...
Move any recording directories from package root directory into var...
Wed Apr 22 13:39:06
===> Step preuninst. USER=tvheadend GROUP=sc-media SHARE_PATH=
Wed Apr 22 13:40:01
===> Step postuninst. USER=tvheadend GROUP=sc-media SHARE_PATH=
Wed Apr 22 13:40:02
===> Step preinst. USER=tvheadend GROUP=sc-media SHARE_PATH=
Wed Apr 22 13:40:03
===> Step postinst. USER=tvheadend GROUP=sc-media SHARE_PATH=
Installing service configuration /var/packages/tvheadend/conf/tvheadend.sc
Invoke service_postinst
Fixing fontconfig links
Granting 'sc-tvheadend' unix ownership on /volume1/@appstore/tvheadend/var
Wed Apr 22 13:40:03
===> Step postupgrade. USER=tvheadend GROUP=sc-media SHARE_PATH=
Granting 'sc-tvheadend' unix ownership on /volume1/@appstore/tvheadend/var
Invoke service_postupgrade
Adding sc-media group permissions on recording directories:
Skip: /usr/local/tvheadend/var/recordings (system directory)
Skip: /usr/local/tvheadend/var/recordings (system directory)
Skip: /usr/local/tvheadend/var/recordings (system directory)
Restore 'sc-tvheadend' unix permissions on package system directories
Granting 'sc-tvheadend' unix ownership on /volume1/@appstore/tvheadend/var


Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by dav1170** [comment]
task is 

sc-tvhe+ 21156  0.4  0.0   6808  2160 ?        S    15:57   2:18  \_ /bin/tar cjf /volume1/@appstore/tvheadend/var/backup/4.3.99rc1~221c29b.tar.bz2 --exclude backup --exclude e
sc-tvhe+ 21157 97.5  0.0  11572  8492 ?        R    15:57 461:29      \_ bzip2

**Comment by ymartin59** [comment]
Recordings should not be in package "var" folder: /usr/local/tvheadend/var/recordings
But located on a DSM volume out of package itself.
@th0ma7 May you help to fix this?

**Comment by th0ma7** [comment]
Hi @dav1170 
Your situation seems a little odd.  Perhaps you can help me understand a few things: first off what is the version and source of the `tvheadend` package you are installing?  Because version 4.3.2 never existed from SynoCommunity sources, have a look at versions available here:
* https://synocommunity.com/package/tvheadend

Also I notice that the backup is making a reference to a "previous" installation referred with a version number of 4.3.99rc1~221c29b which from initial searches points to German sources dating as far as 2017.

SynoCommunity `tvheadend` package doesn't do any bz2 backup as far as I can see so this is most probably a post-uninstall job from a previously installed package from an external soruce.

I believe you are updating a previous version of `tvheadend` that was installed from another source leading to this issue.  SynoCommunity cannot confirm any compatibility with packages provided by other providers.  As such, in order to our provided version I strongly suggest you to use a fresh install such as:
1. create a backup of your `tvheadend` configuration
2. uninstall all previous versions you might have install
3. then proceed with a "fresh" install of SynoCommunity tvheadend package.
4. recover your backup

Lastly note that previous configurations will most probably not be compatible with the newer version and recovering records will be a challenge due to recording folder that must be located under a usual `/volumeX/` directory structure.  A fresh reconfiguration is most probably the easiest.

**Comment by th0ma7** [comment]
Any update @dav1170 ?

**Comment by th0ma7** [comment]
Closing as no updates.
