### ISSUE TITLE
How to integrate Transmission_Web_Control when compiling Transmission?

### ISSUE THREAD

**Issue by fyngd** [SynoCommunity/spksrc#3997]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Transmission
_Package Version:_ 3.00

_NAS Model:_ 
_NAS Architecture:_ x64
_DSM version:_ 6.2.3-25426

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._ 
_2._ 
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by hgy59** [comment]
@fyngd what is your question? Please edit the issue and fill (or remove) "unedited template text"  like "Expected behavior ...."

The web UI of transmission is integrated in the package and is reachable with the link in the DSM package list after installation.
If you request the update to version 3.00 with this issue, this is solved with #4009.

If your question really is `How to integrate Transmission_Web_Control when compiling Transmission?` then you can look into cross/transmission/Makefile or ask your question in transmission forums.

In the cross/transmission/Makefile you find nothing special for this. It uses the standard `configure` for definition of the build configuration. Our framework uses `CONFIGURE_ARGS` to define the arguments for ./configure and building the web UI is enabled by default.
