### ISSUE TITLE
Sonarr won't run

### ISSUE THREAD

**Issue by gordonnmurray** [SynoCommunity/spksrc#4020]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Sonarr
_Package Version:_ 20200409-16

_NAS Model:_ DS1815+
_NAS Architecture:_ Synology
_DSM version:_ 6.2.3-25426

### Expected behavior
Tell us what should happen

When I click on restart it should restart after a few seconds.

### Actual behavior
Tell us what happens instead

I click on restart and the package stops running.  I try and click run but it runs for a few seconds and then stops.  Need to restart nas before it'll run again.

### Steps to reproduce
_1._ click restart
_2._ 
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
Insert the package log here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```
![Screenshot from 2020-06-10 23-46-06](https://user-images.githubusercontent.com/62679392/84326398-b20d6600-ab74-11ea-88a0-4f302a17f3f9.png)

**Comment by Diaoul** [comment]
I think without logs it will be hard to know what's wrong.
I suspect you clicked the restart button in Sonarr itself, leading Sonarr to shutdown and start again. Maybe its locked in shutdown and cannot restart. Package Center cannot start it because it's already running and taking the port.
Hopefully a restart of the NAS should fix this.

**Comment by mreid-tt** [comment]
Hi there! It looks like this issue has been open for some time without any recent updates. Since then, a new version of Sonarr v3 (v20230217-22) has been released which may have resolved this issue. Can you please test with the latest version and let us know if the issue persists? If we don't hear back from you in a few days, we'll assume the issue has been resolved and close this ticket. Thank you!
