### ISSUE TITLE
Synology DS 420 + http://packages.synocommunity.com 

### ISSUE THREAD

**Issue by Herodes1** [SynoCommunity/spksrc#4065]
Hello i get no response from http://packages.synocommunity.com via DSM and website https://synocommunity.com/ seems to have cloudfare problems, and it have been like this for some days now.
Anyone knows when the site will be back up.

On my DS 213j it is working.
On my DS 420+ isnt it.

**Comment by ymartin59** [comment]
You should register https://packages.synocommunity.com in DSM as documented at https://synocommunity.com/
DS420+ is geminilake arch and no arch specific package has been published for this arch yet - https://github.com/SynoCommunity/spksrc/wiki/Synology-and-SynoCommunity-Package-Architectures

**Comment by Herodes1** [comment]
Hallo Yves, I did this but nothing is happening. please take look on the ScreenshotsAm 09.07.2020 22:08 schrieb Yves Martin <notifications@github.com>:
You should register https://packages.synocommunity.com in DSM as documented at https://synocommunity.com/
DS420+ is geminilake arch and no arch specific package has been published for this arch yet - https://github.com/SynoCommunity/spksrc/wiki/Synology-and-SynoCommunity-Package-Architectures

**Comment by icegunner** [comment]
Given that the geminilake arch is a still an x86/x64 arch, shouldn't packages that are built for archs like avoton, apollolake, etc. be supported? Wouldn't most of those packages also be compatible/tagged and therefore show up in Package Manager?
If this isn't the case, isn't there a way to manually install packages even they don't appear in the Package Manager for those brave enough to give it a try? I'd be up for that.

**Comment by ymartin59** [comment]
@icegunner No because package contains exact list of architectures it is expected to support. At worst, it may be possible to edit INFO file in spk tar archive - you may try on your own to use `tar tvf package-version.spk`, extract INFO, edit and update INFO in archive.
Until this trouble https://github.com/SynoCommunity/spkrepo/issues/47 is not fixed, I cannot publish any update

**Comment by icegunner** [comment]
@ymartin59 Now that [SynoCommunity/spkrepo#47](https://github.com/SynoCommunity/spkrepo/issues/47) is fixed, what does the timeline pushing updates look like? Would love to migrate all my packages to my 920+. No rush, just very interested. Thank again for all you do.

**Comment by THX723** [comment]
@ymartin59 I tried building the package on my private server and there appears to be some checksum related issue with x264.
```
make[3]: Entering directory '/spksrc/cross/x264'
===>  Downloading files for x264
wget https://code.videolan.org/videolan/x264/-/archive/stable//x264-snapshot-20200419-stable.tar.bz2
2020-07-14 23:17:26 URL:https://code.videolan.org/videolan/x264/-/archive/stable//x264-snapshot-20200419-stable.tar.bz2 [767777/767777] -> "x264-snapshot-20200419-stable.tar.bz2.part" [1]
===>  Verifying files for x264
===>    Checking sha1sum of file x264-snapshot-20200419-stable.tar.bz2
===>      Wrong sha1sum for file x264-snapshot-20200419-stable.tar.bz2
===>      Renamed as x264-snapshot-20200419-stable.tar.bz2.wrong
===>      Download cookie removed to trigger the download again
make[3]: *** [../../mk/spksrc.checksum.mk:42: checksum_target] Error 1
make[3]: Leaving directory '/spksrc/cross/x264'
make[2]: *** [../../mk/spksrc.depend.mk:44: depend_target] Error 2
make[2]: Leaving directory '/spksrc/cross/ffmpeg'
make[1]: *** [../../mk/spksrc.depend.mk:44: depend_target] Error 2
make[1]: Leaving directory '/spksrc/spk/ffmpeg'
make: [../../mk/spksrc.spk.mk:436: arch-x64] Error 2 (ignored)

```

**Comment by th0ma7** [comment]
Fixes for that issue with `x264` are pending in pull request (PR) https://github.com/SynoCommunity/spksrc/pull/4062
Feel free to use my local ffmpeg tree at:
* version 4.2.3:  https://github.com/th0ma7/spksrc/tree/tvh-next  (pending merge)
* version 4.3: https://github.com/th0ma7/spksrc/tree/ffmpeg-next (work still in progress)

`x64` packages builds should run on newer 420/920 models

**Comment by THX723** [comment]
@th0ma7 Just cloned your fork and rebuilt with the same exact errors.

```
make[3]: Entering directory '/spksrc/cross/x264'
===>  Downloading files for x264
wget https://code.videolan.org/videolan/x264/-/archive/stable//x264-snapshot-20200419-stable.tar.bz2
2020-07-15 03:58:02 URL:https://code.videolan.org/videolan/x264/-/archive/stable//x264-snapshot-20200419-stable.tar.bz2 [767777] -> "x264-snapshot-20200419-stable.tar.bz2.part" [1]
===>  Verifying files for x264
===>    Checking sha1sum of file x264-snapshot-20200419-stable.tar.bz2
===>      Wrong sha1sum for file x264-snapshot-20200419-stable.tar.bz2
===>      Renamed as x264-snapshot-20200419-stable.tar.bz2.wrong
===>      Download cookie removed to trigger the download again
make[3]: *** [../../mk/spksrc.checksum.mk:42: checksum_target] Error 1
make[3]: Leaving directory '/spksrc/cross/x264'
make[2]: *** [../../mk/spksrc.depend.mk:44: depend_target] Error 2
make[2]: Leaving directory '/spksrc/cross/ffmpeg'
make[1]: *** [../../mk/spksrc.depend.mk:44: depend_target] Error 2
make[1]: Leaving directory '/spksrc/spk/ffmpeg'
make: [../../mk/spksrc.spk.mk:436: arch-x64] Error 2 (ignored)

```

**Comment by THX723** [comment]
@th0ma7 I stand corrected. I didn't checkout the right commits. It now completes the build; both 4.2.3 and 4.3. And they installed okay on my DS920+.

No problem with H264. H265/HEVC still exhibits the same decoding bug in previous Intel Media Driver releases. I was really hoping the newer driver 20.2.0 (2020-Q2) in 4.3 would do better. No such luck. The truth of the matter is Intel has not yet started integration and test of Gemini Lake.

In the meantime, I manually deleted the iHD driver to force the use of i965 driver instead. This is workable for now. H265 works okay for the most part, with minor pixelation in specific instances. CPU load is 30-40%, since these drivers are not yet fully optimized for Gemini Lake.

**Comment by THX723** [comment]
Crazy timing. Literally just got notified that Intel has pushed out an update for media driver to 2020Q3 Pre-release 20.3.pre3. @th0ma7 Let me know once you're done updating that and I will take that for another test drive.

**Comment by th0ma7** [comment]
`geminilake` package is on its way (version 4.2.4).  Leave me a day or two and it should be available.

**Comment by th0ma7** [comment]
> Crazy timing. Literally just got notified that Intel has pushed out an update for media driver to [2020Q3 Pre-release 20.3.pre3](https://github.com/intel/media-driver/releases/tag/intel-media-20.3.pre3). @th0ma7 Let me know once you're done updating that and I will check that out for another test drive.

Indeed.  Depending when I can push 4.3.1 out I might include it.  I would suggest you oepn a bug report on intel github at https://github.com/intel/media-driver/issues with a screenshot or something?

Otherwise I made available official `geminilake` packages over the week-end for `ffmpeg`.  Can this bug now be closed?
