### ISSUE TITLE
Syncthing v1.7.1-20 Synology platforms

### ISSUE THREAD

**Issue by Kaelber** [SynoCommunity/spksrc#4097]
I do not understand the changes regarding the changed platform landscape from [Syncthing v1.4.0-19 to v1.7.1-20](https://synocommunity.com/package/syncthing). From version 1.7.1-20 there are missing important and essential platforms like apollolake, avoton, braswell, bromolow, cedarview and other and important new platforms like Geminilake for e.g. DS920 +, DS420 + etc. are also missing. How does it all come?

**Comment by Kaelber** [comment]
I saw now, is also related to the Geminilake issues

https://github.com/SynoCommunity/spksrc/issues/4070#issue-657415255

https://github.com/SynoCommunity/spksrc/issues/4065#issue-653959418

https://github.com/SynoCommunity/spksrc/issues/3999#issue-626399503

**Comment by acolomb** [comment]
I also noticed that change of availability because my DS218j would not show the update (despite the armada38x platform still being listed). Not sure what's going on there but it might be related to recent rework on the package server side and this repo's continuous integration setup.

At least I don't know of any supported platforms being dropped in the latest Syncthing SPK update. Many were folded into more generic platform families for which there is only one compatible package, but that was an independent overall spksrc change.

I'll see what I can find out from my local build, but I'm currently quite short on time.

The geminilake packages are not available simply because the build toolchains were not yet published by Synology AFAIK. As you probably found out in the other issues.

**Comment by acolomb** [comment]
By the way, on the package page you linked, all publishing dates are the same from 2015, so there are obviously still some bugs to be ironed out in the repository server code.

**Comment by acolomb** [comment]
@ymartin59 Apparently at least all the architectures based served by the generic `x64-6.1` build are missing on the page, although the respective [build](https://github.com/SynoCommunity/spksrc/runs/915349489) was successful. Sounds like a bug in the publishing process?

**Comment by ymartin59** [comment]
For unknown reason, publish x64 package has failed. Fixed.
