### ISSUE TITLE
Problem with home assistent 0.114.2-7  on dj218j - Armada38x

### ISSUE THREAD

**Issue by avol-io** [SynoCommunity/spksrc#4171]
Hi thanks for great work.

Unfortunately the application not start.

This is the log:
cat /var/packages/homeassistant/target/var/homeassistant.log

`Thu Sep 10 10:46:08 CEST 2020
Starting homeassistant command /volume1/@appstore/homeassistant/env/bin/hass -v --config /volume1/@appstore/homeassistant/var/config --pid-file /volume1/@appstore/homeassistant/var/homeassistant.pid --log-file /volume1/@appstore/homeassistant/var/homeassistant.log --daemon 
/var/packages/homeassistant/scripts/start-stop-status: line 49: /volume1/@appstore/homeassistant/env/bin/hass: No such file or directory
`

check:
ls: cannot access /volume1/@appstore/homeassistant/env/bin/hass: No such file or directory

I made some mistake?

**Comment by Mr-Groch** [comment]
If there is  `[Errno 28] No space left on device`  in /var/packages/homeassistant/target/var/homeassistant_install.log then you should set TMPDIR environment to some folder in /volume1 and run service_postinst instructions manually, for example:

```
sudo mkdir /var/packages/homeassistant/target/var/tmp
sudo TMPDIR=/var/packages/homeassistant/target/var/tmp /var/packages/homeassistant/target/env/bin/pip install --no-deps --no-index -U --force-reinstall -f /var/packages/homeassistant/target/share/wheelhouse /var/packages/homeassistant/target/share/wheelhouse/*.whl
sudo mkdir /var/packages/homeassistant/target/var/config
sudo chown -R sc-homeassistant /var/packages/homeassistant/target/env
```
Worked for me :)

**Comment by avol-io** [comment]
great! now start! thank you. but I believe that the bug must remain open because the installation file must be modified with a solution similar to yours.

But also if the application start when I go to http://192.168.1.223:8123/  it tells me that the connection with the server is not possible

**Comment by Mr-Groch** [comment]
IMO this should be left opened - issue should  be fixed in package. My answer was just a workaround.

**Comment by avol-io** [comment]
you are right

**Comment by ymartin59** [comment]
May you please provide this `homeassistant_install.log` where you have found error about file system space?

**Comment by jballow** [comment]
I'm experiencing the same issue...
`Installing collected packages: HAP-python, Jinja2, MarkupSafe, PyISY, PyJWT, PyYAML, aioautomatic, aiohttp, aiohttp-cors, aiohue, astral, async-timeoutt
, attrs, boto3, certifi, cffi, chardet, ciso8601, colorlog, curve25519-donna, distro, ecdsa, ed25519, ephem, gTTS-token, gmpy2, home-assistant-frontendd
, homeassistant, homekit, idna-ssl, ifaddr, ledcontroller, multidict, mutagen, netdisco, netifaces, oauth2client, paho-mqtt, phue, pushbullet.py, pycpaa
rser, pycryptodome, pycsspeechtts, pyephem, pyephember, pyfritzhome, pyfttt, pyotp, pysabnzbd, pysnmp, python-libnmap, python-nmap, python-pushover, pyy
thon-slugify, python-wink, pytz, requests, ruamel.yaml, six, text-unidecode, tlslite-ng, transmissionrpc, typing, ua-parser, urllib3, user-agents, voluu
ptuous, voluptuous-serialize, wakeonlan, websocket-client, xbee-helper, xmltodict, yarl, zeroconf
  Attempting uninstall: MarkupSafe
    Found existing installation: MarkupSafe 1.1.1
    Not uninstalling markupsafe at /volume1/@appstore/python3/lib/python3.7/site-packages, outside environment /volume1/@appstore/homeassistant/env
    Can't uninstall 'MarkupSafe'. No files were found to uninstall.
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 5.3
    Not uninstalling pyyaml at /volume1/@appstore/python3/lib/python3.7/site-packages, outside environment /volume1/@appstore/homeassistant/env
    Can't uninstall 'PyYAML'. No files were found to uninstall.
  Attempting uninstall: cffi
    Found existing installation: cffi 1.14.0
    Not uninstalling cffi at /volume1/@appstore/python3/lib/python3.7/site-packages, outside environment /volume1/@appstore/homeassistant/env
    Can't uninstall 'cffi'. No files were found to uninstall.
ERROR: Could not install packages due to an EnvironmentError: [Errno 28] No space left on device

~                                                                                                                                                      
~            `
