### ISSUE TITLE
[Package Request] Unifi Network Controller

### ISSUE THREAD

**Issue by defaultsecurity** [SynoCommunity/spksrc#4315]
Synology NAS is perfect for the job, since it is online 24/7. If the Unifi software could be updated using its own interface, that would be awesome. We know it runs via [docker](https://hub.docker.com/r/jacobalberty/unifi/), but keeping it updated is tedious.

**Comment by hgy59** [comment]
Once upon a time I had the unifi controller package installed from `http://synology.acmenet.ru/` and I must say that this was tedious. (before I used unifi controller on Raspi 2nd gen for about 5 years).

Since I use docker for unifi controller on my DS918+ I have no problems with updates anymore. You only have to regard to use explicit image-tags (avoid latest) and respective container names. Than you can reuse the volume and benefit of automatic db migration.

So my latests version where
- jacobalberty/unifi:5.10.27
- jacobalberty/unifi:5.14.23
- jacobalberty/unifi:6.0.22

My upgrade scenario it the following (use the DSM docker app for all except the first step)
- backup database in current unifi controller (just for the case something goes wrong)
- download new docker image with explicit tag
- duplicate and rename the settings of the current container
- use the new docker image in the new container settings
- stop current container
- start new container
- if everything runs well with the new container: delete the old container

Hop this helps somone

PS
I know that only Diskstations with x86/x64 processors support docker, but IMHO it is not worth any effort to create generic unifi controller packages for ARM 32/64 bit archs.

**Comment by BenjV** [comment]
Besides use in a docker, it is not possible to make a package for this software because Unifi only supplies binaries and no sources so crosscompiling for Synology devices is not possible.

**Comment by Djangox** [comment]
I've never (I don't think) had any issue with http://synology.acmenet.ru/. Alexander updates his packages pretty frequently and me updating is no more tedius than updating anything from here (sometimes much less-grin)... (nothing against synocommunity or docker.. I use both).

**Comment by hgy59** [comment]
As this is already available on http://synology.acmenet.ru/ we won't create a duplicate package here.
