### ISSUE TITLE
PlexPy Custom with Python3

### ISSUE THREAD

**Issue by Wuszek** [SynoCommunity/spksrc#4332]
Hi,

Im using PlexPy Custom and as I can see, Tautulli v2.6.3 is the last version to support Python 2. Python 3 will be required to continue receiving updates. I have Python3 installed, but application still uses Python Version: 2.7.18. 

Is there any way to change used Python version, to make update available? Or will the PlexPy package be updated, to use Python3?

**Comment by Wuszek** [comment]
Bump.
Is it possible to upgrade PlexPy to use Python3 required by the new Tautulli?

**Comment by flobafff** [comment]
I ask myself the same question as Wuszek.
Is there any way to change used Python version, to make update available? Or will the PlexPy package be updated, to use Python3?

Thank you in advance

**Comment by littleneutrino** [comment]
I took a look at both the package and scripts it should be as simple as updating the Tautulli.py and adding some new package files for Python 3 updated from Python 2.7 looks like @cytec is the owner of this particular package (according to the Package manager anyway) Can we get an update on this Thanks. Otherwise we are stuck with 2.6.3 while currently 2.6.5 as of time of this posting is current. (I have tried to use the official Docker but it clears itself after every update) I would rather stick with this package.
