### ISSUE TITLE
Radarr not importing movies correctly

### ISSUE THREAD

**Issue by Moonshinelunacy** [SynoCommunity/spksrc#4586]
_For new Package Requests, see the guidelines_  

### Setup
_Package Name:_ Radarr
_Package Version:_ 3.1.0.4893

_NAS Model:_ DS918+
_NAS Architecture:_ Apollolake
_DSM version:_ 6.2.4-25556

### Expected behavior
Radarr should detect downloaded films and import automatically

### Actual behavior
Manual import must be used. When opening manual import, all films are unknown and must be selected manually. As seen in screenshot, permissions are set up correctly

### Steps to reproduce
_1._ 
_2._ 
_3._ 

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
2021-4-27 09:30:46.2|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: /downloads/Movies/Pagglait.2021.1080p.NF.WEB-DL.DDP5.1.x264-Telly.mkv. Ensure the path exists and the user running Radarr has the correct permissions to access this file/folder
```

![Capture](https://user-images.githubusercontent.com/34224510/116265647-4ced3f80-a749-11eb-87b1-357f085fcec6.PNG)

#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by publicarray** [comment]
Hi @Moonshinelunacy 👋 
Did you give Radarr  (`sc-radarr` "system internal user" or `sc-download`/`sc-media` group) the correct permissions to your shared `downloads` folder? https://github.com/SynoCommunity/spksrc/wiki/Permission-Management#how-to-grant-permissions-for-applications

**Comment by publicarray** [comment]
Sorry only just saw the screenshot. Note that paths are case-sensitive `/downloads/Movies/` is different to `/Downloads/Movies/` which I think it what you want.

**Comment by Moonshinelunacy** [comment]
There is no actual /downloads/Movies/ folder. That is simply the syntax rtorrent uses. All the actual files are in /Downloads/Movies/ which has the correct permissions

**Comment by publicarray** [comment]
Then you should tell radarr about it. It's probably '/Volume1/Downloads/Movies'

**Comment by bakerboy448** [comment]
Sounds like you'd need a remote path map to translate rtorrent paths (those sound like docker?)

if you're getting unknown movie, then either the movie is not added in radarr, an alternative title is needed on TMDb, or the release group just can't name anything right lol

**Comment by publicarray** [comment]
@bakerboy448 
From the log: `path does not exist or is not accessible by Radarr: /downloads/Movies/....` it shows me that radarr is looking in the wrong location since in the screenshot it's clearly `Downloads` and I assume `Volume1` as the volume since it's the most common

@Moonshinelunacy was the issue solved by changing the media folder?

**Comment by bakerboy448** [comment]
> @bakerboy448
> From the log: `path does not exist or is not accessible by Radarr: /downloads/Movies/....` it shows me that radarr is looking in the wrong location since in the screenshot it's `Downloads` and I assume `Volume1` as the volume since it's the most common (this is where shared folders live)
> 


Radarr never looks anywhere by itself. The path comes from the download client with a find/replace done with a remote path map.  Essentially all docker issues are suboptimal or inconsistent paths/permissions

**Comment by publicarray** [comment]
Hm I fail to see why you think docker is involved. I always think issues coming to this repository are related to our [packages](https://synocommunity.com/package/rutorrent) by default. Nothing I see in the issue says docker was used. But we need @Moonshinelunacy to confirm this. Or provide steps to reproduce since they are missing. 

> Radarr never looks anywhere by itself

Yes thats why I think a wrong path was entered in somewhere.

**Comment by bakerboy448** [comment]
The only way it's a inputted path issue is if there is an incorrect remote path map. Otherwise Radarr's path comes from the download client's API.

but docker or not it sounds like the issue is radarr and the download client are not speaking the same language which means either the clients paths need correcting or a remote path map is needed

regardless it's a support issue not a bug
