### ISSUE TITLE
Request: Allow to change port number on package installation for all packages that use a hardcoded port

### ISSUE THREAD

**Issue by Marcoevich** [SynoCommunity/spksrc#4613]
Hello, I downloaded Sabnzbd and Sickchill from the github build artifacts to try and test them on DSM7. Unfortunately the installation was immediately cancelled because of port in use errors.

I suggest that the installers for these packages ask which port to use, instead of hardcoding them. This way the packages can be installed even when the default port is in use by another package or system service.

**Comment by BenjV** [comment]
Synology has designed the package center to use fixed port for every application and the SynoCommunity has adapted to this by making sure every application uses a different port see:

> https://github.com/SynoCommunity/spksrc/wiki/Synology-Used-Ports
> https://github.com/SynoCommunity/spksrc/wiki/SynoCommunity-Used-Ports

So if you are getting a message that getting a message "port in use" you are using ports that are not reserved for other applications.
Choosing a port during installation is creating this problem instead of fixing it.

**Comment by Marcoevich** [comment]
Hmm I understand. Is there a way to find out what application is using port 8080? I've seen the links you posted and I have a DSM6 version of Sabnzbd installed. If I try to install Sabnzbd for DSM7 then it complains about the port in use, but it should be able to upgrade the package without this port in use issue, right? Because it is the same app.

**Comment by hgy59** [comment]
@Marcoevich on your diskstation run:
```bash
sudo netstat -tulpn | grep 8080
tcp6       0      0 :::8080                 :::*                    LISTEN      10872/java
```


In my example it is a java process (a unifiy controller running in a docker image).
