### ISSUE TITLE
HASS Synology login

### ISSUE THREAD

**Issue by Puch-tdi** [SynoCommunity/spksrc#4684]
Hi all,

Does anyone know how to reach the home assistant when it is running as Synology app?
I can install the Ymartin hass but from there i can login into hass but cannot install or write my program in the config files.
Anyone knows this issue? i can connect but then i have no rights to change the files.
I hope someone can help me out here.

Thanks in advance,

Sander Ekeler

**Comment by hgy59** [comment]
For all homeassistant integrations that do not support configuration by the web UI, you need to modify manually the configuration file.
You find the configuration file on the diskstation as:
`/var/packages/homeassistant/target/var/config/configuration.yaml`

To edit this file you need ssh access to your diskstation (enable in Control-Panel - Terminal & SNMP - Terminal: Enable SSH service)

to create an ssh terminal session use putty (or another ssh client) to connect via SSH to your diskstation.

use an editor to edit the configuration file (vi is available by defaut, or install synocli-file that has nano and other editors, or use the integrated editor of mc = midnight-commander that is also bundled with synocli-file).

As the configuration file is owned by the sc-homassistant user, you must login as a user with root permissions to modify such files.

**Comment by BenjV** [comment]
If you modify files this way, don't forget to change the ownership back to sc-homassistant otherwise it is owned by root and not accessible by sc-homassistant.

By the way, the easiest way to access and edit all files on your Nas as root is by installing WinScp on your PC.
This is how you do that:

1 - Activate ssh in DSM Control panel > Configuration > Terminal.
2 - Download: http://winscp.net/eng/download.php
3 - Install WinSCP on the PC
4 - Start WinSCP, Select "new site"
5 - Choose protocol: SCP
6 - Host Name: <NAS-IP>
7 - Port Number: 22
8 - UserName : admin
9 - Then: --> Advanced--> click on SCP/Shell and fill in: sudo -i
10 - Save with a name
11 - Login with Password of admin.

Don't forget to add a file to /etc/sudoers.d folder on your Nas with the correct command in it.

To do so, login on the commandline as admin and give the command.
`sudo echo "admin ALL = NOPASSWD: ALL" >> /etc/sudoers.d/my_sudoers
`
**Don't logout from the commandline**
Test if WinScp can connect to your Nas.
**If you put something wrong in the file "my_sudoers", you can be lockout completely from your Nas after you logout from the commandline!!**
So if WinScp does not work because of this, delete the my_sudoers file from the commandline.
