### ISSUE TITLE
sshl package cannot be installed in DSM 7

### ISSUE THREAD

**Issue by mampfred612** [SynoCommunity/spksrc#4740]
### Setup
_Package Name: sshl
_Package Version: newest version 121c-5

_NAS Model: 1520+
_NAS Architecture:_ 
_DSM version: 7

### Expected behavior
installing sshl package should work

### Actual behavior
i receive the error that the package has an unsupported file format

### Steps to reproduce
_1._ 
_2._ 
_3._ 

### Setup
_Package Name:_ 
_Package Version:_ 

_NAS Model:_ 
_NAS Architecture:_ 
_DSM version:_ 

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._ 
_2._ 
_3._ 

#### Package log
_Installer log: find logfile `/var/log/packages/{package}.log`, for DSM<6: `/var/packages/{package}/target/var/{package}_installer.log` and protocol in Package Center.
You find service log and other log files in `/var/packages/{package}/target/var`.
_
```
Insert the package log(s) here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

**Comment by BenjV** [comment]
https://github.com/SynoCommunity/spksrc/issues/4524

**Comment by ohnoohweh** [comment]
This worked for me:
#4676

**Comment by hgy59** [comment]
Packages for DSM7 are now available as artifacts in the github build action of #4742.

**Comment by mampfred612** [comment]
Thank you, sorry now for the super stupid question, but how can I install this beta package on my Synology

**Comment by hgy59** [comment]
_we should document the download of packages built by github build action somewhere in the wiki_

go to the PR (#4742) and select the "checks" tab. 
When all build jobs failed, there is no artifact to download - otherwise there is an "Artifacts" pull down menu with a link to `packages`.
When you click the packages link, you download packages.zip with all spk files created by the related github action.
As it is not supported to download a single spk, you need to download the zip archive and extract the package for the arch of your diskstation. (see [package archs](https://github.com/SynoCommunity/spksrc/wiki/Synology-and-SynoCommunity-Package-Architectures) in the wiki to find the arch for your NAS model.
Some build jobs might have failed, so check whether the spk for your NAS was built, before download...

**Comment by hgy59** [comment]
Feedback is welcome, as I tested the successful installation on DS218+ only, and without any functional testing.

**Comment by mampfred612** [comment]
Thanks guys, installation was now a piece of cake *LOL*

**Comment by mampfred612** [comment]
function testing successful

**Comment by hgy59** [comment]
Have to fix sslh, as on DSM<7 it is broken now...
