### ISSUE TITLE
Strange error when building package using Wiki procedure

### ISSUE THREAD

**Issue by DigitalBox98** [SynoCommunity/spksrc#4750]
I have a new error I don't understand when trying to perform a basic build on a package.

The error is raised when the make is launched as per below : 

make setup       
Creating local configuration "local.mk"...
Setting default toolchain version to DSM-6.1
Setting default toolchain version to DSM-7.0

cd spk/transmission 

make arch-braswell
===>  Building package for arch braswell
...
make[1]: *** Aucune règle pour fabriquer la cible « 7.0 ». Arrêt.
make: [../../mk/spksrc.spk.mk:508 : arch-braswell] Erreur 2 (ignorée)

When indicating the DSM version (6.1 for instance) the error disappears : 

make arch-braswell-6.1
--> package transmission_braswell-6.1_3.00-19.spk successfully created

Do we have to indicate the DSM version when building a package (I thought the default version was 6.1 when none was indicated during the make call) ?

Maybe something to review in the "spksrc.spk.mk" file or some details to be added in the wiki if I'm not wrong.

**Comment by hgy59** [comment]
@th0ma7 has changed the behaviour of `make setup` to set toolchains versions to 1.6 and 7.0.
So you cannot use `make arch-braswell` (or whatever arch you choose) until you edit local.mk and remove one of the TCVERSIONS there (remove 6.1 or 7.0).
instead of calling `make setup` you should call `make dsm-6.1` _or_ `make dsm-7.0`. But as soon as you use `make all-supported` you will get two default archs in local.mk.

I allready triggered @th0ma7 to find another solution for the `all-supported` target, but he is out for some time.
We could update the wiki now, but IMO this is a bug that should be fixed to the behaviour that is already documented in the wiki.

**Comment by DigitalBox98** [comment]
Ok thanks for all these details it's clear now. 

My suggestion would be to indicate in the wiki for a new joiner this mechanics between dsm-6.1 and dsm-7.0 and the way the file local.mk is populated (I didn't find such information, that's why I have raised this point)

But this workaround is not a big deal once known :)
