### ISSUE TITLE
SABnzbd DSM7 - App recreates /volume1/downloads even if alternate path is used

### ISSUE THREAD

**Issue by Cyruz143** [SynoCommunity/spksrc#4844]
### Setup
_Package Name:_ SABnzbd
_Package Version:_ v3.3.1-49 

_NAS Model:_  DS920+
_NAS Architecture:_ 64bit (Not sure what this is actually asking for)
_DSM version:_ 7.0-41890

### Expected behavior
When you install the DSM7 version of SAB, it automatically creates a folder (volume1/downloads). I didn't want another folder here so once SAB was setup, in the app I changed the file paths to point to /volume1/media/downloads/* (for the 3 required folders).

I had to stop SAB to remove the folder, once it's removed and I started SAB I'd expect it to read the config.ini, see the file path isn't required and not recreate the folder I just removed.

### Actual behavior
Stopping SAB, deleteing the volume1/downloads folder and starting SAB recreates the folder again.

### Steps to reproduce
_1._ Install SAB
_2._ Adjust options to use alternate file path
_3._ Stop SAB
_4_ Delete the default file path (volume1/downloads)
_5_ Start SAB
_6_ Folder is recreated

#### Package log
Attached
[sabnzbd.log](https://github.com/SynoCommunity/spksrc/files/7116251/sabnzbd.log)

**Comment by BenjV** [comment]
If you create your own folder you have to give the "system internal user" sc-sabnzbd read/write permissions on those folders.

The point is that as of DSM 7 packages can only create a share with the correct permissions, because the installation script does not have root privs to create subfolder in a folder that is not owned by the package

**Comment by Cyruz143** [comment]
Thanks for the reply @BenjV. Permissions aren't an issue (as far as I can tell) as SAB can read/write/del from the new dirs fine and the sc-sab group has recursive permissions all the way down.

It's when you start SAB, it recreates the volume (volume1/downloads) which is redundant as there is nothing pointing there anymore.

**Comment by BenjV** [comment]
Only during installation time the packages created the shared folder, not when you stop and start the SabNzbd package.
On DSM 7 no application can create  a share so SabNzbd cannot create the share downloads.
Shares can only be created by the package center during installation or upgrades.

DId you set that permission yourself, because it will never be created by SabNzbd itself.
And that permission must be set for the "system internal user" sc-sabnzbd and not for any group.

**Comment by Cyruz143** [comment]
I've just run through the steps I provided and it recreates the share. Not sure what else I can really add. I assume it comes from the user being configured with this as it's default home path

`2021/09/06 11:23:35	===> Step preinst. USER=sc-sabnzbd GROUP= SHARE_PATH=/volume1/downloads`

I manually gave the sc-sab group permissions for the new share, yes.

**Comment by Cyruz143** [comment]
![image](https://user-images.githubusercontent.com/7225500/132258489-a6bc67a7-e94f-47b9-aec2-5795da5e8070.png)

Logs from Log Center

**Comment by BenjV** [comment]
SabNzbd is not aware of Dsm and try's to create the folder which is configured in its config.
It calls it a share but on Dsm 7 it is not posible to create a share for an application.
To prevebt this you should change this in SabNzb itself.

**Comment by Cyruz143** [comment]
I appreciate you're trying to help but you're not very clear. If there is something you want me to try you'll need to give specific steps.

**Comment by BenjV** [comment]
I will try to explain.

You must understand that there is the application SabNzbd developed by another group and a Synology package for SabNzbd that is an installation wrapper for that application to be able to install SabnNzbd on a Synology Nas.
The latter is build by the SynoCommunity.

So if you install that package it will ask you the name of a share to be create for SabNzbd to be used.
The default is "/volume1/downloads" 
The package then will create that share(if not exists) and also the subfolders "complete", "incomplete" and watch, it will also set the correct permission so SabNzbd can use them and write this information into the config file of SabNzbd.
That is the end of what the package will do and then it starts the application SabnZbd.

SabNzbd will first read that config file, check if those folders exists and if not try to create them.

If you want to change those folders to another location you must not stop SabNzbd but first make sure that those new folder are available and that the "system internal user" "sc-sabnzbd" has read/write permission there.
This must be done on the share (via the control panel, shared folder, Edit, Permissions, System Internal Users) and for the subfolders via FileStation (properties, permissions, create sc-sabnzbd).
If you (as in your case) wants to use an existing share and folders, you only add the correct permissions.

After that you can change the locations in SabNzbd itself (via config, folder make the change and save).

Now SabNzbd will no longer try to create the old share which it cannot because an application cannot create shares, that must be done by the installation package or by yourself via the DSM gui.

Hope this help to understand it, feel free the ask is things are not clear.

**Comment by Cyruz143** [comment]
I deleted SAB, nuked the user from SSH and re-installed it all directly in to the path I wanted. Seems fine now, a bit annoying you can't change it post install but whatever, it's working. Thanks fot the assistance.

**Comment by BenjV** [comment]
Your conclusion is wrong.
If you followed my instructions reinstalling was not needed at all.

**Comment by Cyruz143** [comment]
> 
> 
> Your conclusion is wrong.
> If you followed my instructions reinstalling was not needed at all.

No it's correct, I ran through your instructions as I'd already completed all that, including checking the various .conf files via SSH to make sure there was no trace of that path, it still recreates. As I said before, the user being created in the install having the SHARE_PATH defined means it'll get recreated. Just a limitation of DSM by the looks of it.

**Comment by BenjV** [comment]
You are free to believe you want, but you really don't understand how things are working.
