### ISSUE TITLE
[SynoCli File Tools] Include exa

### ISSUE THREAD

**Issue by screendriver** [SynoCommunity/spksrc#4876]
* Name: [exa](https://github.com/ogham/exa)
* Description: A modern replacement for `ls`
* Website: https://the.exa.website
* Software documentation: https://the.exa.website
* Build/Installation documentation: 
* Source code: https://github.com/ogham/exa
* License: MIT

In addition to `rg` (ripgrep) and `fd` (fd-find) it would be great when `SynoCli File Tools` would also include `exa`.

**Comment by publicarray** [comment]
I love `exa` (I set an alias to ls on my main machine) and other rust tools (`rg, fd, bat, procs, btm, xh`). You might be interested in https://github.com/TaKO8Ki/awesome-alternatives-in-rust
As for adding them, hm maybe, but I don't see it as a priority since the default tools can do the same things (just not as pretty).

**Comment by screendriver** [comment]
No it's not a priority. Just a nice to have. The same for #4877 🙂
