### ISSUE TITLE
[Package Request] download station for nvr216?

### ISSUE THREAD

**Issue by 380121850** [SynoCommunity/spksrc#4954]
* Name: NVR216
* Description: no download station 
* Website: 
* Software documentation: where can i get the download station spk,or the src that i can try porting 
* Build/Installation documentation: 
* Source code:  
* License:

**Comment by BenjV** [comment]
DownloadStation is a package from Synology, so you have to ask them, not here.

**Comment by publicarray** [comment]
Yea NVR216 doesn't have it https://www.synology.com/en-global/support/download/NVR216?version=6.2#packages probably because it's not a NAS product. All of Synology official packages are here https://archive.synology.com/download TBH I would probably just download stuff from the command line at that point. We are not affiliated with Synology, so you are  better off asking https://community.synology.com/enu or https://www.synology.com/en-global/company/contact_us
