### ISSUE TITLE
Add setfacl to SynoCli 

### ISSUE THREAD

**Issue by BenjV** [SynoCommunity/spksrc#4988]
Because Synology has adapted the extended permission setting also know as Linux ACL it would be a good idea to have a tool to see and manipulate the ACL's

The standard linux tool setfacl can do that.
It would be nice to add that to the SynoCli tools.

**Comment by hgy59** [comment]
@BenjV as you stated in https://github.com/SynoCommunity/spksrc/issues/4786#issuecomment-902904976 I thought that regular linux acl will not work on DSM.

Otherwise I could reactivate the ACL support for rsync (including the `getfacl`, `chacl` and `setfacl` tools) in the synocli-net package (see  #4787)

**Comment by publicarray** [comment]
> To see and manipulate ACL

Isn't that what `synoacl` is for? E.g. `synoacl --get <path>`

**Comment by BenjV** [comment]
> @BenjV as you stated in [#4786 (comment)](https://github.com/SynoCommunity/spksrc/issues/4786#issuecomment-902904976) I thought that regular linux acl will not work on DSM.
> 
> Otherwise I could reactivate the ACL support for rsync (including the `getfacl`, `chacl` and `setfacl` tools) in the synocli-net package (see #4787)

@hgy59 
Windows ACL is completely different from Linux ACL they are not compatible.
Only between Linux machines ACL support in rsync **could** work.

@publicarray 
Thanks for the info.
I did not know that there was a synoacl but I found it, so this request is not needed anymore.
By the way it is called synoacltool.
