### ISSUE TITLE
Build native tools as part of the Docker

### ISSUE THREAD

**Issue by Safihre** [SynoCommunity/spksrc#5170]
Maybe this is a stupid idea, but can't we just compile things like `native/python3` as part of the `Dockerfile`?
So we can skip all that when building Python packages?

**Comment by th0ma7** [comment]
It's actually not a stupid idea.  It could also be packaged and made available for downloading from our server for instance.

On a somewhat similar note, there where similar thoughts on building all wheels for all archs and making them available so when users install a package it automagically download it from the SynoCommunity server instead of being provided within the packages.

Making mileage on this we could have a repository server for multiple uses I guess.

**Comment by Safihre** [comment]
One bit at a time 🙂 
I tried to add this to the `Dockerfile`, but failed because I have 0 experience with Docker. 
Would you know how to add this?

**Comment by th0ma7** [comment]
not really... I think this is mostly awesome work from @publicarray and/or @hgy59.

**Comment by hgy59** [comment]
It was always the intention to keep the Docker image small and more or less stable (i.e. independent of spk versions to build).

I already started to install packages instead of building native packages from source and introduced spksrc.native-install.mk (e.g cmake, or go and remove the need of go-1.4)

In most cases we need the exact same native version as a package is created for (python, erlang) or depends on (dotnet-sdk). Here it is easier to work with native packages instead of upgrading the docker image (github actions would not be possible here, as of mutual dependencies).

When building a native package like python from source, it's not like installing python but like python-dev package, as the source and header files are installed too.

...

**Comment by Safihre** [comment]
I see.
Another option would be to use the Github actions cache. Downside would be that it always restores `native/python310` from the cache, even if not needed, but that only takes a few seconds anyway. Will try to set this up.

**Comment by Safihre** [comment]
I tried the cache approach, but it only saves about 2 minutes. It's something, but not a huge change.
