### ISSUE TITLE
subliminal prevents hibernate

### ISSUE THREAD

**Issue by eilandert** [SynoCommunity/spksrc#522]
It seems Subliminal is polling the config every minute, which kinda prevents disk/nas hibernation.

May  8 15:41:00 kernel: [ 9421.255372] [/usr/local/subliminal/var/config.ini] opened by pid 9139 [u:(/usr/local/subliminal/env/bin/p), comm:(python)]
May  8 15:42:00 kernel: [ 9481.314782] [/usr/local/subliminal/var/config.ini] opened by pid 9139 [u:(/usr/local/subliminal/env/bin/p), comm:(python)]
May  8 15:43:00 kernel: [ 9541.372149] [/usr/local/subliminal/var/config.ini] opened by pid 9139 [u:(/usr/local/subliminal/env/bin/p), comm:(python)]

**Comment by Dr-Bean** [comment]
Yes, subliminal might prevent hibernation. As an alternative, you could increase the timeout (think it's in scheduler.py) or turn off the package in package center and schedule a task in the task manager. That task could look something like this:
```/usr/local/subliminal/env/bin/subliminal -l EN -s addic7ed -v --cache-dir /usr/local/subliminal/cache/ /volume1/video```

@Diaoul Not sure if there are other options, but otherwise, feel free to chime in ;)
Closing the issue in the meantime.
