### ISSUE TITLE
[Package Request] cdvdcontrol (SynoCli Disk Tools)

### ISSUE THREAD

**Issue by gingerbeardman** [SynoCommunity/spksrc#5251]
### Software Name

cdvdcontrol

### Brief Description

A command line tool to control the generic features of CD/DVD writers and the vendor-specific features like in Plextor and Pioneer devices.

### Website

https://launchpad.net/ubuntu/+source/qpxtool

### Documentation

http://manpages.ubuntu.com/manpages/trusty/man1/cdvdcontrol.1.html

### Build/Installation documentation

https://qpxtool.sourceforge.io/installation.html

### Source code

https://sourceforge.net/projects/qpxtool/files/qpxtool/0.8.x/0.8.1/

### OpenSource License

GPLv2

**Comment by gingerbeardman** [comment]
Hi,

The tool I am asking about `cdvdcontrol` is command line only. It is one of a half-dozen "console" or "cli" tools that are part of the full package qpxtool (I have no interest in the gui aspect).

I built it on macOS as follows:

1. download and extract `qpxtool-0.8.1.tar.bz2`
2. `cd qpxtool-0.8.1`
3. `./configure`
4. `make cli`

cli and lib files are built, but install needs to be done manually on macOS

Does this help?

**Comment by hgy59** [comment]
configure is not possible with `GNU_CONFIGURE = 1` in our framework, so I doubt that cross compilation will be supported.
```
invalid argument: --build=i686-pc-linux
```

without  `GNU_CONFIGURE = 1` the host compiler is detected by configure instead of the compiler of the toolchain.

This package will need some investigations to patch the configure or Makefile files to successfully compile.

**Comment by gingerbeardman** [comment]
No problem, I will try to run a virtual machine and run it through Ubuntu.
