### ISSUE TITLE
Calibre Server

### ISSUE THREAD

**Issue by lukasmd1989** [SynoCommunity/spksrc#527]
It would be nice to have to have the full Calibre server running on the Synology NAS, because with COPS or BicBucStrimm you still need your PC running to add ebooks to the database.

http://calibre-ebook.com/download_linux

There is a way to compile and install calibre on arm-cpus but you need a chroot and its very difficult for non pros.

http://www.mobileread.com/forums/showthread.php?t=150254

So please make an spk with it so we can install calibre easily. I would help you Alpha and Beta testing..

**Comment by overdrive69** [comment]
Hello to all, i have one question concerning calibre and DS.
There is a docker container with calibre on the DS.

eg.: http://www.mobileread.com/forums/showthread.php?t=267302

My question is if there is no way to run Calibre direktly on the DS without Docker?
Or is there such a big difference to run it on Docker instead of running it on DS.
Sorry if my question sounds stupid.
But i would be great to not need an extra device to run Calibre. 
To have lazylibrarien and Calibre on one device would be perfect.
If there is no chance for this, i have to see if i get it working with docker.

**Comment by KaraokeStu** [comment]
Unfortunately, with the way calibre works, it needs a gui. For this reason, it needs to run in Docker.

I have my system all virtualised anyway, so both my synology and a Windows 10 box run in ESXi, and calibre runs on the Windows 10 box.

The trick is getting Docker to point at the same library location that is accessible to lazylibrarian

**Comment by cytec** [comment]
Technically you can run calibre in headless mode. But you'll still need GTK for installation which isn't present on Synology...

**Comment by overdrive69** [comment]
Thanks for the feedback.
This means at the moment there is not really a program to handle and provide ebooks only on a DS.
Or do i miss something?

**Comment by cytec** [comment]
correct
