### ISSUE TITLE
Bump Homeassistant to 2022.11.0 or 2022.12.07

### ISSUE THREAD

**Issue by chickenandpork** [SynoCommunity/spksrc#5530]
@daxcore requests home-assistant bump to `2022.11.0` which is a fairly big release by itself.  https://github.com/SynoCommunity/spksrc/pull/5385#issuecomment-1359970050

Current release is 2022.12.07: https://www.home-assistant.io/blog/2022/12/07/release-202212/

@daxcore suggests that 2022.11.0 offers HACS compatibility, which I thought was just for the HAOS and docker implementations (whereas this is an OS install, so Home-Assistant is running as a local process outside of any container in the Synology NAS).

I may have missed this in the 2022.11.0 notes (https://www.home-assistant.io/blog/2022/11/02/release-202211/) -- but TBH I skimmed -- but maybe @daxcore can link to docs?

Either way, filing a request to update on @daxcore behalf.

**Comment by hgy59** [comment]
I am working on #5478 that will probably be finished end of this year.
If I restart with the december version now, it will not be finished before end of April 2023 to publish a new release, as my cycles are limited.

It is always difficult to update homeassistant core, due to the huge amount of dependencies.
If one wants an always uptodate version of homeassistant, then one should choose HassOS or the docker image and a platform like Raspberry Pi.

**Comment by Martinezgil** [comment]
I have synology DS220j and i've installed synocommunity HA version by Package Center. It's possible update to last version of HA? It's possible install HACS?
