### ISSUE TITLE
[Package Request] Bump Transmission to 4.0.2

### ISSUE THREAD

**Issue by lpla** [SynoCommunity/spksrc#5595]
### Software Name

Transmission 4.0.2

### Brief Description

Bump Transmission version from 3.00 to 4.0.2.

### Website

https://transmissionbt.com/

### Documentation

https://github.com/transmission/transmission/blob/main/docs/README.md

### Build/Installation documentation

https://github.com/transmission/transmission/blob/main/docs/Building-Transmission.md

### Source code

https://github.com/transmission/transmission

### OpenSource License

other (please specify below)

### Other License

https://github.com/transmission/transmission/blob/main/COPYING

**Comment by Dilbao** [comment]
If possible, please provide packages for EDS14 (DSM 6.0.3-8754 armada370) for this one.

**Comment by ClassicUA** [comment]
When will the update to version 4 be approximately?

**Comment by mreid-tt** [comment]
> When will the update to version 4 be approximately?

I've started some work on it in https://github.com/SynoCommunity/spksrc/pull/5616. Unfortunately, I've run into some build issues as there are major changes from the previous version. I've reached out for assistance in completing the build.

**Comment by mreid-tt** [comment]
As an update, the package is just about ready to go. For those interested they can download and test the current build from the Artefacts section at [v4.0.1 #5097](https://github.com/SynoCommunity/spksrc/actions/runs/4400647234).

**Comment by sochotnicky** [comment]
> As an update, the package is just about ready to go. For those interested they can download and test the current build from the Artefacts section at [v4.0.1 #5097](https://github.com/SynoCommunity/spksrc/actions/runs/4400647234).

I've downloaded & have been running it for a bit. So far no issues but in my case it was a fresh install. So far I can't seem to be able to make peer port test working but that's most likely unrelated

**Comment by ClassicUA** [comment]
Updated over a working version 3, seems to work fine.

**Comment by tothf** [comment]
Well, I upgraded one of my instance but did not have the best experience.
I have modified the default download-dir before and it was pointed to some 3 level deep sub-directory somewhere. Because of this the post upgrade started to move all content from that folder to the new shared folder/complete. Managed to kill the processes via SSH on time...
During the upgrade wizard you should not take any input. The config is already in place and there is a working app on the system. Simply no input, update package and leave existing config in place.
In case we need a more professional upgrade and deliver new config with freshly introduced params in it we should have a post upgrade script which fetches all params from the old config and migrates it to the new one. This way the old settings are saved and the new ones, which were not defined before, imported as well. Can give a hand if needed.

Also watch-dir and incomplete dir was disabled in my settings. After upgrade they are enabled. Should be able to import these I'd say.

I fixed my install with simply setting the download-dir to shared-folder/complete manually via ssh since the app was in error state. After that the upgrade was fine and it works properly now.

**Comment by mreid-tt** [comment]
@tothf, thanks for this detailed feedback. I actually didn't do much in the way of changing what was there before for upgrades. Your point of giving users a choice to not modify their custom configurations is well noted and I'll have a thought on how we can include this.

**Comment by th0ma7** [comment]
@mreid-tt FYI, I transfered the package upgrade process  to using rsync about a year ago.  With that I ensured to generate `.orig` and `.new` (if I recall correctly).  Therefore you can easily overwrite files as needed.  Just a thought.

**Comment by mreid-tt** [comment]
> @mreid-tt FYI, I transfered the package upgrade process to using rsync about a year ago. With that I ensured to generate `.orig` and `.new` (if I recall correctly). Therefore you can easily overwrite files as needed. Just a thought.

@th0ma7, is this in a different branch? I see the upgrade still using `mv` commands. I can change them to `rsync` if this would be preferred.

**Comment by tothf** [comment]
In my opinion for the upgrade there should not be anything. The config is already there and all configured folders should have the right permissions otherwise it's not working. So just just skip the whole "change download folder and move everything there". It breaks all torrents anyway since the data location will be different so they need to be changed one-by-one. The only thing should happen is the import of newly introduced settings in case they are required.
It is like you upgrade transmission on a computer it won't ask you to change your download folder or anything. Just upgrades the software and keeps the settings. On Synology should be the same I would say.
The whole create download, incomplete and watch dir is required for first install when there is nothing exists.
Maybe I'm wrong but this is what makes sense to me.

**Comment by mreid-tt** [comment]
Thanks for sharing. I do see your perspective that the upgrade should be as simple as possible (similar to the approach we have with the `*arr` apps which strive to not change anything). Looking at the code it seems to have been in place to perhaps handle DSM 6 to DSM 7 migrations but I'm not sure. Do we have any scenarios where the user would wish to modify the settings on upgrade? If not, then I'll simplify along the lines you have outlined.

**Comment by voidfel** [comment]
I upgraded from version 3 to 4 on DSM 7 and it was very smooth. No issues.

**Comment by mreid-tt** [comment]
@tothf, after looking at this again it seems that the only purpose of the post-install code is to relocate folders and update the configuration to match. The existing configuration file is used so nothing is really upgraded there. As such, I've implemented your suggestion to perform the upgrade retaining all existing configurations by simply removing the code. I've tested it and seems to work as expected.

**Comment by th0ma7** [comment]
> is this in a different branch? I see the upgrade still using `mv` commands. I can change them to `rsync` if this would be preferred.

The rsync is only in `spksrc.service.installer.dsm7` and aimed to move files to the "real" `var` directory which only exists starting with DSM7.  It does that while ensuring to not overwrite existing.  What it does is:
1. copy then delete from source all new files
2. any files remaining = already existing at destination, therefore rsync while renaming with `.new`

As such by default any existing configuration is always kept... It's then a matter of defining a per application approach to modify or overwrite existing based on `.new` as needed.

Hope this helps, cheers.

**Comment by tothf** [comment]
@mreid-tt Just tested the new build with 4.0.2. It works like a charm. No questions just stops service, upgrades software then starts service. All settings are the same. Perfect. Thanks for that.

**Comment by tothf** [comment]
Just a quick update...
I'm running the latest build, 4.0.2-21-2. One thing I have noticed is that the [lack of nonblocking disk I/O](https://github.com/transmission/transmission/issues/2462) is worst then ever. RPC is non-responsive during heavy download session (>40MB/s). Otherwise it looks stable.
