### ISSUE TITLE
radarr is missing for 86_64

### ISSUE THREAD

**Issue by 100tomer** [SynoCommunity/spksrc#5769]
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

radarr

### Package Version

20230426-20

### Device Model

Any intel synolagy

### Device Architecture

x86_64

### Firmware Version

7.2

### What happened?

I'm unsure if I correctly applied the appropriate tags for the issue, but it seems that the website lacks an x86_64 package for the latest version of Radarr. I'm uncertain whether I have the ability to generate and upload such a package. Furthermore, I've noticed a similar problem with other packages like Jackett.

### Reproduction steps

1. 
2. 
3. 
...

### Install Log

```log
...
```

**Comment by mreid-tt** [comment]
hey @100tomer, the SynoCommunity lists specific CPU architectures rather than processor families. So for example if you have a DS423+ (which runs the Geminilake arch) or a DS723+ (which runs the R1000 arch), these will be listed [7.1 geminilake](https://packages.synocommunity.com/radarr/20/radarr.v20.f42661%5Bapollolake-avoton-braswell-broadwell-broadwellnk-broadwellnkv2-broadwellntbap-bromolow-cedarview-denverton-epyc7002-geminilake-grantley-kvmx64-purley-r1000-v1000%5D.spk) and [7.1 r1000](https://packages.synocommunity.com/radarr/20/radarr.v20.f42661%5Bapollolake-avoton-braswell-broadwell-broadwellnk-broadwellnkv2-broadwellntbap-bromolow-cedarview-denverton-epyc7002-geminilake-grantley-kvmx64-purley-r1000-v1000%5D.spk) respectively on the [website](https://synocommunity.com/package/radarr). You can consult the webpage [What kind of CPU does my Synology NAS have?](https://kb.synology.com/en-me/DSM/tutorial/What_kind_of_CPU_does_my_NAS_have) to get the specific arch for your model if you wish to download the package manually. In most cases the Package Center will select the appropriate arch for your NAS automatically.

**Comment by 100tomer** [comment]
> hey @100tomer, the SynoCommunity lists specific CPU architectures rather than processor families. So for example if you have a DS423+ (which runs the Geminilake arch) or a DS723+ (which runs the R1000 arch), these will be listed as [7.1 geminilake](https://packages.synocommunity.com/radarr/20/radarr.v20.f42661%5Bapollolake-avoton-braswell-broadwell-broadwellnk-broadwellnkv2-broadwellntbap-bromolow-cedarview-denverton-epyc7002-geminilake-grantley-kvmx64-purley-r1000-v1000%5D.spk) and [7.1 r1000](https://packages.synocommunity.com/radarr/20/radarr.v20.f42661%5Bapollolake-avoton-braswell-broadwell-broadwellnk-broadwellnkv2-broadwellntbap-bromolow-cedarview-denverton-epyc7002-geminilake-grantley-kvmx64-purley-r1000-v1000%5D.spk) respectively on the [website](https://synocommunity.com/package/radarr). You can consult the webpage "[What kind of CPU does my Synology NAS have?](https://kb.synology.com/en-me/DSM/tutorial/What_kind_of_CPU_does_my_NAS_have)" to get the specific arch for your model if you wish to download the package manually. In most cases the Package Center will select the appropriate arch for your NAS automatically.
> 
> EDIT: Do let me know if you have any other questions. If not, feel free to close this issue.

Thanks for helping! I didn't know it's by the specific cpu architecture, good to know :) 
I'm kinda new to all of this, can I download packages from SynoCommunityin the Package Center? I thought it needed to be manually installed

**Comment by hgy59** [comment]
@100tomer  you find instructions here: https://synocommunity.com/#easy-install

**Comment by 100tomer** [comment]
> @100tomer you find instructions here: https://synocommunity.com/#easy-install

I can't believe I've been using SynoCommunity for so long without realizing this! My admiration for SynoCommunity has now grown even stronger! I'm eager to contribute by designing a new webpage for the main site, which will assist others like me who may have overlooked it. I would be more than happy to repay the favor for this incredible open-source project.

**Comment by mreid-tt** [comment]
Closing issue as resolved
