### ISSUE TITLE
Update Home Assistant core to version 2023.5.0

### ISSUE THREAD

**Issue by evilz** [SynoCommunity/spksrc#5770]
### Software Name

Home Assistant

### Brief Description

@hgy59 Hello do you think it's possible to update the package to version 2023.5.0 or more ?

Some packages from HACS need this version at least 😅.

![image](https://github.com/SynoCommunity/spksrc/assets/2937862/f676fdc8-a72b-492b-9880-f11ef29344fe)

🙏thank

### Website

https://community.home-assistant.io/

### Build/Installation documentation

https://www.home-assistant.io/installation/linux#install-home-assistant-core

### Source code

https://www.home-assistant.io/installation/linux#install-home-assistant-core

### OpenSource License

MIT

**Comment by hgy59** [comment]
There is already #5757 for update Home Assistant Core to v2023.5.4
But do not expect an updated package release shortly (it needs hours to validate all dependencies of the integrations, and my resources are limited).
But you can try the packages built by github action in #5757.

**Comment by jcastang** [comment]
Hello, I can find where to download artifact homeassistant_armv7-7.1_2023.5.4-21.spk.

Can you point me url please ?

**Comment by jcastang** [comment]
> You are the best ! 😘 Looks working nice

Hello

How did you manage to download and install this package from github action please ? 

Thanks a lot

**Comment by hgy59** [comment]
you find the packages here https://github.com/SynoCommunity/spksrc/actions/runs/5703347015?pr=5757#artifacts
but artifacts will be deleted 90 days after creation.

**Comment by jcastang** [comment]
Can I use 2023.7.1 package ? 
Or does it require python 3.11 to be installed before ?

**Comment by hgy59** [comment]
> Can I use 2023.7.1 package ? Or does it require python 3.11 to be installed before ?

You mean 2023.7.3? 
Currently I am working on 2023.7.3 and this version already depends on `python311>=3.11.4-7` and package version ´3.11.4-7´ is not yet available (WIP in #5820).
Locally I removed the version restriction for my builds and I am testing with python311 3.11.4-5 (an inofficial version with openssl3).

So I cannot recommend to use homeassistant 2023.7.3 now, as it really depends on #5820.
_If you really want to use it, you have to download the spk and create a new spk with a patched INFO file to remove the python311 version restriction, and probably this will work or not due to the openssl version._

**Comment by hgy59** [comment]
completed by #5757 and finally by #5869

**Comment by ekanters71** [comment]
@hgy, I am still running DSM 6. Any chance that newer version of Home Assistent than 2023.7.3 will be supported? I am missing a lot of integrations and it seem that the "Add integration to my" does not work.
