### ISSUE TITLE
How can i found package's old version?

### ISSUE THREAD

**Issue by bingqichen** [SynoCommunity/spksrc#5802]
My android tv jellyfin client version is 0.15.10 (need minimum jellyfin server 10.8.1), My device is 32bit, but maximum version support 32bit on synocommunity is 10.7.7, so we have a archive there versions between 10.8.1 and 10.8.9 ? How can i found it ?

**Comment by hgy59** [comment]
I suppose you need to update DSM at least to v7.1 to get latest Jellyfin.

**Comment by bingqichen** [comment]
> 



> I suppose you need to update DSM at least to v7.1 to get latest Jellyfin.

I am already update to DSM7.1，but i only get 10.7.7, you can see below image show the maximum version support 32bit is 10.7.7
<img width="1280" alt="image" src="https://github.com/SynoCommunity/spksrc/assets/13115737/a58cbae0-312e-40f5-ba86-3f71fada7ada">

[https://synocommunity.com/package/jellyfin](https://synocommunity.com/package/jellyfin)

**Comment by mreid-tt** [comment]
In Jellyfin 10.8.0 the app moved to dotnet 6. As a result of this a number of 32-bit ARM processors became incompatible with certain DSM combinations (see https://github.com/SynoCommunity/spksrc/issues/5574). After discussion with another dev (https://github.com/SynoCommunity/spksrc/pull/5585#issuecomment-1412784516), it was proposed that all 32-bit processors be dropped due to performance concerns with transcoding. As a result, unfortunately there is not a version (10.8.1 or newer) which will support your processor.

**Comment by bingqichen** [comment]
> In Jellyfin 10.8.0 the app moved to dotnet 6. As a result of this a number of ARM processors became incompatible with certain DSM combinations (see #5574). After discussion with another dev ([#5585 (comment)](https://github.com/SynoCommunity/spksrc/pull/5585#issuecomment-1412784516)), all 32-bit processors be dropped due to performance concerns with transcoding. Unfortunately there is not a version (10.8.1 or newer) which will support your processor.

Thanks for your reply, i find the maximum version in SynoCommunity support 32bit is [this commit](https://github.com/SynoCommunity/spksrc/tree/da829e70cb0dc82c22e83d63175f7120ad93649d) submit the 10.8.5 version. So i get the code and compile it, now i get the 10.8.5 version for armada38x architecture with dsm 7.1. 
[jellyfin_armada38x-7.1_10.8.5-8.spk](https://drive.google.com/file/d/1tTp9-1uHqm9ONCFaXAXtlRdJCknXZ02w/view?usp=sharing)
![image](https://github.com/SynoCommunity/spksrc/assets/13115737/0d266889-1b97-4b5a-99ec-d4d7abcbc7f2)
