### ISSUE TITLE
Where is the debian-chroot package for DSM5.2?

### ISSUE THREAD

**Issue by rpgdev** [SynoCommunity/spksrc#5803]
I'm trying to find the debian-chroot package for DSM 5.2, can't find it on the package center nor the synocommunity page. I know it had issues on dsm6 and it probably won't make it to dsm7 but why isn't it available on 5.2? Did something happen to it?

**Comment by hgy59** [comment]
We dropped all chroot packages because we run out of disk space on the server.
Unfortunately it is not possible to recreate the packages, as debian jessie is EOL and cannot be downloaded anymore.

I gave it a try and it is possible to download chroot resources for debian buster, bullseye and bookworm.
But the DSM integration of the debian-chroot package works only on DSM < 6 (i.e. 5.2) and depends on Python 2 (EOL too).
And Synology retiered all Toolchains for DSM < 6.2.4.

**Comment by rpgdev** [comment]
>We dropped all chroot packages because we run out of disk space on the server.

That's a strange explanation since all the packages are here and all are available from the server: https://synocommunity.com/package/debian-chroot the page simply isn't listed on the main directory. I don't see why the package should still be listed for dsm5 since it works well. Why not list it seeing as the files are actually in the server anyways?

**Comment by hgy59** [comment]
You are right. the debian-chroot packages are deactivated and not deleted.
Since there is no active version, i suppose that the package is not shown in the packages site at all, but the details site is still reachable and still works.

This was fixed in https://github.com/SynoCommunity/spkrepo/issues/97, but until it is applied to the production server this hidden feature still works.

@mreid-tt IMHO it was by intention that a manual download of deactivated packages was possible. 
The former publish workflow was to manually download, install and test the packages before activation.

**Comment by hgy59** [comment]
fixed by https://github.com/SynoCommunity/spkrepo/pull/111
