### ISSUE TITLE
[Package Request] stars.synology

### ISSUE THREAD

**Issue by ld-2022** [SynoCommunity/spksrc#5835]
### Software Name

stars.synology

### Brief Description

Nebula: Boundless communication, within reach
Smooth access anytime, anywhere, making work and life easy and convenient. Starry clouds help you break through the limitations of time and space.

### Website

https://ip4.ink

### Documentation

https://ip4.ink/help/

### Build/Installation documentation

https://github.com/ld-2022/stars.synology/blob/master/README.md

### Source code

https://github.com/ld-2022/stars.synology

### OpenSource License

Apache

**Comment by mreid-tt** [comment]
This seems to be written by Synology, what exactly does this package do?

**Comment by publicarray** [comment]
The package appears to aak for ssh credentials and then installs this docker container 

https://hub.docker.com/r/xianwei2022/stars.client

Using translate this is some sort of remote access solution:

Anytime, anywhere, use Xingkong cloud remote access to realize efficient operation and data acquisition of Synology NAS, so that your private cloud will never leave your hand.

**Comment by publicarray** [comment]
Since the developer of the software is requesting their own package that can already be downloaded from their page I don't see a reason to include it here. Fyi there already are many different solutions to remotely access a Synology nas.
