### ISSUE TITLE
[Package Request] Kopia

### ISSUE THREAD

**Issue by mdhowle** [SynoCommunity/spksrc#5842]
### Software Name

kopia

### Brief Description

Kopia is a backup software that provides efficient and secure data protection by creating snapshots of files, enabling you to easily store and restore your data across various storage locations while ensuring data integrity and encryption.

### Website

https://kopia.io

### Documentation

https://kopia.io/docs/

### Build/Installation documentation

https://github.com/kopia/kopia/blob/master/BUILD.md

### Source code

https://github.com/kopia/kopia

### OpenSource License

Apache

**Comment by hgy59** [comment]
just another backup solution...
We already have packages for borgbackup, duplicity, rdiff-backup, rsnapshot and some deduplication tools. And restic is on the way in #5557...

Anyway, it is not a huge task to create a kopia package, since the binaries for several archs are available for download and we do not have to cross compile it.
I successfully started a kopia server with `./kopia server start --ui --insecure --address=http://0.0.0.0:51515 --server-password={myserverpassword}` on a DS218 (aarch64 on DSM 6.2.4).
And I can log in to the server with the web ui as user kopia with the given server-password.

The connection from KopiaUI on a windows machine was not possible, as only secure connections (https with server certificate thumbprint) are allowed.

So such a package would require additional investigations:
- provide a server certificate for TLS (on DSM 6 we could use DSM server certificates as in the syncthing package, but on DSM 7 this is not supported)
- a guidance on how to create local repositories on the CLI and with the web UI
- the server must be configured to use `/var/packages/kopia/var` for the cache (the package will run as sc-kopia user and must not use it's home folder for the cache - when running as root kopia stores log and other files in `/root/.cache/kopia/`)
- we need to document how to use this package. What can be done by WebUI and what must be done with the CLI. How to create a local repository, etc.


@mdhowle we can create a kopia package, but are you willing to act as a maintainer for testing the usability and documenting the usage of such a package?

**Comment by mdhowle** [comment]
Hey @hgy59, I didn't expect anyone to respond so quickly.

> we can create a kopia package, but are you willing to act as a maintainer for testing the usability and documenting the usage of such a package?
Yes, I will.

Thank you!
