### ISSUE TITLE
Invalid format on DSM 6

### ISSUE THREAD

**Issue by nesch52** [SynoCommunity/spksrc#5844]
Hi , I am using a DS1812+ w.Ver. 6.2.4-25556 update 7
trying to reinstall manually PetaSpace  version  1.0.41-0256
from
https://archive.synology.com/download/Package/PetaSpace
gives me an Error: Ungültiges Format (Format-Error)
I know i had installed this before,  until my NAS crashed a while ago.
Now when i had reinstalled everything 
Petaspace is not installable anyhow..
how can i proceede??(70y old "Newbie" with low Linux knowledge..)
who can give me please detailed instruction how to install this *.spk?
best regards
Norbert
![PetaSpace-x86_64-1 0 41-0256_spk_Error=Format Error](https://github.com/SynoCommunity/spksrc/assets/39209634/6eb0160c-a018-409f-a352-aaddf23dd3df)

**Comment by hgy59** [comment]
@nesch52 Synology changed the internal package format for DSM 7.
I downloaded some of the PetaSpace packages and found, that the latest version that is for DSM 6 is `PetaSpace-x86_64-1.0.38-0059.spk`
The newer Versions are for DSM 7 only and when you try to install such a package in DSM 6 you will get an "Invalid Format" error. The same error message appears, when you try to install a DSM 6 package on DSM 7.
I looks like the build numbers > 0200 of the PetaSpace package are for DSM 7 only.

DSM 6 compatible spk files are tar archives that can be opened with tar (I use 7-zip on Windows). The newer spk Formats are encrypted and/or signed and cannot be opened by archive tools anymore. Since Synology did not document this new format, there is no chance to look into spk files for DSM 7 created by Synology.
On DSM 7 you can still install packages in the old format that are created for DSM 7, as we do in SynoCommunity. But the Installation wizard will display an extra warning for packages that are not in the newer format, i.e are not created by Synology.

**Comment by nesch52** [comment]
Thank You very ,very much !! It worked, thanks to your experience! Problem solved!
best regards nesch52
