### ISSUE TITLE
Update eza to the latest version (0.16.1)

### ISSUE THREAD

**Issue by MilesTEG1** [SynoCommunity/spksrc#5935]
Hello,
The version included in the SynoCli File Tools is pretty old now : 0.13
Could you please update this binarie to the latest version 0.16.1 
https://github.com/eza-community/eza/releases/tag/v0.16.1

Thanks in advance.

**Comment by hgy59** [comment]
@MilesTEG1 eza in the synocli-file package is not old (less than 3 months). Normally we do not update just for the sake of a newer version, since this is a community project with very limitted resources...
We expect you create an issue when you have problems with a package, or miss a feature, or when an update solves security issues.

Nevertheless I started to update synocli-file and added another `ls` tool `lsd` that was requested.

**Comment by MilesTEG1** [comment]
Hello,
Thanks for responding to my message.
I wasn't asking to update just for the sake of an update.
Eza is in active development as it's a pretty new project to replace exa which isn't maintained anymore.
And every builds came with fixes , some important , some less. But fixes anyway. It came also with new features.

I understand that this is a community works with limited time and manpower. If a could help, I'd be happy to, but my skills in development are pretty limited.

Do you intend to add eza latest version in the upcoming update with lsd?


Have you a detailed procedure to update a binary inside the package? And how to build the package in order to submit it here ?

Thanks again for your time 😊

**Comment by mreid-tt** [comment]
Hello @MilesTEG1, please take a moment to review the newly created #5937, linked above. It incorporates the requested updates. Typically, PRs like this one undergo a review and testing process, which may take a few days or even weeks, but progress is underway.

For guidance on updating procedures, you can refer to the Wiki for insights into our package-building process. Alternatively, examining previous PRs that involve updating the same package can provide valuable insights into how other developers have approached similar tasks.
