### ISSUE TITLE
jellyfin on a Synology DS413j?

### ISSUE THREAD

**Issue by Savasdotexe** [SynoCommunity/spksrc#5943]
Is there a possibility for jellyfin on a Synology DS413j?

**Comment by mreid-tt** [comment]
> Is there a possibility for jellyfin on a Synology DS413j?

Regrettably, the DS413j is incompatible with Jellyfin due to its reliance on an ARM v5 CPU architecture (see [here](https://github.com/SynoCommunity/spksrc/wiki/Synology-and-SynoCommunity-Package-Architectures#x13-series)). Jellyfin currently requires the ARM v7 architecture to run, and even within the ARM v7 category, not all models are supported with dotnet 6.x, as outlined in issue #5574.
