### ISSUE TITLE
Include vidir from moreutils in synocli-misc

### ISSUE THREAD

**Issue by DrMcCoy** [SynoCommunity/spksrc#5944]
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

synocli-misc

### Package Version

1.1-3

### Device Model

DS1520+

### Device Architecture

x86_64

### Firmware Version

DSM 7.2.1-69057 Update 3

### What happened?

You already install moreutils in synocli-misc, but without vidir. It would be great if vidir could be pulled in as well.  
It does depend on vi or vim, though, which is why I assume it was left out?

(Sorry, this is kind of an in-between between a bug and a package request. Neither template really fits here.)

**Comment by hgy59** [comment]
@found that `vidir` is just a perl script.
You can download it and it might run, if you have installed the Perl package of Synology.

IMHO it is not worth to add it to synocli-misc, since it would add Perl as additinal Package dependency.
And you cannot use vidir out of the box. You have at least to set the env variable EDITOR to specify the editor to use.

You can download current (not yet updated to 0.68) version at https://deb.debian.org/debian/pool/main/m/moreutils/moreutils_0.67.orig.tar.gz

If vidir depends on perl modules/libraries not installed by the Synology Perl Package, it is out of scope of a SynoCommunity Package to provide it.


_we could add the perl scripts of moreutils (vidir vipe ts combine zrun chronic) without perl package dependency, so it would be the users responsibility to install Perl to use the scripts - if this helps?_

**Comment by DrMcCoy** [comment]
Oh, I didn't know that it's a Perl script.

And yeah, just putting it on my NAS works, after installing Perl. Thanks!

> we could add the perl scripts of moreutils (vidir vipe ts combine zrun chronic) without perl package dependency, so it would be the users responsibility to install Perl to use the scripts - if this helps?

Knowing that it's a Perl script I can just pop the thing in there manually, instead of having to compile it first, I don't personally need that anymore.

I guess it's your decision whether it would be confusing for people to find something there that might not run at all, due to it requiring Perl.

**Comment by hgy59** [comment]
@DrMcCoy good to hear you found a solution.
