### ISSUE TITLE
Python: Invalid file format. Please contact the package developer.

### ISSUE THREAD

**Issue by Mediatros** [SynoCommunity/spksrc#5950]
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

Python

### Package Version

2.7.18-25

### Device Model

DS718+

### Device Architecture

x86_64

### Firmware Version

DSM 7.1.1-42962 Update 6

### What happened?

The package is downloaded
Then i've got this error message :

Python: Invalid file format. Please contact the package developer.

### Reproduction steps

1. I clic on install button
2. The package is downloaded
3. Then i've got this error message :
Python: Invalid file format. Please contact the package developer.
<img width="1183" alt="Capture d’écran 2023-12-06 à 13 32 53" src="https://github.com/SynoCommunity/spksrc/assets/3978957/5e050698-883f-4b7b-a2ba-a6d3e4d970d8">

### Install Log

```log
no log created
```

**Comment by mreid-tt** [comment]
Hi @Mediatros, this version of Python is very old and has not been updated since 2020-10-14. As such, the versions in our repo only support DSM 6 as shown on the [webpage](https://synocommunity.com/package/python) for the package:

<img width="1164" alt="Screenshot 2023-12-06 at 9 18 48 AM" src="https://github.com/SynoCommunity/spksrc/assets/943378/b547d015-a702-4040-aa77-29320d27f314">

The backend repo does have a bug where is will unfortunately show these packages available for DSM 7 even though they are not compatible if one specific to DSM 7 isn't present. There is already an [issue](https://github.com/SynoCommunity/spkrepo/issues/63) to track this but it has not been resolved as of yet.

Can you share some more details of why you need this older version of Python? Perhaps there can be other solutions to meet your need.

**Comment by Mediatros** [comment]
Dear Michael,

I am interested in setting up the GateOne package, developed by M4tt075. GateOne serves as an HTML5 terminal emulator as well as an SSH client.

Please note that Python is a prerequisite package for this installation.

I hope this provides you with a clearer picture of my requirements. I appreciate your assistance in this matter.

Kind Regards,
Mediatros

**Comment by hgy59** [comment]
This is a known issue of the synocommunity package repository.
https://github.com/SynoCommunity/spkrepo/issues/63

**Comment by hgy59** [comment]
GateOne will never run on DSM 7.
