### ISSUE TITLE
some pkgs creates shared folder

### ISSUE THREAD

**Issue by MAngel666** [SynoCommunity/spksrc#6291]
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

sabnzb, deluge

### Package Version

4.3.3-71, 2.1.1.61-23

### Device Model

DS1819+

### Device Architecture

x86_64

### Firmware Version

7.2.2-72806

### What happened?

The packages unnecessarily create their own shared folders. I use a different structure and don’t need these folders. If I delete the folders, they are recreated when the packages start.

### Reproduction steps

1. Install pkg
2. Stop service
3. Delete corresponding shared folder
4. Start service

### Install Log

```log
I think this is not necessary
```

**Comment by mreid-tt** [comment]
@MAngel666, thanks for your suggestion. I can't comment on Deluge, but for SABnzbd, the installation process creates several folders to manage downloads. It's important to set the necessary permissions for these folders before installing the package to avoid errors.

Do you have any recommendations on how the installation process could better accommodate users who prefer using shared folders versus those who don’t, like yourself?

**Comment by hgy59** [comment]
This is by design. Since we migrated the shared folders to system resources (required for DSM 7) the shared folders are managed by DSM for the packages.
It is even curious that you can delete such a shared folder. AFAICR DSM tells you that the folder is used by the related package and prevents the deletion.

**Comment by MAngel666** [comment]
> This is by design. Since we migrated the shared folders to system resources (required for DSM 7) the shared folders are managed by DSM for the packages. It is even curious that you can delete such a shared folder. AFAICR DSM tells you that the folder is used by the related package and prevents the deletion.

If you stop the service, you can delete the folder but it will be created again if you start the service again.

**Comment by MAngel666** [comment]
> @MAngel666, thanks for your suggestion. I can't comment on Deluge, but for SABnzbd, the installation process creates several folders to manage downloads. It's important to set the necessary permissions for these folders before installing the package to avoid errors.
> 
> Do you have any recommendations on how the installation process could better accommodate users who prefer using shared folders versus those who don’t, like yourself?

For me, it would be sufficient if the corresponding folders could be configured afterwards or if they are not recreated after being deleted.

**Comment by hgy59** [comment]
You can manually adjust the folders in package specific configuration files

for deluge those are:
`/var/packages/deluge/var/core.conf`
and
`/var/packages/deluge/var/autoadd.conf`

for sabnzbd it is:
`/var/packages/sabnzbd/var/config.ini`


You can specifiy an exiting shared folder and the installer will add permissions for the package user. But if your existing structure does not have a shared folder at the top level (i.e. /volume?/share-name) you have to use a dummy for the shared folder that will be recreated if you delete it.

**Comment by MAngel666** [comment]
These are the normal config files from the respective programs. I have already adjusted everything to my structure there. I have not found any references to the shared folders that are always created - sabnzb always creates a "downloads" and deluge creates a "deluge" shared folder.

sabnzb:
`root@lucypher:~# grep downloads /var/packages/sabnzbd/var/config.ini
root@lucypher:~#`

not wanted shared folder: 
/volume11/downloads/


Shared Folder: 
/volume11/deluge/

deluge:
`root@lucypher:~# grep deluge /var/packages/deluge/var/core.conf
    "download_location": "/volume7/work/deluge/incomplete/",
    "plugins_location": "/volume11/@appdata/deluge/plugins",
    "torrentfiles_location": "/volume7/deluge/incomplete",
root@lucypher:~# 
root@lucypher:~# grep deluge /var/packages/deluge/var/autoadd.conf
            "download_location": "/volume7/work/deluge/incomplete/"`

not wanted shared folder: 
/volume11/deluge/

**Comment by mreid-tt** [comment]
@hgy59, I think the folder re-creation is as a result of the data share resource worker not the individual package configuration files.

@MAngel666, editing the installed resources for a package is generally not recommended. However, since you seem quite skilled with the terminal, you can try the following:

For SABnzbd, the file would be in the location `/var/packages/sabnzbd/conf/resource.own`. For me, it looks like:

```
{"data-share":{"shares":[{"created":true,"target":"downloads"}]},"port-config":{},"systemd-unit":{},"usr-local-linker":{"links":["/usr/local/bin/7za"]}}
```

I believe if you change `"created":true` to `"created":false` and then restart the package it should prevent the shared folder from being recreated. A sequence like this should achieve that:
```
jq -c '.["data-share"].shares[].created = false' /var/packages/sabnzbd/conf/resource.own > /var/packages/sabnzbd/conf/resource.own.new
mv /var/packages/sabnzbd/conf/resource.own /var/packages/sabnzbd/conf/resource.own.bak && mv /var/packages/sabnzbd/conf/resource.own.new /var/packages/sabnzbd/conf/resource.own
```
If this doesn't work, the whole `data-share` object can be removed as an alternate approach. A sequence like this should achieve that:
```
jq -c 'del(.["data-share"])' /var/packages/sabnzbd/conf/resource.own > /var/packages/sabnzbd/conf/resource.own.new
mv /var/packages/sabnzbd/conf/resource.own /var/packages/sabnzbd/conf/resource.own.bak && mv /var/packages/sabnzbd/conf/resource.own.new /var/packages/sabnzbd/conf/resource.own
```
Editing this file is not recommended. The backups created above can be used to revert any changes if needed. Note that the file may be reverted during a package upgrade, so your results may vary.

**Comment by hgy59** [comment]
@MAngel666 as I said this is by design
When you originally installed the packages, you defined the shared folders (`downloads` is the default for sabnzbd and `deluge` is the default for deluge).
You could define your own folders at the time of intallation, but you can't omit it. The packages are designed so.

If you absolutely want to get rid of those, you must modify the resources (json) file of the installed package.
But each package update will enforce you to configure a shared folder again.

**Comment by hgy59** [comment]
@mreid-tt thanks for the detailed description, I gave the same hint without the details.

The real solution would be to ask in the install wizard whether to use a shared folder or existing directories.
But this would not only make the installer complicated, it is not possible to give the package user access to existing folders (DSM 7 restrictions) and it is not possible to manually add the package user to the folders before the installation is completed.

An installation without the use of shared folders needs a lot of handwork that we want to omit.

**Comment by MAngel666** [comment]
Unfortunately, neither option works… 

> I believe if you change `"created":true` to `"created":false` and then restart the package it should prevent the shared folder from being recreated. A sequence like this should achieve that:
In this case, the folders are still recreated. 

> If this doesn't work, the whole `data-share` object can be removed as an alternate approach. A sequence like this should achieve that:
> 
> ```
> jq -c 'del(.["data-share"])' /var/packages/sabnzbd/conf/resource.own > /var/packages/sabnzbd/conf/resource.own.new
> mv /var/packages/sabnzbd/conf/resource.own /var/packages/sabnzbd/conf/resource.own.bak && mv /var/packages/sabnzbd/conf/resource.own.new /var/packages/sabnzbd/conf/resource.own
> ```
This option results in a broken package, and repairing it naturally recreates everything.

But I could change the "data-share" option to my folder what I use and the "downloads" and "deluge" shared folder arent recreated again :)

**Comment by mreid-tt** [comment]
> But I could change the "data-share" option to my folder what I use and the "downloads" and "deluge" shared folder arent recreated again :)

Glad it worked out for you. The issue of it reverting during upgrades may still be an issue. You can perhaps look into editing the `installer-variables` file to match your environment as this should help. For SABnzbd, it would be at this location: `/var/packages/sabnzbd/etc/installer-variables`
