### ISSUE TITLE
Compiling packages on OS X

### ISSUE THREAD

**Issue by Decipher** [SynoCommunity/spksrc#747]
Hi,

I'm aware the README recommends using a Debian VM to compile packages, but it would make my life easier if I could use OS X natively.

I've started looking into it myself and have managed to get some stuff working, I have atleast managed to compile Mylar with a few minor tweaks.

Currently, the issues I am having are with Busybox (which throws errors) and with the '--group=root --owner=root' flag in the tarring of the package.

The easy one here is the tarring, as OS X just doesn't support that flag, nor does OS X have a 'root' group, I simply removed it, but I would like to be able to make a change that I can commit back, so are there any suggestions for this?

And as for Busybox, I have no idea, I'll see if I can dig a bit further into this issue myself.

Also, for anyone trying to compile with OS X, the main things that I've done (on top of my existing setup) was to install the 'coreutils' and 'imagemagick' homebrew brews.

**Comment by digitalbox94** [comment]
Hello, 
I have succeed in cross compiling diskutils with spksrc on macosx.
You need to install homebrew and apply a few changes on spksrc scripts and have a correct toolchain running on mac for your nas model.
However it’s more like a challenge than a useable tool at the moment because not sure toolchains are available for all nas models at the moment for mac and not all spk are building fine (transmission is failing for instance)
But it can work partially at the moment :)

**Comment by Decipher** [comment]
It's all good. Docker solves all, I haven't needed to cross compile anything since upgrading my NAS :) But I'm sure others will still find this helpful.
