### ISSUE TITLE
Use Docker and Vagrant to create a uniform dev environment

### ISSUE THREAD

**Issue by Skindred** [SynoCommunity/spksrc#788]
Using Docker ( http://www.docker.io/ ) and Vagrant ( http://www.vagrantup.com/ ),
a consistent easy and fast to deploy development environment is extremely easy to set up:

Install vagrant

Move to a folder where you want to keep your Vagrant VM's
(eg. %UserProfile%\VirtualBox VMs)

Run:

git clone https://github.com/dotcloud/docker.git
cd docker
vagrant up && vagrant down && vagrant up

The VM should now be live in VirtualBox.
Connect to the VM using vagrant:vagrant on localhost:2222 and run (be sure to replace all instances of Skindred/spksrc with <YourUsername>/spksrc:

docker build -t Skindred/spksrc https://raw.github.com/Skindred/docker-spksrc/master/Dockerfile

This will:

- pull in Debian 7.3
- download / install all needed packages into the Docker image
- git checkout spksrc to /spksrc
- perform make setup

Should this fail, (it happened to me twice since apt-get gave me broken pipes while downloading packages), you can run:

docker stop $(docker ps -q)
docker rm $(docker ps -a -q)
docker rmi $(docker images -a -q)

If the image has been successfully built, cleanup all containers:

docker rm $(docker ps -a -q)

You can now use the image by spawning a new container from it:

docker run -i -t Skindred/spksrc /bin/bash
cd /spksrc/toolchains/; for i in *; do cd $i; make; cd ..; done; rm -f /spksrc/distrib/gcc*.tgz #install all toolchains, you can ofcourse also choose to install only one

Once you exit out of this container, the instance can be found using:

docker ps -a

You must then commit that container using:

docker commit <id> Skindred/spksrc:<tag>

If you have an issue compiling one piece of software, that depends on another piece, and you want to try out different versions, you can just:

Version A:

- docker run -i -t Skindred/spksrc[:<tag>] /bin/bash
- make version a
- exit
- docker ps -a
- docker commit <id> Skindred/spksrc:python-libtorrent
- docker run -i -t Skindred/spksrc:python-libtorrent /bin/bash
- do whatever you want to test

Version B:

- docker run -i -t Skindred/spksrc[:<tag>] /bin/bash
- make version b
- exit
- docker ps -a
- docker commit <id> Skindred/spksrc:python-libtorrent-rakshasa
- docker run -i -t Skindred/spksrc:python-libtorrent-rakshasa /bin/bash
- do whatever you want to test

The Dockerfile is based off of https://github.com/bydavy/docker-spksrc, which I found after I had created my own Dockerfile.
The Dockerfile by bydavy was better than mine, but will no longer be needed once I have a working 32 bit base.

**Comment by Diaoul** [comment]
I'm currently working with Docker as my VM crashed and I didn't have time to rebuild it. It seems to work okay so far. I based my Dockerfile on someone else's, can't remember who and added some missing pieces.

I had also to understand the concept of volumes, now I got it but still have some permission issues, basically the container creates files as root on my volume on my host so I can't edit the generated files from my host. How can I fix this?

Also, the best practices are not clear to me, should spksrc be sent to the daemon? That seems useless to me so I created a simple dockerignore file in addition.
Should spksrc be cloned inside the container or in a volume so host can access it?
In order to improve spksrc accessibility, how can we mix vagrant and docker and keep it DRY for windows users? In that case should we mount spksrc in vagrant from the host then in docker from vagrant or should vagrant take care of the cloning part?

**Comment by Diaoul** [comment]
I'm considering changing the base distro for something more current like a Ubuntu LTS. What do you think @SynoCommunity/developers ?

**Comment by wind-rider** [comment]
Yes, please!

**Comment by Dr-Bean** [comment]
Personally, I dislike Ubuntu. I don't agree with the views of Canonical/Shuttleworth and the direction they're going, with examples such as Wayland vs Mir, Unity and the home lens functionality to name a few.
I understand Debian has its shortcomings, enough to warrant a look around. I just wish there was a more obvious choice than Ubuntu...

**Comment by bru7us** [comment]
I have no issues with with Ubuntu - using ti quite heavily at work - one of the biggest benefits is that it's so popular in the community that solutions to problems are very easy to find with a quick search.

I've also spent a LOT of time playing with Docker in the last month (also for work), so can offer help and advice there too if needed.

That said - have you looked into CoreOS yet? I've heard some things... but haven't looked in detail myself.

**Comment by Diaoul** [comment]
Well, Ubuntu GUI stuff would be hidden as we don't need that in Docker, just the package manager and interactive access to bash. You can use your regular OS (except Windows), your regular git tools, your spksrc fork, etc. You can start a container on any spksrc directory of your choice on your current OS, it will mount the spksrc folder from the host inside the container.

I'm currently cross compiling python inside my container, I have a successful build for 88f6281, now I'm making all archs simultaneously and check the result when I get back from work. Fingers crossed.

Yes, python is my test case :)

**Comment by Dr-Bean** [comment]
My remark was meant philosophical, not so much practical (although Unity...*shudder* ;))

Since I haven't worked with Docker before, a question: you say I can use my regular/current OS, 'except Windows'? So we can't run an spksrc Docker container directly on Windows? 
My current setup is that I run Debian in a VM, but if I would essentially be running a Docker container in a VM, not sure where the upside is in that.

**Comment by Diaoul** [comment]
In that case what it changes is that you can run any distribution you want in the VM and run the Docker container inside it. Currently we're stuck with Debian.

**Comment by bru7us** [comment]
@Diaoul when you say you're building all arches simultaneously - is this inside a single single container?
One of the issues with Docker is that because each container is "ideally" supposed to contain/manage a single process - you likely are going to be bound to a single cpu core.
For ultimate parallelisation, it might be better to try to spin up a container per 'thread' to maximise utilisation of system resources (and speed things up).

Going that route however would mean that we'd have to depend very heavily on docker and modify the Makefiles to "docker run -it <spksrc_img> make" instead of just make... which doesn't seem entirely ideal.

**Comment by Diaoul** [comment]
@bru7us: parallelisation is done by Make inside the container, looking at my CPU usage on the host it is clear to me that more than one core is used. I don't know if that's optimal but it seems to use all my CPU just fine.

**Comment by bru7us** [comment]
Good to know!

**Comment by Diaoul** [comment]
I've pushed the Dockerfile, I just compile python for all archs with it the same way I did on my VM so it seems to work flawlessly.

TODO: Update the documentation

**Comment by Diaoul** [comment]
Here is the automated build based on this GitHub repository: https://registry.hub.docker.com/u/synocommunity/spksrc/
