### ISSUE TITLE
Add a configuration backup SPK

### ISSUE THREAD

**Issue by Diaoul** [SynoCommunity/spksrc#95]
To backup SPKs configuration files and restore them.
- All available SPKs are in /usr/local/\* filtered with a hardcoded list of SPKs we support for this feature
- Send a zip to the user with the /var directory and without the pid file
- Ability to restore from such a zip + chown the /var directory with the same owner:group as its parent directory
##

**Comment by mreppen** [comment]
Are there any news on this front? Being able to select an application under Backup and restore would be great!

**Comment by piwi82** [comment]
Ask Synology.

**Comment by Dr-Bean** [comment]
Fwiw, it's technically possible. Here's a starting point: http://www.synology-forum.de/showthread.html?68578-HowTo-3rdparty-Apps-in-DSM-Sicherung-Replication-integrieren.
Synology currently hasn't included it in their developers guide though, and someone will have to find to time to integrate it into spksrc.

**Comment by cytec** [comment]
@Dr-Bean so if i get this right... we just need to support copying a folder (backup) to the scripts folder when building the SPK and maybe automatically generate the version file?

**Comment by Dr-Bean** [comment]
Indeed, although I was thinking that the files could be completely auto-generated via spksrc, probably similar to how the INFO file is created. I'd prefer that over a manual approach for each package, because that just looks like a bunch of mindless copy/pasting once you've figured out what goes where.

As an example (and yes, I realize it's more advanced than a straight-forward package with just files): if a database is included in the package, let spksrc add the handler and fill the dbname in the `info` file, and set the offline mode to ensure the package is stopped before starting the backup.

Note that I haven't spent a lot of time on it, but from what I can see, it looks feasible to automate it for a large majority of the packages.
